import type { ExecutiveModuleRegistry } from "./module-registry.types";

/** Tüm Executive modüllerinin merkezi registry kaydı. Sadece metadata; servis çağrısı yoktur. */
export const DEFAULT_EXECUTIVE_MODULE_REGISTRY: ExecutiveModuleRegistry = {
  modules: {
    "conversation-understanding": {
      key: "conversation-understanding",
      displayName: "Conversation Understanding",
      description: "Mesajın amacını, türünü ve executive reasoning gereksinimini analiz eder.",
      version: "0.1.0",
      status: "experimental",
      defaultTimeoutMs: 3000,
      executionMode: "sequential",
      dependencies: [],
      adapterName: "conversation-understanding-adapter",
      producesSnapshotFields: ["userIntentSummary", "situationSummary"],
    },
    "executive-context-builder": {
      key: "executive-context-builder",
      displayName: "Executive Context Builder",
      description: "Organizasyon verilerinden executive context paketi oluşturur.",
      version: "0.1.0",
      status: "experimental",
      defaultTimeoutMs: 4000,
      executionMode: "sequential",
      dependencies: ["conversation-understanding"],
      adapterName: "executive-context-builder-adapter",
      producesSnapshotFields: ["companySituationSummary"],
    },
    "company-model": {
      key: "company-model",
      displayName: "Company Model",
      description: "Şirketin stratejik profilini ve finansal durumunu modellendirir.",
      version: "0.1.0",
      status: "experimental",
      defaultTimeoutMs: 3000,
      executionMode: "parallel",
      dependencies: [],
      adapterName: "company-model-adapter",
      producesSnapshotFields: ["companySituationSummary"],
    },
    "executive-reasoning": {
      key: "executive-reasoning",
      displayName: "Executive Reasoning",
      description: "Yönetici muhakemesi üretir; risk, öncelik ve trade-off analizi yapar.",
      version: "0.1.0",
      status: "experimental",
      defaultTimeoutMs: 12000,
      executionMode: "sequential",
      dependencies: ["executive-context-builder", "company-model"],
      adapterName: "executive-reasoning-adapter",
      producesSnapshotFields: ["topPriority", "topRisk", "currentExecutiveOpinion"],
    },
    "recommended-next-move": {
      key: "recommended-next-move",
      displayName: "Recommended Next Move",
      description: "GM'in önerdiği somut bir sonraki adımı üretir.",
      version: "0.1.0",
      status: "experimental",
      defaultTimeoutMs: 8000,
      executionMode: "sequential",
      dependencies: ["executive-reasoning"],
      adapterName: "recommended-next-move-adapter",
      producesSnapshotFields: ["recommendedAction"],
    },
    "learning-loop": {
      key: "learning-loop",
      displayName: "Learning Loop",
      description: "Konuşmadan öğrenme sinyalleri çıkarır ve öğrenme adayları üretir.",
      version: "0.1.0",
      status: "experimental",
      defaultTimeoutMs: 6000,
      executionMode: "parallel",
      dependencies: [],
      adapterName: "learning-loop-adapter",
      producesSnapshotFields: ["learningSummary"],
    },
    "executive-brain-shadow": {
      key: "executive-brain-shadow",
      displayName: "Executive Brain Shadow",
      description: "GM karar yargısını shadow modda üretir; production davranışını etkilemez.",
      version: "0.1.0",
      status: "experimental",
      defaultTimeoutMs: 4000,
      executionMode: "parallel",
      dependencies: [],
      adapterName: "executive-brain-shadow-adapter",
      producesSnapshotFields: [],
    },
    "forecast": {
      key: "forecast",
      displayName: "Forecast",
      description: "Şirket verilerinden kısa vadeli tahmin ve projeksiyon üretir.",
      version: "0.1.0",
      status: "experimental",
      defaultTimeoutMs: 5000,
      executionMode: "parallel",
      dependencies: ["company-model"],
      adapterName: "forecast-adapter",
      producesSnapshotFields: [],
    },
    "decision-loop": {
      key: "decision-loop",
      displayName: "Decision Loop",
      description: "Açık kararları takip eder ve karar döngüsünü yönetir.",
      version: "0.1.0",
      status: "experimental",
      defaultTimeoutMs: 4000,
      executionMode: "parallel",
      dependencies: [],
      adapterName: "decision-loop-adapter",
      producesSnapshotFields: ["openDecisionsSummary", "commitmentsSummary"],
    },
    "snapshot-composer": {
      key: "snapshot-composer",
      displayName: "Snapshot Composer",
      description: "Worker çıktılarını birleştirerek prompt-ready snapshot üretir.",
      version: "0.1.0",
      status: "experimental",
      defaultTimeoutMs: 2000,
      executionMode: "sequential",
      dependencies: [],
      adapterName: "snapshot-composer-adapter",
      producesSnapshotFields: [],
    },
  },
};
