import type { ExecutiveAwarenessWatchArea } from "@/lib/executive-awareness/executive-awareness.types";
import type { ExecutiveScorecardArea } from "@/lib/executive-scorecard/executive-scorecard.types";
import type { ExecutiveFocusArea, ExecutiveFocusLevel } from "@/lib/executive-focus/executive-focus.types";
import type { ExecutiveNarrativeTone, ExecutiveNarrativePosture } from "@/lib/executive-narrative/executive-narrative.types";
import type { ExecutiveAwarenessDirection } from "@/lib/executive-awareness/executive-awareness.types";
import type { ExecutiveScorecardLevel } from "@/lib/executive-scorecard/executive-scorecard.types";
import type { ExecutiveCouncilPosition } from "@/lib/executive-council/executive-council.types";
import type { ExecutiveDecisionPromptSummary } from "@/lib/executive-decision-engine";
import type { ExecutiveDecisionFollowUpPromptSummary } from "@/lib/executive-decision-follow-up";
import type { ExecutiveAccountabilityPromptSummary } from "@/lib/executive-accountability";
import type { ExecutiveDelegationPromptSummary } from "@/lib/executive-delegation";
import type { ExecutiveResponsibilityMatrixPromptSummary } from "@/lib/executive-responsibility-matrix";
import type { ExecutivePerformanceSignalPromptSummary } from "@/lib/executive-performance-signal";
import type { ExecutiveManagementReviewPromptSummary } from "@/lib/executive-management-review";
import type { CustomerPortfolioPromptSummary } from "@/lib/customer-portfolio-intelligence";
import type { CustomerHealthPromptSummary } from "@/lib/customer-health-intelligence";
import type { ExpenseContext, ExpenseIntelligence } from "@/lib/core/expenses";
import type { FinancialHealthPromptSummary } from "@/lib/financial-health-intelligence";
import type { CompanyPerformanceSignalPromptSummary } from "@/lib/company-performance-signal";
import type { ExecutivePrioritizationResult } from "@/lib/executive-prioritization";
import type { ExecutiveOperatingRhythm } from "@/lib/executive-operating-rhythm";
import type { ExecutiveFollowUpPromptSummary } from "@/lib/executive-follow-up-intelligence";

export type ExecutiveManagerContextConfidence = "LOW" | "MEDIUM" | "HIGH";

export type GoalAchievementSnapshot = {
  monthlyTarget: number | null;
  forecastedMonthEndRevenue: number | null;
  goalAchievementRate: number | null;
  goalGap: number | null;
};

export type ExecutiveManagerContext = {
  posture: ExecutiveNarrativePosture;
  direction: ExecutiveAwarenessDirection;
  health: ExecutiveScorecardLevel;
  tone: ExecutiveNarrativeTone;
  situationalRead: string;
  primaryFocusArea: ExecutiveFocusArea;
  primaryFocusLevel: ExecutiveFocusLevel;
  primaryFirstMove: string;
  secondaryFocusArea: ExecutiveFocusArea | null;
  focusInstruction: string;
  firstAttention: string | null;
  weakestArea: ExecutiveScorecardArea | null;
  watchAreas: ExecutiveAwarenessWatchArea[];
  contextConfidence: ExecutiveManagerContextConfidence;
  dataQualityNote: string | null;
  councilPosition: ExecutiveCouncilPosition | null;
  councilStanceRationale: string | null;
  topCouncilAction: string | null;
  topConcern: string | null;
  goalSummary: string | null;
  executiveDecision: ExecutiveDecisionPromptSummary | null;
  executiveDecisionFollowUp: ExecutiveDecisionFollowUpPromptSummary | null;
  executiveAccountability: ExecutiveAccountabilityPromptSummary | null;
  executiveDelegation: ExecutiveDelegationPromptSummary | null;
  executiveResponsibilityMatrix: ExecutiveResponsibilityMatrixPromptSummary | null;
  executivePerformanceSignal: ExecutivePerformanceSignalPromptSummary | null;
  executiveManagementReview: ExecutiveManagementReviewPromptSummary | null;
  customerPortfolio: CustomerPortfolioPromptSummary | null;
  customerHealth: CustomerHealthPromptSummary | null;
  expenseContext: ExpenseContext | null;
  expenseIntelligence: ExpenseIntelligence | null;
  financialHealth: FinancialHealthPromptSummary | null;
  companyPerformance: CompanyPerformanceSignalPromptSummary | null;
  goalAchievement: GoalAchievementSnapshot;
  executivePriority: ExecutivePrioritizationResult | null;
  executiveOperatingRhythm: ExecutiveOperatingRhythm | null;
  executiveFollowUpIntelligence: ExecutiveFollowUpPromptSummary | null;
};
