import type { StructuredFieldCandidate } from "@/lib/field-authority/structured-field-ingestion";
import type { CanonicalCaptureEnvelope, CaptureFieldCandidateInput, EntityHint } from "./contracts";

export type SourceAdapterInput = Readonly<{ captureId: string; correlationId: string; occurredAt: string; receivedAt: string; entityHint: EntityHint; operation: "CREATE" | "UPDATE" | "ENRICH"; explicitCommitIntent: boolean }>;
const base = (input: SourceAdapterInput, source: CanonicalCaptureEnvelope["source"], candidates: readonly CaptureFieldCandidateInput[], sourceRef?: string): CanonicalCaptureEnvelope => Object.freeze({ captureId: input.captureId, correlationId: input.correlationId, source, ...(sourceRef ? { sourceRef } : {}), occurredAt: input.occurredAt, receivedAt: input.receivedAt, entityHints: Object.freeze([input.entityHint]), observations: Object.freeze([]), fieldCandidates: Object.freeze([...candidates]), requestedOperation: input.operation, explicitCommitIntent: input.explicitCommitIntent, adapterMetadata: Object.freeze({ name: source.adapter, version: source.version }) });
export function adaptPlannerCandidates(input: SourceAdapterInput & Readonly<{ sourceRef?: string; candidates: readonly Readonly<{ fieldId?: string; key?: string; label?: string; value: unknown; confidence?: number; explicit?: boolean }>[] }>): CanonicalCaptureEnvelope { const candidates = input.candidates.map((item, index) => Object.freeze({ candidateId: `${input.captureId}:${index}`, field: Object.freeze({ ...(item.fieldId ? { fieldId: item.fieldId } : {}), ...(item.key ? { key: item.key } : {}), ...(item.label ? { label: item.label } : {}) }), rawValue: item.value, confidence: item.confidence ?? .9, evidence: Object.freeze([{ kind: "planner", ...(input.sourceRef ? { sourceRef: input.sourceRef } : {}) }]), warnings: Object.freeze([]), explicit: item.explicit ?? true, observedAt: input.occurredAt })); return base(input, Object.freeze({ id: "conversation-planner", category: "conversation", adapter: "planner-candidate-adapter", version: "1" }), candidates, input.sourceRef); }
export function adaptStructuredDocumentCandidates(input: SourceAdapterInput & Readonly<{ sourceRef: string; candidates: readonly StructuredFieldCandidate[] }>): CanonicalCaptureEnvelope { const candidates = input.candidates.map((item, index) => Object.freeze({ candidateId: `${input.captureId}:${index}`, field: Object.freeze({ fieldId: item.fieldId }), rawValue: item.extractedValue, confidence: item.confidence, evidence: Object.freeze([{ kind: "document", sourceRef: input.sourceRef, ...(item.source.evidence ? { excerpt: item.source.evidence } : {}) }]), warnings: Object.freeze([...item.warnings]), explicit: false, observedAt: input.occurredAt })); return base(input, Object.freeze({ id: "structured-document", category: "document", adapter: "structured-document-candidate-adapter", version: "1" }), candidates, input.sourceRef); }
export function adaptConversationCaptureSource(envelope: CanonicalCaptureEnvelope, channel: "text" | "voice"): CanonicalCaptureEnvelope { const source = Object.freeze({ ...envelope.source, id: channel === "voice" ? "voice-conversation" : "text-conversation", category: channel }); return Object.freeze({ ...envelope, source, adapterMetadata: Object.freeze({ name: source.adapter, version: source.version }) }); }
export type FutureTransportAdapter = Readonly<{ readonly sourceCategory: string; validate(payload: unknown): boolean; toEnvelope(payload: unknown, trustedInput: SourceAdapterInput): CanonicalCaptureEnvelope }>;
