import { CAPTURE_LIMITS, type CanonicalCaptureEnvelope, type CaptureEvidence, type CaptureFieldCandidateInput } from "./contracts";

const keys = (value: Record<string, unknown>, allowed: readonly string[]) => Object.keys(value).every((key) => allowed.includes(key));
const record = (value: unknown): value is Record<string, unknown> => typeof value === "object" && value !== null && !Array.isArray(value) && ["__proto__", "prototype", "constructor"].every((key) => !Object.prototype.hasOwnProperty.call(value, key));
const text = (value: unknown, max = 200) => typeof value === "string" && value.length > 0 && value.length <= max;
const date = (value: unknown) => typeof value === "string" && text(value, 40) && !Number.isNaN(Date.parse(value));
function evidence(value: unknown): value is CaptureEvidence { return record(value) && keys(value, ["kind", "sourceRef", "excerpt", "observedAt"]) && text(value.kind, 50) && (value.sourceRef === undefined || text(value.sourceRef, 120)) && (value.excerpt === undefined || text(value.excerpt, CAPTURE_LIMITS.evidenceText)) && (value.observedAt === undefined || date(value.observedAt)); }
function boundedJson(value: unknown, depth = 0): boolean { if (depth > 4) return false; if (value === null || typeof value === "boolean" || (typeof value === "number" && Number.isFinite(value)) || (typeof value === "string" && value.length <= 2_000)) return true; if (Array.isArray(value)) return value.length <= 50 && value.every((item) => boundedJson(item, depth + 1)); return record(value) && Object.keys(value).length <= 50 && Object.values(value).every((item) => boundedJson(item, depth + 1)); }
function candidate(value: unknown): value is CaptureFieldCandidateInput { if (!record(value) || !keys(value, ["candidateId", "field", "rawValue", "confidence", "evidence", "warnings", "explicit", "observedAt"]) || !text(value.candidateId, 120) || !record(value.field) || !keys(value.field, ["fieldId", "key", "label", "valueType"]) || !boundedJson(value.rawValue) || typeof value.confidence !== "number" || value.confidence < 0 || value.confidence > 1 || typeof value.explicit !== "boolean" || !date(value.observedAt)) return false; if (![value.field.fieldId, value.field.key, value.field.label].some((item) => text(item, 160))) return false; if (value.evidence !== undefined && (!Array.isArray(value.evidence) || value.evidence.length > CAPTURE_LIMITS.evidence || !value.evidence.every(evidence))) return false; return value.warnings === undefined || (Array.isArray(value.warnings) && value.warnings.length <= 20 && value.warnings.every((item) => text(item, 300))); }
export function validateCaptureEnvelope(raw: unknown): CanonicalCaptureEnvelope {
  if (!record(raw) || !keys(raw, ["captureId", "correlationId", "sessionRef", "conversationRef", "source", "sourceRef", "occurredAt", "receivedAt", "transport", "entityHints", "observations", "fieldCandidates", "requestedOperation", "explicitCommitIntent", "adapterMetadata"])) throw new Error("CAPTURE_INVALID_SHAPE");
  if (!text(raw.captureId, 120) || !text(raw.correlationId, 120) || !date(raw.occurredAt) || !date(raw.receivedAt) || !record(raw.source) || !keys(raw.source, ["id", "category", "adapter", "version"]) || ![raw.source.id, raw.source.category, raw.source.adapter, raw.source.version].every((item) => text(item, 80))) throw new Error("CAPTURE_INVALID_IDENTITY");
  if (!record(raw.adapterMetadata) || !keys(raw.adapterMetadata, ["name", "version"]) || !text(raw.adapterMetadata.name, 80) || !text(raw.adapterMetadata.version, 40)) throw new Error("CAPTURE_INVALID_ADAPTER");
  if (!Array.isArray(raw.entityHints) || raw.entityHints.length !== 1 || !raw.entityHints.every((hint) => record(hint) && keys(hint, ["entityType", "reference", "identifiers", "createIfMissing"]) && text(hint.entityType, 80) && (hint.reference === undefined || text(hint.reference, 200)) && (hint.createIfMissing === undefined || typeof hint.createIfMissing === "boolean") && (hint.identifiers === undefined || (record(hint.identifiers) && Object.keys(hint.identifiers).length <= 20 && Object.entries(hint.identifiers).every(([key, value]) => text(key, 80) && text(value, 200)))))) throw new Error("CAPTURE_INVALID_ENTITY_HINT");
  if (!Array.isArray(raw.observations) || raw.observations.length > CAPTURE_LIMITS.observations || !raw.observations.every((item) => record(item) && keys(item, ["kind", "value", "evidence"]) && text(item.kind, 80) && text(item.value, 500) && (item.evidence === undefined || (Array.isArray(item.evidence) && item.evidence.length <= CAPTURE_LIMITS.evidence && item.evidence.every(evidence)))) || !Array.isArray(raw.fieldCandidates) || raw.fieldCandidates.length > CAPTURE_LIMITS.candidates || !raw.fieldCandidates.every(candidate)) throw new Error("CAPTURE_INVALID_CANDIDATES");
  const ids = raw.fieldCandidates.map((item) => item.candidateId); if (new Set(ids).size !== ids.length) throw new Error("CAPTURE_DUPLICATE_CANDIDATE_ID");
  if (!["CREATE", "UPDATE", "ENRICH"].includes(String(raw.requestedOperation)) || typeof raw.explicitCommitIntent !== "boolean") throw new Error("CAPTURE_INVALID_OPERATION");
  if (raw.transport !== undefined && (!record(raw.transport) || Object.keys(raw.transport).length > CAPTURE_LIMITS.metadataKeys || Object.values(raw.transport).some((item) => !["string", "number", "boolean"].includes(typeof item) || (typeof item === "string" && item.length > CAPTURE_LIMITS.metadataText)))) throw new Error("CAPTURE_INVALID_TRANSPORT");
  return structuredClone(raw) as CanonicalCaptureEnvelope;
}
