import { describe, expect, it } from "vitest";
import { CUSTOMER_BUILT_IN_FIELDS } from "@/lib/customers/customer-field-registry";
import { adaptCustomerCreatePlan, createCustomerEntityResolutionProvider, customerCaptureHandoffProvider } from "@/lib/customers/customer-universal-capture-adapter";
import { adaptStructuredDocumentCandidates } from "../adapters";
import { createHandoffPlan } from "../handoff";
import { UniversalCaptureOrchestrator } from "../orchestrator";
const now = "2026-07-20T10:00:00.000Z"; const context = { organizationId: "org-1", actorId: "user-1", permissions: ["customers.read", "customers.write"] };
const data = { async list(organizationId: string) { return organizationId === "org-1" ? [{ id: "cus-1", displayName: "Atlas Yapı", legalName: null, phone: null, email: null, cariKodu: null, taxNumber: null }] : []; }, async baseline(organizationId: string, customerId: string) { if (organizationId !== "org-1" || customerId !== "cus-1") throw new Error("TENANT"); return { currency: "TRY" }; } };
const runtime = () => new UniversalCaptureOrchestrator({ fields: async () => CUSTOMER_BUILT_IN_FIELDS, entityProviders: [createCustomerEntityResolutionProvider(data)] });
describe("customer production reference adapter", () => {
  it("adapts a multi-field create as one capture and one handoff", async () => { const input = { captureId: "create-1", correlationId: "conversation-1", occurredAt: now, receivedAt: now, entityHint: { entityType: "customer", createIfMissing: true }, operation: "CREATE" as const, explicitCommitIntent: false }; const capture = adaptCustomerCreatePlan({ ...input, fields: CUSTOMER_BUILT_IN_FIELDS, plan: { kind: "CREATE_PLAN", intent: "OPEN", explicitCommit: false, unsupportedFields: [], fields: { displayName: "Atlas Yapı", phone: "0532 111 22 33", email: "INFO@ATLAS.COM", "primaryContact.fullName": "Ahmet Yılmaz", "commercialTerms.paymentTermDays": 30, currency: "EUR" } } }); const result = await runtime().process(capture, context); const handoff = createHandoffPlan({ result, explicitCommitIntent: false, provider: customerCaptureHandoffProvider }); expect(capture.fieldCandidates).toHaveLength(6); expect(result.draftOperations).toHaveLength(6); expect(handoff?.actionName).toBe("customer.create"); expect(handoff?.explicitCommitIntent).toBe(false); });
  it("passes document candidates through the same core while retaining explicit review", async () => { const capture = adaptStructuredDocumentCandidates({ captureId: "doc-1", correlationId: "doc-corr", occurredAt: now, receivedAt: now, entityHint: { entityType: "customer", reference: "Atlas Yapı" }, operation: "ENRICH", explicitCommitIntent: false, sourceRef: "attachment-1", candidates: [{ fieldId: "customer.phone", extractedValue: "0532", normalizedValue: "0532", confidence: .95, source: { sourceId: "attachment-1", mediaType: "application/pdf", evidence: "Telefon: 0532" }, warnings: [], conflicts: [], conflictStatus: "NONE", requiresUserConfirmation: true }] }); const result = await runtime().process(capture, context); expect(result.resolvedCandidates[0]?.evidence[0]?.kind).toBe("document"); expect(result.status).toBe("DRAFT_READY"); expect(capture.explicitCommitIntent).toBe(false); });
  it("keeps tenant scope in trusted context", async () => { const provider = createCustomerEntityResolutionProvider(data); const result = await provider.resolve({ context: { ...context, organizationId: "org-2" }, hint: { entityType: "customer", reference: "Atlas Yapı" }, operation: "UPDATE" }); expect(result.status).toBe("NOT_FOUND"); });
  it("resolves strong identifiers consistently", async () => { const provider = createCustomerEntityResolutionProvider(data); const result = await provider.resolve({ context, hint: { entityType: "customer", identifiers: { id: "cus-1", name: "Atlas Yapı" } }, operation: "UPDATE" }); expect(result.status).toBe("RESOLVED"); expect(result.reasonCodes).toContain("CUSTOMER_IDENTIFIERS_CONSISTENT"); });
});
