import { describe, expect, it } from "vitest";
import { CUSTOMER_BUILT_IN_FIELDS, customerCustomDefinitionToField } from "@/lib/customers/customer-field-registry";
import { adaptPlannerCandidates } from "../adapters";
import { calculateInformationMaturity } from "../maturity";
import { renderTurkishDelta } from "../decision-services";
import { UniversalCaptureOrchestrator } from "../orchestrator";
import { validateCaptureEnvelope } from "../validation";
import { projectToActiveSurface } from "../handoff";
import type { CaptureEntityResolution, EntityResolutionProvider, TrustedCaptureContext } from "../contracts";

const now = "2026-07-20T10:00:00.000Z";
const context: TrustedCaptureContext = { organizationId: "org-1", actorId: "user-1", permissions: ["customers.read", "customers.write"] };
const resolved = (baseline: Record<string, unknown> = {}): EntityResolutionProvider => ({ entityType: "customer", async resolve({ context: ctx }) { return { status: "RESOLVED", entityType: "customer", reference: { organizationId: ctx.organizationId, entityType: "customer", entityId: "cus-1" }, candidates: [], confidence: 1, evidence: [], reasonCodes: ["EXACT"] }; }, async readBaseline() { return baseline; } });
const envelope = (candidates: readonly { fieldId?: string; key?: string; label?: string; value: unknown }[] = [{ fieldId: "customer.phone", value: "0532 111 22 33" }]) => adaptPlannerCandidates({ captureId: "cap-1", correlationId: "corr-1", occurredAt: now, receivedAt: now, entityHint: { entityType: "customer", reference: "Atlas" }, operation: "ENRICH", explicitCommitIntent: false, candidates });
const orchestrator = (provider: EntityResolutionProvider = resolved()) => new UniversalCaptureOrchestrator({ fields: async () => CUSTOMER_BUILT_IN_FIELDS, entityProviders: [provider] });

describe("universal capture contract", () => {
  it("accepts a valid immutable-compatible envelope and rejects unknown keys", () => { expect(validateCaptureEnvelope(envelope()).captureId).toBe("cap-1"); expect(() => validateCaptureEnvelope({ ...envelope(), actionName: "customer.update" })).toThrow("CAPTURE_INVALID_SHAPE"); });
  it("rejects invalid confidence, duplicate ids and oversized batches", () => { const valid = envelope(); expect(() => validateCaptureEnvelope({ ...valid, fieldCandidates: [{ ...valid.fieldCandidates[0], confidence: 2 }] })).toThrow("CAPTURE_INVALID_CANDIDATES"); expect(() => validateCaptureEnvelope({ ...valid, fieldCandidates: [valid.fieldCandidates[0], valid.fieldCandidates[0]] })).toThrow("CAPTURE_DUPLICATE_CANDIDATE_ID"); expect(() => validateCaptureEnvelope({ ...valid, fieldCandidates: Array.from({ length: 101 }, (_, i) => ({ ...valid.fieldCandidates[0], candidateId: `c${i}` })) })).toThrow("CAPTURE_INVALID_CANDIDATES"); });
  it("does not carry actor, tenant, action, route or persistence directives", () => { const value = envelope(); expect(value).not.toHaveProperty("organizationId"); expect(value).not.toHaveProperty("actorId"); expect(value).not.toHaveProperty("actionName"); });
});

describe("orchestrator", () => {
  it("creates one batch draft plan for multiple fields", async () => { const result = await orchestrator().process(envelope([{ fieldId: "customer.phone", value: "0532 111 22 33" }, { fieldId: "customer.email", value: "INFO@ATLAS.COM" }]), context); expect(result.status).toBe("DRAFT_READY"); expect(result.draftOperations).toHaveLength(2); expect(result.resolvedCandidates[1]?.normalizedValue).toBe("info@atlas.com"); expect(renderTurkishDelta(result.delta)).toBe("Telefon eklendi. E-posta eklendi."); });
  it("does not silently overwrite a conflicting currency", async () => { const result = await orchestrator(resolved({ currency: "TRY" })).process(envelope([{ fieldId: "customer.currency", value: "eur" }]), context); expect(result.draftOperations).toEqual([]); expect(result.resolvedCandidates[0]?.conflictStatus).toBe("CONFIRMATION_REQUIRED"); expect(result.delta.pendingConfirmation[0]?.previousValue).toBe("TRY"); });
  it("auto-drafts a missing high confidence field, rejects invented/read-only fields and preserves mixed batches", async () => { const result = await orchestrator().process(envelope([{ fieldId: "customer.phone", value: "0532" }, { fieldId: "customer.status", value: "ACTIVE" }, { fieldId: "customer.invented", value: "x" }]), context); expect(result.draftOperations.map((item) => item.fieldId)).toEqual(["customer.phone"]); expect(result.unresolvedCandidates.map((item) => item.status)).toEqual(["READ_ONLY", "UNKNOWN"]); });
  it("blocks all handoff on ambiguous entity and is idempotent", async () => { const provider: EntityResolutionProvider = { entityType: "customer", async resolve(): Promise<CaptureEntityResolution> { return { status: "AMBIGUOUS", entityType: "customer", reference: null, candidates: [{ reference: { organizationId: "org-1", entityType: "customer", entityId: "1" }, score: .5, evidence: [] }, { reference: { organizationId: "org-1", entityType: "customer", entityId: "2" }, score: .5, evidence: [] }], confidence: .5, evidence: [], reasonCodes: ["AMBIGUOUS"] }; } }; const runtime = orchestrator(provider); const first = await runtime.process(envelope(), context); const second = await runtime.process(envelope(), context); expect(first.draftOperations).toEqual([]); expect(first.userInteraction).toBe("CLARIFICATION"); expect(second.duplicate).toBe(true); });
  it("resolves tenant custom fields from the trusted registry", async () => { const custom = customerCustomDefinitionToField({ id: "cf-1", organizationId: "org-1", key: "region", label: "Bölge", description: null, valueType: "string", required: false, options: [], active: true }); const runtime = new UniversalCaptureOrchestrator({ fields: async () => [...CUSTOMER_BUILT_IN_FIELDS, custom], entityProviders: [resolved()] }); const result = await runtime.process(envelope([{ label: "Bölge", value: "Marmara" }]), context); expect(result, JSON.stringify(result)).toMatchObject({ draftOperations: [{ fieldId: "customer.custom.cf-1" }] }); });
  it("projects to a current writable surface and defers stale targets", async () => { const result = await orchestrator().process(envelope([{ fieldId: "customer.phone", value: "1" }, { fieldId: "customer.email", value: "a@b.com" }]), context); const values = new Map<string, unknown>(); const projection = projectToActiveSurface(result, { discover: (fieldId) => ({ token: fieldId, generation: 1, writable: true }), isCurrent: (token) => token === "customer.phone", set: (_token, fieldId, value) => { values.set(fieldId, value); } }); expect(projection.applied).toEqual(["customer.phone"]); expect(projection.deferred).toEqual(["customer.email"]); expect(values.get("customer.phone")).toBe("1"); });
});

describe("information maturity", () => {
  it("is deterministic and excludes inaccessible/system fields", () => { const input = { fields: CUSTOMER_BUILT_IN_FIELDS, values: { displayName: "Atlas", phone: "1" }, accessibleFieldIds: CUSTOMER_BUILT_IN_FIELDS.filter((field) => field.readable).map((field) => field.fieldId), metadata: { "customer.displayName": { category: "identity", weight: 3 }, "customer.phone": { category: "communication", weight: 2 } }, generatedAt: now }; const a = calculateInformationMaturity(input); const b = calculateInformationMaturity(input); expect(a).toEqual(b); expect(a.completedWeightedFields).toContain("customer.displayName"); expect(a.excludedFields).toContain("customer.status"); expect(a.unavailableFields).toContain("customer.organizationId"); });
});
