"use client";

import { useCallback, useEffect, useMemo, useState, type ReactNode } from "react";
import { getOrder, mutateOrder, type OrderRecord } from "@/lib/orders/orders-client";

const TRANSITIONS: Record<string, readonly string[]> = {
  DRAFT: ["PENDING_APPROVAL", "APPROVED", "CANCELLED"], PENDING_APPROVAL: ["APPROVED", "CANCELLED"], APPROVED: ["PLANNED", "CANCELLED"],
  PLANNED: ["IN_PRODUCTION", "ON_HOLD", "CANCELLED"], IN_PRODUCTION: ["READY", "ON_HOLD", "CANCELLED"], ON_HOLD: ["PLANNED"],
  READY: ["PARTIALLY_SHIPPED", "SHIPPED", "CANCELLED"], PARTIALLY_SHIPPED: ["SHIPPED", "CANCELLED"], SHIPPED: ["COMPLETED"], COMPLETED: [], CANCELLED: [],
};
const STATUS: Record<string, string> = { DRAFT: "Taslak", PENDING_APPROVAL: "Onay bekliyor", APPROVED: "Onaylandı", PLANNED: "Planlandı", IN_PRODUCTION: "Üretimde", ON_HOLD: "Beklemede", READY: "Hazır", PARTIALLY_SHIPPED: "Kısmen sevk edildi", SHIPPED: "Sevk edildi", COMPLETED: "Tamamlandı", CANCELLED: "İptal edildi" };
const EXCEPTIONS = ["CUSTOMER_HOLD_REQUEST", "PRODUCTION_STOPPED", "QUALITY_ISSUE", "SUPPLY_DELAY", "PAYMENT_HOLD", "SHIPMENT_DELAYED", "CUSTOMER_ADDRESS_CHANGED", "OTHER"] as const;
const EXCEPTION: Record<string, string> = { CUSTOMER_HOLD_REQUEST: "Müşteri bekletme talebi", PRODUCTION_STOPPED: "Üretim durdu", QUALITY_ISSUE: "Kalite sorunu", SUPPLY_DELAY: "Tedarik gecikmesi", PAYMENT_HOLD: "Ödeme blokesi", SHIPMENT_DELAYED: "Sevkiyat gecikti", CUSTOMER_ADDRESS_CHANGED: "Müşteri adresi değişti", OTHER: "Diğer" };
const CHANGE: Record<string, string> = { QUANTITY_CHANGED: "Miktar değişikliği", DEADLINE_CHANGED: "Teslim tarihi değişikliği", ITEM_REMOVED: "Kalem silme", ITEM_ADDED: "Kalem ekleme" };
const inputClass = "w-full rounded-xl border border-white/[.1] bg-white/[.04] px-3 py-2.5 text-sm text-[#EDE7D9] outline-none focus:border-[#34e6cf]/45";

export function OrderActionSurface({ orderId, onReady, onFailure }: { orderId: string; onReady?: () => void; onFailure?: () => void }) {
  const [order, setOrder] = useState<OrderRecord | null>(null); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  const [quantity, setQuantity] = useState(""); const [quantityItem, setQuantityItem] = useState(""); const [quantityReason, setQuantityReason] = useState("");
  const [deadline, setDeadline] = useState(""); const [deadlineReason, setDeadlineReason] = useState(""); const [removeItem, setRemoveItem] = useState(""); const [removeReason, setRemoveReason] = useState("");
  const [exceptionCategory, setExceptionCategory] = useState(EXCEPTIONS[0]); const [exceptionNote, setExceptionNote] = useState(""); const [statusReason, setStatusReason] = useState(""); const [cancelReason, setCancelReason] = useState("");
  const load = useCallback(async () => { const result = await getOrder(orderId); if (result.ok) { setOrder(result.data.order); setError(null); onReady?.(); } else { setError(result.error); onFailure?.(); } }, [onFailure, onReady, orderId]);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { if (order?.items[0]) { setQuantityItem((value) => value || order.items[0]!.id); setRemoveItem((value) => value || order.items[0]!.id); } }, [order]);
  const targets = useMemo(() => order ? (TRANSITIONS[order.status] ?? []).filter((value) => value !== "CANCELLED") : [], [order]);
  async function act(payload: Record<string, unknown>, reset?: () => void) { setBusy(true); setError(null); const result = await mutateOrder(orderId, payload); if (result.ok) { reset?.(); await load(); } else setError(result.error); setBusy(false); }
  if (!order && !error) return <p className="py-12 text-center text-sm text-[#7C7466]">Sipariş yükleniyor…</p>;
  if (!order) return <Message error={error ?? "Sipariş bulunamadı."} />;
  const canCancel = (TRANSITIONS[order.status] ?? []).includes("CANCELLED");
  return <div className="mx-auto max-w-5xl space-y-4 pb-8" data-order-action-surface={order.id}>
    <header className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs uppercase tracking-[.18em] text-[#7C7466]">Sipariş çalışma alanı</p><h2 className="mt-1 text-xl font-semibold text-[#EDE7D9]">{order.orderNumber}</h2><p className="mt-1 text-sm text-[#A79F91]">{order.customer?.displayName ?? "Müşteri"} · {formatDate(order.deadlineAt)}</p></div><Badge>{STATUS[order.status] ?? order.status}</Badge></header>
    {error ? <Message error={error} /> : null}
    <Card title="Sipariş kalemleri"><div className="space-y-2">{order.items.map((item) => <div className="grid grid-cols-[1fr_auto] gap-3 rounded-xl border border-white/[.06] bg-black/10 p-3" key={item.id}><div><p className="text-sm font-semibold text-[#EDE7D9]">{item.name}</p><p className="mt-1 text-xs text-[#7C7466]">{item.quantity} {item.unit ?? "birim"}</p></div><p className="text-sm text-[#C9BFA8]">{money(item.lineTotalCents, order.currency)}</p></div>)}</div></Card>
    <div className="grid gap-4 lg:grid-cols-2">
      <Card title="Miktar değişikliği"><form className="space-y-3" onSubmit={(e) => { e.preventDefault(); void act({ action: "revise", changeType: "QUANTITY_CHANGED", orderItemId: quantityItem, quantity: Number(quantity), reason: quantityReason }, () => { setQuantity(""); setQuantityReason(""); }); }}><Select label="Sipariş kalemi" value={quantityItem} set={setQuantityItem} options={order.items.map((item) => ({ value: item.id, label: item.name }))}/><Field label="Yeni miktar"><input aria-label="Yeni miktar" className={inputClass} min="0.001" required step="0.001" type="number" value={quantity} onChange={(e) => setQuantity(e.target.value)}/></Field><Field label="Sebep"><input aria-label="Miktar değişikliği sebebi" className={inputClass} value={quantityReason} onChange={(e) => setQuantityReason(e.target.value)}/></Field><Action disabled={busy || !quantityItem || Number(quantity) <= 0}>Miktarı güncelle</Action></form></Card>
      <Card title="Teslim tarihi değişikliği"><form className="space-y-3" onSubmit={(e) => { e.preventDefault(); void act({ action: "revise", changeType: "DEADLINE_CHANGED", deadlineAt: deadline ? new Date(`${deadline}T12:00:00`).toISOString() : null, reason: deadlineReason }, () => setDeadlineReason("")); }}><Field label="Yeni teslim tarihi (boşsa kaldırılır)"><input aria-label="Yeni teslim tarihi" className={inputClass} type="date" value={deadline} onChange={(e) => setDeadline(e.target.value)}/></Field><Field label="Sebep"><input aria-label="Teslim tarihi değişikliği sebebi" className={inputClass} value={deadlineReason} onChange={(e) => setDeadlineReason(e.target.value)}/></Field><Action disabled={busy}>Teslim tarihini güncelle</Action></form></Card>
      <Card title="Kalem silme"><form className="space-y-3" onSubmit={(e) => { e.preventDefault(); void act({ action: "revise", changeType: "ITEM_REMOVED", orderItemId: removeItem, reason: removeReason }, () => setRemoveReason("")); }}><Select label="Silinecek kalem" value={removeItem} set={setRemoveItem} options={order.items.map((item) => ({ value: item.id, label: item.name }))}/><Field label="Sebep"><input aria-label="Kalem silme sebebi" className={inputClass} value={removeReason} onChange={(e) => setRemoveReason(e.target.value)}/></Field><Action disabled={busy || !removeItem} danger>Kalemi sil</Action></form></Card>
      <Card title="İstisna kaydı"><form className="space-y-3" onSubmit={(e) => { e.preventDefault(); void act({ action: "exception", category: exceptionCategory, note: exceptionNote }, () => setExceptionNote("")); }}><Select label="Kategori" value={exceptionCategory} set={(value) => setExceptionCategory(value as typeof exceptionCategory)} options={EXCEPTIONS.map((value) => ({ value, label: EXCEPTION[value] }))}/><Field label="Not"><textarea aria-label="İstisna notu" className={`${inputClass} min-h-20`} value={exceptionNote} onChange={(e) => setExceptionNote(e.target.value)}/></Field><Action disabled={busy}>İstisna kaydet</Action></form></Card>
    </div>
    <Card title="Durum yönetimi"><Field label="Geçiş sebebi"><input aria-label="Durum geçişi sebebi" className={inputClass} value={statusReason} onChange={(e) => setStatusReason(e.target.value)}/></Field><div className="mt-3 flex flex-wrap gap-2">{targets.map((target) => <button className="rounded-xl border border-[#34e6cf]/25 bg-[#34e6cf]/10 px-3 py-2 text-xs font-semibold text-[#34e6cf] disabled:opacity-40" disabled={busy} key={target} onClick={() => void act({ toStatus: target, reason: statusReason }, () => setStatusReason(""))} type="button">{STATUS[target] ?? target}</button>)}{!targets.length && !canCancel ? <p className="text-sm text-[#7C7466]">Bu durumdan izin verilen başka bir geçiş yok.</p> : null}</div>{canCancel ? <form className="mt-4 flex flex-col gap-3 border-t border-white/[.07] pt-4 sm:flex-row sm:items-end" onSubmit={(e) => { e.preventDefault(); void act({ action: "cancel", reason: cancelReason }, () => setCancelReason("")); }}><div className="flex-1"><Field label="İptal sebebi"><input aria-label="İptal sebebi" className={inputClass} required value={cancelReason} onChange={(e) => setCancelReason(e.target.value)}/></Field></div><Action disabled={busy || !cancelReason.trim()} danger>Siparişi iptal et</Action></form> : null}</Card>
    <div className="grid gap-4 lg:grid-cols-3"><History title="Revizyon geçmişi" empty="Henüz revizyon yok" rows={[...order.revisions].reverse().map((row) => <HistoryRow key={row.id} title={`Revizyon ${row.revisionNumber} · ${CHANGE[row.changeType] ?? row.changeType}`} detail={row.reason ?? "Sebep belirtilmedi"} date={row.createdAt}><Snapshots before={row.beforeSnapshot} after={row.afterSnapshot}/></HistoryRow>)}/><History title="İstisna geçmişi" empty="Henüz istisna yok" rows={[...order.exceptions].reverse().map((row) => <HistoryRow key={row.id} title={EXCEPTION[row.category] ?? row.category} detail={row.note ?? "Not yok"} date={row.createdAt}/>)}/><History title="Durum geçmişi" empty="Henüz durum kaydı yok" rows={[...order.statusHistory].reverse().map((row) => <HistoryRow key={row.id} title={`${row.fromStatus ? STATUS[row.fromStatus] ?? row.fromStatus : "Başlangıç"} → ${STATUS[row.toStatus] ?? row.toStatus}`} detail={row.reason ?? "Sebep belirtilmedi"} date={row.createdAt}/>)}/></div>
  </div>;
}

function Card({ title, children }: { title: string; children: ReactNode }) { return <section className="rounded-[20px] border border-white/[.08] bg-white/[.035] p-4"><h3 className="mb-3 text-sm font-semibold text-[#EDE7D9]">{title}</h3>{children}</section>; }
function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="block text-xs font-medium text-[#A79F91]"><span className="mb-1.5 block">{label}</span>{children}</label>; }
function Select({ label, value, set, options }: { label: string; value: string; set: (value: string) => void; options: Array<{ value: string; label: string }> }) { return <Field label={label}><select aria-label={label} className={inputClass} value={value} onChange={(e) => set(e.target.value)}>{options.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></Field>; }
function Action({ children, disabled, danger }: { children: ReactNode; disabled: boolean; danger?: boolean }) { return <button className={`rounded-xl px-4 py-2.5 text-sm font-bold disabled:opacity-40 ${danger ? "border border-[#f16a7a]/30 bg-[#f16a7a]/10 text-[#f16a7a]" : "bg-[#34e6cf] text-[#14120F]"}`} disabled={disabled} type="submit">{children}</button>; }
function Badge({ children }: { children: ReactNode }) { return <span className="rounded-full border border-[#C9BFA8]/20 bg-[#C9BFA8]/10 px-3 py-1.5 text-xs font-semibold text-[#C9BFA8]">{children}</span>; }
function Message({ error }: { error: string }) { return <p className="rounded-xl border border-[#f16a7a]/20 bg-[#f16a7a]/10 p-3 text-sm text-[#f16a7a]" role="alert">{error}</p>; }
function History({ title, empty, rows }: { title: string; empty: string; rows: ReactNode[] }) { return <Card title={title}>{rows.length ? <div className="space-y-3">{rows}</div> : <p className="text-xs text-[#7C7466]">{empty}</p>}</Card>; }
function HistoryRow({ title, detail, date, children }: { title: string; detail: string; date: string; children?: ReactNode }) { return <article className="border-b border-white/[.06] pb-3 last:border-0 last:pb-0"><p className="text-xs font-semibold text-[#EDE7D9]">{title}</p><p className="mt-1 text-xs text-[#A79F91]">{detail}</p>{children}<time className="mt-1 block text-[10px] text-[#7C7466]">{formatDate(date)}</time></article>; }
function Snapshots({ before, after }: { before: unknown; after: unknown }) { return <details className="mt-2 text-[11px] text-[#7C7466]"><summary className="cursor-pointer">Önce / sonra ayrıntısı</summary><pre className="mt-2 max-h-40 overflow-auto whitespace-pre-wrap rounded-lg bg-black/20 p-2">Önce: {JSON.stringify(before, null, 2)}{"\n"}Sonra: {JSON.stringify(after, null, 2)}</pre></details>; }
function formatDate(value: string | null) { return value ? new Intl.DateTimeFormat("tr-TR", { dateStyle: "medium", timeStyle: value.includes("T") ? "short" : undefined }).format(new Date(value)) : "Teslim tarihi yok"; }
function money(value: string, currency: string) { return new Intl.NumberFormat("tr-TR", { style: "currency", currency }).format(Number(value) / 100); }
