import { afterEach, describe, expect, it, vi } from "vitest";
import { supplierManagementConversationExtension } from "../supplier-management-conversation-extension";
const supplier = { id: "s1", displayName: "Mavi Tedarik", legalName: null, phone: null, email: null, taxNumber: "123", taxOffice: null, status: "ACTIVE" as const, updatedAt: "2026-01-01T00:00:00.000Z" };
describe("supplierManagementConversationExtension", () => { afterEach(() => vi.restoreAllMocks());
  it("opens list and create surfaces", async () => { await expect(supplierManagementConversationExtension.execute("tedarikçileri göster")).resolves.toMatchObject({ status: "HANDOFF", handoff: { outcomeCode: "SUPPLIER_LIST_OPENED" } }); await expect(supplierManagementConversationExtension.execute("yeni tedarikçi ekle")).resolves.toMatchObject({ status: "HANDOFF", handoff: { outcomeCode: "SUPPLIER_CREATE_OPENED" } }); });
  it("accepts the undiacritic speech-transcription variant", async () => { await expect(supplierManagementConversationExtension.execute("yeni tedarikci ekle")).resolves.toMatchObject({ status: "HANDOFF", handoff: { outcomeCode: "SUPPLIER_CREATE_OPENED" } }); });
  it("resolves a supplier by name", async () => { vi.stubGlobal("fetch", vi.fn().mockResolvedValue({ json: async () => ({ ok: true, data: { suppliers: [supplier], count: 1 } }) })); await expect(supplierManagementConversationExtension.execute("Mavi Tedarik tedarikçisini aç")).resolves.toMatchObject({ status: "HANDOFF", handoff: { outcomeCode: "SUPPLIER_PERFORMANCE_OPENED", entityResolution: "RESOLVED" } }); });
  it("reports not found without navigation", async () => { vi.stubGlobal("fetch", vi.fn().mockResolvedValue({ json: async () => ({ ok: true, data: { suppliers: [supplier], count: 1 } }) })); await expect(supplierManagementConversationExtension.execute("Yok Tedarik tedarikçisini aç")).resolves.toMatchObject({ status: "HANDOFF", handoff: { outcomeCode: "SUPPLIER_NOT_FOUND", entityResolution: "NOT_FOUND", navigationRequested: false } }); });
});
