/**
 * Minimal CalDAV client for iCloud Calendar (RFC 4791 + RFC 4918 WebDAV),
 * scoped to exactly what this operation needs: discover a user's calendar
 * collections, then read events in an arbitrary time range. No write.
 *
 * ACCESS METHOD, PROVEN (not guessed) from Apple's own support
 * documentation before any of this was written:
 *   - support.apple.com/en-us/121539 ("Access your iCloud Mail, Calendar,
 *     and Contacts in third-party apps"): third-party apps authorize either
 *     via a closed, Apple-vetted "authorize with your Apple Account" flow
 *     ("supported third-party application", no public developer
 *     registration/OAuth client-id process exists for it — not something
 *     METRIX can enroll in) or, when that isn't supported, an app-specific
 *     password.
 *   - support.apple.com/en-us/102654: app-specific passwords require the
 *     Apple Account to have two-factor authentication, are generated by the
 *     user themselves at account.apple.com, and are independently
 *     revocable (never the primary Apple Account password).
 *   - CalDAV (RFC 4791) is iCloud Calendar's only third-party read/write
 *     protocol; authentication is HTTP Basic (Apple ID + app-specific
 *     password) over TLS.
 * There is no public iCloud Calendar REST API and no OAuth scope system for
 * it — CalDAV + app-specific password is the sole practical, documented
 * path for a server-side app like METRIX. This module never hard-codes a
 * per-account host: the partition host (pNN-caldav.icloud.com) is
 * discovered per RFC 4791/RFC 5397 via current-user-principal and
 * calendar-home-set, starting only from the well-known caldav.icloud.com.
 */

const CALDAV_ENTRY = "https://caldav.icloud.com";

function basicAuthHeader(appleId: string, appSpecificPassword: string): string {
  return `Basic ${Buffer.from(`${appleId}:${appSpecificPassword}`, "utf8").toString("base64")}`;
}

async function davRequest(url: string, method: "PROPFIND" | "REPORT", body: string, appleId: string, appSpecificPassword: string, depth: "0" | "1"): Promise<{ status: number; text: string }> {
  const response = await fetch(url, {
    method,
    headers: {
      Authorization: basicAuthHeader(appleId, appSpecificPassword),
      "Content-Type": "application/xml; charset=utf-8",
      Depth: depth,
    },
    body,
  });
  const text = await response.text();
  return { status: response.status, text };
}

// Namespace-agnostic tag text extraction (d:href, D:href, href all match) —
// iCloud's multistatus XML is well-formed and predictable enough that a
// small, tightly-scoped regex is correct here without pulling in an XML DOM
// dependency for a handful of known tags.
function extractTagValues(xml: string, tag: string): string[] {
  const re = new RegExp(`<(?:[a-zA-Z0-9]+:)?${tag}(?:\\s[^>]*)?>([\\s\\S]*?)<\\/(?:[a-zA-Z0-9]+:)?${tag}>`, "gi");
  const out: string[] = [];
  let match: RegExpExecArray | null;
  while ((match = re.exec(xml))) out.push(match[1].trim());
  return out;
}

function resolveHref(href: string, baseUrl: string): string {
  return href.startsWith("http") ? href : new URL(href, baseUrl).toString();
}

// Every multistatus response also carries the requested resource's own
// <response><href> (e.g. "/" for the entry-point request) alongside the
// property we actually asked for — extractTagValues alone would grab that
// outer href first. This narrows to the href nested specifically inside the
// named property element (current-user-principal / calendar-home-set).
function extractNestedHref(xml: string, containerTag: string): string | undefined {
  const container = new RegExp(`<(?:[a-zA-Z0-9]+:)?${containerTag}(?:\\s[^>]*)?>([\\s\\S]*?)<\\/(?:[a-zA-Z0-9]+:)?${containerTag}>`, "i").exec(xml);
  if (!container) return undefined;
  return extractTagValues(container[1], "href")[0];
}

export type CalDAVDiscoveryResult =
  | { readonly status: "OK"; readonly principalUrl: string; readonly homeSetUrl: string; readonly calendarUrls: readonly string[] }
  | { readonly status: "AUTH_REQUIRED" }
  | { readonly status: "UNAVAILABLE"; readonly detail: string };

/**
 * Full discovery: current-user-principal → calendar-home-set → enumerate
 * calendar collections under the home set. Run once at connect time (its
 * result is cached on IcloudConnection) — see listCalendarCollections for
 * the cheaper per-read re-enumeration that reuses the cached home set URL.
 */
export async function discoverCalDAVHome(appleId: string, appSpecificPassword: string): Promise<CalDAVDiscoveryResult> {
  const principalBody = `<?xml version="1.0" encoding="utf-8"?><D:propfind xmlns:D="DAV:"><D:prop><D:current-user-principal/></D:prop></D:propfind>`;
  const principalRes = await davRequest(`${CALDAV_ENTRY}/`, "PROPFIND", principalBody, appleId, appSpecificPassword, "0");
  if (principalRes.status === 401) return { status: "AUTH_REQUIRED" };
  if (principalRes.status >= 400) return { status: "UNAVAILABLE", detail: `CALDAV_PRINCIPAL_${principalRes.status}` };
  const principalHref = extractNestedHref(principalRes.text, "current-user-principal");
  if (!principalHref) return { status: "UNAVAILABLE", detail: "CALDAV_NO_PRINCIPAL" };
  const principalUrl = resolveHref(principalHref, CALDAV_ENTRY);

  const homeSetRes = await davRequest(principalUrl, "PROPFIND", homeSetBody(), appleId, appSpecificPassword, "0");
  if (homeSetRes.status === 401) return { status: "AUTH_REQUIRED" };
  if (homeSetRes.status >= 400) return { status: "UNAVAILABLE", detail: `CALDAV_HOMESET_${homeSetRes.status}` };
  const homeHref = extractNestedHref(homeSetRes.text, "calendar-home-set");
  if (!homeHref) return { status: "UNAVAILABLE", detail: "CALDAV_NO_HOMESET" };
  const homeSetUrl = resolveHref(homeHref, principalUrl);

  const collections = await listCalendarCollections(appleId, appSpecificPassword, homeSetUrl);
  if (collections.status !== "OK") return collections;
  return { status: "OK", principalUrl, homeSetUrl, calendarUrls: collections.calendarUrls };
}

function homeSetBody(): string {
  return `<?xml version="1.0" encoding="utf-8"?><D:propfind xmlns:D="DAV:" xmlns:C="urn:ietf:params:xml:ns:caldav"><D:prop><C:calendar-home-set/></D:prop></D:propfind>`;
}

export type CalDAVCollectionsResult =
  | { readonly status: "OK"; readonly calendarUrls: readonly string[] }
  | { readonly status: "AUTH_REQUIRED" }
  | { readonly status: "UNAVAILABLE"; readonly detail: string };

/**
 * Cheaper per-read re-enumeration: one PROPFIND (Depth:1) on the already-
 * known home set URL, skipping the principal lookup. Re-run on every range
 * read (never trusted from a stale cache) so a calendar the user adds or
 * removes on their device is reflected without reconnecting.
 */
export async function listCalendarCollections(appleId: string, appSpecificPassword: string, homeSetUrl: string): Promise<CalDAVCollectionsResult> {
  const body = `<?xml version="1.0" encoding="utf-8"?><D:propfind xmlns:D="DAV:" xmlns:C="urn:ietf:params:xml:ns:caldav"><D:prop><D:resourcetype/><D:displayname/></D:prop></D:propfind>`;
  const res = await davRequest(homeSetUrl, "PROPFIND", body, appleId, appSpecificPassword, "1");
  if (res.status === 401) return { status: "AUTH_REQUIRED" };
  if (res.status >= 400) return { status: "UNAVAILABLE", detail: `CALDAV_CALENDARS_${res.status}` };

  const blocks = res.text.split(/<(?:[a-zA-Z0-9]+:)?response(?:\s[^>]*)?>/i).slice(1);
  const calendarUrls: string[] = [];
  for (const block of blocks) {
    const isCalendarCollection = /resourcetype/i.test(block) && /<(?:[a-zA-Z0-9]+:)?calendar\b/i.test(block);
    const href = extractTagValues(block, "href")[0];
    if (!isCalendarCollection || !href) continue;
    // Exclude Apple's special-purpose scheduling collections — not a real
    // user calendar, never a source of narrated/Workspace events.
    if (/\/(inbox|outbox|notification)\/?(?:$|")/i.test(href)) continue;
    calendarUrls.push(resolveHref(href, homeSetUrl));
  }
  return { status: "OK", calendarUrls };
}

export type CalDAVEventRecord = {
  readonly uid: string;
  readonly calendarUrl: string;
  readonly summary: string;
  readonly description: string;
  readonly startAt: string;
  readonly endAt: string;
  readonly allDay: boolean;
  readonly status: "CONFIRMED" | "CANCELLED";
};

export type CalDAVRangeQueryResult =
  | { readonly status: "OK"; readonly events: readonly CalDAVEventRecord[] }
  | { readonly status: "AUTH_REQUIRED" }
  | { readonly status: "UNAVAILABLE"; readonly detail: string };

function toICSTimestamp(date: Date): string {
  return date.toISOString().replace(/[-:]/g, "").replace(/\.\d{3}Z$/, "Z");
}

/**
 * REPORT (calendar-query, RFC 4791 §7.8) with a VEVENT time-range filter,
 * against every given calendar collection. One collection failing does not
 * fail the whole read — its events are simply absent, same additive-
 * degradation rule the rest of the calendar federation already follows;
 * only AUTH_REQUIRED (credential itself is bad) or every collection failing
 * is reported as a real failure.
 */
export async function queryEventsInRange(input: { readonly appleId: string; readonly appSpecificPassword: string; readonly calendarUrls: readonly string[]; readonly rangeStart: Date; readonly rangeEnd: Date }): Promise<CalDAVRangeQueryResult> {
  if (input.calendarUrls.length === 0) return { status: "OK", events: [] };
  const body = `<?xml version="1.0" encoding="utf-8"?><C:calendar-query xmlns:D="DAV:" xmlns:C="urn:ietf:params:xml:ns:caldav"><D:prop><D:getetag/><C:calendar-data/></D:prop><C:filter><C:comp-filter name="VCALENDAR"><C:comp-filter name="VEVENT"><C:time-range start="${toICSTimestamp(input.rangeStart)}" end="${toICSTimestamp(input.rangeEnd)}"/></C:comp-filter></C:comp-filter></C:filter></C:calendar-query>`;

  const events: CalDAVEventRecord[] = [];
  let sawAuthRequired = false;
  let failureCount = 0;
  for (const calendarUrl of input.calendarUrls) {
    const res = await davRequest(calendarUrl, "REPORT", body, input.appleId, input.appSpecificPassword, "1");
    if (res.status === 401) { sawAuthRequired = true; continue; }
    if (res.status >= 400) { failureCount += 1; continue; }
    for (const icsBlock of extractTagValues(res.text, "calendar-data")) {
      events.push(...parseICSEvents(decodeXmlEntities(icsBlock), calendarUrl));
    }
  }
  if (sawAuthRequired && events.length === 0 && failureCount === 0) return { status: "AUTH_REQUIRED" };
  if (failureCount === input.calendarUrls.length) return { status: "UNAVAILABLE", detail: "CALDAV_ALL_CALENDARS_FAILED" };
  return { status: "OK", events };
}

function decodeXmlEntities(text: string): string {
  return text.replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/&quot;/g, '"').replace(/&apos;/g, "'").replace(/&amp;/g, "&");
}

function unfoldICS(text: string): string {
  return text.replace(/\r\n/g, "\n").replace(/\n[ \t]/g, "");
}

function unescapeICSText(value: string): string {
  return value.replace(/\\n/gi, "\n").replace(/\\,/g, ",").replace(/\\;/g, ";").replace(/\\\\/g, "\\");
}

/**
 * Converts a wall-clock date/time in an IANA zone to a UTC Date using only
 * the ICU data Intl already carries — no bundled timezone database/
 * dependency needed, and DST-correct because it asks the real ICU rules for
 * that exact instant's offset rather than a fixed offset table.
 */
function zonedWallTimeToUTC(year: number, month: number, day: number, hour: number, minute: number, second: number, timeZone: string): Date {
  const utcGuess = Date.UTC(year, month - 1, day, hour, minute, second);
  const formatter = new Intl.DateTimeFormat("en-US", { timeZone, hourCycle: "h23", year: "numeric", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit", second: "2-digit" });
  const parts: Record<string, string> = {};
  for (const part of formatter.formatToParts(new Date(utcGuess))) parts[part.type] = part.value;
  const asIfUTC = Date.UTC(Number(parts.year), Number(parts.month) - 1, Number(parts.day), Number(parts.hour), Number(parts.minute), Number(parts.second));
  return new Date(utcGuess - (asIfUTC - utcGuess));
}

function parseICSDateTime(value: string, tzid: string | undefined): { readonly iso: string; readonly allDay: boolean } {
  const year = Number(value.slice(0, 4));
  const month = Number(value.slice(4, 6));
  const day = Number(value.slice(6, 8));
  if (/^\d{8}$/.test(value)) return { iso: new Date(Date.UTC(year, month - 1, day)).toISOString(), allDay: true };

  const hour = Number(value.slice(9, 11));
  const minute = Number(value.slice(11, 13));
  const second = Number(value.slice(13, 15) || "0");
  if (value.endsWith("Z")) return { iso: new Date(Date.UTC(year, month - 1, day, hour, minute, second)).toISOString(), allDay: false };
  if (tzid) {
    try {
      return { iso: zonedWallTimeToUTC(year, month, day, hour, minute, second, tzid).toISOString(), allDay: false };
    } catch {
      // Unknown/invalid TZID — fall through to the floating-time best effort below.
    }
  }
  // Floating local time with neither Z nor a resolvable TZID (rare for
  // iCloud in practice): best-effort as UTC rather than refusing the event.
  return { iso: new Date(Date.UTC(year, month - 1, day, hour, minute, second)).toISOString(), allDay: false };
}

/** One VEVENT's raw property lines, keyed by name (already unfolded). */
function parseEventProps(block: string): Record<string, { readonly params: string; readonly value: string }> {
  const props: Record<string, { params: string; value: string }> = {};
  for (const line of block.split("\n")) {
    if (!line.trim()) continue;
    const separatorIndex = line.indexOf(":");
    if (separatorIndex === -1) continue;
    const left = line.slice(0, separatorIndex);
    const value = line.slice(separatorIndex + 1);
    const [name, ...paramParts] = left.split(";");
    if (!name) continue;
    props[name.toUpperCase()] = { params: paramParts.join(";"), value };
  }
  return props;
}

function tzidOf(prop: { readonly params: string } | undefined): string | undefined {
  return prop ? /TZID=([^;:]+)/i.exec(prop.params)?.[1] : undefined;
}

function parseICSEvents(icsRaw: string, calendarUrl: string): CalDAVEventRecord[] {
  const ics = unfoldICS(icsRaw);
  const blocks = ics.match(/BEGIN:VEVENT[\s\S]*?END:VEVENT/g) ?? [];
  const events: CalDAVEventRecord[] = [];
  for (const block of blocks) {
    const props = parseEventProps(block);
    const uid = props.UID?.value.trim();
    const dtstart = props.DTSTART;
    if (!uid || !dtstart) continue;

    const start = parseICSDateTime(dtstart.value.trim(), tzidOf(dtstart));
    const end = props.DTEND
      ? parseICSDateTime(props.DTEND.value.trim(), tzidOf(props.DTEND))
      : { iso: new Date(new Date(start.iso).getTime() + 3_600_000).toISOString(), allDay: start.allDay };

    events.push({
      uid,
      calendarUrl,
      summary: props.SUMMARY ? unescapeICSText(props.SUMMARY.value.trim()) : "",
      description: props.DESCRIPTION ? unescapeICSText(props.DESCRIPTION.value.trim()).slice(0, 1000) : "",
      startAt: start.iso,
      endAt: end.iso,
      allDay: start.allDay,
      status: props.STATUS?.value.trim().toUpperCase() === "CANCELLED" ? "CANCELLED" : "CONFIRMED",
    });
  }
  return events;
}
