"use client";

import { useCallback, useEffect, useState, type FormEvent, type ReactNode } from "react";
import { archiveSupplier, getSupplier, updateSupplier, type SupplierRecord, type SupplierStatus } from "@/lib/suppliers/suppliers-client";

type Draft = { displayName: string; legalName: string; phone: string; email: string; website: string; taxNumber: string; taxOffice: string; metrixNote: string; riskNotes: string; status: SupplierStatus };
const EMPTY: Draft = { displayName: "", legalName: "", phone: "", email: "", website: "", taxNumber: "", taxOffice: "", metrixNote: "", riskNotes: "", status: "ACTIVE" };
const STATUS_LABELS: Record<SupplierStatus, string> = { ACTIVE: "Aktif", PASSIVE: "Pasif", ARCHIVED: "Arşivlendi" };
const inputClass = "w-full rounded-xl border border-white/[.1] bg-white/[.04] px-3 py-2.5 text-sm text-[#EDE7D9] outline-none focus:border-[#34e6cf]/45";

export function SupplierEditSurface({ supplierId, onReady, onFailure }: { supplierId: string; onReady?: () => void; onFailure?: () => void }) {
  const [supplier, setSupplier] = useState<SupplierRecord | null>(null); const [draft, setDraft] = useState<Draft>(EMPTY); const [error, setError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { const result = await getSupplier(supplierId); if (result.ok) { setSupplier(result.data.supplier); setDraft(toDraft(result.data.supplier)); setError(null); onReady?.(); } else { setError(result.error); onFailure?.(); } }, [onFailure, onReady, supplierId]);
  useEffect(() => { void load(); }, [load]);
  function set<K extends keyof Draft>(key: K, value: Draft[K]) { setDraft((current) => ({ ...current, [key]: value })); setNotice(null); }
  async function save(event: FormEvent) { event.preventDefault(); if (!draft.displayName.trim()) return; setBusy(true); setError(null); setNotice(null); const result = await updateSupplier(supplierId, draft); if (result.ok) { setSupplier(result.data.supplier); setDraft(toDraft(result.data.supplier)); setNotice("Tedarikçi bilgileri kaydedildi."); } else setError(result.error); setBusy(false); }
  async function archive() { setBusy(true); setError(null); setNotice(null); const result = await archiveSupplier(supplierId); if (result.ok) { await load(); setNotice("Tedarikçi arşivlendi."); } else setError(result.error); setBusy(false); }
  if (!supplier && !error) return <p className="py-12 text-center text-sm text-[#7C7466]">Tedarikçi yükleniyor…</p>;
  if (!supplier) return <Message error={error ?? "Tedarikçi bulunamadı."} />;
  return <div className="mx-auto max-w-5xl space-y-4 pb-8" data-supplier-edit-surface={supplier.id}>
    <header className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs uppercase tracking-[.18em] text-[#7C7466]">Tedarikçi çalışma alanı</p><h2 className="mt-1 text-xl font-semibold text-[#EDE7D9]">{supplier.displayName}</h2><p className="mt-1 text-sm text-[#A79F91]">Bilgiler, risk notları ve durum yönetimi</p></div><Badge>{STATUS_LABELS[supplier.status]}</Badge></header>
    {error ? <Message error={error} /> : null}{notice ? <p className="rounded-xl border border-[#34e6cf]/20 bg-[#34e6cf]/10 p-3 text-sm text-[#34e6cf]" role="status">{notice}</p> : null}
    <form className="space-y-4" onSubmit={(event) => void save(event)}>
      <Card title="Temel bilgiler"><div className="grid gap-3 md:grid-cols-2"><Input label="Tedarikçi adı" required value={draft.displayName} onChange={(value) => set("displayName", value)} /><Input label="Ticari unvan" value={draft.legalName} onChange={(value) => set("legalName", value)} /><Input label="Telefon" value={draft.phone} onChange={(value) => set("phone", value)} /><Input label="E-posta" type="email" value={draft.email} onChange={(value) => set("email", value)} /><Input label="Web sitesi" value={draft.website} onChange={(value) => set("website", value)} /><Input label="Vergi no" value={draft.taxNumber} onChange={(value) => set("taxNumber", value)} /><Input label="Vergi dairesi" value={draft.taxOffice} onChange={(value) => set("taxOffice", value)} /><Field label="Durum"><select aria-label="Durum" className={inputClass} value={draft.status} onChange={(event) => set("status", event.target.value as SupplierStatus)}>{Object.entries(STATUS_LABELS).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></Field></div></Card>
      <Card title="Operasyon notları"><div className="grid gap-3 md:grid-cols-2"><Field label="Not"><textarea aria-label="Not" className={`${inputClass} min-h-28`} value={draft.metrixNote} onChange={(event) => set("metrixNote", event.target.value)} /></Field><Field label="Risk notları"><textarea aria-label="Risk notları" className={`${inputClass} min-h-28`} value={draft.riskNotes} onChange={(event) => set("riskNotes", event.target.value)} /></Field></div></Card>
      <div className="flex flex-wrap items-center justify-between gap-3"><button className="rounded-xl border border-[#f16a7a]/30 bg-[#f16a7a]/10 px-4 py-2.5 text-sm font-bold text-[#f16a7a] disabled:opacity-40" disabled={busy || supplier.status === "ARCHIVED"} onClick={() => void archive()} type="button">Tedarikçiyi arşivle</button><div className="flex gap-2"><button className="rounded-xl border border-white/10 px-4 py-2.5 text-sm font-semibold text-[#C9BFA8] disabled:opacity-40" disabled={busy} onClick={() => { setDraft(toDraft(supplier)); setError(null); setNotice("Değişiklikler geri alındı."); }} type="button">Geri al</button><button className="rounded-xl bg-[#34e6cf] px-4 py-2.5 text-sm font-bold text-[#14120F] disabled:opacity-40" disabled={busy || !draft.displayName.trim()} type="submit">Değişiklikleri kaydet</button></div></div>
    </form>
  </div>;
}

function toDraft(supplier: SupplierRecord): Draft { return { displayName: supplier.displayName, legalName: supplier.legalName ?? "", phone: supplier.phone ?? "", email: supplier.email ?? "", website: supplier.website ?? "", taxNumber: supplier.taxNumber ?? "", taxOffice: supplier.taxOffice ?? "", metrixNote: supplier.metrixNote ?? "", riskNotes: supplier.riskNotes ?? "", status: supplier.status }; }
function Card({ title, children }: { title: string; children: ReactNode }) { return <section className="rounded-[20px] border border-white/[.08] bg-white/[.035] p-4"><h3 className="mb-3 text-sm font-semibold text-[#EDE7D9]">{title}</h3>{children}</section>; }
function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="block text-xs font-medium text-[#A79F91]"><span className="mb-1.5 block">{label}</span>{children}</label>; }
function Input({ label, value, onChange, required, type = "text" }: { label: string; value: string; onChange: (value: string) => void; required?: boolean; type?: string }) { return <Field label={label}><input aria-label={label} className={inputClass} required={required} type={type} value={value} onChange={(event) => onChange(event.target.value)} /></Field>; }
function Badge({ children }: { children: ReactNode }) { return <span className="rounded-full border border-[#C9BFA8]/20 bg-[#C9BFA8]/10 px-3 py-1.5 text-xs font-semibold text-[#C9BFA8]">{children}</span>; }
function Message({ error }: { error: string }) { return <p className="rounded-xl border border-[#f16a7a]/20 bg-[#f16a7a]/10 p-3 text-sm text-[#f16a7a]" role="alert">{error}</p>; }
