"use client";

import { useEffect, useMemo, useState } from "react";

type Financial = { revenueByCurrency: Record<string, string>; costByCurrency: Record<string, string>; measurable: boolean; profitCents: string | null; profitCurrency: string | null; marginPercent: number | null };
type User = { id: string; name: string | null; email: string; company: string | null; status: "ACTIVE" | "SUSPENDED"; subscription: { plan: string; status: string; renewsAt: string | null } | null; financial: Financial };
type App = { id: string; name: string; company: string; email: string; phone: string | null; note: string | null; createdAt: string };
type Invitation = { id: string; name: string | null; company: string; email: string; createdAt: string; expiresAt: string; status: "PENDING" | "ACCEPTED" | "EXPIRED" };
type Data = { kpis: { users: number } & Financial; users: User[]; applications: App[]; invitations: Invitation[] };

const money = (value: string, currency: string) => new Intl.NumberFormat("tr-TR", { style: "currency", currency }).format(Number(value) / 100);
const totals = (values: Record<string, string>) => Object.entries(values).map(([currency, value]) => money(value, currency)).join(" · ") || "—";
const date = (value: string) => new Date(value).toLocaleDateString("tr-TR");
const invitationLabel = (status: Invitation["status"]) => status === "ACCEPTED" ? "Kabul edildi" : status === "EXPIRED" ? "Süresi doldu" : "Gönderildi / Bekliyor";

export function AdminDashboard() {
  const [data, setData] = useState<Data | null>(null); const [denied, setDenied] = useState(false); const [tab, setTab] = useState("users"); const [q, setQ] = useState(""); const [selected, setSelected] = useState<User | null>(null); const [invite, setInvite] = useState(false); const [error, setError] = useState<string | null>(null);
  const load = () => fetch("/api/admin", { credentials: "include" }).then(async response => response.status === 403 ? setDenied(true) : setData(await response.json())).catch(() => setDenied(true));
  useEffect(() => { load(); }, []);
  const users = useMemo(() => data?.users.filter(user => `${user.name} ${user.company} ${user.email}`.toLowerCase().includes(q.toLowerCase())) ?? [], [data, q]);
  async function action(body: unknown) { setError(null); const response = await fetch("/api/admin/actions", { method: "POST", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); if (response.ok) { setInvite(false); setSelected(null); load(); } else { setError((await response.json().catch(() => null))?.code === "INVITATION_ALREADY_PENDING" ? "Bu e-posta için bekleyen bir davet zaten var." : "İşlem tamamlanamadı."); } }
  if (denied) return <main className="admin-denied"><h1>Erişim reddedildi</h1><p>Bu alan yalnız Platform Admin içindir.</p><a href="/login">Girişe dön</a></main>;
  if (!data) return <main className="admin-loading">Yükleniyor…</main>;
  const counts = { users: data.users.length, applications: data.applications.length, expiring: data.users.filter(user => user.subscription?.renewsAt && new Date(user.subscription.renewsAt).getTime() - Date.now() < 7 * 864e5).length, inactive: data.users.filter(user => user.status === "SUSPENDED").length };
  const filtered = users.filter(user => tab === "inactive" ? user.status === "SUSPENDED" : tab === "expiring" ? Boolean(user.subscription?.renewsAt && new Date(user.subscription.renewsAt).getTime() - Date.now() < 7 * 864e5) : true);
  return <main className="admin-shell"><header className="admin-header"><div><p>METRIX / PLATFORM</p><h1>Kontrol Merkezi</h1></div><button className="admin-primary" onClick={() => setInvite(true)}>Davet gönder</button></header>
    <section className="admin-kpis">{[["Toplam kullanıcı", String(data.kpis.users), "Gerçek müşteri hesapları"], ["Toplam maliyet", totals(data.kpis.costByCurrency), data.kpis.measurable ? "Ölçülebilen kullanım" : "Ölçülemeyen kullanım var"], ["Toplam gelir", totals(data.kpis.revenueByCurrency), "Kaydedilmiş ödemeler"], ["Kâr / zarar", data.kpis.profitCents && data.kpis.profitCurrency ? money(data.kpis.profitCents, data.kpis.profitCurrency) : "—", data.kpis.profitCents === null ? "Farklı para birimleri dönüştürülmez" : "Gelir − maliyet"], ["Kazanç oranı", data.kpis.marginPercent === null ? "—" : `%${data.kpis.marginPercent}`, data.kpis.marginPercent === null ? "Karşılaştırılabilir para birimi yok" : "(gelir − maliyet) / gelir"]].map(([label, value, note]) => <article key={label}><span>{label}</span><strong>{value}</strong><small>{note}</small></article>)}</section>
    <nav className="admin-tabs">{[["users", "Kullanıcılar"], ["applications", "Başvurular"], ["expiring", "Yakında Bitecek"], ["inactive", "Pasifler"]].map(([id, label]) => <button aria-current={tab === id ? "page" : undefined} onClick={() => setTab(id)} key={id}>{label}<b>{counts[id as keyof typeof counts]}</b></button>)}</nav>
    {error ? <p className="admin-action-error" role="alert">{error}</p> : null}
    {tab === "applications" ? <Applications values={data.applications} invitations={data.invitations} onReview={(id, decision) => action({ action: "reviewApplication", applicationId: id, decision })} /> : <section className="admin-table-wrap"><div className="admin-toolbar"><input value={q} onChange={event => setQ(event.target.value)} placeholder="Kullanıcı, firma veya e-posta ara" aria-label="Kullanıcı ara" /><span>{filtered.length} kayıt</span></div><div className="admin-table"><div className="admin-tr admin-th"><span>Kullanıcı / Firma</span><span>E-mail</span><span>Abonelik</span><span>Yenileme</span><span>Durum</span><span>Alınan</span><span>Kullanım</span><span>Kâr / Zarar</span><span>Aksiyon</span></div>{filtered.map(user => <button className="admin-tr" onClick={() => setSelected(user)} key={user.id}><span><b>{user.name ?? "—"}</b><small>{user.company ?? "Firma yok"}</small></span><span>{user.email}</span><span>{user.subscription?.plan ?? "—"}</span><span>{user.subscription?.renewsAt ? date(user.subscription.renewsAt) : "—"}</span><span><i className={user.status === "ACTIVE" ? "badge ok" : "badge off"}>{user.status === "ACTIVE" ? "Aktif" : "Pasif"}</i></span><span>{totals(user.financial.revenueByCurrency)}</span><span>{totals(user.financial.costByCurrency)}</span><span className={user.financial.profitCents === null ? "" : BigInt(user.financial.profitCents) >= 0n ? "profit" : "loss"}>{user.financial.profitCents && user.financial.profitCurrency ? money(user.financial.profitCents, user.financial.profitCurrency) : "—"}</span><span>›</span></button>)}</div></section>}
    {selected ? <Drawer user={selected} close={() => setSelected(null)} action={action} /> : null}{invite ? <Invite close={() => setInvite(false)} action={action} /> : null}
  </main>;
}

function Applications({ values, invitations, onReview }: { values: App[]; invitations: Invitation[]; onReview: (id: string, decision: string) => void }) { return <section className="admin-table-wrap"><div className="admin-table">{values.length ? values.map(application => <div className="application-row" key={application.id}><div><b>{application.name}</b><small>{application.company} · {application.email}</small></div><div><button onClick={() => onReview(application.id, "REJECTED")}>Reddet</button><button className="admin-primary" onClick={() => onReview(application.id, "APPROVED")}>Onayla</button></div></div>) : <p className="admin-empty">Bekleyen başvuru yok.</p>}<div className="admin-invitation-list"><p>DAVET DURUMU</p>{invitations.length ? invitations.map(invitation => <div className="application-row" key={invitation.id}><div><b>{invitation.name ?? invitation.email}</b><small>{invitation.company} · {invitation.email} · {date(invitation.createdAt)}</small></div><div><i className={`badge ${invitation.status === "ACCEPTED" ? "ok" : invitation.status === "EXPIRED" ? "off" : ""}`}>{invitationLabel(invitation.status)}</i><small>{invitation.status === "PENDING" ? `Son: ${date(invitation.expiresAt)}` : null}</small></div></div>) : <p className="admin-empty">Gönderilmiş davet yok.</p>}</div></div></section>; }
function Drawer({ user, close, action }: { user: User; close: () => void; action: (value: unknown) => void }) { const [amount, setAmount] = useState(""); return <aside className="admin-drawer" role="dialog" aria-modal="true" aria-label="Kullanıcı detay"><button className="drawer-close" onClick={close} aria-label="Detayı kapat">×</button><p>KULLANICI DETAYI</p><h2>{user.name ?? user.email}</h2><section><h3>GENEL</h3><dl><dt>Firma</dt><dd>{user.company ?? "—"}</dd><dt>E-mail</dt><dd>{user.email}</dd></dl></section><section><h3>ABONELİK</h3><dl><dt>Paket</dt><dd>{user.subscription?.plan ?? "—"}</dd><dt>Yenileme</dt><dd>{user.subscription?.renewsAt ? date(user.subscription.renewsAt) : "—"}</dd><dt>Durum</dt><dd>{user.status}</dd></dl></section><section><h3>FİNANSAL</h3><dl><dt>Alınan</dt><dd>{totals(user.financial.revenueByCurrency)}</dd><dt>Kullanım</dt><dd>{totals(user.financial.costByCurrency)}</dd><dt>Kâr / Zarar</dt><dd>{user.financial.profitCents && user.financial.profitCurrency ? money(user.financial.profitCents, user.financial.profitCurrency) : "Para birimi karşılaştırılamıyor"}</dd></dl></section><section><h3>İŞLEMLER</h3><div className="drawer-actions"><input aria-label="Ödeme tutarı kuruş" value={amount} onChange={event => setAmount(event.target.value)} placeholder="Ödeme tutarı (kuruş)" inputMode="numeric" /><button disabled={!/^\d+$/.test(amount)} onClick={() => action({ action: "payment", userId: user.id, amountCents: amount })}>Ödeme ekle</button><button onClick={() => action({ action: "renew", userId: user.id, plan: user.subscription?.plan ?? "Standard", renewsAt: new Date(Date.now() + 30 * 864e5).toISOString() })}>30 gün yenile</button><button className="danger" onClick={() => confirm(`${user.name ?? user.email} erişimi değiştirilsin mi?`) && action({ action: "setStatus", userId: user.id, status: user.status === "ACTIVE" ? "SUSPENDED" : "ACTIVE" })}>{user.status === "ACTIVE" ? "Erişimi durdur" : "Erişimi aç"}</button></div></section></aside>; }
function Invite({ close, action }: { close: () => void; action: (value: unknown) => void }) { const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [company, setCompany] = useState(""); return <div className="admin-modal" role="dialog" aria-modal="true" aria-label="Yeni davetiye"><form onSubmit={event => { event.preventDefault(); action({ action: "invite", name, email, company }); }}><button type="button" onClick={close} aria-label="Davetiye formunu kapat">×</button><p>YENİ DAVETİYE</p><h2>Kontrollü erişim</h2><label>Ad soyad<input required value={name} onChange={event => setName(event.target.value)} /></label><label>E-posta<input type="email" required value={email} onChange={event => setEmail(event.target.value)} /></label><label>Firma<input required value={company} onChange={event => setCompany(event.target.value)} /></label><button className="admin-primary">Davet gönder</button></form></div>; }
