"use client";
import { useEffect } from "react";

type PublicOffer = { id: string; title: string; customerName: string; amount: string | null; currency: string; customerNote: string | null; validUntil: string | null; paymentTerm: string | null; deliveryTerm: string | null; deliveryMethod: string | null; organizationName: string; items: Array<{ id: string; name: string; unit: string | null; quantity: string; unitPriceCents: string; lineTotalCents: string }> };
const money = (value: string | null, currency: string) => new Intl.NumberFormat("tr-TR", { style: "currency", currency }).format(Number(value ?? 0));
const cents = (value: string, currency: string) => new Intl.NumberFormat("tr-TR", { style: "currency", currency }).format(Number(value) / 100);

export function PublicOfferView({ offer, token }: { offer: PublicOffer; token: string }) {
  useEffect(() => {
    void fetch(`/api/public/offers/${encodeURIComponent(token)}/view`, { method: "POST" }).catch(() => undefined);
  }, [token]);
  return <main className="min-h-screen bg-[#0d0c0a] px-5 py-10 text-[#ede7d9]"><article className="mx-auto max-w-4xl overflow-hidden rounded-[2rem] border border-[#342e25] bg-[#171410] shadow-2xl"><header className="border-b border-[#342e25] px-8 py-9 sm:px-12"><p className="text-xs font-semibold tracking-[.32em] text-[#c89b54]">{offer.organizationName}</p><h1 className="mt-5 text-3xl font-semibold sm:text-5xl">{offer.title}</h1><p className="mt-3 text-[#a69d8d]">{offer.customerName} için hazırlanmıştır.</p></header><section className="px-8 py-8 sm:px-12"><div className="overflow-hidden rounded-2xl border border-[#342e25]"><div className="grid grid-cols-[1fr_auto] bg-[#211c16] px-5 py-3 text-xs uppercase tracking-wider text-[#988c79]"><span>Teklif kalemleri</span><span>Tutar</span></div>{offer.items.map((item) => <div className="grid grid-cols-[1fr_auto] gap-6 border-t border-[#342e25] px-5 py-5 first:border-t-0" key={item.id}><div><strong>{item.name}</strong><p className="mt-1 text-sm text-[#928979]">{item.quantity} {item.unit ?? "adet"} × {cents(item.unitPriceCents, offer.currency)}</p></div><strong>{cents(item.lineTotalCents, offer.currency)}</strong></div>)}</div><div className="mt-8 flex items-end justify-between border-t border-[#342e25] pt-7"><span className="text-sm text-[#9e9585]">Toplam teklif</span><strong className="text-3xl text-[#ddb56f]">{money(offer.amount, offer.currency)}</strong></div>{offer.customerNote ? <div className="mt-8 rounded-2xl bg-[#211c16] p-5"><h2 className="text-sm font-semibold">Not</h2><p className="mt-2 text-sm leading-6 text-[#bcb3a3]">{offer.customerNote}</p></div> : null}<dl className="mt-8 grid gap-4 text-sm sm:grid-cols-2">{offer.validUntil ? <div><dt className="text-[#887f71]">Geçerlilik tarihi</dt><dd className="mt-1">{new Intl.DateTimeFormat("tr-TR", { dateStyle: "long" }).format(new Date(offer.validUntil))}</dd></div> : null}{offer.paymentTerm ? <div><dt className="text-[#887f71]">Ödeme koşulu</dt><dd className="mt-1">{offer.paymentTerm}</dd></div> : null}{offer.deliveryTerm ? <div><dt className="text-[#887f71]">Teslim koşulu</dt><dd className="mt-1">{offer.deliveryTerm}</dd></div> : null}{offer.deliveryMethod ? <div><dt className="text-[#887f71]">Teslim yöntemi</dt><dd className="mt-1">{offer.deliveryMethod}</dd></div> : null}</dl></section></article></main>;
}
