// ─── Executive Knowledge Registry V1 ─────────────────────────────────────────
//
// Tüm knowledge key'lerin merkezi kaynağı.
// Prisma import yok. DB bağımlılığı yok. Saf TypeScript data + lookup.
// Sync: MemoryItemType, MemorySubjectType (prisma/schema.prisma) ile uyumlu string literal kullanıldı.

import {
  getBusinessModelDefinition as _getBusinessModelDefinition,
  resolveBusinessModelFamily,
} from "./executive-business-model-map";

import {
  getIndustryDefinition as _getIndustryDefinition,
  resolveIndustryFamily,
} from "./executive-industry-map";

import type {
  BusinessModelFamily,
  IndustryFamily,
  KnowledgeGapScore,
  KnowledgeKeyEntry,
} from "./executive-knowledge-registry.types";

// ─── Re-exports ───────────────────────────────────────────────────────────────

export { resolveIndustryFamily, resolveBusinessModelFamily };
export type { KnowledgeKeyEntry, KnowledgeGapScore, BusinessModelFamily, IndustryFamily };

// ─── Registry ─────────────────────────────────────────────────────────────────

export const EXECUTIVE_KNOWLEDGE_REGISTRY: KnowledgeKeyEntry[] = [

  // ══════════════════════════════════════════════════════════════════════════
  // LEVEL 1 — FOUNDATION (Kim olduğunu ve ne yaptığını anlatan kritik bilgiler)
  // ══════════════════════════════════════════════════════════════════════════

  {
    key: "company_name",
    aliases: [],
    label: "Şirket Adı",
    description: "Şirketin ticari adı",
    level: 1,
    memoryType: "FACT",
    subjectType: "ORGANIZATION",
    priority: "HIGH",
    industryApplicability: "ALL",
    businessModelApplicability: "ALL",
    requiredForDecision: ["GENERAL"],
    acquisitionModes: ["ONBOARDING", "CONVERSATION"],
    defaultConfidence: 0.98,
    defaultIsAssumption: false,
    suggestedQuestion: "Şirketinizin adı nedir?",
    reason: "Şirket adı bilinmeden kişiselleştirilmiş yönetim desteği verilemez.",
    hasExistingMemoryKey: false,
  },

  {
    key: "business_model",
    aliases: ["businessType"],
    label: "İş Modeli",
    description: "Şirketin nasıl para kazandığını tanımlayan model (TRADING, MANUFACTURING, SERVICE vb.)",
    level: 1,
    memoryType: "FACT",
    subjectType: "ORGANIZATION",
    priority: "HIGH",
    industryApplicability: "ALL",
    businessModelApplicability: "ALL",
    requiredForDecision: ["PRICING", "STRATEGY", "CASHFLOW", "SALES", "GENERAL"],
    acquisitionModes: ["ONBOARDING", "CONVERSATION", "INFERENCE"],
    defaultConfidence: 0.90,
    defaultIsAssumption: false,
    suggestedQuestion: "Şirketiniz ağırlıklı olarak nasıl para kazanıyor? (ticaret, üretim, hizmet, proje, abonelik vb.)",
    reason: "İş modeli bilinmeden tahsilat riski, fiyatlama ve strateji önerileri kişiselleştirilemez.",
    hasExistingMemoryKey: false,
    existingMemoryKeyName: "businessType",
  },

  {
    key: "industry",
    aliases: [],
    label: "Sektör",
    description: "Şirketin faaliyet gösterdiği ana sektör",
    level: 1,
    memoryType: "FACT",
    subjectType: "ORGANIZATION",
    priority: "HIGH",
    industryApplicability: "ALL",
    businessModelApplicability: "ALL",
    requiredForDecision: ["PRICING", "OPERATIONS", "STRATEGY", "GENERAL"],
    acquisitionModes: ["ONBOARDING", "CONVERSATION", "INFERENCE"],
    defaultConfidence: 0.95,
    defaultIsAssumption: false,
    suggestedQuestion: "Hangi sektörde faaliyet gösteriyorsunuz?",
    reason: "Sektör bilinmeden benchmark, risk ve operasyon önerileri kişiselleştirilemez.",
    hasExistingMemoryKey: true,
    existingMemoryKeyName: "industry",
  },

  {
    key: "sub_industry",
    aliases: [],
    label: "Alt Sektör",
    description: "Sektör içindeki spesifik niş veya alt alan",
    level: 1,
    memoryType: "FACT",
    subjectType: "ORGANIZATION",
    priority: "MEDIUM",
    industryApplicability: "ALL",
    businessModelApplicability: "ALL",
    requiredForDecision: ["GENERAL"],
    acquisitionModes: ["ONBOARDING", "CONVERSATION"],
    defaultConfidence: 0.88,
    defaultIsAssumption: false,
    suggestedQuestion: "Sektörünüz içinde daha spesifik bir alan var mı? (ör. medikal cihaz, organik gıda, kurumsal danışmanlık)",
    reason: "Alt sektör bilindiğinde sektör önerilerinin isabeti artar.",
    hasExistingMemoryKey: false,
  },

  {
    key: "primary_products_services",
    aliases: [],
    label: "Ana Ürün / Hizmet",
    description: "Şirketin sunduğu başlıca ürün veya hizmet kategorileri",
    level: 1,
    memoryType: "FACT",
    subjectType: "ORGANIZATION",
    priority: "HIGH",
    industryApplicability: "ALL",
    businessModelApplicability: "ALL",
    requiredForDecision: ["PRICING", "SALES", "GENERAL"],
    acquisitionModes: ["ONBOARDING", "CONVERSATION"],
    defaultConfidence: 0.92,
    defaultIsAssumption: false,
    suggestedQuestion: "Şirketinizin ana ürünü veya hizmeti nedir?",
    reason: "Ürün/hizmet bilinmeden fiyatlama ve satış önerileri gerçekçi olamaz.",
    hasExistingMemoryKey: false,
  },

  {
    key: "operating_region",
    aliases: ["city"],
    label: "Faaliyet Bölgesi",
    description: "Şirketin ağırlıklı olarak faaliyet gösterdiği şehir veya bölge",
    level: 1,
    memoryType: "FACT",
    subjectType: "ORGANIZATION",
    priority: "MEDIUM",
    industryApplicability: "ALL",
    businessModelApplicability: "ALL",
    requiredForDecision: ["OPERATIONS", "GENERAL"],
    acquisitionModes: ["ONBOARDING", "CONVERSATION"],
    defaultConfidence: 0.95,
    defaultIsAssumption: false,
    suggestedQuestion: "İşletmeniz ağırlıklı olarak hangi şehir veya bölgede faaliyet gösteriyor?",
    reason: "Bölge bilinmeden yerel pazar ve lojistik önerileri eksik kalır.",
    hasExistingMemoryKey: true,
    existingMemoryKeyName: "city",
  },

  {
    key: "owner_name",
    aliases: [],
    label: "Yönetici Adı",
    description: "İşletme sahibi veya karar yetkisindeki yöneticinin adı",
    level: 1,
    memoryType: "FACT",
    subjectType: "USER",
    priority: "HIGH",
    industryApplicability: "ALL",
    businessModelApplicability: "ALL",
    requiredForDecision: ["PERSONAL", "GENERAL"],
    acquisitionModes: ["ONBOARDING", "CONVERSATION"],
    defaultConfidence: 0.98,
    defaultIsAssumption: false,
    suggestedQuestion: "Sizi nasıl hitap etmemi istersiniz?",
    reason: "Yönetici adı bilinmeden kişiselleştirilmiş iletişim kurulamaz.",
    hasExistingMemoryKey: false,
  },

  {
    key: "owner_role",
    aliases: [],
    label: "Yönetici Rolü",
    description: "Yöneticinin şirketteki pozisyonu (sahip, CEO, genel müdür vb.)",
    level: 1,
    memoryType: "FACT",
    subjectType: "USER",
    priority: "MEDIUM",
    industryApplicability: "ALL",
    businessModelApplicability: "ALL",
    requiredForDecision: ["PERSONAL", "GENERAL"],
    acquisitionModes: ["ONBOARDING", "CONVERSATION"],
    defaultConfidence: 0.92,
    defaultIsAssumption: false,
    suggestedQuestion: "Şirketteki rolünüz nedir? (kurucu, CEO, genel müdür, ortak vb.)",
    reason: "Rol bilindiğinde kararların kapsamı ve otoritesi daha iyi değerlendirilebilir.",
    hasExistingMemoryKey: false,
  },

  {
    key: "primary_goal",
    aliases: ["first_goal", "top_goal"],
    label: "Ana Hedef",
    description: "Şirketin şu an için en önemli kısa ve orta vadeli hedefi",
    level: 1,
    memoryType: "STRATEGIC",
    subjectType: "ORGANIZATION",
    priority: "HIGH",
    industryApplicability: "ALL",
    businessModelApplicability: "ALL",
    requiredForDecision: ["STRATEGY", "SALES", "CASHFLOW", "GENERAL"],
    acquisitionModes: ["ONBOARDING", "CONVERSATION"],
    defaultConfidence: 0.90,
    defaultIsAssumption: false,
    suggestedQuestion: "Şu anda işletmeniz için en önemli hedef nedir?",
    reason: "Hedef bilinmeden öneriler önceliğe bağlanamaz.",
    hasExistingMemoryKey: true,
    existingMemoryKeyName: "top_goal",
  },

  {
    key: "primary_challenge",
    aliases: ["main_challenge"],
    label: "Ana Zorluk",
    description: "Şirketi şu an en çok zorlayan operasyonel veya stratejik problem",
    level: 1,
    memoryType: "PROCESS",
    subjectType: "ORGANIZATION",
    priority: "HIGH",
    industryApplicability: "ALL",
    businessModelApplicability: "ALL",
    requiredForDecision: ["STRATEGY", "OPERATIONS", "GENERAL"],
    acquisitionModes: ["ONBOARDING", "CONVERSATION"],
    defaultConfidence: 0.90,
    defaultIsAssumption: false,
    suggestedQuestion: "Şu anda en çok hangi konuda zorlanıyorsunuz?",
    reason: "Ana zorluk bilinmeden müdahale önerileri yüzeyde kalır.",
    hasExistingMemoryKey: true,
    existingMemoryKeyName: "main_challenge",
  },

  {
    key: "decision_style",
    aliases: ["decision_preference"],
    label: "Karar Tarzı",
    description: "Yöneticinin karar alırken tercih ettiği format ve hız (hızlı/analitik, sezgisel/veri, vb.)",
    level: 1,
    memoryType: "PREFERENCE",
    subjectType: "USER",
    priority: "HIGH",
    industryApplicability: "ALL",
    businessModelApplicability: "ALL",
    requiredForDecision: ["PERSONAL", "STRATEGY"],
    acquisitionModes: ["ONBOARDING", "CONVERSATION", "INFERENCE"],
    defaultConfidence: 0.75,
    defaultIsAssumption: true,
    suggestedQuestion: "Karar alırken nasıl bir bilgi formatı size daha çok yardımcı olur?",
    reason: "Karar tarzı bilinmeden öneri formatı ve detay seviyesi uyarlanamaz.",
    hasExistingMemoryKey: true,
    existingMemoryKeyName: "decision_preference",
  },

  {
    key: "response_length_preference",
    aliases: [],
    label: "Cevap Uzunluğu Tercihi",
    description: "Kullanıcının cevapların genel olarak kısa/öz mü yoksa detaylı mı olmasını istediğine dair kalıcı tercihi.",
    level: 1,
    memoryType: "PREFERENCE",
    subjectType: "USER",
    priority: "MEDIUM",
    industryApplicability: "ALL",
    businessModelApplicability: "ALL",
    requiredForDecision: ["PERSONAL"],
    acquisitionModes: ["CONVERSATION"],
    defaultConfidence: 0.9,
    defaultIsAssumption: false,
    suggestedQuestion: "Cevapların genelde kısa mı yoksa detaylı mı olmasını tercih edersin?",
    reason: "Kullanıcı cevap uzunluğunu açıkça belirtirse sonraki cevaplar buna göre ayarlanmalı.",
    hasExistingMemoryKey: false,
  },

  {
    key: "question_frequency_preference",
    aliases: [],
    label: "Soru Sıklığı Tercihi",
    description: "Kullanıcının karar öncesi netleştirme sorularının sıklığına dair kalıcı tercihi (az soru / daha çok soru).",
    level: 1,
    memoryType: "PREFERENCE",
    subjectType: "USER",
    priority: "MEDIUM",
    industryApplicability: "ALL",
    businessModelApplicability: "ALL",
    requiredForDecision: ["PERSONAL"],
    acquisitionModes: ["CONVERSATION"],
    defaultConfidence: 0.9,
    defaultIsAssumption: false,
    suggestedQuestion: "Karar vermeden önce sana daha az mı yoksa daha çok mu soru sormamı istersin?",
    reason: "Kullanıcı soru sıklığına dair açıkça tercih belirtirse sonraki turlerde buna göre davranılmalı.",
    hasExistingMemoryKey: false,
  },

  {
    key: "employee_count",
    aliases: ["team_size"],
    label: "Çalışan Sayısı",
    description: "Şirketteki aktif çalışan sayısı",
    level: 1,
    memoryType: "FACT",
    subjectType: "ORGANIZATION",
    priority: "HIGH",
    industryApplicability: "ALL",
    businessModelApplicability: "ALL",
    requiredForDecision: ["TEAM", "OPERATIONS", "HIRING"],
    acquisitionModes: ["ONBOARDING", "CONVERSATION"],
    defaultConfidence: 0.95,
    defaultIsAssumption: false,
    suggestedQuestion: "Şu anda kaç çalışanınız var?",
    reason: "Ekip büyüklüğü bilinmeden görev dağılımı, yönetim yükü ve büyüme kapasitesi değerlendirilemez.",
    hasExistingMemoryKey: true,
    existingMemoryKeyName: "team_size",
  },

  {
    key: "department_count",
    aliases: [],
    label: "Departman / Birim Sayısı",
    description: "Şirketteki aktif departman veya iş birimi sayısı",
    level: 1,
    memoryType: "FACT",
    subjectType: "ORGANIZATION",
    priority: "MEDIUM",
    industryApplicability: "ALL",
    businessModelApplicability: "ALL",
    requiredForDecision: ["TEAM", "OPERATIONS"],
    acquisitionModes: ["ONBOARDING", "CONVERSATION"],
    defaultConfidence: 0.90,
    defaultIsAssumption: false,
    suggestedQuestion: "Şirketinizde kaç farklı departman veya iş birimi var?",
    reason: "Departman yapısı bilinmeden koordinasyon ve sorumluluk önerileri eksik kalır.",
    hasExistingMemoryKey: false,
  },

  {
    key: "key_people",
    aliases: [],
    label: "Kilit Kişiler",
    description: "Şirkette kritik rol oynayan yönetici, ortak veya uzman isimleri",
    level: 1,
    memoryType: "FACT",
    subjectType: "ORGANIZATION",
    priority: "MEDIUM",
    industryApplicability: "ALL",
    businessModelApplicability: "ALL",
    requiredForDecision: ["TEAM", "GENERAL"],
    acquisitionModes: ["CONVERSATION"],
    defaultConfidence: 0.88,
    defaultIsAssumption: false,
    suggestedQuestion: "Şirkette kritik rol oynayan başka kişiler var mı? (ortak, kilit yönetici, uzman)",
    reason: "Kilit kişiler bilinmeden ekip ve devir riski değerlendirilemez.",
    hasExistingMemoryKey: false,
  },

  {
    key: "weekly_work_days",
    aliases: [],
    label: "Haftalık Çalışma Günü",
    description: "Şirketin haftada kaç gün aktif çalıştığı",
    level: 1,
    memoryType: "FACT",
    subjectType: "ORGANIZATION",
    priority: "LOW",
    industryApplicability: "ALL",
    businessModelApplicability: "ALL",
    requiredForDecision: ["OPERATIONS", "TEAM"],
    acquisitionModes: ["ONBOARDING", "CONVERSATION"],
    defaultConfidence: 0.90,
    defaultIsAssumption: false,
    suggestedQuestion: "Haftada kaç gün çalışıyorsunuz?",
    reason: "Çalışma günü bilinmeden kapasite ve ritim hesaplamaları yapılamaz.",
    hasExistingMemoryKey: false,
  },

  {
    key: "daily_work_hours",
    aliases: [],
    label: "Günlük Çalışma Saati",
    description: "Şirketin günlük ortalama çalışma süresi",
    level: 1,
    memoryType: "FACT",
    subjectType: "ORGANIZATION",
    priority: "LOW",
    industryApplicability: "ALL",
    businessModelApplicability: "ALL",
    requiredForDecision: ["OPERATIONS"],
    acquisitionModes: ["ONBOARDING", "CONVERSATION"],
    defaultConfidence: 0.90,
    defaultIsAssumption: false,
    suggestedQuestion: "Günlük ortalama kaç saat çalışıyorsunuz?",
    reason: "Günlük çalışma saati bilinmeden zaman bazlı kapasite planlaması yapılamaz.",
    hasExistingMemoryKey: false,
  },

  {
    key: "shift_count",
    aliases: [],
    label: "Vardiya Sayısı",
    description: "Günlük vardiya sayısı (tek, çift, üç vardiya vb.)",
    level: 1,
    memoryType: "FACT",
    subjectType: "ORGANIZATION",
    priority: "LOW",
    industryApplicability: ["URETIM", "LOJISTIK", "YEME_ICME", "SAGLIK", "GUVENLIK_TEMIZLIK"],
    businessModelApplicability: ["MANUFACTURING", "LOGISTICS", "HOSPITALITY", "WORKFORCE"],
    requiredForDecision: ["OPERATIONS"],
    acquisitionModes: ["CONVERSATION"],
    defaultConfidence: 0.88,
    defaultIsAssumption: false,
    suggestedQuestion: "Günlük kaç vardiyayla çalışıyorsunuz?",
    reason: "Vardiya sayısı bilinmeden üretim kapasitesi ve personel planlaması eksik kalır.",
    hasExistingMemoryKey: false,
  },

  {
    key: "seasonality",
    aliases: [],
    label: "Sezonluk Yapı",
    description: "İşin belirli aylara veya dönemlere göre nasıl değiştiği",
    level: 1,
    memoryType: "FACT",
    subjectType: "ORGANIZATION",
    priority: "MEDIUM",
    industryApplicability: ["TURIZM_KONAKLAMA", "YEME_ICME", "TARIM_HAYVANCILIK", "EGITIM", "PERAKENDE", "E_TICARET"],
    businessModelApplicability: "ALL",
    requiredForDecision: ["SALES", "OPERATIONS", "CASHFLOW"],
    acquisitionModes: ["ONBOARDING", "CONVERSATION"],
    defaultConfidence: 0.85,
    defaultIsAssumption: true,
    suggestedQuestion: "İşinizde belirgin bir mevsimsel dalgalanma var mı? Hangi dönemler yoğun, hangileri sakin?",
    reason: "Sezonluk yapı bilinmeden nakit planlaması ve kapasite kararları yanlış yapılır.",
    hasExistingMemoryKey: false,
  },

  {
    key: "last_month_revenue",
    aliases: [],
    label: "Geçen Ay Ciro",
    description: "Bir önceki ayın toplam geliri / cirosu",
    level: 1,
    memoryType: "FACT",
    subjectType: "ORGANIZATION",
    priority: "HIGH",
    industryApplicability: "ALL",
    businessModelApplicability: "ALL",
    requiredForDecision: ["SALES", "CASHFLOW", "PRICING", "STRATEGY"],
    acquisitionModes: ["CONVERSATION", "USER_CORRECTION"],
    defaultConfidence: 0.85,
    defaultIsAssumption: false,
    suggestedQuestion: "Geçen ay toplam cironuz ne kadardı?",
    reason: "Geçen ayın cirosu bilinmeden büyüme trendi, nakit durumu ve hedef gerçekçiliği değerlendirilemez.",
    hasExistingMemoryKey: false,
  },

  {
    key: "average_monthly_revenue",
    aliases: [],
    label: "Ortalama Aylık Ciro",
    description: "Son 3-6 aydaki ortalama aylık gelir",
    level: 1,
    memoryType: "FACT",
    subjectType: "ORGANIZATION",
    priority: "HIGH",
    industryApplicability: "ALL",
    businessModelApplicability: "ALL",
    requiredForDecision: ["PRICING", "CASHFLOW", "STRATEGY"],
    acquisitionModes: ["CONVERSATION", "USER_CORRECTION", "INFERENCE"],
    defaultConfidence: 0.80,
    defaultIsAssumption: true,
    suggestedQuestion: "Son birkaç aydaki ortalama aylık cirolara bakıldığında yaklaşık ne kadar?",
    reason: "Ortalama ciro bilinmeden nakit planlaması ve karlılık analizi temelsiz kalır.",
    hasExistingMemoryKey: false,
  },

  {
    key: "current_month_target_revenue",
    aliases: [],
    label: "Bu Ay Ciro Hedefi",
    description: "Cari ay için belirlenen gelir hedefi",
    level: 1,
    memoryType: "FACT",
    subjectType: "ORGANIZATION",
    priority: "HIGH",
    industryApplicability: "ALL",
    businessModelApplicability: "ALL",
    requiredForDecision: ["STRATEGY", "SALES"],
    acquisitionModes: ["CONVERSATION"],
    defaultConfidence: 0.90,
    defaultIsAssumption: false,
    suggestedQuestion: "Bu ay için belirlediğiniz ciro hedefiniz nedir?",
    reason: "Aylık hedef bilinmeden 'hedefe ulaşılır mı' sorusu cevaplanamaz.",
    hasExistingMemoryKey: false,
  },

  {
    key: "annual_target_revenue",
    aliases: [],
    label: "Yıllık Ciro Hedefi",
    description: "Cari yıl için belirlenen toplam gelir hedefi",
    level: 1,
    memoryType: "FACT",
    subjectType: "ORGANIZATION",
    priority: "MEDIUM",
    industryApplicability: "ALL",
    businessModelApplicability: "ALL",
    requiredForDecision: ["STRATEGY"],
    acquisitionModes: ["CONVERSATION"],
    defaultConfidence: 0.85,
    defaultIsAssumption: false,
    suggestedQuestion: "Bu yıl için toplam ciro hedefiniz var mı?",
    reason: "Yıllık hedef bilinmeden stratejik öncelik sıralaması yapılamaz.",
    hasExistingMemoryKey: false,
  },

  {
    key: "active_customer_count",
    aliases: [],
    label: "Aktif Müşteri Sayısı",
    description: "Şu anda aktif çalışılan müşteri veya hesap sayısı",
    level: 1,
    memoryType: "FACT",
    subjectType: "ORGANIZATION",
    priority: "HIGH",
    industryApplicability: "ALL",
    businessModelApplicability: "ALL",
    requiredForDecision: ["SALES", "COLLECTION", "OPERATIONS"],
    acquisitionModes: ["CONVERSATION", "IMPORT"],
    defaultConfidence: 0.85,
    defaultIsAssumption: false,
    suggestedQuestion: "Şu anda kaç aktif müşteriniz var?",
    reason: "Aktif müşteri sayısı bilinmeden büyüme, tahsilat ve kaynak planlaması yapılamaz.",
    hasExistingMemoryKey: false,
  },

  {
    key: "customer_type",
    aliases: ["primary_customer_type"],
    label: "Müşteri Tipi",
    description: "Müşterilerin profili: bireysel, kurumsal, kamu, karma vb.",
    level: 1,
    memoryType: "FACT",
    subjectType: "ORGANIZATION",
    priority: "HIGH",
    industryApplicability: "ALL",
    businessModelApplicability: "ALL",
    requiredForDecision: ["PRICING", "SALES", "COLLECTION", "CUSTOMER_CONFLICT"],
    acquisitionModes: ["ONBOARDING", "CONVERSATION"],
    defaultConfidence: 0.92,
    defaultIsAssumption: false,
    suggestedQuestion: "Müşterileriniz ağırlıklı olarak bireysel mi yoksa şirket mi?",
    reason: "Müşteri tipi fiyatlama, tahsilat riski ve iletişim stratejisi kararlarını doğrudan etkiler.",
    hasExistingMemoryKey: true,
    existingMemoryKeyName: "primary_customer_type",
  },

  {
    key: "largest_customer",
    aliases: [],
    label: "En Büyük Müşteri",
    description: "Ciro içinde en yüksek paya sahip müşteri veya hesap",
    level: 1,
    memoryType: "FACT",
    subjectType: "ORGANIZATION",
    priority: "MEDIUM",
    industryApplicability: "ALL",
    businessModelApplicability: "ALL",
    requiredForDecision: ["COLLECTION", "CUSTOMER_CONFLICT", "SALES"],
    acquisitionModes: ["CONVERSATION"],
    defaultConfidence: 0.88,
    defaultIsAssumption: false,
    suggestedQuestion: "Cironuzun önemli bir kısmını oluşturan en büyük müşteriniz var mı?",
    reason: "Büyük müşteri konsantrasyonu tahsilat ve risk yönetimi kararlarında belirleyicidir.",
    hasExistingMemoryKey: false,
  },

  {
    key: "monthly_fixed_cost",
    aliases: [],
    label: "Aylık Sabit Gider",
    description: "Maaş, kira, abonelik ve diğer sabit aylık giderlerin toplamı",
    level: 1,
    memoryType: "FACT",
    subjectType: "ORGANIZATION",
    priority: "HIGH",
    industryApplicability: "ALL",
    businessModelApplicability: "ALL",
    requiredForDecision: ["CASHFLOW", "PRICING", "OPERATIONS"],
    acquisitionModes: ["CONVERSATION", "USER_CORRECTION"],
    defaultConfidence: 0.82,
    defaultIsAssumption: false,
    suggestedQuestion: "Aylık sabit giderleriniz (maaş + kira + abonelikler) yaklaşık ne kadar?",
    reason: "Sabit maliyet bilinmeden başabaş noktası, karlılık ve nakit riski hesaplanamaz.",
    hasExistingMemoryKey: false,
  },

  {
    key: "cash_flow_status",
    aliases: ["cashflow_priority"],
    label: "Nakit Akışı Durumu",
    description: "Şu anki nakit akışının genel durumu ve öncelik seviyesi",
    level: 1,
    memoryType: "FACT",
    subjectType: "ORGANIZATION",
    priority: "HIGH",
    industryApplicability: "ALL",
    businessModelApplicability: "ALL",
    requiredForDecision: ["CASHFLOW", "GENERAL"],
    acquisitionModes: ["CONVERSATION", "INFERENCE"],
    defaultConfidence: 0.78,
    defaultIsAssumption: true,
    suggestedQuestion: "Nakit akışınız şu an rahat mı, gergin mi? Kısaca nasıl tanımlarsınız?",
    reason: "Nakit akışı durumu bilinmeden aciliyet ve likidite kararları verilemez.",
    hasExistingMemoryKey: true,
    existingMemoryKeyName: "cashflow_priority",
  },

  {
    key: "average_profitability",
    aliases: ["profitability_focus"],
    label: "Ortalama Karlılık",
    description: "Şirketin ortalama brüt veya net kar marjı",
    level: 1,
    memoryType: "FACT",
    subjectType: "ORGANIZATION",
    priority: "HIGH",
    industryApplicability: "ALL",
    businessModelApplicability: "ALL",
    requiredForDecision: ["PRICING", "CASHFLOW", "STRATEGY"],
    acquisitionModes: ["CONVERSATION", "USER_CORRECTION"],
    defaultConfidence: 0.75,
    defaultIsAssumption: true,
    suggestedQuestion: "Yaklaşık olarak kar marjınız ne kadar? (brüt veya net)",
    reason: "Karlılık bilinmeden fiyatlama, indirim ve büyüme kararları temelsiz kalır.",
    hasExistingMemoryKey: true,
    existingMemoryKeyName: "profitability_focus",
  },

  {
    key: "primary_risk",
    aliases: [],
    label: "Ana Risk",
    description: "Şirketin şu an karşı karşıya olduğu en kritik risk",
    level: 1,
    memoryType: "PROCESS",
    subjectType: "ORGANIZATION",
    priority: "HIGH",
    industryApplicability: "ALL",
    businessModelApplicability: "ALL",
    requiredForDecision: ["STRATEGY", "GENERAL"],
    acquisitionModes: ["ONBOARDING", "CONVERSATION"],
    defaultConfidence: 0.85,
    defaultIsAssumption: false,
    suggestedQuestion: "Şu an şirketiniz için en büyük risk ne?",
    reason: "Ana risk bilinmeden savunma ve önlem önerileri önceliklendirilemez.",
    hasExistingMemoryKey: false,
  },

  {
    key: "primary_bottleneck",
    aliases: ["main_bottleneck"],
    label: "Ana Darboğaz",
    description: "Şirkette büyümeyi veya verimliliği en çok kısıtlayan faktör",
    level: 1,
    memoryType: "PROCESS",
    subjectType: "ORGANIZATION",
    priority: "HIGH",
    industryApplicability: "ALL",
    businessModelApplicability: "ALL",
    requiredForDecision: ["STRATEGY", "OPERATIONS", "GENERAL"],
    acquisitionModes: ["ONBOARDING", "CONVERSATION", "INFERENCE"],
    defaultConfidence: 0.72,
    defaultIsAssumption: true,
    suggestedQuestion: "Şu an büyümenizi veya verimliliğinizi en çok kısıtlayan şey nedir?",
    reason: "Darboğaz bilinmeden müdahale kaynakları yanlış yere yönlendirilebilir.",
    hasExistingMemoryKey: true,
    existingMemoryKeyName: "main_bottleneck",
  },

  // ══════════════════════════════════════════════════════════════════════════
  // LEVEL 2 — OPERATIONAL (Şu anki operasyonel durumu gösteren bilgiler)
  // ══════════════════════════════════════════════════════════════════════════

  {
    key: "active_workload",
    aliases: [],
    label: "Aktif İş Yükü",
    description: "Şu anda devam eden iş, sipariş veya görev yoğunluğu",
    level: 2,
    memoryType: "FACT",
    subjectType: "ORGANIZATION",
    priority: "MEDIUM",
    industryApplicability: "ALL",
    businessModelApplicability: "ALL",
    requiredForDecision: ["OPERATIONS", "SALES"],
    acquisitionModes: ["CONVERSATION"],
    defaultConfidence: 0.80,
    defaultIsAssumption: false,
    suggestedQuestion: "Şu an iş yükünüz nasıl? Kapasitenizin ne kadarını kullanıyorsunuz?",
    reason: "Aktif iş yükü bilinmeden yeni iş alma kapasitesi ve kaynak önceliklendirmesi yapılamaz.",
    hasExistingMemoryKey: false,
  },

  {
    key: "delivery_time",
    aliases: [],
    label: "Teslimat / Hizmet Süresi",
    description: "Ürün veya hizmetin müşteriye ortalama teslim süresi",
    level: 2,
    memoryType: "FACT",
    subjectType: "ORGANIZATION",
    priority: "MEDIUM",
    industryApplicability: "ALL",
    businessModelApplicability: "ALL",
    requiredForDecision: ["OPERATIONS", "CUSTOMER_CONFLICT"],
    acquisitionModes: ["CONVERSATION"],
    defaultConfidence: 0.82,
    defaultIsAssumption: false,
    suggestedQuestion: "Müşteriye ortalama ne kadar sürede teslim veya hizmet veriyorsunuz?",
    reason: "Teslimat süresi bilinmeden müşteri memnuniyeti ve kapasite sorunları doğru analiz edilemez.",
    hasExistingMemoryKey: false,
  },

  {
    key: "quality_issues",
    aliases: [],
    label: "Kalite Sorunları",
    description: "Şu anda yaşanan ürün veya hizmet kalite problemleri",
    level: 2,
    memoryType: "PROCESS",
    subjectType: "ORGANIZATION",
    priority: "MEDIUM",
    industryApplicability: "ALL",
    businessModelApplicability: "ALL",
    requiredForDecision: ["OPERATIONS", "CUSTOMER_CONFLICT"],
    acquisitionModes: ["CONVERSATION"],
    defaultConfidence: 0.80,
    defaultIsAssumption: false,
    suggestedQuestion: "Son dönemde kalite veya iade şikayetleri var mı?",
    reason: "Kalite sorunları bilinmeden operasyonel iyileştirme önerileri isabetsiz kalır.",
    hasExistingMemoryKey: false,
  },

  {
    key: "total_receivables",
    aliases: [],
    label: "Toplam Açık Alacak",
    description: "Faturalandırılmış ancak tahsil edilmemiş toplam alacak tutarı",
    level: 2,
    memoryType: "FACT",
    subjectType: "ORGANIZATION",
    priority: "HIGH",
    industryApplicability: "ALL",
    businessModelApplicability: "ALL",
    requiredForDecision: ["COLLECTION", "CASHFLOW"],
    acquisitionModes: ["CONVERSATION", "IMPORT"],
    defaultConfidence: 0.82,
    defaultIsAssumption: false,
    suggestedQuestion: "Şu anda toplam açık alacağınız ne kadar?",
    reason: "Açık alacak bilinmeden nakit riski ve tahsilat önceliği hesaplanamaz.",
    hasExistingMemoryKey: false,
  },

  {
    key: "overdue_receivables",
    aliases: [],
    label: "Vadesi Geçmiş Alacak",
    description: "Ödeme vadesi geçmiş ve hâlâ tahsil edilmemiş alacaklar",
    level: 2,
    memoryType: "FACT",
    subjectType: "ORGANIZATION",
    priority: "HIGH",
    industryApplicability: "ALL",
    businessModelApplicability: "ALL",
    requiredForDecision: ["COLLECTION", "CASHFLOW"],
    acquisitionModes: ["CONVERSATION", "IMPORT"],
    defaultConfidence: 0.82,
    defaultIsAssumption: false,
    suggestedQuestion: "Vadesi geçmiş alacağınız var mı? Varsa toplam tutarı ne kadar?",
    reason: "Vadesi geçmiş alacak tahsilat risk seviyesinin temel göstergesidir.",
    hasExistingMemoryKey: false,
  },

  {
    key: "collection_issue_exists",
    aliases: [],
    label: "Tahsilat Sorunu Var Mı",
    description: "Şu an aktif bir tahsilat sorunu yaşanıp yaşanmadığı",
    level: 2,
    memoryType: "FACT",
    subjectType: "ORGANIZATION",
    priority: "HIGH",
    industryApplicability: "ALL",
    businessModelApplicability: "ALL",
    requiredForDecision: ["COLLECTION", "CASHFLOW"],
    acquisitionModes: ["CONVERSATION", "INFERENCE"],
    defaultConfidence: 0.78,
    defaultIsAssumption: true,
    suggestedQuestion: "Şu an tahsilat yapamadığınız müşteriniz var mı?",
    reason: "Tahsilat sorununun varlığı bilinmeden gap detection doğru çalışamaz.",
    hasExistingMemoryKey: false,
  },

  {
    key: "vehicle_count",
    aliases: [],
    label: "Araç Sayısı",
    description: "İşletmeye ait veya kullanılan araç sayısı",
    level: 2,
    memoryType: "FACT",
    subjectType: "ORGANIZATION",
    priority: "LOW",
    industryApplicability: ["LOJISTIK", "INSAAT_TAAHHUT", "URETIM", "GUVENLIK_TEMIZLIK"],
    businessModelApplicability: ["LOGISTICS", "MANUFACTURING", "WORKFORCE"],
    requiredForDecision: ["OPERATIONS"],
    acquisitionModes: ["CONVERSATION"],
    defaultConfidence: 0.88,
    defaultIsAssumption: false,
    suggestedQuestion: "Kaç araç kullanıyorsunuz? (şirkete ait veya kiralanmış)",
    reason: "Araç sayısı lojistik kapasite ve maliyet planlamasının temelidir.",
    hasExistingMemoryKey: false,
  },

  {
    key: "machine_count",
    aliases: [],
    label: "Makine Sayısı",
    description: "Üretimde veya hizmet sunumunda kullanılan makine sayısı",
    level: 2,
    memoryType: "FACT",
    subjectType: "ORGANIZATION",
    priority: "LOW",
    industryApplicability: ["URETIM", "TEKNIK_SERVIS"],
    businessModelApplicability: ["MANUFACTURING"],
    requiredForDecision: ["OPERATIONS"],
    acquisitionModes: ["CONVERSATION"],
    defaultConfidence: 0.88,
    defaultIsAssumption: false,
    suggestedQuestion: "Üretimde kaç makine kullanıyorsunuz?",
    reason: "Makine sayısı üretim kapasitesi ve yatırım planlaması için temel veridir.",
    hasExistingMemoryKey: false,
  },

  {
    key: "branch_count",
    aliases: [],
    label: "Şube / Lokasyon Sayısı",
    description: "Şirketin aktif şube veya operasyon noktası sayısı",
    level: 2,
    memoryType: "FACT",
    subjectType: "ORGANIZATION",
    priority: "LOW",
    industryApplicability: "ALL",
    businessModelApplicability: "ALL",
    requiredForDecision: ["OPERATIONS", "STRATEGY"],
    acquisitionModes: ["CONVERSATION"],
    defaultConfidence: 0.92,
    defaultIsAssumption: false,
    suggestedQuestion: "Kaç şube veya farklı lokasyonda faaliyet gösteriyorsunuz?",
    reason: "Şube sayısı koordinasyon yükü ve büyüme stratejisi kararlarını etkiler.",
    hasExistingMemoryKey: false,
  },

  {
    key: "property_count",
    aliases: [],
    label: "Mülk / Varlık Sayısı",
    description: "Şirkete ait gayrimenkul, taşınmaz veya kiralanan fiziksel alan sayısı",
    level: 2,
    memoryType: "FACT",
    subjectType: "ORGANIZATION",
    priority: "LOW",
    industryApplicability: ["GAYRIMENKUL", "URETIM", "LOJISTIK"],
    businessModelApplicability: ["RENTAL", "MANUFACTURING", "LOGISTICS"],
    requiredForDecision: ["OPERATIONS"],
    acquisitionModes: ["CONVERSATION"],
    defaultConfidence: 0.88,
    defaultIsAssumption: false,
    suggestedQuestion: "Kaç mülk veya fiziksel alana sahipsiniz ya da kira ödüyorsunuz?",
    reason: "Mülk sayısı sabit maliyet ve varlık yönetimi kararlarını etkiler.",
    hasExistingMemoryKey: false,
  },

  {
    key: "monthly_capacity",
    aliases: [],
    label: "Aylık Kapasite",
    description: "Teorik veya pratik aylık üretim veya hizmet kapasitesi",
    level: 2,
    memoryType: "FACT",
    subjectType: "ORGANIZATION",
    priority: "HIGH",
    industryApplicability: ["URETIM", "INSAAT_TAAHHUT", "SAGLIK", "PROFESYONEL_HIZMETLER", "LOJISTIK"],
    businessModelApplicability: ["MANUFACTURING", "SERVICE", "PROJECT", "LOGISTICS"],
    requiredForDecision: ["OPERATIONS", "PRICING", "SALES"],
    acquisitionModes: ["CONVERSATION"],
    defaultConfidence: 0.78,
    defaultIsAssumption: true,
    suggestedQuestion: "Bir ayda teorik olarak ne kadar iş veya sipariş çıkarabiliyorsunuz?",
    reason: "Kapasite bilinmeden büyüme planı, yeni iş alma ve fiyatlama kararları eksik kalır.",
    hasExistingMemoryKey: false,
  },

  {
    key: "capacity_utilization",
    aliases: [],
    label: "Kapasite Kullanım Oranı",
    description: "Mevcut kapasiteden ne kadarının kullanıldığı (yüzde veya kalitatif)",
    level: 2,
    memoryType: "FACT",
    subjectType: "ORGANIZATION",
    priority: "MEDIUM",
    industryApplicability: ["URETIM", "SAGLIK", "PROFESYONEL_HIZMETLER", "LOJISTIK"],
    businessModelApplicability: ["MANUFACTURING", "SERVICE", "LOGISTICS"],
    requiredForDecision: ["OPERATIONS"],
    acquisitionModes: ["CONVERSATION", "INFERENCE"],
    defaultConfidence: 0.72,
    defaultIsAssumption: true,
    suggestedQuestion: "Şu an kapasitenizin yaklaşık yüzde kaçını kullanıyorsunuz?",
    reason: "Kapasite kullanımı yeni iş alma ve fiyat artışı kararlarını doğrudan etkiler.",
    hasExistingMemoryKey: false,
  },

  {
    key: "capacity_constraint",
    aliases: [],
    label: "Kapasite Kısıtı",
    description: "Kapasiteyi kısıtlayan başlıca faktör (insan, makine, alan, finans vb.)",
    level: 2,
    memoryType: "PROCESS",
    subjectType: "ORGANIZATION",
    priority: "MEDIUM",
    industryApplicability: "ALL",
    businessModelApplicability: "ALL",
    requiredForDecision: ["OPERATIONS", "STRATEGY"],
    acquisitionModes: ["CONVERSATION", "INFERENCE"],
    defaultConfidence: 0.72,
    defaultIsAssumption: true,
    suggestedQuestion: "Daha fazla iş veya sipariş almanızı engelleyen en büyük kısıt ne?",
    reason: "Kapasite kısıtı bilinmeden büyüme müdahalesi doğru kaynaklara yönlendirilemiyor.",
    hasExistingMemoryKey: false,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // LEVEL 3 — STRATEGIC (Nereye gittiğini anlatan bilgiler)
  // ══════════════════════════════════════════════════════════════════════════

  {
    key: "one_year_goal",
    aliases: [],
    label: "1 Yıllık Hedef",
    description: "12 ay sonra ulaşılmak istenen sayısal veya niteliksel hedef",
    level: 3,
    memoryType: "STRATEGIC",
    subjectType: "STRATEGY",
    priority: "HIGH",
    industryApplicability: "ALL",
    businessModelApplicability: "ALL",
    requiredForDecision: ["STRATEGY"],
    acquisitionModes: ["CONVERSATION", "ONBOARDING"],
    defaultConfidence: 0.88,
    defaultIsAssumption: false,
    suggestedQuestion: "12 ay sonra şirketinizin nerede olmasını istiyorsunuz?",
    reason: "Uzun vadeli hedef bilinmeden stratejik öneri işletmenin yönüne bağlanamaz.",
    hasExistingMemoryKey: false,
  },

  {
    key: "three_year_goal",
    aliases: [],
    label: "3 Yıllık Vizyon",
    description: "Şirketin üç yıl içinde ulaşmak istediği konum veya büyüklük",
    level: 3,
    memoryType: "STRATEGIC",
    subjectType: "STRATEGY",
    priority: "MEDIUM",
    industryApplicability: "ALL",
    businessModelApplicability: "ALL",
    requiredForDecision: ["STRATEGY"],
    acquisitionModes: ["CONVERSATION"],
    defaultConfidence: 0.82,
    defaultIsAssumption: false,
    suggestedQuestion: "3 yıl sonra şirketinizin nerede olmasını hayal ediyorsunuz?",
    reason: "Orta vadeli vizyon bilinmeden yatırım ve büyüme yol haritası çizilemez.",
    hasExistingMemoryKey: false,
  },

  {
    key: "growth_target",
    aliases: [],
    label: "Büyüme Hedefi",
    description: "Yıllık veya aylık büyüme hedefi (yüzde veya mutlak değer)",
    level: 3,
    memoryType: "STRATEGIC",
    subjectType: "STRATEGY",
    priority: "MEDIUM",
    industryApplicability: "ALL",
    businessModelApplicability: "ALL",
    requiredForDecision: ["STRATEGY", "SALES"],
    acquisitionModes: ["CONVERSATION"],
    defaultConfidence: 0.82,
    defaultIsAssumption: false,
    suggestedQuestion: "Bu yıl için büyüme hedefiniz var mı? Varsa yüzde kaç veya ne kadar?",
    reason: "Büyüme hedefi bilinmeden satış ve yatırım önerileri yönlendirilemez.",
    hasExistingMemoryKey: false,
  },

  {
    key: "planned_investments",
    aliases: [],
    label: "Planlanan Yatırımlar",
    description: "Kısa veya orta vadede yapılması düşünülen yatırımlar",
    level: 3,
    memoryType: "STRATEGIC",
    subjectType: "STRATEGY",
    priority: "MEDIUM",
    industryApplicability: "ALL",
    businessModelApplicability: "ALL",
    requiredForDecision: ["STRATEGY"],
    acquisitionModes: ["CONVERSATION"],
    defaultConfidence: 0.80,
    defaultIsAssumption: false,
    suggestedQuestion: "Önümüzdeki dönemde planladığınız önemli bir yatırım var mı?",
    reason: "Planlanan yatırımlar nakit yönetimi ve kaynak planlamasını etkiler.",
    hasExistingMemoryKey: false,
  },

  {
    key: "expansion_plans",
    aliases: [],
    label: "Genişleme Planları",
    description: "Yeni ürün, hizmet, şube, pazar veya coğrafyaya açılma planları",
    level: 3,
    memoryType: "STRATEGIC",
    subjectType: "STRATEGY",
    priority: "LOW",
    industryApplicability: "ALL",
    businessModelApplicability: "ALL",
    requiredForDecision: ["STRATEGY"],
    acquisitionModes: ["CONVERSATION"],
    defaultConfidence: 0.80,
    defaultIsAssumption: false,
    suggestedQuestion: "Yeni bir pazara, ürüne veya şehre açılma planınız var mı?",
    reason: "Genişleme planları risk ve kaynak tahsisi kararlarını şekillendirir.",
    hasExistingMemoryKey: false,
  },

  {
    key: "main_competitors",
    aliases: [],
    label: "Ana Rakipler",
    description: "Şirketin doğrudan rekabet ettiği başlıca rakip isimler veya kategoriler",
    level: 3,
    memoryType: "FACT",
    subjectType: "ORGANIZATION",
    priority: "MEDIUM",
    industryApplicability: "ALL",
    businessModelApplicability: "ALL",
    requiredForDecision: ["PRICING", "STRATEGY", "SALES"],
    acquisitionModes: ["CONVERSATION"],
    defaultConfidence: 0.85,
    defaultIsAssumption: false,
    suggestedQuestion: "Sizi en çok etkileyen rakipleriniz kimler?",
    reason: "Rakip bilinmeden fiyatlama pozisyonu ve satış stratejisi netleşemez.",
    hasExistingMemoryKey: false,
  },

  {
    key: "competitive_advantages",
    aliases: [],
    label: "Rekabetçi Üstünlükler",
    description: "Şirketi rakiplerden ayıran güçlü yönler ve avantajlar",
    level: 3,
    memoryType: "STRATEGIC",
    subjectType: "ORGANIZATION",
    priority: "MEDIUM",
    industryApplicability: "ALL",
    businessModelApplicability: "ALL",
    requiredForDecision: ["PRICING", "STRATEGY", "SALES"],
    acquisitionModes: ["CONVERSATION"],
    defaultConfidence: 0.82,
    defaultIsAssumption: false,
    suggestedQuestion: "Müşterileriniz neden sizi rakiplerinize tercih ediyor?",
    reason: "Rekabetçi avantaj bilinmeden fiyat savunma ve satış argümanı üretilemiyor.",
    hasExistingMemoryKey: false,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // BUSINESS MODEL PACK KEYS — TRADING
  // ══════════════════════════════════════════════════════════════════════════

  {
    key: "product_groups",
    aliases: [],
    label: "Ürün Grupları",
    description: "Alım-satım veya perakende yapılan başlıca ürün kategorileri",
    level: 2,
    memoryType: "FACT",
    subjectType: "ORGANIZATION",
    priority: "HIGH",
    industryApplicability: ["TICARET", "PERAKENDE", "E_TICARET", "TARIM_HAYVANCILIK"],
    businessModelApplicability: ["TRADING", "RETAIL"],
    requiredForDecision: ["PRICING", "SALES", "OPERATIONS"],
    acquisitionModes: ["ONBOARDING", "CONVERSATION"],
    defaultConfidence: 0.90,
    defaultIsAssumption: false,
    suggestedQuestion: "Hangi ürün gruplarında alım-satım yapıyorsunuz?",
    reason: "Ürün grupları bilinmeden tedarik, stok ve fiyatlama önerileri yapılamaz.",
    hasExistingMemoryKey: false,
  },

  {
    key: "supplier_count",
    aliases: [],
    label: "Tedarikçi Sayısı",
    description: "Aktif çalışılan tedarikçi veya üretici sayısı",
    level: 2,
    memoryType: "FACT",
    subjectType: "ORGANIZATION",
    priority: "MEDIUM",
    industryApplicability: ["TICARET", "PERAKENDE", "URETIM", "TARIM_HAYVANCILIK"],
    businessModelApplicability: ["TRADING", "RETAIL", "MANUFACTURING"],
    requiredForDecision: ["OPERATIONS"],
    acquisitionModes: ["CONVERSATION"],
    defaultConfidence: 0.85,
    defaultIsAssumption: false,
    suggestedQuestion: "Kaç farklı tedarikçiyle çalışıyorsunuz?",
    reason: "Tedarikçi sayısı tedarik zinciri riski ve müzakere gücü analizini etkiler.",
    hasExistingMemoryKey: false,
  },

  {
    key: "inventory_level",
    aliases: [],
    label: "Stok Seviyesi",
    description: "Mevcut stok durumu ve tutarı (fazla, yeterli, yetersiz)",
    level: 2,
    memoryType: "FACT",
    subjectType: "ORGANIZATION",
    priority: "HIGH",
    industryApplicability: ["TICARET", "PERAKENDE", "E_TICARET", "URETIM", "TARIM_HAYVANCILIK"],
    businessModelApplicability: ["TRADING", "RETAIL", "MANUFACTURING"],
    requiredForDecision: ["OPERATIONS", "CASHFLOW"],
    acquisitionModes: ["CONVERSATION"],
    defaultConfidence: 0.80,
    defaultIsAssumption: false,
    suggestedQuestion: "Şu an stok durumunuz nasıl? Yeterli mi, fazla mı, yetersiz mi?",
    reason: "Stok seviyesi nakit bağlama ve operasyon sürekliliği kararlarını doğrudan etkiler.",
    hasExistingMemoryKey: false,
  },

  {
    key: "inventory_turnover",
    aliases: [],
    label: "Stok Devir Hızı",
    description: "Stoğun ortalama kaç günde bir satıldığı veya tüketildiği",
    level: 2,
    memoryType: "FACT",
    subjectType: "ORGANIZATION",
    priority: "MEDIUM",
    industryApplicability: ["TICARET", "PERAKENDE", "URETIM"],
    businessModelApplicability: ["TRADING", "RETAIL", "MANUFACTURING"],
    requiredForDecision: ["OPERATIONS", "CASHFLOW"],
    acquisitionModes: ["CONVERSATION", "INFERENCE"],
    defaultConfidence: 0.72,
    defaultIsAssumption: true,
    suggestedQuestion: "Stoğunuz ortalama kaç günde bir dönüyor?",
    reason: "Stok devir hızı nakit döngüsü ve stok optimizasyon kararlarının temelidir.",
    hasExistingMemoryKey: false,
  },

  {
    key: "average_margin",
    aliases: [],
    label: "Ortalama Marj",
    description: "Ürün veya hizmet başına ortalama brüt kar marjı",
    level: 2,
    memoryType: "FACT",
    subjectType: "ORGANIZATION",
    priority: "HIGH",
    industryApplicability: ["TICARET", "PERAKENDE", "E_TICARET", "URETIM"],
    businessModelApplicability: ["TRADING", "RETAIL", "MANUFACTURING"],
    requiredForDecision: ["PRICING", "CASHFLOW"],
    acquisitionModes: ["CONVERSATION", "USER_CORRECTION"],
    defaultConfidence: 0.78,
    defaultIsAssumption: true,
    suggestedQuestion: "Ortalama ürün marjınız yüzde kaç?",
    reason: "Marj bilinmeden indirim kararı, fiyat savunması ve karlılık analizi yapılamaz.",
    hasExistingMemoryKey: false,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // BUSINESS MODEL PACK KEYS — MANUFACTURING
  // ══════════════════════════════════════════════════════════════════════════

  {
    key: "monthly_production_capacity",
    aliases: [],
    label: "Aylık Üretim Kapasitesi",
    description: "Aylık maksimum üretim miktarı (adet, ton, metrekare vb.)",
    level: 2,
    memoryType: "FACT",
    subjectType: "ORGANIZATION",
    priority: "HIGH",
    industryApplicability: ["URETIM", "TARIM_HAYVANCILIK"],
    businessModelApplicability: ["MANUFACTURING"],
    requiredForDecision: ["OPERATIONS", "PRICING"],
    acquisitionModes: ["CONVERSATION"],
    defaultConfidence: 0.82,
    defaultIsAssumption: false,
    suggestedQuestion: "Aylık en fazla kaç birim üretebiliyorsunuz?",
    reason: "Üretim kapasitesi bilinmeden sipariş alımı, fiyatlama ve büyüme kararları hatalı olur.",
    hasExistingMemoryKey: false,
  },

  {
    key: "production_method",
    aliases: [],
    label: "Üretim Yöntemi",
    description: "Üretim tipi: seri, sipariş, proje bazlı, sürekli üretim vb.",
    level: 2,
    memoryType: "FACT",
    subjectType: "ORGANIZATION",
    priority: "MEDIUM",
    industryApplicability: ["URETIM"],
    businessModelApplicability: ["MANUFACTURING"],
    requiredForDecision: ["OPERATIONS"],
    acquisitionModes: ["ONBOARDING", "CONVERSATION"],
    defaultConfidence: 0.88,
    defaultIsAssumption: false,
    suggestedQuestion: "Üretiminiz nasıl yapılıyor? (seri, sipariş bazlı, proje bazlı vb.)",
    reason: "Üretim yöntemi bilinmeden kapasite ve maliyet yapısı analiz edilemez.",
    hasExistingMemoryKey: false,
  },

  {
    key: "critical_machines",
    aliases: [],
    label: "Kritik Makineler",
    description: "Üretim sürecinde en kritik rol oynayan makine veya ekipmanlar",
    level: 2,
    memoryType: "FACT",
    subjectType: "ORGANIZATION",
    priority: "MEDIUM",
    industryApplicability: ["URETIM"],
    businessModelApplicability: ["MANUFACTURING"],
    requiredForDecision: ["OPERATIONS"],
    acquisitionModes: ["CONVERSATION"],
    defaultConfidence: 0.85,
    defaultIsAssumption: false,
    suggestedQuestion: "Üretimde en kritik makine veya ekipmanınız hangisi?",
    reason: "Kritik makine bilinmeden arıza riski ve bakım planlaması ihmal edilebilir.",
    hasExistingMemoryKey: false,
  },

  {
    key: "scrap_rate",
    aliases: [],
    label: "Fire Oranı",
    description: "Üretimde oluşan fire, hata veya iade oranı",
    level: 2,
    memoryType: "FACT",
    subjectType: "ORGANIZATION",
    priority: "MEDIUM",
    industryApplicability: ["URETIM"],
    businessModelApplicability: ["MANUFACTURING"],
    requiredForDecision: ["OPERATIONS", "PRICING"],
    acquisitionModes: ["CONVERSATION"],
    defaultConfidence: 0.75,
    defaultIsAssumption: true,
    suggestedQuestion: "Üretimde yaklaşık fire veya hata oranınız nedir?",
    reason: "Fire oranı bilinmeden gerçek üretim maliyeti ve fiyatlama hesaplanamaz.",
    hasExistingMemoryKey: false,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // BUSINESS MODEL PACK KEYS — PROJECT
  // ══════════════════════════════════════════════════════════════════════════

  {
    key: "active_project_count",
    aliases: [],
    label: "Aktif Proje Sayısı",
    description: "Şu anda devam eden proje veya taahhüt sayısı",
    level: 2,
    memoryType: "FACT",
    subjectType: "ORGANIZATION",
    priority: "HIGH",
    industryApplicability: ["INSAAT_TAAHHUT", "MIMARLIK_PROJE"],
    businessModelApplicability: ["PROJECT"],
    requiredForDecision: ["OPERATIONS", "SALES", "CASHFLOW"],
    acquisitionModes: ["CONVERSATION", "IMPORT"],
    defaultConfidence: 0.88,
    defaultIsAssumption: false,
    suggestedQuestion: "Şu an kaç aktif projeniz devam ediyor?",
    reason: "Aktif proje sayısı kapasite kullanımı ve nakit akışı tahmininin temelidir.",
    hasExistingMemoryKey: false,
  },

  {
    key: "average_project_duration",
    aliases: [],
    label: "Ortalama Proje Süresi",
    description: "Bir projenin başlangıçtan teslime kadar ortalama süresi",
    level: 2,
    memoryType: "FACT",
    subjectType: "ORGANIZATION",
    priority: "MEDIUM",
    industryApplicability: ["INSAAT_TAAHHUT", "MIMARLIK_PROJE"],
    businessModelApplicability: ["PROJECT"],
    requiredForDecision: ["OPERATIONS", "PRICING"],
    acquisitionModes: ["CONVERSATION"],
    defaultConfidence: 0.80,
    defaultIsAssumption: false,
    suggestedQuestion: "Projeleriniz ortalama ne kadar sürüyor?",
    reason: "Proje süresi bilinmeden nakit akışı tahmini ve kaynak planlaması hatalı olur.",
    hasExistingMemoryKey: false,
  },

  {
    key: "project_capacity",
    aliases: [],
    label: "Proje Kapasitesi",
    description: "Aynı anda alınabilecek maksimum proje sayısı",
    level: 2,
    memoryType: "FACT",
    subjectType: "ORGANIZATION",
    priority: "HIGH",
    industryApplicability: ["INSAAT_TAAHHUT", "MIMARLIK_PROJE"],
    businessModelApplicability: ["PROJECT"],
    requiredForDecision: ["OPERATIONS"],
    acquisitionModes: ["CONVERSATION"],
    defaultConfidence: 0.78,
    defaultIsAssumption: true,
    suggestedQuestion: "Aynı anda en fazla kaç proje yürütebiliyorsunuz?",
    reason: "Proje kapasitesi bilinmeden yeni iş alma kararı verilemiyor.",
    hasExistingMemoryKey: false,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // BUSINESS MODEL PACK KEYS — SERVICE
  // ══════════════════════════════════════════════════════════════════════════

  {
    key: "appointment_capacity",
    aliases: [],
    label: "Randevu / Seans Kapasitesi",
    description: "Günlük veya aylık karşılanabilecek maksimum randevu veya seans sayısı",
    level: 2,
    memoryType: "FACT",
    subjectType: "ORGANIZATION",
    priority: "HIGH",
    industryApplicability: ["SAGLIK", "EGITIM", "PROFESYONEL_HIZMETLER"],
    businessModelApplicability: ["SERVICE"],
    requiredForDecision: ["OPERATIONS", "SALES"],
    acquisitionModes: ["CONVERSATION"],
    defaultConfidence: 0.82,
    defaultIsAssumption: false,
    suggestedQuestion: "Günlük veya aylık kaç randevu veya seans kapasitesi var?",
    reason: "Randevu kapasitesi bilinmeden büyüme sınırı ve gelir tavanı hesaplanamaz.",
    hasExistingMemoryKey: false,
  },

  {
    key: "expert_count",
    aliases: [],
    label: "Uzman / Teknik Personel Sayısı",
    description: "Hizmet sunan uzman, terapist, danışman veya teknik personel sayısı",
    level: 2,
    memoryType: "FACT",
    subjectType: "ORGANIZATION",
    priority: "HIGH",
    industryApplicability: ["SAGLIK", "EGITIM", "PROFESYONEL_HIZMETLER", "MIMARLIK_PROJE"],
    businessModelApplicability: ["SERVICE", "PROJECT"],
    requiredForDecision: ["TEAM", "OPERATIONS", "HIRING"],
    acquisitionModes: ["CONVERSATION"],
    defaultConfidence: 0.88,
    defaultIsAssumption: false,
    suggestedQuestion: "Şu an kaç uzman veya teknik personel çalışıyor?",
    reason: "Uzman sayısı hizmet kapasitesini ve büyüme için işe alım kararını belirler.",
    hasExistingMemoryKey: false,
  },

  {
    key: "service_utilization",
    aliases: [],
    label: "Hizmet Doluluk Oranı",
    description: "Mevcut hizmet kapasitesinin ne kadarının kullanıldığı",
    level: 2,
    memoryType: "FACT",
    subjectType: "ORGANIZATION",
    priority: "MEDIUM",
    industryApplicability: ["SAGLIK", "EGITIM", "PROFESYONEL_HIZMETLER", "TEKNIK_SERVIS"],
    businessModelApplicability: ["SERVICE"],
    requiredForDecision: ["OPERATIONS", "STRATEGY"],
    acquisitionModes: ["CONVERSATION", "INFERENCE"],
    defaultConfidence: 0.72,
    defaultIsAssumption: true,
    suggestedQuestion: "Hizmet kapasitenizin yaklaşık yüzde kaçı dolu?",
    reason: "Doluluk oranı bilinmeden büyüme baskısı ve işe alım kararı verilemiyor.",
    hasExistingMemoryKey: false,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // BUSINESS MODEL PACK KEYS — BROKERAGE
  // ══════════════════════════════════════════════════════════════════════════

  {
    key: "portfolio_count",
    aliases: [],
    label: "Portföy Adedi",
    description: "Aktif olarak yönetilen veya pazarlanan portföy, mülk veya ürün adedi",
    level: 2,
    memoryType: "FACT",
    subjectType: "ORGANIZATION",
    priority: "HIGH",
    industryApplicability: ["GAYRIMENKUL", "FINANS_SIGORTA", "MEDYA_PAZARLAMA"],
    businessModelApplicability: ["BROKERAGE"],
    requiredForDecision: ["SALES", "STRATEGY"],
    acquisitionModes: ["CONVERSATION"],
    defaultConfidence: 0.85,
    defaultIsAssumption: false,
    suggestedQuestion: "Şu an aktif olarak kaç portföy veya ürün yönetiyorsunuz?",
    reason: "Portföy adedi gelir kapasitesinin ve büyüme potansiyelinin göstergesidir.",
    hasExistingMemoryKey: false,
  },

  {
    key: "conversion_rate",
    aliases: [],
    label: "Dönüşüm Oranı",
    description: "Müşteri adayından gerçek satış veya anlaşmaya dönüşme oranı",
    level: 2,
    memoryType: "FACT",
    subjectType: "ORGANIZATION",
    priority: "HIGH",
    industryApplicability: ["GAYRIMENKUL", "FINANS_SIGORTA", "MEDYA_PAZARLAMA", "E_TICARET"],
    businessModelApplicability: ["BROKERAGE", "RETAIL"],
    requiredForDecision: ["SALES", "PRICING"],
    acquisitionModes: ["CONVERSATION", "INFERENCE"],
    defaultConfidence: 0.72,
    defaultIsAssumption: true,
    suggestedQuestion: "Müşteri adaylarınızın yaklaşık yüzde kaçı gerçek satışa dönüşüyor?",
    reason: "Dönüşüm oranı bilinmeden satış verimliliği ve pazarlama yatırımı kararları hatalı olur.",
    hasExistingMemoryKey: false,
  },

  {
    key: "average_commission",
    aliases: [],
    label: "Ortalama Komisyon",
    description: "Her satış veya aracılık işleminden elde edilen ortalama komisyon tutarı veya oranı",
    level: 2,
    memoryType: "FACT",
    subjectType: "ORGANIZATION",
    priority: "HIGH",
    industryApplicability: ["GAYRIMENKUL", "FINANS_SIGORTA"],
    businessModelApplicability: ["BROKERAGE"],
    requiredForDecision: ["PRICING", "CASHFLOW"],
    acquisitionModes: ["CONVERSATION"],
    defaultConfidence: 0.82,
    defaultIsAssumption: false,
    suggestedQuestion: "Bir satıştan ortalama ne kadar komisyon alıyorsunuz?",
    reason: "Komisyon bilinmeden gelir tahmini ve satış önceliği belirlenemiyor.",
    hasExistingMemoryKey: false,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // BUSINESS MODEL PACK KEYS — SUBSCRIPTION
  // ══════════════════════════════════════════════════════════════════════════

  {
    key: "subscriber_count",
    aliases: [],
    label: "Abone / Üye Sayısı",
    description: "Aktif abonelik veya üyelik sahiplerinin sayısı",
    level: 2,
    memoryType: "FACT",
    subjectType: "ORGANIZATION",
    priority: "HIGH",
    industryApplicability: ["YAZILIM_TEKNOLOJI", "EGITIM", "MEDYA_PAZARLAMA"],
    businessModelApplicability: ["SUBSCRIPTION"],
    requiredForDecision: ["SALES", "CASHFLOW", "STRATEGY"],
    acquisitionModes: ["CONVERSATION", "IMPORT"],
    defaultConfidence: 0.88,
    defaultIsAssumption: false,
    suggestedQuestion: "Şu an kaç aktif aboneniz veya üyeniz var?",
    reason: "Abone sayısı tekrarlayan gelirin ve büyüme hızının temelidir.",
    hasExistingMemoryKey: false,
  },

  {
    key: "monthly_recurring_revenue",
    aliases: ["mrr"],
    label: "Aylık Tekrarlayan Gelir (MRR)",
    description: "Aboneliklerden elde edilen aylık garantili gelir",
    level: 2,
    memoryType: "FACT",
    subjectType: "ORGANIZATION",
    priority: "HIGH",
    industryApplicability: ["YAZILIM_TEKNOLOJI", "EGITIM", "MEDYA_PAZARLAMA"],
    businessModelApplicability: ["SUBSCRIPTION"],
    requiredForDecision: ["CASHFLOW", "STRATEGY"],
    acquisitionModes: ["CONVERSATION", "IMPORT"],
    defaultConfidence: 0.88,
    defaultIsAssumption: false,
    suggestedQuestion: "Aylık garantili abonelik geliriniz (MRR) ne kadar?",
    reason: "MRR bilinmeden nakit öngörülebilirliği ve büyüme hızı değerlendirilemiyor.",
    hasExistingMemoryKey: false,
  },

  {
    key: "churn_rate",
    aliases: [],
    label: "Kayıp Oranı (Churn)",
    description: "Aylık abonelik iptali veya müşteri kaybı oranı",
    level: 2,
    memoryType: "FACT",
    subjectType: "ORGANIZATION",
    priority: "HIGH",
    industryApplicability: ["YAZILIM_TEKNOLOJI", "EGITIM", "MEDYA_PAZARLAMA"],
    businessModelApplicability: ["SUBSCRIPTION"],
    requiredForDecision: ["STRATEGY", "SALES"],
    acquisitionModes: ["CONVERSATION", "INFERENCE"],
    defaultConfidence: 0.72,
    defaultIsAssumption: true,
    suggestedQuestion: "Aylık abone kaybı (churn) oranınız yaklaşık yüzde kaç?",
    reason: "Churn oranı bilinmeden büyüme sürdürülebilirliği ve müşteri tutma öncelikleri değerlendirilemez.",
    hasExistingMemoryKey: false,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // BUSINESS MODEL PACK KEYS — RENTAL
  // ══════════════════════════════════════════════════════════════════════════

  {
    key: "asset_count",
    aliases: [],
    label: "Kiralık Varlık Sayısı",
    description: "Kiraya verilen gayrimenkul, araç veya ekipman sayısı",
    level: 2,
    memoryType: "FACT",
    subjectType: "ORGANIZATION",
    priority: "HIGH",
    industryApplicability: ["GAYRIMENKUL", "LOJISTIK"],
    businessModelApplicability: ["RENTAL"],
    requiredForDecision: ["OPERATIONS"],
    acquisitionModes: ["CONVERSATION"],
    defaultConfidence: 0.90,
    defaultIsAssumption: false,
    suggestedQuestion: "Kaç adet kiraladığınız veya kiraya verdiğiniz varlığınız var?",
    reason: "Varlık sayısı gelir kapasitesinin ve doluluk analizinin temelidir.",
    hasExistingMemoryKey: false,
  },

  {
    key: "occupancy_rate",
    aliases: [],
    label: "Doluluk Oranı",
    description: "Kiralık varlıkların veya kapasitelerin doluluk yüzdesi",
    level: 2,
    memoryType: "FACT",
    subjectType: "ORGANIZATION",
    priority: "HIGH",
    industryApplicability: ["GAYRIMENKUL", "TURIZM_KONAKLAMA", "YEME_ICME"],
    businessModelApplicability: ["RENTAL", "HOSPITALITY"],
    requiredForDecision: ["OPERATIONS", "CASHFLOW", "STRATEGY"],
    acquisitionModes: ["CONVERSATION"],
    defaultConfidence: 0.80,
    defaultIsAssumption: true,
    suggestedQuestion: "Şu an doluluk oranınız yaklaşık yüzde kaç?",
    reason: "Doluluk oranı bilinmeden gelir optimizasyonu ve fiyatlandırma kararı verilemiyor.",
    hasExistingMemoryKey: false,
  },

  {
    key: "average_rental_income",
    aliases: [],
    label: "Ortalama Kira Geliri",
    description: "Varlık başına veya toplam aylık ortalama kira geliri",
    level: 2,
    memoryType: "FACT",
    subjectType: "ORGANIZATION",
    priority: "HIGH",
    industryApplicability: ["GAYRIMENKUL"],
    businessModelApplicability: ["RENTAL"],
    requiredForDecision: ["CASHFLOW", "PRICING"],
    acquisitionModes: ["CONVERSATION"],
    defaultConfidence: 0.85,
    defaultIsAssumption: false,
    suggestedQuestion: "Ortalama aylık kira geliriniz ne kadar?",
    reason: "Kira geliri bilinmeden nakit planlaması ve yatırım geri dönüşü hesaplanamaz.",
    hasExistingMemoryKey: false,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // BUSINESS MODEL PACK KEYS — LOGISTICS
  // ══════════════════════════════════════════════════════════════════════════

  {
    key: "fleet_size",
    aliases: [],
    label: "Filo Büyüklüğü",
    description: "Aktif kullanılan araç veya taşıt sayısı",
    level: 2,
    memoryType: "FACT",
    subjectType: "ORGANIZATION",
    priority: "HIGH",
    industryApplicability: ["LOJISTIK"],
    businessModelApplicability: ["LOGISTICS"],
    requiredForDecision: ["OPERATIONS"],
    acquisitionModes: ["CONVERSATION"],
    defaultConfidence: 0.90,
    defaultIsAssumption: false,
    suggestedQuestion: "Filohanuzda kaç araç var?",
    reason: "Filo büyüklüğü kapasite ve maliyet hesaplamalarının temelidir.",
    hasExistingMemoryKey: false,
  },

  {
    key: "route_density",
    aliases: [],
    label: "Rota Yoğunluğu",
    description: "Aktif teslimat veya servis rotası sayısı ve yoğunluğu",
    level: 2,
    memoryType: "FACT",
    subjectType: "ORGANIZATION",
    priority: "MEDIUM",
    industryApplicability: ["LOJISTIK"],
    businessModelApplicability: ["LOGISTICS"],
    requiredForDecision: ["OPERATIONS"],
    acquisitionModes: ["CONVERSATION"],
    defaultConfidence: 0.78,
    defaultIsAssumption: true,
    suggestedQuestion: "Günlük aktif teslimat rotası sayınız nedir?",
    reason: "Rota yoğunluğu yakıt maliyeti ve operasyonel verimlilik kararlarını etkiler.",
    hasExistingMemoryKey: false,
  },

  {
    key: "delivery_capacity",
    aliases: [],
    label: "Teslimat Kapasitesi",
    description: "Günlük veya aylık maksimum teslimat veya sevkiyat kapasitesi",
    level: 2,
    memoryType: "FACT",
    subjectType: "ORGANIZATION",
    priority: "HIGH",
    industryApplicability: ["LOJISTIK"],
    businessModelApplicability: ["LOGISTICS"],
    requiredForDecision: ["OPERATIONS", "SALES"],
    acquisitionModes: ["CONVERSATION"],
    defaultConfidence: 0.80,
    defaultIsAssumption: false,
    suggestedQuestion: "Günlük maksimum kaç teslimat yapabiliyorsunuz?",
    reason: "Teslimat kapasitesi bilinmeden yeni müşteri alma ve büyüme kararı verilemiyor.",
    hasExistingMemoryKey: false,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // BUSINESS MODEL PACK KEYS — HOSPITALITY
  // ══════════════════════════════════════════════════════════════════════════

  {
    key: "room_table_capacity",
    aliases: [],
    label: "Oda / Masa Kapasitesi",
    description: "Otel, pansiyon veya restoran için toplam oda veya masa sayısı",
    level: 2,
    memoryType: "FACT",
    subjectType: "ORGANIZATION",
    priority: "HIGH",
    industryApplicability: ["TURIZM_KONAKLAMA", "YEME_ICME"],
    businessModelApplicability: ["HOSPITALITY"],
    requiredForDecision: ["OPERATIONS"],
    acquisitionModes: ["ONBOARDING", "CONVERSATION"],
    defaultConfidence: 0.92,
    defaultIsAssumption: false,
    suggestedQuestion: "Kaç oda veya masa kapasitesiyle faaliyet gösteriyorsunuz?",
    reason: "Oda/masa kapasitesi maksimum gelir ve doluluk analizinin temelidir.",
    hasExistingMemoryKey: false,
  },

  {
    key: "average_guest_revenue",
    aliases: [],
    label: "Ortalama Misafir Geliri",
    description: "Misafir veya müşteri başına ortalama harcama tutarı",
    level: 2,
    memoryType: "FACT",
    subjectType: "ORGANIZATION",
    priority: "HIGH",
    industryApplicability: ["TURIZM_KONAKLAMA", "YEME_ICME"],
    businessModelApplicability: ["HOSPITALITY"],
    requiredForDecision: ["PRICING", "CASHFLOW"],
    acquisitionModes: ["CONVERSATION"],
    defaultConfidence: 0.78,
    defaultIsAssumption: true,
    suggestedQuestion: "Misafir veya müşteri başına ortalama harcama ne kadar?",
    reason: "Misafir başı gelir bilinmeden fiyatlama ve doluluk hedefleri optimize edilemiyor.",
    hasExistingMemoryKey: false,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // BUSINESS MODEL PACK KEYS — WORKFORCE
  // ══════════════════════════════════════════════════════════════════════════

  {
    key: "field_staff_count",
    aliases: [],
    label: "Saha Personeli Sayısı",
    description: "Müşteri lokasyonlarında görev yapan saha çalışanı sayısı",
    level: 2,
    memoryType: "FACT",
    subjectType: "ORGANIZATION",
    priority: "HIGH",
    industryApplicability: ["GUVENLIK_TEMIZLIK", "TEKNIK_SERVIS"],
    businessModelApplicability: ["WORKFORCE"],
    requiredForDecision: ["TEAM", "OPERATIONS"],
    acquisitionModes: ["CONVERSATION"],
    defaultConfidence: 0.88,
    defaultIsAssumption: false,
    suggestedQuestion: "Sahada çalışan kaç personeliniz var?",
    reason: "Saha personel sayısı faturalanabilir kapasite ve büyüme kararlarının temelidir.",
    hasExistingMemoryKey: false,
  },

  {
    key: "contract_count",
    aliases: [],
    label: "Aktif Sözleşme Sayısı",
    description: "Devam eden müşteri sözleşmesi veya hizmet anlaşması sayısı",
    level: 2,
    memoryType: "FACT",
    subjectType: "ORGANIZATION",
    priority: "HIGH",
    industryApplicability: ["GUVENLIK_TEMIZLIK", "TEKNIK_SERVIS", "PROFESYONEL_HIZMETLER"],
    businessModelApplicability: ["WORKFORCE", "SERVICE"],
    requiredForDecision: ["SALES", "CASHFLOW"],
    acquisitionModes: ["CONVERSATION"],
    defaultConfidence: 0.88,
    defaultIsAssumption: false,
    suggestedQuestion: "Şu an kaç aktif müşteri sözleşmeniz var?",
    reason: "Sözleşme sayısı tahmin edilebilir gelir ve yenileme fırsatlarının göstergesidir.",
    hasExistingMemoryKey: false,
  },

  {
    key: "billable_capacity",
    aliases: [],
    label: "Faturalanabilir Kapasite",
    description: "Aylık faturalanabilecek maksimum saat veya hizmet birimi",
    level: 2,
    memoryType: "FACT",
    subjectType: "ORGANIZATION",
    priority: "HIGH",
    industryApplicability: ["GUVENLIK_TEMIZLIK", "TEKNIK_SERVIS", "PROFESYONEL_HIZMETLER"],
    businessModelApplicability: ["WORKFORCE", "SERVICE"],
    requiredForDecision: ["OPERATIONS", "PRICING", "CASHFLOW"],
    acquisitionModes: ["CONVERSATION"],
    defaultConfidence: 0.78,
    defaultIsAssumption: true,
    suggestedQuestion: "Aylık faturalanabilir maksimum kapasiteniz ne kadar? (saat, gün veya hizmet birimi)",
    reason: "Faturalanabilir kapasite bilinmeden gelir tavanı ve büyüme için işe alım kararı verilemiyor.",
    hasExistingMemoryKey: false,
  },
];

// ─── Lookup Fonksiyonları ──────────────────────────────────────────────────────

export function getKnowledgeKey(keyOrAlias: string): KnowledgeKeyEntry | undefined {
  const normalized = keyOrAlias.trim().toLowerCase();
  return EXECUTIVE_KNOWLEDGE_REGISTRY.find(
    (entry) =>
      entry.key === normalized ||
      entry.aliases.some((alias) => alias === normalized),
  );
}

export function getKeysByLevel(level: 1 | 2 | 3): KnowledgeKeyEntry[] {
  return EXECUTIVE_KNOWLEDGE_REGISTRY.filter((entry) => entry.level === level);
}

export function getKeysByDecisionCategory(
  category: import("./executive-knowledge-registry.types").DecisionCategory,
): KnowledgeKeyEntry[] {
  return EXECUTIVE_KNOWLEDGE_REGISTRY.filter((entry) =>
    entry.requiredForDecision.includes(category),
  );
}

export function getKeysByBusinessModel(businessModelId: string): KnowledgeKeyEntry[] {
  return EXECUTIVE_KNOWLEDGE_REGISTRY.filter((entry) => {
    if (entry.businessModelApplicability === "ALL") return true;
    return entry.businessModelApplicability.includes(businessModelId);
  });
}

export function getRequiredLevelOneKeys(): KnowledgeKeyEntry[] {
  return EXECUTIVE_KNOWLEDGE_REGISTRY.filter((entry) => entry.level === 1);
}

export function getRequiredLevelTwoKeysForBusinessModel(
  businessModelId: string,
): KnowledgeKeyEntry[] {
  const modelDef = _getBusinessModelDefinition(businessModelId);
  const criticalL2KeyNames = new Set(
    (modelDef?.criticalL2Keys ?? []).map((k) => k.key),
  );
  const packKeyNames = new Set(modelDef?.packKeys ?? []);

  return EXECUTIVE_KNOWLEDGE_REGISTRY.filter(
    (entry) =>
      entry.level === 2 &&
      (criticalL2KeyNames.has(entry.key) ||
        packKeyNames.has(entry.key) ||
        entry.businessModelApplicability === "ALL"),
  );
}

export function getBusinessModelDefinition(
  id: string,
): BusinessModelFamily | undefined {
  return _getBusinessModelDefinition(id);
}

export function getIndustryDefinition(
  id: string,
): IndustryFamily | undefined {
  return _getIndustryDefinition(id);
}

export function computeKnowledgeGapScore(input: {
  activeMemoryKeys: string[];
  industryValue?: string;
  businessModelValue?: string;
}): KnowledgeGapScore {
  const knownKeys = new Set(
    input.activeMemoryKeys.map((k) => k.trim().toLowerCase()),
  );

  const isKnown = (entry: KnowledgeKeyEntry): boolean =>
    knownKeys.has(entry.key) ||
    entry.aliases.some((a) => knownKeys.has(a));

  // L1 gap'ler
  const l1Entries = getRequiredLevelOneKeys();
  const missingL1 = l1Entries.filter((e) => !isKnown(e)).map((e) => e.key);

  // criticalL2: sektör + model bazlı
  const industryFamily = input.industryValue
    ? resolveIndustryFamily(input.industryValue)
    : null;
  const modelFamily = input.businessModelValue
    ? resolveBusinessModelFamily(input.businessModelValue)
    : null;

  const criticalL2Set = new Set<string>([
    ...(industryFamily?.criticalKeyOverrides.map((k) => k.key) ?? []),
    ...(modelFamily?.criticalL2Keys.map((k) => k.key) ?? []),
    ...(modelFamily?.packKeys ?? []),
  ]);

  const allL2Entries = getKeysByLevel(2);
  const criticalL2Entries = allL2Entries.filter((e) => criticalL2Set.has(e.key));
  const otherL2Entries = allL2Entries.filter((e) => !criticalL2Set.has(e.key));

  const missingCriticalL2 = criticalL2Entries
    .filter((e) => !isKnown(e))
    .map((e) => e.key);
  const missingOtherL2 = otherL2Entries
    .filter((e) => !isKnown(e))
    .map((e) => e.key);

  // L3
  const l3Entries = getKeysByLevel(3);
  const missingL3 = l3Entries.filter((e) => !isKnown(e)).map((e) => e.key);

  const totalRequired = l1Entries.length + criticalL2Entries.length;
  const knownCount = totalRequired - missingL1.length - missingCriticalL2.length;
  const completionRatio =
    totalRequired === 0 ? 1 : Math.max(0, knownCount) / totalRequired;

  return {
    criticalGaps: missingL1,
    highGaps: missingCriticalL2,
    mediumGaps: missingOtherL2,
    lowGaps: missingL3,
    completionRatio,
    overallReadiness: resolveReadiness(missingL1.length, missingCriticalL2.length),
  };
}

function resolveReadiness(
  missingL1Count: number,
  missingCriticalL2Count: number,
): KnowledgeGapScore["overallReadiness"] {
  if (missingL1Count >= Math.ceil(getRequiredLevelOneKeys().length / 2)) return "BLIND";
  if (missingL1Count >= 1) return "INSUFFICIENT";
  if (missingCriticalL2Count >= 2) return "PARTIAL";
  if (missingCriticalL2Count >= 1) return "READY";
  return "COMPLETE";
}

// ─── Industry + Business Model map re-exports ──────────────────────────────
export { BUSINESS_MODEL_MAP } from "./executive-business-model-map";
export { INDUSTRY_MAP } from "./executive-industry-map";
export { listBusinessModelIds } from "./executive-business-model-map";
export { listIndustryIds } from "./executive-industry-map";

