import { prisma } from "@/lib/core/shared/prisma";
import type { Prisma } from "@prisma/client";
import type { CreateSupplierInput, ListSuppliersInput, UpdateSupplierInput } from "./supplier.types";
const include = { contacts: { where: { isPrimary: true }, take: 1 }, products: true, contracts: true, customFieldValues: true } as const;
export function findSupplierByIdentity(organizationId: string, displayName: string, taxNumber?: string, excludeId?: string) { return prisma.supplier.findFirst({ where: { organizationId, id: excludeId ? { not: excludeId } : undefined, OR: [{ displayName: { equals: displayName, mode: "insensitive" } }, ...(taxNumber ? [{ taxNumber }] : [])] } }); }
export function createSupplier(input: CreateSupplierInput, tx: Prisma.TransactionClient = prisma) { return tx.supplier.create({ data: { organizationId: input.organizationId, displayName: input.displayName.trim(), legalName: input.legalName?.trim(), phone: input.phone, email: input.email, website: input.website, taxNumber: input.taxNumber, taxOffice: input.taxOffice, currency: input.currency ?? "TRY", address: input.address as Prisma.InputJsonValue | undefined, metrixNote: input.metrixNote, riskNotes: input.riskNotes } }); }
export function getSupplierById(id: string, organizationId: string, tx: Prisma.TransactionClient = prisma) { return tx.supplier.findFirst({ where: { id, organizationId }, include }); }
export function listSuppliersForOrganization(input: ListSuppliersInput) { return prisma.supplier.findMany({ where: { organizationId: input.organizationId, status: input.status }, orderBy: { displayName: "asc" }, take: Math.min(input.limit ?? 100, 500), include }); }
// listSuppliersForOrganization caps at take (a payload-size limit) — the
// real total, unbounded by that cap, for callers that need to display
// "how many total" rather than "how many loaded".
export function countSuppliersForOrganization(input: Pick<ListSuppliersInput, "organizationId" | "status">) { return prisma.supplier.count({ where: { organizationId: input.organizationId, status: input.status } }); }
export function updateSupplier(input: UpdateSupplierInput, tx: Prisma.TransactionClient = prisma) { const data: Prisma.SupplierUpdateManyMutationInput = {}; for (const key of ["displayName","legalName","phone","email","website","taxNumber","taxOffice","currency","metrixNote","riskNotes","status"] as const) if (input[key] !== undefined) (data as Record<string, unknown>)[key] = (typeof input[key] === "string" ? (input[key] as string).trim() : input[key]) as unknown; if (input.address !== undefined) data.address = input.address as Prisma.InputJsonValue; return tx.supplier.updateMany({ where: { id: input.id, organizationId: input.organizationId }, data }); }
export function archiveSupplier(id: string, organizationId: string) { return prisma.supplier.updateMany({ where: { id, organizationId }, data: { status: "ARCHIVED" } }); }
