import { prisma } from "@/lib/core/shared/prisma";
import { ApiValidationError } from "@/lib/api/validation";
import { validateCustomerCustomFieldValue } from "@/lib/field-authority/custom-field.service";
import { archiveSupplier, createSupplier, findSupplierByIdentity, getSupplierById, listSuppliersForOrganization, updateSupplier } from "./supplier.repository";
import type { CreateSupplierInput, ListSuppliersInput, UpdateSupplierInput } from "./supplier.types";
export async function createNewSupplier(input: CreateSupplierInput) { assert(input.organizationId,"organizationId"); assert(input.displayName,"displayName"); if (await findSupplierByIdentity(input.organizationId,input.displayName,input.taxNumber)) throw new ApiValidationError("A supplier with this identity already exists."); return prisma.$transaction(async tx => { const supplier = await createSupplier(input,tx); if (input.primaryContact && Object.values(input.primaryContact).some(Boolean)) await tx.supplierContact.create({ data: { organizationId: input.organizationId, supplierId: supplier.id, ...input.primaryContact, isPrimary: true } }); if (input.customFields?.length) await persistCustomFields(tx,input.organizationId,supplier.id,input.customFields); return getSupplierById(supplier.id,input.organizationId,tx); }); }
export function listSuppliers(input: ListSuppliersInput) { assert(input.organizationId,"organizationId"); return listSuppliersForOrganization(input); }
export function getSupplierByIdForOrganization(id: string, organizationId: string) { assert(id,"id"); assert(organizationId,"organizationId"); return getSupplierById(id,organizationId); }
export async function updateSupplierDetails(input: UpdateSupplierInput) { assert(input.id,"id"); assert(input.organizationId,"organizationId"); return prisma.$transaction(async tx => { const count = await updateSupplier(input,tx); if (!count.count) throw new ApiValidationError("Supplier not found."); if (input.primaryContact) await tx.supplierContact.updateMany({ where: { supplierId: input.id, organizationId: input.organizationId, isPrimary: true }, data: { ...input.primaryContact } }); if (input.customFields) await persistCustomFields(tx,input.organizationId,input.id,input.customFields); return getSupplierById(input.id,input.organizationId,tx); }); }
export async function archiveSupplierById(id: string, organizationId: string) { assert(id,"id"); assert(organizationId,"organizationId"); const result = await archiveSupplier(id,organizationId); if (!result.count) throw new ApiValidationError("Supplier not found."); }
async function persistCustomFields(tx: any, organizationId: string, supplierId: string, values: Array<{definitionId:string;value:unknown}>) { const ids=[...new Set(values.map(v=>v.definitionId))]; const defs=await tx.customFieldDefinition.findMany({where:{organizationId,module:"suppliers",entityType:"supplier",active:true,id:{in:ids}}}); if(defs.length!==ids.length) throw new ApiValidationError("Supplier custom field definition is unavailable."); for(const item of values){const d=defs.find((x:any)=>x.id===item.definitionId)!; const value=validateCustomerCustomFieldValue(d,organizationId,item.value); if(value===null||value==="") await tx.supplierCustomFieldValue.deleteMany({where:{supplierId,definitionId:item.definitionId}}); else await tx.supplierCustomFieldValue.upsert({where:{supplierId_definitionId:{supplierId,definitionId:item.definitionId}},create:{organizationId,supplierId,definitionId:item.definitionId,valueJson:value},update:{valueJson:value}});}}
function assert(value: string, field: string) { if (!value?.trim()) throw new Error(`${field} is required.`); }
