import { isRecord } from "@/lib/api/validation";
export const GOAL_EDIT_FIELD_NAMES = ["title", "period", "revenue", "collection", "startsAt", "endsAt", "status"] as const;
export const GOAL_EDIT_CLEARABLE_FIELD_NAMES = ["revenue", "collection", "startsAt", "endsAt"] as const;
export const GOAL_PERIOD_VALUES = ["MONTHLY", "QUARTERLY", "YEARLY", "CUSTOM"] as const;
export const GOAL_STATUS_VALUES = ["ACTIVE", "COMPLETED", "CANCELLED"] as const;
export type GoalEditFieldName = (typeof GOAL_EDIT_FIELD_NAMES)[number];
export type GoalEditCommand = { type: "set_field"; field: GoalEditFieldName; value: string } | { type: "clear_field"; field: (typeof GOAL_EDIT_CLEARABLE_FIELD_NAMES)[number] } | { type: "revert_field"; field: GoalEditFieldName } | { type: "commit" } | { type: "discard" };
export type GoalEditCommandResolution = { kind: "executable"; command: GoalEditCommand } | { kind: "unsupported" } | { kind: "clarification_required"; message: string };
export type GoalEditCommandExecutionResult = { status: "EXECUTED"; command: GoalEditCommand; appliedField?: string; appliedValue?: string; commitOutcome?: "SAVED"; revertedFields?: string[] } | { status: "UNSUPPORTED" } | { status: "CLARIFICATION_REQUIRED"; message: string } | { status: "NO_ACTIVE_SURFACE" } | { status: "STALE_SURFACE" } | { status: "VALIDATION_FAILED"; reason: string } | { status: "EXECUTION_FAILED"; error: string };
function member(value: unknown, values: readonly string[]): value is string { return typeof value === "string" && values.includes(value); }
export function validateGoalEditCommandResolution(raw: unknown): GoalEditCommandResolution | null { if (!isRecord(raw)) return null; if (raw.result === "unsupported") return { kind: "unsupported" }; if (raw.result === "clarification_required") return typeof raw.message === "string" && raw.message.trim() ? { kind: "clarification_required", message: raw.message.trim() } : null; if (raw.result !== "executable") return null; if (raw.action === "commit" || raw.action === "discard") return { kind: "executable", command: { type: raw.action } }; if (raw.action === "set_field" && member(raw.field, GOAL_EDIT_FIELD_NAMES) && typeof raw.value === "string" && raw.value.trim() && (raw.field !== "period" || member(raw.value, GOAL_PERIOD_VALUES)) && (raw.field !== "status" || member(raw.value, GOAL_STATUS_VALUES))) return { kind: "executable", command: { type: "set_field", field: raw.field as GoalEditFieldName, value: raw.value } }; if (raw.action === "clear_field" && member(raw.field, GOAL_EDIT_CLEARABLE_FIELD_NAMES)) return { kind: "executable", command: { type: "clear_field", field: raw.field as (typeof GOAL_EDIT_CLEARABLE_FIELD_NAMES)[number] } }; if (raw.action === "revert_field" && member(raw.field, GOAL_EDIT_FIELD_NAMES)) return { kind: "executable", command: { type: "revert_field", field: raw.field as GoalEditFieldName } }; return null; }
export function revalidateGoalEditCommandResolution(raw: unknown): GoalEditCommandResolution | null { if (!isRecord(raw)) return null; if (raw.kind === "unsupported") return { kind: "unsupported" }; if (raw.kind === "clarification_required") return typeof raw.message === "string" && raw.message.trim() ? { kind: "clarification_required", message: raw.message.trim() } : null; if (raw.kind !== "executable" || !isRecord(raw.command)) return null; return validateGoalEditCommandResolution({ result: "executable", action: raw.command.type, ...raw.command }); }
