import { isRecord } from "@/lib/api/validation";
export const GOAL_CREATE_FIELD_NAMES = ["title", "period", "scope", "goalType", "revenue", "collection", "startsAt", "endsAt", "currency"] as const;
export const GOAL_CREATE_CLEARABLE_FIELD_NAMES = ["revenue", "collection", "startsAt", "endsAt", "currency"] as const;
export type GoalCreateFieldName = (typeof GOAL_CREATE_FIELD_NAMES)[number];
export type GoalCreateCommand = { type: "set_field"; field: GoalCreateFieldName; value: string } | { type: "clear_field"; field: (typeof GOAL_CREATE_CLEARABLE_FIELD_NAMES)[number] } | { type: "revert_field"; field: GoalCreateFieldName } | { type: "commit" } | { type: "discard" };
export type GoalCreateCommandResolution = { kind: "executable"; command: GoalCreateCommand } | { kind: "unsupported" } | { kind: "clarification_required"; message: string };
export type GoalCreateCommandExecutionResult = { status: "EXECUTED"; command: GoalCreateCommand; appliedField?: string; appliedValue?: string; commitOutcome?: "SAVED"; revertedFields?: string[] } | { status: "UNSUPPORTED" } | { status: "CLARIFICATION_REQUIRED"; message: string } | { status: "NO_ACTIVE_SURFACE" } | { status: "STALE_SURFACE" } | { status: "VALIDATION_FAILED"; reason: string } | { status: "EXECUTION_FAILED"; error: string };
const PERIODS = ["MONTHLY", "QUARTERLY", "YEARLY", "CUSTOM"]; const SCOPES = ["COMPANY", "TEAM", "PERSON", "CUSTOMER_SEGMENT", "PRODUCT", "BRANCH"]; const TYPES = ["SALES", "COLLECTION", "REVENUE", "GROSS_PROFIT", "NEW_CUSTOMER", "ACTIVITY", "CUSTOM"];
function member(value: unknown, values: readonly string[]): value is string { return typeof value === "string" && values.includes(value); }
export function validateGoalCreateCommandResolution(raw: unknown): GoalCreateCommandResolution | null { if (!isRecord(raw)) return null; if (raw.result === "unsupported") return { kind: "unsupported" }; if (raw.result === "clarification_required") return typeof raw.message === "string" && raw.message.trim() ? { kind: "clarification_required", message: raw.message.trim() } : null; if (raw.result !== "executable") return null; if (raw.action === "commit" || raw.action === "discard") return { kind: "executable", command: { type: raw.action } }; if (raw.action === "set_field" && member(raw.field, GOAL_CREATE_FIELD_NAMES) && typeof raw.value === "string" && raw.value.trim() && (raw.field !== "period" || member(raw.value, PERIODS)) && (raw.field !== "scope" || member(raw.value, SCOPES)) && (raw.field !== "goalType" || member(raw.value, TYPES))) return { kind: "executable", command: { type: "set_field", field: raw.field as GoalCreateFieldName, value: raw.value } }; if (raw.action === "clear_field" && member(raw.field, GOAL_CREATE_CLEARABLE_FIELD_NAMES)) return { kind: "executable", command: { type: "clear_field", field: raw.field as (typeof GOAL_CREATE_CLEARABLE_FIELD_NAMES)[number] } }; if (raw.action === "revert_field" && member(raw.field, GOAL_CREATE_FIELD_NAMES)) return { kind: "executable", command: { type: "revert_field", field: raw.field as GoalCreateFieldName } }; return null; }
export function revalidateGoalCreateCommandResolution(raw: unknown): GoalCreateCommandResolution | null { if (!isRecord(raw)) return null; if (raw.kind === "unsupported") return { kind: "unsupported" }; if (raw.kind === "clarification_required") return typeof raw.message === "string" && raw.message.trim() ? { kind: "clarification_required", message: raw.message.trim() } : null; if (raw.kind !== "executable" || !isRecord(raw.command)) return null; return validateGoalCreateCommandResolution({ result: "executable", action: raw.command.type, ...raw.command }); }
