import { beforeEach, describe, expect, it, vi } from "vitest";
const db = vi.hoisted(() => ({ conversation: { findFirst: vi.fn() }, customerDocumentAttachment: { deleteMany: vi.fn(), count: vi.fn(), create: vi.fn(), findFirst: vi.fn(), update: vi.fn() } }));
vi.mock("@/lib/core/shared/prisma", () => ({ prisma: db }));
import { createCustomerAttachmentReference, resolveCustomerAttachment, sanitizeCustomerAttachmentFilename, validateCustomerAttachmentFile } from "../customer-document-attachment.service";
describe("customer document attachment authority", () => {
  beforeEach(() => { vi.clearAllMocks(); db.customerDocumentAttachment.deleteMany.mockResolvedValue({ count: 0 }); db.customerDocumentAttachment.count.mockResolvedValue(0); });
  it("sanitizes path-like filenames and enforces MIME/size", () => { expect(sanitizeCustomerAttachmentFilename("../../vergi\0levhası.pdf")).not.toMatch(/[\\/\0]/); expect(() => validateCustomerAttachmentFile({ name: "x.svg", type: "image/svg+xml", size: 2 })).toThrow("ATTACHMENT_UNSUPPORTED_MIME"); expect(() => validateCustomerAttachmentFile({ name: "x.pdf", type: "application/pdf", size: 11 * 1024 * 1024 })).toThrow("ATTACHMENT_SIZE_INVALID"); });
  it("creates an opaque actor/tenant scoped reference with bounded expiry", async () => { db.customerDocumentAttachment.create.mockImplementation(async ({ data }: { data: Record<string, unknown> }) => ({ ...data, conversationId: null })); const now = new Date("2026-07-19T00:00:00Z"); const result = await createCustomerAttachmentReference({ organizationId: "org-1", actorId: "actor-1", file: new File(["pdf"], "../vergi.pdf", { type: "application/pdf" }), now }); expect(result.attachmentRef).toMatch(/^[0-9a-f-]{36}$/); expect(result.filename).toBe(".._vergi.pdf"); expect(new Date(result.expiresAt).getTime() - now.getTime()).toBe(30 * 60_000); expect(db.customerDocumentAttachment.create).toHaveBeenCalledWith(expect.objectContaining({ data: expect.objectContaining({ organizationId: "org-1", actorUserId: "actor-1" }) })); });
  it("rejects missing/cross-tenant references and expires owned rows", async () => { db.customerDocumentAttachment.findFirst.mockResolvedValueOnce(null); await expect(resolveCustomerAttachment({ organizationId: "org-other", actorId: "actor-1", attachmentRef: "11111111-1111-1111-1111-111111111111" })).rejects.toThrow("ATTACHMENT_NOT_FOUND"); db.customerDocumentAttachment.findFirst.mockResolvedValueOnce({ id: "11111111-1111-1111-1111-111111111111", conversationId: null, expiresAt: new Date(0) }); await expect(resolveCustomerAttachment({ organizationId: "org-1", actorId: "actor-1", attachmentRef: "11111111-1111-1111-1111-111111111111" })).rejects.toThrow("ATTACHMENT_EXPIRED"); expect(db.customerDocumentAttachment.deleteMany).toHaveBeenCalled(); });
  it("rejects conversation mismatch without exposing the attachment", async () => { db.customerDocumentAttachment.findFirst.mockResolvedValue({ id: "11111111-1111-1111-1111-111111111111", conversationId: "conversation-1", expiresAt: new Date("2099-01-01") }); await expect(resolveCustomerAttachment({ organizationId: "org-1", actorId: "actor-1", attachmentRef: "11111111-1111-1111-1111-111111111111", conversationId: "conversation-2" })).rejects.toThrow("ATTACHMENT_CONVERSATION_MISMATCH"); });
});
