import { describe, expect, it, vi } from "vitest";
import { CustomerIngestionPreviewRuntime } from "../customer-ingestion-preview-runtime";
const candidate = { fieldId: "customer.taxNumber", extractedValue: "1234567890", normalizedValue: "1234567890", confidence: .95, source: { sourceId: "doc", mediaType: "application/pdf", page: 1, evidence: "1234567890" }, warnings: [], conflicts: [], conflictStatus: "NONE" as const, requiresUserConfirmation: true as const };
describe("customer ingestion preview runtime", () => {
  it("keeps extraction preview-only and supports accept, reject, edit and apply", () => { const runtime = new CustomerIngestionPreviewRuntime(); runtime.load({ candidates: [candidate], conflicts: [], warnings: [], expiresAt: new Date(Date.now() + 60_000).toISOString() }); expect(runtime.state.lifecycle).toBe("REVIEW_REQUIRED"); expect(runtime.state.draftSnapshot).toEqual({}); runtime.decide(candidate.fieldId, false); expect(runtime.state.rejected).toContain(candidate.fieldId); runtime.decide(candidate.fieldId, true); runtime.edit(candidate.fieldId, "9876543210"); runtime.applyToDraft({}); expect(runtime.state).toMatchObject({ lifecycle: "READY", draftSnapshot: { "customer.taxNumber": "9876543210" } }); expect(runtime.state.executionId).toBeUndefined(); });
  it("cancels without a mutation and rejects expired previews", () => { const runtime = new CustomerIngestionPreviewRuntime(); runtime.load({ candidates: [candidate], conflicts: [], warnings: [], expiresAt: new Date(0).toISOString() }); expect(() => runtime.decide(candidate.fieldId, true)).toThrow("PREVIEW_EXPIRED"); expect(runtime.cancel()).toMatchObject({ lifecycle: "CANCELLED", candidates: [], draftSnapshot: {} }); });
  it("replays once per mounted surface and commits exactly once", async () => { const runtime = new CustomerIngestionPreviewRuntime(); runtime.load({ candidates: [candidate], conflicts: [], warnings: [], expiresAt: new Date(Date.now() + 60_000).toISOString() }); runtime.applyToDraft({}); const replay = vi.fn(); expect(runtime.replayToSurface("surface-1", replay)).toBe(true); expect(runtime.replayToSurface("surface-1", replay)).toBe(false); expect(runtime.replayToSurface("surface-2", replay)).toBe(true); const execute = vi.fn().mockResolvedValue({ executionId: "execution-1", entityId: "customer-1" }); const [first, second] = await Promise.all([runtime.commit(execute), runtime.commit(execute)]); expect(first).toEqual(second); expect(execute).toHaveBeenCalledOnce(); expect(runtime.state).toMatchObject({ lifecycle: "SUCCEEDED", entityId: "customer-1" }); });
  it("requires trusted duplicate selection and explicit create-anyway confirmation", () => { const runtime = new CustomerIngestionPreviewRuntime(); runtime.load({ candidates: [candidate], conflicts: [], warnings: [], duplicateMatches: [{ customerId: "customer-1", strength: "STRONG" }], expiresAt: new Date(Date.now() + 60_000).toISOString() }); expect(runtime.state.lifecycle).toBe("DUPLICATE_CONFLICT"); expect(() => runtime.resolveDuplicate({ kind: "OPEN_EXISTING", customerId: "customer-other" })).toThrow("UNTRUSTED_CUSTOMER_ID"); runtime.resolveDuplicate({ kind: "CREATE_NEW_ANYWAY", confirmed: false }); expect(runtime.state.lifecycle).toBe("DUPLICATE_CONFLICT"); runtime.resolveDuplicate({ kind: "CREATE_NEW_ANYWAY", confirmed: true }); expect(runtime.state.lifecycle).toBe("REVIEW_REQUIRED"); });
});
