import { isRecord } from "@/lib/api/validation";
export const COMPANY_ASSET_CREATE_FIELD_NAMES = ["name", "assetType", "description", "acquisitionDate", "acquisitionValue", "currentBookValue", "estimatedCurrentValue"] as const;
export type CompanyAssetCreateFieldName = (typeof COMPANY_ASSET_CREATE_FIELD_NAMES)[number];
export type CompanyAssetCreateCommand = { type: "set_field"; field: CompanyAssetCreateFieldName; value: string } | { type: "commit" };
export type CompanyAssetCreateCommandResolution = { kind: "executable"; command: CompanyAssetCreateCommand } | { kind: "unsupported" } | { kind: "clarification_required"; message: string };
export type CompanyAssetCreateCommandExecutionResult = { status: "EXECUTED"; command: CompanyAssetCreateCommand; appliedField?: string; appliedValue?: string; commitOutcome?: "SAVED" } | { status: "UNSUPPORTED" } | { status: "CLARIFICATION_REQUIRED"; message: string } | { status: "NO_ACTIVE_SURFACE" } | { status: "STALE_SURFACE" } | { status: "VALIDATION_FAILED"; reason: string } | { status: "EXECUTION_FAILED"; error: string };
const ASSET_TYPES = ["CASH_BANK_REFERENCE", "MACHINE", "VEHICLE", "REAL_ESTATE", "EQUIPMENT", "OTHER_NON_INVENTORY"] as const;
function member(value: unknown, values: readonly string[]): value is string { return typeof value === "string" && values.includes(value); }
export function validateCompanyAssetCreateCommandResolution(raw: unknown): CompanyAssetCreateCommandResolution | null { if (!isRecord(raw)) return null; if (raw.result === "unsupported") return { kind: "unsupported" }; if (raw.result === "clarification_required") return typeof raw.message === "string" && raw.message.trim() ? { kind: "clarification_required", message: raw.message.trim() } : null; if (raw.result !== "executable") return null; if (raw.action === "commit") return { kind: "executable", command: { type: "commit" } }; if (raw.action === "set_field" && member(raw.field, COMPANY_ASSET_CREATE_FIELD_NAMES) && typeof raw.value === "string" && raw.value.trim() && (raw.field !== "assetType" || member(raw.value, ASSET_TYPES))) return { kind: "executable", command: { type: "set_field", field: raw.field as CompanyAssetCreateFieldName, value: raw.value } }; return null; }
export function revalidateCompanyAssetCreateCommandResolution(raw: unknown): CompanyAssetCreateCommandResolution | null { if (!isRecord(raw)) return null; if (raw.kind === "unsupported") return { kind: "unsupported" }; if (raw.kind === "clarification_required") return typeof raw.message === "string" && raw.message.trim() ? { kind: "clarification_required", message: raw.message.trim() } : null; if (raw.kind !== "executable" || !isRecord(raw.command)) return null; return validateCompanyAssetCreateCommandResolution({ result: "executable", action: raw.command.type, ...raw.command }); }
