import { isRecord } from "@/lib/api/validation";
export const COMPANY_SOURCE_CREATE_FIELD_NAMES = ["provider", "sourceType"] as const;
export type CompanySourceCreateFieldName = (typeof COMPANY_SOURCE_CREATE_FIELD_NAMES)[number];
export type CompanySourceCreateCommand = { type: "set_field"; field: CompanySourceCreateFieldName; value: string } | { type: "commit" };
export type CompanySourceCreateCommandResolution = { kind: "executable"; command: CompanySourceCreateCommand } | { kind: "unsupported" } | { kind: "clarification_required"; message: string };
export type CompanySourceCreateCommandExecutionResult = { status: "EXECUTED"; command: CompanySourceCreateCommand; appliedField?: string; appliedValue?: string; commitOutcome?: "SAVED" } | { status: "UNSUPPORTED" } | { status: "CLARIFICATION_REQUIRED"; message: string } | { status: "NO_ACTIVE_SURFACE" } | { status: "STALE_SURFACE" } | { status: "VALIDATION_FAILED"; reason: string } | { status: "EXECUTION_FAILED"; error: string };
const SOURCE_TYPES = ["ERP", "CRM", "ACCOUNTING", "DOCUMENT", "API", "OTHER"] as const;
function member(value: unknown, values: readonly string[]): value is string { return typeof value === "string" && values.includes(value); }
export function validateCompanySourceCreateCommandResolution(raw: unknown): CompanySourceCreateCommandResolution | null { if (!isRecord(raw)) return null; if (raw.result === "unsupported") return { kind: "unsupported" }; if (raw.result === "clarification_required") return typeof raw.message === "string" && raw.message.trim() ? { kind: "clarification_required", message: raw.message.trim() } : null; if (raw.result !== "executable") return null; if (raw.action === "commit") return { kind: "executable", command: { type: "commit" } }; if (raw.action === "set_field" && member(raw.field, COMPANY_SOURCE_CREATE_FIELD_NAMES) && typeof raw.value === "string" && raw.value.trim() && (raw.field !== "sourceType" || member(raw.value, SOURCE_TYPES))) return { kind: "executable", command: { type: "set_field", field: raw.field as CompanySourceCreateFieldName, value: raw.value } }; return null; }
export function revalidateCompanySourceCreateCommandResolution(raw: unknown): CompanySourceCreateCommandResolution | null { if (!isRecord(raw)) return null; if (raw.kind === "unsupported") return { kind: "unsupported" }; if (raw.kind === "clarification_required") return typeof raw.message === "string" && raw.message.trim() ? { kind: "clarification_required", message: raw.message.trim() } : null; if (raw.kind !== "executable" || !isRecord(raw.command)) return null; return validateCompanySourceCreateCommandResolution({ result: "executable", action: raw.command.type, ...raw.command }); }
