import { isRecord } from "@/lib/api/validation";
export const COMPANY_GOAL_CREATE_FIELD_NAMES = ["title", "scope", "goalType", "period", "currency", "targetValue"] as const;
export type CompanyGoalCreateFieldName = (typeof COMPANY_GOAL_CREATE_FIELD_NAMES)[number];
export type CompanyGoalCreateCommand = { type: "set_field"; field: CompanyGoalCreateFieldName; value: string } | { type: "commit" };
export type CompanyGoalCreateCommandResolution = { kind: "executable"; command: CompanyGoalCreateCommand } | { kind: "unsupported" } | { kind: "clarification_required"; message: string };
export type CompanyGoalCreateCommandExecutionResult = { status: "EXECUTED"; command: CompanyGoalCreateCommand; appliedField?: string; appliedValue?: string; commitOutcome?: "SAVED" } | { status: "UNSUPPORTED" } | { status: "CLARIFICATION_REQUIRED"; message: string } | { status: "NO_ACTIVE_SURFACE" } | { status: "STALE_SURFACE" } | { status: "VALIDATION_FAILED"; reason: string } | { status: "EXECUTION_FAILED"; error: string };
const SCOPES = ["COMPANY", "TEAM", "PERSON", "CUSTOMER_SEGMENT", "PRODUCT", "BRANCH"] as const;
const GOAL_TYPES = ["SALES", "COLLECTION", "REVENUE", "GROSS_PROFIT", "NEW_CUSTOMER", "ACTIVITY", "CUSTOM"] as const;
const PERIODS = ["MONTHLY", "QUARTERLY", "YEARLY", "CUSTOM"] as const;
function member(value: unknown, values: readonly string[]): value is string { return typeof value === "string" && values.includes(value); }
export function validateCompanyGoalCreateCommandResolution(raw: unknown): CompanyGoalCreateCommandResolution | null { if (!isRecord(raw)) return null; if (raw.result === "unsupported") return { kind: "unsupported" }; if (raw.result === "clarification_required") return typeof raw.message === "string" && raw.message.trim() ? { kind: "clarification_required", message: raw.message.trim() } : null; if (raw.result !== "executable") return null; if (raw.action === "commit") return { kind: "executable", command: { type: "commit" } }; if (raw.action === "set_field" && member(raw.field, COMPANY_GOAL_CREATE_FIELD_NAMES) && typeof raw.value === "string" && raw.value.trim() && (raw.field !== "scope" || member(raw.value, SCOPES)) && (raw.field !== "goalType" || member(raw.value, GOAL_TYPES)) && (raw.field !== "period" || member(raw.value, PERIODS))) return { kind: "executable", command: { type: "set_field", field: raw.field as CompanyGoalCreateFieldName, value: raw.value } }; return null; }
export function revalidateCompanyGoalCreateCommandResolution(raw: unknown): CompanyGoalCreateCommandResolution | null { if (!isRecord(raw)) return null; if (raw.kind === "unsupported") return { kind: "unsupported" }; if (raw.kind === "clarification_required") return typeof raw.message === "string" && raw.message.trim() ? { kind: "clarification_required", message: raw.message.trim() } : null; if (raw.kind !== "executable" || !isRecord(raw.command)) return null; return validateCompanyGoalCreateCommandResolution({ result: "executable", action: raw.command.type, ...raw.command }); }
