import { isRecord } from "@/lib/api/validation";
export const COMPANY_UNIT_FORM_FIELD_NAMES = ["name", "code", "unitType", "country", "city", "district", "postalCode", "addressLine1", "addressLine2"] as const;
export type CompanyUnitFormFieldName = (typeof COMPANY_UNIT_FORM_FIELD_NAMES)[number];
export type CompanyUnitFormCommand = { type: "set_field"; field: CompanyUnitFormFieldName; value: string } | { type: "commit" } | { type: "discard" } | { type: "load_unit"; unitId: string };
export type CompanyUnitFormCommandResolution = { kind: "executable"; command: CompanyUnitFormCommand } | { kind: "unsupported" } | { kind: "clarification_required"; message: string };
export type CompanyUnitFormCommandExecutionResult = { status: "EXECUTED"; command: CompanyUnitFormCommand; appliedField?: string; appliedValue?: string; commitOutcome?: "SAVED" } | { status: "TARGET_NOT_FOUND" } | { status: "UNSUPPORTED" } | { status: "CLARIFICATION_REQUIRED"; message: string } | { status: "NO_ACTIVE_SURFACE" } | { status: "STALE_SURFACE" } | { status: "VALIDATION_FAILED"; reason: string } | { status: "EXECUTION_FAILED"; error: string };
function member(value: unknown, values: readonly string[]): value is string { return typeof value === "string" && values.includes(value); }
export function validateCompanyUnitFormCommandResolution(raw: unknown): CompanyUnitFormCommandResolution | null { if (!isRecord(raw)) return null; if (raw.result === "unsupported") return { kind: "unsupported" }; if (raw.result === "clarification_required") return typeof raw.message === "string" && raw.message.trim() ? { kind: "clarification_required", message: raw.message.trim() } : null; if (raw.result !== "executable") return null; if (raw.action === "commit" || raw.action === "discard") return { kind: "executable", command: { type: raw.action } }; if (raw.action === "set_field" && member(raw.field, COMPANY_UNIT_FORM_FIELD_NAMES) && typeof raw.value === "string" && raw.value.trim()) return { kind: "executable", command: { type: "set_field", field: raw.field as CompanyUnitFormFieldName, value: raw.value } }; if (raw.action === "load_unit" && typeof raw.unitId === "string" && raw.unitId.trim()) return { kind: "executable", command: { type: "load_unit", unitId: raw.unitId } }; return null; }
export function revalidateCompanyUnitFormCommandResolution(raw: unknown): CompanyUnitFormCommandResolution | null { if (!isRecord(raw)) return null; if (raw.kind === "unsupported") return { kind: "unsupported" }; if (raw.kind === "clarification_required") return typeof raw.message === "string" && raw.message.trim() ? { kind: "clarification_required", message: raw.message.trim() } : null; if (raw.kind !== "executable" || !isRecord(raw.command)) return null; return validateCompanyUnitFormCommandResolution({ result: "executable", action: raw.command.type, ...raw.command }); }
