import { isRecord } from "@/lib/api/validation";
export const COMPANY_PROFILE_CANDIDATE_FIELD_NAMES = ["taxOffice", "taxNumber", "mersisNo", "tradeRegistryNo", "chamberRegistration", "kepAddress", "eInvoiceEnabled", "eArchiveEnabled", "authorizedRepresentativesJson", "officialDocumentsJson", "baseCurrency", "currenciesJson", "fiscalYearStartMonth", "defaultPaymentTerms", "standardMaturityDays", "discountPolicy", "creditRiskPolicy", "profitabilityPolicy", "budgetPeriod"] as const;
export const COMPANY_PROFILE_CANDIDATE_CLEARABLE_FIELD_NAMES = COMPANY_PROFILE_CANDIDATE_FIELD_NAMES;
export type CompanyProfileCandidateFieldName = (typeof COMPANY_PROFILE_CANDIDATE_FIELD_NAMES)[number];
export type CompanyProfileCandidateCommand = { type: "set_field"; field: CompanyProfileCandidateFieldName; value: string } | { type: "clear_field"; field: (typeof COMPANY_PROFILE_CANDIDATE_CLEARABLE_FIELD_NAMES)[number] } | { type: "revert_field"; field: CompanyProfileCandidateFieldName } | { type: "commit" } | { type: "discard" };
export type CompanyProfileCandidateCommandResolution = { kind: "executable"; command: CompanyProfileCandidateCommand } | { kind: "unsupported" } | { kind: "clarification_required"; message: string };
export type CompanyProfileCandidateCommandExecutionResult = { status: "EXECUTED"; command: CompanyProfileCandidateCommand; appliedField?: string; appliedValue?: string; commitOutcome?: "PENDING_APPROVAL"; revertedFields?: string[] } | { status: "UNSUPPORTED" } | { status: "CLARIFICATION_REQUIRED"; message: string } | { status: "NO_ACTIVE_SURFACE" } | { status: "STALE_SURFACE" } | { status: "VALIDATION_FAILED"; reason: string } | { status: "EXECUTION_FAILED"; error: string };
function member(value: unknown, values: readonly string[]): value is string { return typeof value === "string" && values.includes(value); }
export function validateCompanyProfileCandidateCommandResolution(raw: unknown): CompanyProfileCandidateCommandResolution | null { if (!isRecord(raw)) return null; if (raw.result === "unsupported") return { kind: "unsupported" }; if (raw.result === "clarification_required") return typeof raw.message === "string" && raw.message.trim() ? { kind: "clarification_required", message: raw.message.trim() } : null; if (raw.result !== "executable") return null; if (raw.action === "commit" || raw.action === "discard") return { kind: "executable", command: { type: raw.action } }; if (raw.action === "set_field" && member(raw.field, COMPANY_PROFILE_CANDIDATE_FIELD_NAMES) && typeof raw.value === "string" && raw.value.trim()) return { kind: "executable", command: { type: "set_field", field: raw.field as CompanyProfileCandidateFieldName, value: raw.value } }; if (raw.action === "clear_field" && member(raw.field, COMPANY_PROFILE_CANDIDATE_CLEARABLE_FIELD_NAMES)) return { kind: "executable", command: { type: "clear_field", field: raw.field as (typeof COMPANY_PROFILE_CANDIDATE_CLEARABLE_FIELD_NAMES)[number] } }; if (raw.action === "revert_field" && member(raw.field, COMPANY_PROFILE_CANDIDATE_FIELD_NAMES)) return { kind: "executable", command: { type: "revert_field", field: raw.field as CompanyProfileCandidateFieldName } }; return null; }
export function revalidateCompanyProfileCandidateCommandResolution(raw: unknown): CompanyProfileCandidateCommandResolution | null { if (!isRecord(raw)) return null; if (raw.kind === "unsupported") return { kind: "unsupported" }; if (raw.kind === "clarification_required") return typeof raw.message === "string" && raw.message.trim() ? { kind: "clarification_required", message: raw.message.trim() } : null; if (raw.kind !== "executable" || !isRecord(raw.command)) return null; return validateCompanyProfileCandidateCommandResolution({ result: "executable", action: raw.command.type, ...raw.command }); }
