import { isRecord } from "@/lib/api/validation";
export const COMPANY_PROFILE_EDIT_FIELD_NAMES = ["brandName", "legalName", "shortName", "companyType", "foundedAt", "country", "city", "primaryLanguage", "website", "phone", "email", "logoRef", "description", "industry", "subIndustry", "activityAreasJson", "revenueModelJson", "salesChannelsJson", "customerTypesJson", "servedRegionsJson", "seasonality", "supplyStructure", "managementContext"] as const;
export const COMPANY_PROFILE_EDIT_CLEARABLE_FIELD_NAMES = ["legalName", "shortName", "companyType", "foundedAt", "country", "city", "primaryLanguage", "website", "phone", "email", "logoRef", "description", "industry", "subIndustry", "activityAreasJson", "revenueModelJson", "salesChannelsJson", "customerTypesJson", "servedRegionsJson", "seasonality", "supplyStructure", "managementContext"] as const;
export type CompanyProfileEditFieldName = (typeof COMPANY_PROFILE_EDIT_FIELD_NAMES)[number];
export type CompanyProfileEditCommand = { type: "set_field"; field: CompanyProfileEditFieldName; value: string } | { type: "clear_field"; field: (typeof COMPANY_PROFILE_EDIT_CLEARABLE_FIELD_NAMES)[number] } | { type: "revert_field"; field: CompanyProfileEditFieldName } | { type: "commit" } | { type: "discard" };
export type CompanyProfileEditCommandResolution = { kind: "executable"; command: CompanyProfileEditCommand } | { kind: "unsupported" } | { kind: "clarification_required"; message: string };
export type CompanyProfileEditCommandExecutionResult = { status: "EXECUTED"; command: CompanyProfileEditCommand; appliedField?: string; appliedValue?: string; commitOutcome?: "SAVED"; revertedFields?: string[] } | { status: "UNSUPPORTED" } | { status: "CLARIFICATION_REQUIRED"; message: string } | { status: "NO_ACTIVE_SURFACE" } | { status: "STALE_SURFACE" } | { status: "VALIDATION_FAILED"; reason: string } | { status: "EXECUTION_FAILED"; error: string };
function member(value: unknown, values: readonly string[]): value is string { return typeof value === "string" && values.includes(value); }
export function validateCompanyProfileEditCommandResolution(raw: unknown): CompanyProfileEditCommandResolution | null { if (!isRecord(raw)) return null; if (raw.result === "unsupported") return { kind: "unsupported" }; if (raw.result === "clarification_required") return typeof raw.message === "string" && raw.message.trim() ? { kind: "clarification_required", message: raw.message.trim() } : null; if (raw.result !== "executable") return null; if (raw.action === "commit" || raw.action === "discard") return { kind: "executable", command: { type: raw.action } }; if (raw.action === "set_field" && member(raw.field, COMPANY_PROFILE_EDIT_FIELD_NAMES) && typeof raw.value === "string" && raw.value.trim()) return { kind: "executable", command: { type: "set_field", field: raw.field as CompanyProfileEditFieldName, value: raw.value } }; if (raw.action === "clear_field" && member(raw.field, COMPANY_PROFILE_EDIT_CLEARABLE_FIELD_NAMES)) return { kind: "executable", command: { type: "clear_field", field: raw.field as (typeof COMPANY_PROFILE_EDIT_CLEARABLE_FIELD_NAMES)[number] } }; if (raw.action === "revert_field" && member(raw.field, COMPANY_PROFILE_EDIT_FIELD_NAMES)) return { kind: "executable", command: { type: "revert_field", field: raw.field as CompanyProfileEditFieldName } }; return null; }
export function revalidateCompanyProfileEditCommandResolution(raw: unknown): CompanyProfileEditCommandResolution | null { if (!isRecord(raw)) return null; if (raw.kind === "unsupported") return { kind: "unsupported" }; if (raw.kind === "clarification_required") return typeof raw.message === "string" && raw.message.trim() ? { kind: "clarification_required", message: raw.message.trim() } : null; if (raw.kind !== "executable" || !isRecord(raw.command)) return null; return validateCompanyProfileEditCommandResolution({ result: "executable", action: raw.command.type, ...raw.command }); }
