"use client";
import type { CreateCustomerBody } from "@/lib/customers/customers-client";
import { CUSTOMER_BUILT_IN_FIELDS, CUSTOMER_FIELD_SECTIONS } from "@/lib/customers/customer-field-registry";
import type { ModuleFieldDefinition } from "@/lib/field-authority/field-authority";
import { GlassCard, SectionTitle } from "./ui";
export function CustomerAuthorityForm({ value, customFields = [], onChange, errors = {}, registerFieldElement, executiveTargetId }: { value: CreateCustomerBody; customFields?: ModuleFieldDefinition[]; onChange: (key: string, value: unknown) => void; errors?: Record<string, string>; registerFieldElement?: (fieldId: string, element: HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement | null) => void; executiveTargetId?: (field: ModuleFieldDefinition) => string }) {
  const fields = [...CUSTOMER_BUILT_IN_FIELDS, ...customFields].filter((field) => field.writable);
  return <div className="mt-4 space-y-4">{CUSTOMER_FIELD_SECTIONS.map((section) => { const sectionFields = fields.filter((field) => field.uiSection === section); if (!sectionFields.length) return null; return <GlassCard className="p-4" key={section}><SectionTitle>{section}</SectionTitle><div className="grid gap-3 md:grid-cols-2">{sectionFields.map((field) => <AuthorityInput error={errors[field.fieldId]} executiveTargetId={executiveTargetId?.(field)} field={field} key={field.fieldId} onChange={onChange} registerFieldElement={registerFieldElement} value={readValue(value, field)} />)}</div></GlassCard>; })}</div>;
}
function readValue(value: CreateCustomerBody, field: ModuleFieldDefinition): unknown { if (field.custom) return value.customFields?.find((item) => `customer.custom.${item.definitionId}` === field.fieldId)?.value ?? ""; const path = field.key.split("."); let current: unknown = value; for (const part of path) current = typeof current === "object" && current !== null ? (current as Record<string, unknown>)[part] : undefined; return current ?? (field.valueType === "boolean" ? false : ""); }
function AuthorityInput({ field, value, error, onChange, registerFieldElement, executiveTargetId }: { field: ModuleFieldDefinition; value: unknown; error?: string; onChange: (key: string, value: unknown) => void; registerFieldElement?: (fieldId: string, element: HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement | null) => void; executiveTargetId?: string }) { const key = field.custom ? `custom.${field.fieldId.replace("customer.custom.", "")}` : field.key; const common = { className: inputClass, id: field.fieldId, disabled: !field.writable, ...(executiveTargetId ? { "data-executive-target": executiveTargetId } : {}), ref: (element: HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement | null) => registerFieldElement?.(field.fieldId, element) };
  return <label className={field.valueType === "multiline_string" || field.valueType === "address" ? "md:col-span-2" : ""}><span className="text-xs font-medium text-[#8b95a3]">{field.label}{field.requiredOnCreate ? " *" : ""}</span>{field.valueType === "boolean" ? <select {...common} onChange={(event) => onChange(key, event.target.value === "true")} value={String(value)}><option value="false">Pasif</option><option value="true">Aktif</option></select> : field.valueType === "enum" ? <select {...common} onChange={(event) => onChange(key, event.target.value)} value={String(value)}><option value="">Seçiniz</option>{field.validation?.options?.map((option) => <option key={option} value={option}>{option}</option>)}</select> : field.valueType === "multiline_string" ? <textarea {...common} className={`${inputClass} min-h-24 resize-none`} onChange={(event) => onChange(key, event.target.value)} value={String(value)} /> : <input {...common} inputMode={["integer", "money", "percentage"].includes(field.valueType) ? "decimal" : undefined} onChange={(event) => onChange(key, event.target.value)} type={field.valueType === "email" ? "email" : field.valueType === "date" ? "date" : "text"} value={String(value)} />}{error ? <span className="mt-1 block text-[10px] text-[#f16a7a]">{error}</span> : null}</label>; }
const inputClass = "mt-1.5 w-full rounded-xl border border-white/[0.08] bg-white/[0.03] px-3 py-2.5 text-sm text-[#f4f7f8] outline-none focus:border-[#34e6cf]/40 disabled:opacity-50";
