"use client";
import { useRef, useState } from "react";
import { useExecutivePresence } from "@/components/executive-presence/ExecutivePresenceContext";
import type { DocumentLifecycleEnvelope } from "@/lib/executive-lifecycle";
import type { StructuredFieldCandidate } from "@/lib/field-authority/structured-field-ingestion";
import type { ModuleFieldDefinition } from "@/lib/field-authority/field-authority";
import { CUSTOMER_BUILT_IN_FIELDS } from "@/lib/customers/customer-field-registry";
import { GlassCard, SectionTitle } from "./ui";
type Extraction = { lifecycle: "REVIEW_REQUIRED" | "DUPLICATE_CONFLICT"; attachment: { attachmentRef: string; filename: string; mimeType: string; size: number; expiresAt: string }; extractionRequestId: string; candidates: StructuredFieldCandidate[]; unsupportedObservations: Array<{ label: string; explanation: string }>; duplicates: Array<{ customerId: string; displayName: string; strength: "STRONG" | "WEAK"; matchedFields: string[] }>; requiresExplicitCommit: true };
export function CustomerDocumentIngestionPanel({ customFields, onApply }: { customFields: ModuleFieldDefinition[]; onApply: (key: string, value: unknown) => void }) {
  const { publishLifecycleEnvelope } = useExecutivePresence();
  const lifecycleRef = useRef<{ documentId: string; correlationId: string; filename: string; mediaType: string } | null>(null);
  const [state, setState] = useState<"IDLE" | "UPLOADING" | "REVIEW_REQUIRED" | "FAILED" | "APPLIED">("IDLE"); const [extraction, setExtraction] = useState<Extraction | null>(null); const [accepted, setAccepted] = useState<string[]>([]); const [edits, setEdits] = useState<Record<string, unknown>>({}); const [error, setError] = useState<string>(); const inputRef = useRef<HTMLInputElement>(null);
  function emit(source: DocumentLifecycleEnvelope["source"], phase: DocumentLifecycleEnvelope["phase"], status: DocumentLifecycleEnvelope["status"], summary: string, metadata: Partial<DocumentLifecycleEnvelope["document"]> = {}, errorMessage?: string) { const lifecycle = lifecycleRef.current; if (!lifecycle) return; publishLifecycleEnvelope({ envelopeId: `${source}:${lifecycle.documentId}:${phase}`, source, phase, status, timestamp: Date.now(), correlationId: lifecycle.correlationId, sessionId: lifecycle.correlationId, module: "customers", summary, outcome: status === "failed" ? "failed" : status === "cancelled" ? "cancelled" : undefined, recoverability: status === "failed" ? "retryable" : undefined, error: errorMessage ? { code: "DOCUMENT_LIFECYCLE_FAILED", message: errorMessage, retryable: true } : undefined, document: { documentId: lifecycle.documentId, filename: lifecycle.filename, mediaType: lifecycle.mediaType, ...metadata } }); }
  async function upload(file: File) { const correlationId = crypto.randomUUID(); lifecycleRef.current = { documentId: crypto.randomUUID(), correlationId, filename: file.name, mediaType: file.type }; setState("UPLOADING"); setError(undefined); const form = new FormData(); form.set("file", file); try { const uploadResponse = await fetch("/api/customers/document-attachments", { method: "POST", credentials: "include", body: form }); const uploadJson = await uploadResponse.json() as { ok: true; data: { attachmentRef: string } } | { ok: false; error: { message: string } }; if (!uploadJson.ok) throw new Error(uploadJson.error.message); lifecycleRef.current.documentId = uploadJson.data.attachmentRef; emit("document", "uploaded", "succeeded", "Dosya kabul edildi"); emit("extraction", "extracting", "active", "Belge alanları çıkarılıyor"); const response = await fetch("/api/customers/document-extractions", { method: "POST", credentials: "include", headers: { "Content-Type": "application/json", "X-Correlation-Id": correlationId }, body: JSON.stringify({ attachmentRef: uploadJson.data.attachmentRef, targetOperation: "CREATE_NEW_CUSTOMER" }) }); const json = await response.json() as { ok: true; data: Extraction } | { ok: false; error: { message: string } }; if (!json.ok) throw new Error(json.error.message); setExtraction(json.data); setAccepted(json.data.candidates.filter((item) => item.conflictStatus === "NONE").map((item) => item.fieldId)); sessionStorage.setItem("metrix-customer-ingestion-preview", JSON.stringify({ ...json.data, correlationId })); setState("REVIEW_REQUIRED"); emit("extraction", "extracted", "succeeded", "Belge çıkarımı tamamlandı", { extractedFieldCount: json.data.candidates.length }); emit("preview", "preview_ready", "succeeded", "Belge önizlemesi hazır", { extractedFieldCount: json.data.candidates.length, previewRef: json.data.attachment.attachmentRef }); } catch (cause) { const message = cause instanceof Error ? cause.message : "Belge işlenemedi."; setError(message); setState("FAILED"); emit("extraction", "failed", "failed", "Belge çıkarımı başarısız", {}, message); } finally { if (inputRef.current) inputRef.current.value = ""; } }
  function apply() { if (!extraction || extraction.duplicates.some((item) => item.strength === "STRONG")) return; const registry = [...CUSTOMER_BUILT_IN_FIELDS, ...customFields]; let applied = 0; for (const candidate of extraction.candidates) { if (!accepted.includes(candidate.fieldId) || candidate.conflictStatus === "CONFLICT") continue; const field = registry.find((item) => item.fieldId === candidate.fieldId); if (!field?.writable) continue; const key = field.custom ? `custom.${field.fieldId.replace("customer.custom.", "")}` : field.key; onApply(key, edits[candidate.fieldId] ?? candidate.normalizedValue); applied += 1; } sessionStorage.setItem("metrix-customer-ingestion-preview", JSON.stringify({ ...extraction, lifecycle: "READY", accepted, rejected: extraction.candidates.map((item) => item.fieldId).filter((id) => !accepted.includes(id)), edits, correlationId: lifecycleRef.current?.correlationId })); setState("APPLIED"); emit("preview", "draft_handoff", "succeeded", "Seçilen alanlar taslağa aktarıldı", { extractedFieldCount: applied }); }
  function cancel() { emit("preview", "cancelled", "cancelled", "Belge önizlemesi iptal edildi"); if (extraction) void fetch(`/api/customers/document-attachments/${encodeURIComponent(extraction.attachment.attachmentRef)}`, { method: "DELETE", credentials: "include" }); sessionStorage.removeItem("metrix-customer-ingestion-preview"); setExtraction(null); setAccepted([]); setEdits({}); setError(undefined); setState("IDLE"); }
  return <GlassCard className="mt-4 p-4"><SectionTitle>Belgeden müşteri taslağı</SectionTitle><p className="mb-3 text-xs text-[#8b95a3]">JPEG, PNG, WebP veya PDF yükleyin. Çıkarılan bilgiler siz inceleyip taslağa uygulayana kadar kaydedilmez.</p><input ref={inputRef} accept="image/jpeg,image/png,image/webp,application/pdf" className="block w-full text-xs text-[#8b95a3] file:mr-3 file:rounded-lg file:border-0 file:bg-[#34e6cf]/10 file:px-3 file:py-2 file:text-[#34e6cf]" disabled={state === "UPLOADING"} onChange={(event) => { const file = event.target.files?.[0]; if (file) void upload(file); }} type="file" />{state === "UPLOADING" ? <p className="mt-3 text-xs text-[#8b95a3]">Belge çıkarılıyor…</p> : null}{error ? <p className="mt-3 text-xs text-[#f16a7a]">{error}</p> : null}{extraction ? <div className="mt-4 space-y-3">{extraction.duplicates.length ? <div className="rounded-xl border border-amber-400/30 bg-amber-400/5 p-3 text-xs text-amber-200">Olası mevcut müşteri: {extraction.duplicates.map((item) => `${item.displayName} (${item.matchedFields.join(", ")})`).join("; ")}. Güçlü eşleşme çözülmeden yeni kayıt taslağına uygulanamaz.</div> : null}{extraction.candidates.map((candidate) => { const field = [...CUSTOMER_BUILT_IN_FIELDS, ...customFields].find((item) => item.fieldId === candidate.fieldId); return <label className="block rounded-xl border border-white/[0.08] p-3" key={candidate.fieldId}><span className="flex items-center gap-2 text-xs text-[#dce3e8]"><input checked={accepted.includes(candidate.fieldId)} onChange={(event) => setAccepted((current) => event.target.checked ? [...new Set([...current, candidate.fieldId])] : current.filter((id) => id !== candidate.fieldId))} type="checkbox" />{field?.label ?? candidate.fieldId}<span className="ml-auto text-[#6f7a86]">%{Math.round(candidate.confidence * 100)}</span></span><input className="mt-2 w-full rounded-lg border border-white/[0.08] bg-white/[0.03] px-2 py-1.5 text-xs" onChange={(event) => setEdits((current) => ({ ...current, [candidate.fieldId]: event.target.value }))} value={String(edits[candidate.fieldId] ?? candidate.normalizedValue ?? "")} />{candidate.source.evidence ? <span className="mt-1 block text-[10px] text-[#6f7a86]">{candidate.source.page ? `Sayfa ${candidate.source.page}: ` : ""}{candidate.source.evidence}</span> : null}</label>; })}<div className="flex gap-2"><button className="rounded-lg bg-[#34e6cf] px-3 py-2 text-xs font-semibold text-[#07110f] disabled:opacity-40" disabled={extraction.duplicates.some((item) => item.strength === "STRONG") || state === "APPLIED"} onClick={apply} type="button">{state === "APPLIED" ? "Taslağa uygulandı" : "Seçilenleri taslağa uygula"}</button><button className="rounded-lg border border-white/10 px-3 py-2 text-xs" onClick={cancel} type="button">İptal</button></div><p className="text-[10px] text-[#6f7a86]">Müşteriyi kaydetmek için aşağıdaki Oluştur düğmesi ayrıca kullanılmalıdır.</p></div> : null}</GlassCard>;
}
