import { describe, expect, it } from "vitest";
import { applyFieldDraftOperation, createFieldAuthorityDraft } from "../field-authority-draft";
import { mergeCustomFieldDefinitions, validateModuleFieldRegistry } from "../field-authority";
import { CUSTOMER_BUILT_IN_FIELDS, customerCustomDefinitionToField } from "@/lib/customers/customer-field-registry";
describe("universal module field authority", () => {
  it("registers every persisted customer area with unique typed authority", () => { expect(validateModuleFieldRegistry(CUSTOMER_BUILT_IN_FIELDS)).toEqual([]); expect(new Set(CUSTOMER_BUILT_IN_FIELDS.map((field) => field.fieldId)).size).toBe(CUSTOMER_BUILT_IN_FIELDS.length); expect(CUSTOMER_BUILT_IN_FIELDS.map((field) => field.fieldId)).toEqual(expect.arrayContaining(["customer.displayName", "customer.primaryContact.fullName", "customer.billingAddress.city", "customer.shippingAddress.postalCode", "customer.currency", "customer.commercialTerms.paymentTermDays", "customer.balanceCents", "customer.createdAt"])); expect(CUSTOMER_BUILT_IN_FIELDS.find((field) => field.fieldId === "customer.displayName")).toMatchObject({ requiredOnCreate: true, clearable: false }); expect(CUSTOMER_BUILT_IN_FIELDS.find((field) => field.fieldId === "customer.balanceCents")).toMatchObject({ writable: false }); });
  it("uses one draft contract for scalar, nested, clear, validation, reset and rebase", () => { let draft = createFieldAuthorityDraft(); const context = { operation: "create" as const, permissions: ["customers.write", "customers.read"] }; draft = applyFieldDraftOperation(draft, { kind: "set_field", fieldId: "customer.displayName", value: " Arda Yapı " }, CUSTOMER_BUILT_IN_FIELDS, context); draft = applyFieldDraftOperation(draft, { kind: "set_nested_field", fieldId: "customer.primaryContact.fullName", nestedKey: "fullName", value: "Murat Arda" }, CUSTOMER_BUILT_IN_FIELDS, context); expect(draft.values["customer.displayName"]).toBe("Arda Yapı"); expect(draft.values["customer.primaryContact.fullName"]).toBe("Murat Arda"); expect(() => applyFieldDraftOperation(draft, { kind: "clear_field", fieldId: "customer.displayName" }, CUSTOMER_BUILT_IN_FIELDS, context)).toThrow("FIELD_NOT_CLEARABLE"); expect(applyFieldDraftOperation(draft, { kind: "validate" }, CUSTOMER_BUILT_IN_FIELDS, context).errors).toEqual({}); expect(applyFieldDraftOperation(draft, { kind: "rebase", values: { "customer.displayName": "Yeni" } }, CUSTOMER_BUILT_IN_FIELDS, context).dirty).toEqual([]); });
  it("merges tenant-provided custom definitions without weakening registry validation", () => { const custom = customerCustomDefinitionToField({ id: "field_1", organizationId: "org_1", key: "bayi_bolgesi", label: "Bayi Bölgesi", description: null, valueType: "string", required: false, options: null, active: true }); expect(mergeCustomFieldDefinitions(CUSTOMER_BUILT_IN_FIELDS, [custom])).toContainEqual(expect.objectContaining({ fieldId: "customer.custom.field_1", custom: true, storageKind: "custom_value" })); expect(() => mergeCustomFieldDefinitions(CUSTOMER_BUILT_IN_FIELDS, [{ ...custom, fieldId: "customer.displayName" }])).toThrow("Duplicate fieldId"); });
});
