import type { ModuleFieldDefinition, ModuleFieldValueType } from "@/lib/field-authority/field-authority";

export const UNIVERSAL_INPUT_TARGET_KINDS = ["page", "surface", "section", "field", "selection", "attachment", "action"] as const;
export type UniversalInputTargetKind = (typeof UNIVERSAL_INPUT_TARGET_KINDS)[number];
export const UNIVERSAL_SURFACE_TYPES = ["page", "workspace", "form", "section", "tab_list", "tab", "tab_panel", "accordion", "accordion_item", "dialog", "modal", "drawer", "side_panel", "bottom_sheet", "popover", "overlay", "wizard", "wizard_step", "table", "editable_table", "grid", "editable_grid", "list", "detail", "create", "edit", "composer", "floating_composer", "command_panel", "activity_panel", "document_preview", "attachment_review", "approval", "custom"] as const;
export type UniversalSurfaceType = (typeof UNIVERSAL_SURFACE_TYPES)[number];
export type UniversalSurfaceState = Readonly<{ visible: boolean; active: boolean; open: boolean; expanded: boolean; selected: boolean; modal: boolean; disabled: boolean; currentStep?: number; selectedChildTargetId?: string }>;
export const UNIVERSAL_INPUT_FIELD_TYPES = ["text", "multiline", "phone", "email", "integer", "number", "money", "percentage", "boolean", "date", "datetime", "enum", "address", "contact", "json", "file", "image", "document", "lookup", "entity_picker", "multi_select", "editable_grid", "custom"] as const;
export type UniversalInputFieldType = (typeof UNIVERSAL_INPUT_FIELD_TYPES)[number];
export type UniversalInputValidation = { state?: "unknown" | "valid" | "invalid" | "missing"; message?: string; min?: number; max?: number; pattern?: string; options?: readonly string[] };
export type UniversalInputAttachmentAcceptance = { mediaTypes: readonly string[]; extensions?: readonly string[]; maxBytes?: number; multiple: boolean };
export type UniversalInputTargetDescriptor = Readonly<{
  executiveTargetId: string; authorityKey: string; targetKind: UniversalInputTargetKind; module: string; entityType?: string; entityId?: string;
  fieldId?: string; fieldType?: UniversalInputFieldType; label: string; description?: string; parentTargetId?: string; sectionId?: string; surfaceId?: string;
  required?: boolean; readable?: boolean; mutable?: boolean; clearable?: boolean; focusable?: boolean; selectable?: boolean; supportsVoice?: boolean; supportsDraft?: boolean;
  supportsApproval?: boolean; approvalPolicy?: ModuleFieldDefinition["approvalPolicy"]; riskLevel?: ModuleFieldDefinition["riskLevel"];
  permissionRead?: string; permissionWrite?: string | null; validation?: UniversalInputValidation; actionName?: string; draftActionName?: string; commitActionName?: string;
  attachmentAcceptance?: UniversalInputAttachmentAcceptance; aliases?: readonly string[]; order?: number; visibility?: "visible" | "hidden"; disabled?: boolean; readOnly?: boolean;
  surfaceType?: UniversalSurfaceType; parentSurfaceId?: string; rootPageId?: string; navigationScope?: string; focusScope?: boolean; modal?: boolean; dismissible?: boolean; closable?: boolean; openable?: boolean; activatable?: boolean; expandable?: boolean; collapsible?: boolean; stepNavigable?: boolean; active?: boolean; mounted?: boolean; zOrder?: number; selectedChildTargetId?: string; activeStepTargetId?: string; currentStepIndex?: number; stepCount?: number; expanded?: boolean; open?: boolean; selected?: boolean; openActionName?: string; closeActionName?: string; activateActionName?: string; dismissActionName?: string;
}>;
export type UniversalInputValidationResult = Readonly<{ valid: boolean; message?: string; missing?: boolean }>;
export type UniversalInputAttachment = Readonly<{ name: string; mediaType: string; size: number; payload: unknown }>;
export type UniversalInputTargetRuntimeAdapter = Readonly<{
  read?: () => unknown | Promise<unknown>; set?: (value: unknown) => unknown | Promise<unknown>; clear?: () => unknown | Promise<unknown>;
  focus?: () => void | Promise<void>; reveal?: () => void | Promise<void>; validate?: () => UniversalInputValidationResult | Promise<UniversalInputValidationResult>;
  select?: (value: unknown) => unknown | Promise<unknown>; open?: () => void | Promise<void>; close?: () => void | Promise<void>;
  commit?: () => unknown | Promise<unknown>; cancel?: () => unknown | Promise<unknown>; createDraft?: () => unknown | Promise<unknown>;
  receiveAttachment?: (attachment: UniversalInputAttachment) => unknown | Promise<unknown>;
  readState?: () => UniversalSurfaceState | Promise<UniversalSurfaceState>; activate?: () => unknown | Promise<unknown>; deactivate?: () => unknown | Promise<unknown>; expand?: () => unknown | Promise<unknown>; collapse?: () => unknown | Promise<unknown>; nextStep?: () => unknown | Promise<unknown>; previousStep?: () => unknown | Promise<unknown>; goToStep?: (step: number) => unknown | Promise<unknown>; dismiss?: () => unknown | Promise<unknown>;
}>;
export type UniversalInputRegistration = Readonly<{ registrationToken: string; generation: number; descriptor: UniversalInputTargetDescriptor; adapter: UniversalInputTargetRuntimeAdapter; mountedAt: string; updatedAt: string }>;

export type UniversalSurfaceDiscovery = Readonly<{ activePage: UniversalInputTargetDescriptor | null; activeWorkspace: UniversalInputTargetDescriptor | null; activeSurfacePath: readonly UniversalInputTargetDescriptor[]; visibleSurfaces: readonly UniversalInputTargetDescriptor[]; activeSurfaces: readonly UniversalInputTargetDescriptor[]; openDialogs: readonly UniversalInputTargetDescriptor[]; openDrawers: readonly UniversalInputTargetDescriptor[]; activeTabs: readonly UniversalInputTargetDescriptor[]; activeTabPanels: readonly UniversalInputTargetDescriptor[]; expandedSections: readonly UniversalInputTargetDescriptor[]; activeWizard: UniversalInputTargetDescriptor | null; activeWizardStep: UniversalInputTargetDescriptor | null; modalStack: readonly UniversalInputTargetDescriptor[]; topInteractionSurface: UniversalInputTargetDescriptor | null; focusScope: UniversalInputTargetDescriptor | null; surfaceCount: number; visibleSurfaceCount: number; activeSurfaceCount: number }>;
export type UniversalInputDiscoverySnapshot = Readonly<{ snapshotId: number; generatedAt: string; activePage: UniversalInputTargetDescriptor | null; activeSurfaces: readonly UniversalInputTargetDescriptor[]; surfaces: UniversalSurfaceDiscovery; sections: readonly UniversalInputTargetDescriptor[]; fields: readonly UniversalInputTargetDescriptor[]; selections: readonly UniversalInputTargetDescriptor[]; attachments: readonly UniversalInputTargetDescriptor[]; actions: readonly UniversalInputTargetDescriptor[]; validation: Readonly<{ valid: number; invalid: number; missing: number; unknown: number }>; writableTargetCount: number; invalidTargetCount: number; requiredMissingTargetCount: number }>;
export type UniversalInputCommandType = "DISCOVER" | "DISCOVER_SURFACES" | "READ" | "READ_SURFACE_STATE" | "SET" | "CLEAR" | "FOCUS" | "REVEAL" | "VALIDATE" | "SELECT" | "OPEN" | "CLOSE" | "COMMIT" | "CANCEL" | "CREATE_DRAFT" | "RECEIVE_ATTACHMENT" | "OPEN_SURFACE" | "CLOSE_SURFACE" | "ACTIVATE_SURFACE" | "DEACTIVATE_SURFACE" | "REVEAL_SURFACE" | "FOCUS_SURFACE" | "SELECT_SURFACE" | "EXPAND_SURFACE" | "COLLAPSE_SURFACE" | "NEXT_STEP" | "PREVIOUS_STEP" | "GO_TO_STEP" | "DISMISS_SURFACE";
export type UniversalInputAuthorityCommand = Readonly<{ type: UniversalInputCommandType; executiveTargetId?: string; authorityKey?: string; expectedRegistrationToken?: string; expectedGeneration?: number; value?: unknown; step?: number; attachment?: UniversalInputAttachment }>;
export type UniversalInputExecutionStatus = "EXECUTED" | "DISCOVERED" | "NOT_FOUND" | "AMBIGUOUS_TARGET" | "CAPABILITY_UNAVAILABLE" | "STALE_TARGET" | "READ_ONLY" | "VALIDATION_FAILED" | "APPROVAL_REQUIRED" | "DRAFT_CREATED" | "CANCELLED" | "SURFACE_HIDDEN" | "SURFACE_DISABLED" | "ALREADY_OPEN" | "ALREADY_CLOSED" | "ALREADY_ACTIVE" | "INVALID_HIERARCHY" | "INVALID_STEP" | "EXECUTION_FAILED";
export type UniversalInputAuthorityExecutionResult = Readonly<{ status: UniversalInputExecutionStatus; descriptor?: UniversalInputTargetDescriptor; registrationToken?: string; generation?: number; value?: unknown; discovery?: UniversalInputDiscoverySnapshot; surfaceDiscovery?: UniversalSurfaceDiscovery; validation?: UniversalInputValidationResult; error?: string; revealChain?: readonly string[] }>;

const FIELD_TYPE_MAP: Record<ModuleFieldValueType, UniversalInputFieldType> = { string: "text", multiline_string: "multiline", phone: "phone", email: "email", integer: "integer", money: "money", percentage: "percentage", boolean: "boolean", date: "date", datetime: "datetime", enum: "enum", address: "address", contact: "contact", json: "json" };
export function mapModuleFieldValueType(valueType: ModuleFieldValueType): UniversalInputFieldType { return FIELD_TYPE_MAP[valueType]; }
