import type { UniversalInputAuthorityCommand, UniversalInputAuthorityExecutionResult, UniversalInputRegistration, UniversalSurfaceState } from "./contracts";
import { UniversalInputRegistry, universalInputRegistry } from "./registry";

const METHODS = { READ: "read", SET: "set", CLEAR: "clear", FOCUS: "focus", REVEAL: "reveal", VALIDATE: "validate", SELECT: "select", OPEN: "open", CLOSE: "close", COMMIT: "commit", CANCEL: "cancel", CREATE_DRAFT: "createDraft", RECEIVE_ATTACHMENT: "receiveAttachment", READ_SURFACE_STATE: "readState", OPEN_SURFACE: "open", CLOSE_SURFACE: "close", ACTIVATE_SURFACE: "activate", DEACTIVATE_SURFACE: "deactivate", REVEAL_SURFACE: "reveal", FOCUS_SURFACE: "focus", SELECT_SURFACE: "select", EXPAND_SURFACE: "expand", COLLAPSE_SURFACE: "collapse", NEXT_STEP: "nextStep", PREVIOUS_STEP: "previousStep", GO_TO_STEP: "goToStep", DISMISS_SURFACE: "dismiss" } as const;
type ExecutableCommand = keyof typeof METHODS;

export class UniversalInputAuthorityHost {
  constructor(private readonly registry: UniversalInputRegistry = universalInputRegistry) {}
  async execute(command: UniversalInputAuthorityCommand): Promise<UniversalInputAuthorityExecutionResult> {
    if (command.type === "DISCOVER") return { status: "DISCOVERED", discovery: this.registry.discover() };
    if (command.type === "DISCOVER_SURFACES") return { status: "DISCOVERED", surfaceDiscovery: this.registry.discover().surfaces };
    const resolved = this.resolve(command); if ("status" in resolved) return resolved; const registration = resolved;
    const stale = this.checkStale(command, registration); if (stale) return stale;
    if ((command.type === "SET" || command.type === "CLEAR") && (!registration.descriptor.mutable || registration.descriptor.readOnly || registration.descriptor.disabled)) return this.result("READ_ONLY", registration);
    if (registration.descriptor.disabled && isSurfaceCommand(command.type)) return this.result("SURFACE_DISABLED", registration);
    if ((command.type === "FOCUS_SURFACE" || command.type === "SELECT_SURFACE") && registration.descriptor.visibility === "hidden") return this.result("SURFACE_HIDDEN", registration);
    if (command.type === "GO_TO_STEP" && (command.step === undefined || command.step < 0 || (registration.descriptor.stepCount !== undefined && command.step >= registration.descriptor.stepCount))) return this.result("INVALID_STEP", registration);
    if ((command.type === "OPEN_SURFACE" && registration.descriptor.open === true) || (command.type === "CLOSE_SURFACE" && registration.descriptor.open === false) || (command.type === "ACTIVATE_SURFACE" && registration.descriptor.active === true)) return this.result(command.type === "OPEN_SURFACE" ? "ALREADY_OPEN" : command.type === "CLOSE_SURFACE" ? "ALREADY_CLOSED" : "ALREADY_ACTIVE", registration);
    if ((command.type === "FOCUS" || command.type === "REVEAL" || command.type === "FOCUS_SURFACE" || command.type === "REVEAL_SURFACE") && this.registry.getAncestors(registration.descriptor.executiveTargetId).length) { const prepared = await this.prepareRevealChain(registration); if (prepared.status !== "EXECUTED") return prepared; }
    return this.invoke(command, registration);
  }
  resolveRevealChain(targetId: string) { return Object.freeze([...this.registry.getAncestors(targetId)].reverse()); }
  private async prepareRevealChain(target: UniversalInputRegistration): Promise<UniversalInputAuthorityExecutionResult> { const completed: string[] = []; for (const descriptor of this.resolveRevealChain(target.descriptor.executiveTargetId)) { const parent = this.registry.getByTargetId(descriptor.executiveTargetId); if (!parent || descriptor.visibility !== "hidden" && descriptor.active !== false && descriptor.expanded !== false && descriptor.open !== false) continue; const method = descriptor.visibility === "hidden" ? parent.adapter.reveal ?? parent.adapter.open : descriptor.expanded === false ? parent.adapter.expand : descriptor.open === false ? parent.adapter.open : parent.adapter.activate ?? parent.adapter.select; if (!method) return { ...this.result("CAPABILITY_UNAVAILABLE", parent), error: `Reveal chain could not prepare ${descriptor.executiveTargetId}.`, revealChain: Object.freeze(completed) }; try { await (method as (value?: unknown) => unknown)(); completed.push(descriptor.executiveTargetId); } catch (error) { return { ...this.result("EXECUTION_FAILED", parent), error: error instanceof Error ? error.message : "Unknown reveal-chain adapter failure.", revealChain: Object.freeze(completed) }; } } return { ...this.result("EXECUTED", target), revealChain: Object.freeze(completed) }; }
  private async invoke(command: UniversalInputAuthorityCommand, registration: UniversalInputRegistration): Promise<UniversalInputAuthorityExecutionResult> { const method = METHODS[command.type as ExecutableCommand]; const capability = method ? registration.adapter[method] : undefined; if (!capability) return this.result("CAPABILITY_UNAVAILABLE", registration); try { let value: unknown; if (command.type === "SET" || command.type === "SELECT") value = await (capability as (value: unknown) => unknown)(command.value); else if (command.type === "GO_TO_STEP") value = await (capability as (step: number) => unknown)(command.step as number); else if (command.type === "RECEIVE_ATTACHMENT") value = command.attachment ? await (capability as (value: NonNullable<typeof command.attachment>) => unknown)(command.attachment) : undefined; else value = await (capability as () => unknown)(); if (command.type === "VALIDATE" && isInvalidValidation(value)) return { ...this.result("VALIDATION_FAILED", registration), validation: value }; return { ...this.result(command.type === "CREATE_DRAFT" ? "DRAFT_CREATED" : command.type === "CANCEL" ? "CANCELLED" : "EXECUTED", registration), value }; } catch (error) { return { ...this.result("EXECUTION_FAILED", registration), error: error instanceof Error ? error.message : "Unknown adapter failure." }; } }
  private resolve(command: UniversalInputAuthorityCommand): UniversalInputRegistration | UniversalInputAuthorityExecutionResult { if (command.executiveTargetId) return this.registry.getByTargetId(command.executiveTargetId) ?? { status: "NOT_FOUND" }; if (!command.authorityKey) return { status: "NOT_FOUND" }; const matches = this.registry.getByAuthorityKey(command.authorityKey); return matches.length === 0 ? { status: "NOT_FOUND" } : matches.length > 1 ? { status: "AMBIGUOUS_TARGET" } : matches[0]; }
  private checkStale(command: UniversalInputAuthorityCommand, registration: UniversalInputRegistration) { return (command.expectedRegistrationToken && command.expectedRegistrationToken !== registration.registrationToken) || (command.expectedGeneration !== undefined && command.expectedGeneration !== registration.generation) ? this.result("STALE_TARGET", registration) : null; }
  private result(status: UniversalInputAuthorityExecutionResult["status"], registration: UniversalInputRegistration): UniversalInputAuthorityExecutionResult { return { status, descriptor: registration.descriptor, registrationToken: registration.registrationToken, generation: registration.generation }; }
}
function isSurfaceCommand(type: UniversalInputAuthorityCommand["type"]) { return type.endsWith("_SURFACE") || ["NEXT_STEP", "PREVIOUS_STEP", "GO_TO_STEP"].includes(type); }
function isInvalidValidation(value: unknown): value is UniversalSurfaceState & { valid: false; message?: string; missing?: boolean } { return typeof value === "object" && value !== null && "valid" in value && value.valid === false; }
export const universalInputAuthorityHost = new UniversalInputAuthorityHost();
