import type { UniversalInputDiscoverySnapshot, UniversalInputRegistration, UniversalInputTargetDescriptor, UniversalInputTargetRuntimeAdapter } from "./contracts";

export type RegisterUniversalInput = { descriptor: UniversalInputTargetDescriptor; adapter: UniversalInputTargetRuntimeAdapter };
const freezeList = <T>(items: T[]): readonly T[] => Object.freeze(items.map((item) => Object.freeze(item)));
const descriptorOrder = (a: UniversalInputRegistration, b: UniversalInputRegistration) => (a.descriptor.order ?? 0) - (b.descriptor.order ?? 0) || a.descriptor.executiveTargetId.localeCompare(b.descriptor.executiveTargetId);

export class UniversalInputRegistry {
  private registrations = new Map<string, UniversalInputRegistration>(); private generation = 0; private version = 0; private tokenSequence = 0; private listeners = new Set<() => void>(); private cachedSnapshot: UniversalInputDiscoverySnapshot | null = null;
  register(input: RegisterUniversalInput): UniversalInputRegistration { const now = new Date().toISOString(); const registration = Object.freeze({ registrationToken: `ui_${++this.tokenSequence}`, generation: ++this.generation, descriptor: Object.freeze({ ...input.descriptor }), adapter: Object.freeze({ ...input.adapter }), mountedAt: now, updatedAt: now }); this.registrations.set(input.descriptor.executiveTargetId, registration); this.changed(); return registration; }
  unregister(targetId: string, registrationToken: string): boolean { const current = this.registrations.get(targetId); if (!current || current.registrationToken !== registrationToken) return false; this.registrations.delete(targetId); this.changed(); return true; }
  updateDescriptor(targetId: string, registrationToken: string, descriptor: UniversalInputTargetDescriptor): UniversalInputRegistration | null { const current = this.registrations.get(targetId); if (!current || current.registrationToken !== registrationToken || descriptor.executiveTargetId !== targetId) return null; const next = Object.freeze({ ...current, descriptor: Object.freeze({ ...descriptor }), updatedAt: new Date().toISOString() }); this.registrations.set(targetId, next); this.changed(); return next; }
  getByTargetId(targetId: string) { return this.registrations.get(targetId) ?? null; }
  getByAuthorityKey(authorityKey: string) { return freezeList(this.list().filter((item) => item.descriptor.authorityKey === authorityKey)); }
  list() { return freezeList([...this.registrations.values()].sort(descriptorOrder)); }
  discover(): UniversalInputDiscoverySnapshot { if (this.cachedSnapshot) return this.cachedSnapshot; const list = this.list(); const descriptors = (kind: UniversalInputTargetDescriptor["targetKind"]) => freezeList(list.filter((item) => item.descriptor.targetKind === kind).map((item) => item.descriptor)); const fields = descriptors("field"); const count = (state: string) => fields.filter((field) => (field.validation?.state ?? "unknown") === state).length; const snapshot = { snapshotId: this.version, generatedAt: new Date().toISOString(), activePage: descriptors("page")[0] ?? null, activeSurfaces: descriptors("surface"), sections: descriptors("section"), fields, selections: descriptors("selection"), attachments: descriptors("attachment"), actions: descriptors("action"), validation: Object.freeze({ valid: count("valid"), invalid: count("invalid"), missing: count("missing"), unknown: count("unknown") }), writableTargetCount: fields.filter((field) => field.mutable && !field.readOnly && !field.disabled).length, invalidTargetCount: count("invalid"), requiredMissingTargetCount: fields.filter((field) => field.required && field.validation?.state === "missing").length }; this.cachedSnapshot = Object.freeze(snapshot); return this.cachedSnapshot; }
  getSnapshot = () => this.discover(); subscribe = (listener: () => void) => { this.listeners.add(listener); return () => this.listeners.delete(listener); };
  resetForTests() { this.registrations.clear(); this.generation = 0; this.version = 0; this.tokenSequence = 0; this.changed(); }
  private changed() { this.version += 1; this.cachedSnapshot = null; for (const listener of this.listeners) listener(); }
}
export const universalInputRegistry = new UniversalInputRegistry();
