import type { UniversalInputDiscoverySnapshot, UniversalInputRegistration, UniversalInputTargetDescriptor, UniversalInputTargetRuntimeAdapter } from "./contracts";

export type RegisterUniversalInput = { descriptor: UniversalInputTargetDescriptor; adapter: UniversalInputTargetRuntimeAdapter };
const freezeList = <T>(items: T[]): readonly T[] => Object.freeze(items.map((item) => Object.freeze(item)));
const descriptorOrder = (a: UniversalInputRegistration, b: UniversalInputRegistration) => (a.descriptor.order ?? 0) - (b.descriptor.order ?? 0) || a.descriptor.executiveTargetId.localeCompare(b.descriptor.executiveTargetId);
const isSurface = (descriptor: UniversalInputTargetDescriptor) => descriptor.surfaceType !== undefined || descriptor.targetKind === "page" || descriptor.targetKind === "surface" || descriptor.targetKind === "section";
const visible = (descriptor: UniversalInputTargetDescriptor) => descriptor.mounted !== false && descriptor.visibility !== "hidden";
const active = (descriptor: UniversalInputTargetDescriptor) => visible(descriptor) && descriptor.active !== false;

export class UniversalInputRegistry {
  private registrations = new Map<string, UniversalInputRegistration>(); private generation = 0; private version = 0; private tokenSequence = 0; private listeners = new Set<() => void>(); private cachedSnapshot: UniversalInputDiscoverySnapshot | null = null;
  register(input: RegisterUniversalInput): UniversalInputRegistration { this.assertHierarchy(input.descriptor); const now = new Date().toISOString(); const registration = Object.freeze({ registrationToken: `ui_${++this.tokenSequence}`, generation: ++this.generation, descriptor: Object.freeze({ ...input.descriptor }), adapter: Object.freeze({ ...input.adapter }), mountedAt: now, updatedAt: now }); this.registrations.set(input.descriptor.executiveTargetId, registration); this.changed(); return registration; }
  unregister(targetId: string, registrationToken: string): boolean { const current = this.registrations.get(targetId); if (!current || current.registrationToken !== registrationToken) return false; this.registrations.delete(targetId); this.changed(); return true; }
  updateDescriptor(targetId: string, registrationToken: string, descriptor: UniversalInputTargetDescriptor): UniversalInputRegistration | null { const current = this.registrations.get(targetId); if (!current || current.registrationToken !== registrationToken || descriptor.executiveTargetId !== targetId) return null; this.assertHierarchy(descriptor); const next = Object.freeze({ ...current, descriptor: Object.freeze({ ...descriptor }), updatedAt: new Date().toISOString() }); this.registrations.set(targetId, next); this.changed(); return next; }
  updateAdapter(targetId: string, registrationToken: string, adapter: UniversalInputTargetRuntimeAdapter): UniversalInputRegistration | null { const current = this.registrations.get(targetId); if (!current || current.registrationToken !== registrationToken) return null; const next = Object.freeze({ ...current, adapter: Object.freeze({ ...adapter }), updatedAt: new Date().toISOString() }); this.registrations.set(targetId, next); this.changed(); return next; }
  getByTargetId(targetId: string) { return this.registrations.get(targetId) ?? null; }
  getByAuthorityKey(authorityKey: string) { return freezeList(this.list().filter((item) => item.descriptor.authorityKey === authorityKey)); }
  list() { return freezeList([...this.registrations.values()].sort(descriptorOrder)); }
  getDirectChildren(targetId: string) { return freezeList(this.list().filter((item) => this.parentId(item.descriptor) === targetId).map((item) => item.descriptor)); }
  getAncestors(targetId: string) { const result: UniversalInputTargetDescriptor[] = []; const seen = new Set<string>(); let current = this.registrations.get(targetId)?.descriptor; while (current) { const parentId = this.parentId(current); if (!parentId || seen.has(parentId)) break; seen.add(parentId); const parent = this.registrations.get(parentId)?.descriptor; if (!parent) break; result.push(parent); current = parent; } return freezeList(result); }
  getDescendants(targetId: string) { const result: UniversalInputTargetDescriptor[] = []; const visit = (id: string) => { for (const child of this.getDirectChildren(id)) { result.push(child); visit(child.executiveTargetId); } }; visit(targetId); return freezeList(result); }
  getRootSurface(targetId: string) { const lineage = [this.registrations.get(targetId)?.descriptor, ...this.getAncestors(targetId)].filter((item): item is UniversalInputTargetDescriptor => item !== undefined).filter(isSurface); return lineage.at(-1) ?? null; }
  getNearestActiveParent(targetId: string) { return this.getAncestors(targetId).find((item) => isSurface(item) && active(item)) ?? null; }
  getNearestFocusScope(targetId: string) { return this.getAncestors(targetId).find((item) => item.focusScope === true && visible(item)) ?? null; }
  getNearestModalParent(targetId: string) { return this.getAncestors(targetId).find((item) => item.modal === true && visible(item)) ?? null; }
  discover(): UniversalInputDiscoverySnapshot { if (this.cachedSnapshot) return this.cachedSnapshot; const list = this.list(); const descriptors = (kind: UniversalInputTargetDescriptor["targetKind"]) => freezeList(list.filter((item) => item.descriptor.targetKind === kind).map((item) => item.descriptor)); const fields = descriptors("field"); const count = (state: string) => fields.filter((field) => (field.validation?.state ?? "unknown") === state).length; const surfaceList = list.map((item) => item.descriptor).filter(isSurface); const visibleSurfaces = freezeList(surfaceList.filter(visible)); const activeSurfaces = freezeList(surfaceList.filter(active)); const byType = (types: readonly string[], source = visibleSurfaces) => freezeList(source.filter((item) => item.surfaceType && types.includes(item.surfaceType)));
    const interaction = [...visibleSurfaces].sort((a, b) => Number(b.modal) - Number(a.modal) || (b.zOrder ?? 0) - (a.zOrder ?? 0) || this.getAncestors(b.executiveTargetId).length - this.getAncestors(a.executiveTargetId).length || a.executiveTargetId.localeCompare(b.executiveTargetId)); const top = interaction[0] ?? null; const path = top ? freezeList([...this.getAncestors(top.executiveTargetId)].reverse().filter(isSurface).concat(top)) : freezeList<UniversalInputTargetDescriptor>([]); const modalStack = freezeList(visibleSurfaces.filter((item) => item.modal).sort((a, b) => (a.zOrder ?? 0) - (b.zOrder ?? 0) || a.executiveTargetId.localeCompare(b.executiveTargetId)));
    const activePage = activeSurfaces.find((item) => item.surfaceType === "page" || item.targetKind === "page") ?? null; const surfaces = Object.freeze({ activePage, activeWorkspace: activeSurfaces.find((item) => item.surfaceType === "workspace") ?? null, activeSurfacePath: path, visibleSurfaces, activeSurfaces, openDialogs: byType(["dialog", "modal"]), openDrawers: byType(["drawer", "side_panel", "bottom_sheet"]), activeTabs: byType(["tab"], activeSurfaces), activeTabPanels: byType(["tab_panel"], activeSurfaces), expandedSections: freezeList(visibleSurfaces.filter((item) => (item.surfaceType === "section" || item.surfaceType === "accordion_item") && item.expanded === true)), activeWizard: activeSurfaces.find((item) => item.surfaceType === "wizard") ?? null, activeWizardStep: activeSurfaces.find((item) => item.surfaceType === "wizard_step") ?? null, modalStack, topInteractionSurface: top, focusScope: interaction.find((item) => item.focusScope) ?? null, surfaceCount: surfaceList.length, visibleSurfaceCount: visibleSurfaces.length, activeSurfaceCount: activeSurfaces.length });
    const snapshot = { snapshotId: this.version, generatedAt: new Date().toISOString(), activePage, activeSurfaces, surfaces, sections: descriptors("section"), fields, selections: descriptors("selection"), attachments: descriptors("attachment"), actions: descriptors("action"), validation: Object.freeze({ valid: count("valid"), invalid: count("invalid"), missing: count("missing"), unknown: count("unknown") }), writableTargetCount: fields.filter((field) => field.mutable && !field.readOnly && !field.disabled).length, invalidTargetCount: count("invalid"), requiredMissingTargetCount: fields.filter((field) => field.required && field.validation?.state === "missing").length }; this.cachedSnapshot = Object.freeze(snapshot); return this.cachedSnapshot; }
  getSnapshot = () => this.discover(); subscribe = (listener: () => void) => { this.listeners.add(listener); return () => this.listeners.delete(listener); };
  resetForTests() { this.registrations.clear(); this.generation = 0; this.version = 0; this.tokenSequence = 0; this.changed(); }
  private changed() { this.version += 1; this.cachedSnapshot = null; for (const listener of this.listeners) listener(); }
  private parentId(descriptor: UniversalInputTargetDescriptor) { return descriptor.parentTargetId ?? descriptor.parentSurfaceId; }
  private assertHierarchy(descriptor: UniversalInputTargetDescriptor) { const parentId = this.parentId(descriptor); if (!parentId) return; if (parentId === descriptor.executiveTargetId) throw new Error("INVALID_HIERARCHY: a target cannot parent itself."); let current = this.registrations.get(parentId)?.descriptor; const seen = new Set([descriptor.executiveTargetId]); while (current) { if (seen.has(current.executiveTargetId)) throw new Error("INVALID_HIERARCHY: cycle detected."); seen.add(current.executiveTargetId); const next = this.parentId(current); if (next === descriptor.executiveTargetId) throw new Error("INVALID_HIERARCHY: cycle detected."); current = next ? this.registrations.get(next)?.descriptor : undefined; } }
}
export const universalInputRegistry = new UniversalInputRegistry();
