import { beforeEach, describe, expect, it, vi } from "vitest";
import { UniversalInputAuthorityHost, UniversalInputRegistry, type UniversalInputTargetDescriptor } from "@/lib/input-authority";

const surface = (id: string, overrides: Partial<UniversalInputTargetDescriptor> = {}): UniversalInputTargetDescriptor => ({ executiveTargetId: id, authorityKey: id, targetKind: id === "page" ? "page" : "surface", surfaceType: id === "page" ? "page" : "section", module: "test", label: id, visibility: "visible", mounted: true, active: true, ...overrides });

describe("universal surface registry", () => {
  let registry: UniversalInputRegistry;
  beforeEach(() => { registry = new UniversalInputRegistry(); });
  it("registers semantic surfaces and returns a stable immutable snapshot", () => { registry.register({ descriptor: surface("page"), adapter: {} }); const first = registry.discover(); expect(first.surfaces.activePage?.executiveTargetId).toBe("page"); expect(first).toBe(registry.discover()); expect(Object.isFrozen(first.surfaces.visibleSurfaces)).toBe(true); });
  it("resolves children, ancestors, descendants and root independent of registration order", () => { registry.register({ descriptor: surface("child", { parentTargetId: "parent" }), adapter: {} }); registry.register({ descriptor: surface("page"), adapter: {} }); registry.register({ descriptor: surface("parent", { parentTargetId: "page" }), adapter: {} }); expect(registry.getDirectChildren("parent").map((x) => x.executiveTargetId)).toEqual(["child"]); expect(registry.getAncestors("child").map((x) => x.executiveTargetId)).toEqual(["parent", "page"]); expect(registry.getDescendants("page").map((x) => x.executiveTargetId)).toEqual(["parent", "child"]); expect(registry.getRootSurface("child")?.executiveTargetId).toBe("page"); });
  it("rejects self-parent and cycles while tolerating missing parents", () => { expect(() => registry.register({ descriptor: surface("self", { parentTargetId: "self" }), adapter: {} })).toThrow("INVALID_HIERARCHY"); registry.register({ descriptor: surface("a", { parentTargetId: "later" }), adapter: {} }); expect(() => registry.register({ descriptor: surface("later", { parentTargetId: "a" }), adapter: {} })).toThrow("INVALID_HIERARCHY"); });
  it("discovers tabs, dialogs, expanded sections and deterministic modal stack", () => { registry.register({ descriptor: surface("z", { surfaceType: "dialog", modal: true, zOrder: 20 }), adapter: {} }); registry.register({ descriptor: surface("a", { surfaceType: "modal", modal: true, zOrder: 10 }), adapter: {} }); registry.register({ descriptor: surface("tab", { surfaceType: "tab", selected: true }), adapter: {} }); registry.register({ descriptor: surface("section", { expanded: true }), adapter: {} }); const discovery = registry.discover().surfaces; expect(discovery.openDialogs).toHaveLength(2); expect(discovery.activeTabs[0].executiveTargetId).toBe("tab"); expect(discovery.expandedSections[0].executiveTargetId).toBe("section"); expect(discovery.modalStack.map((x) => x.executiveTargetId)).toEqual(["a", "z"]); expect(discovery.topInteractionSurface?.executiveTargetId).toBe("z"); });
  it("preserves token and generation stale cleanup protection", () => { const first = registry.register({ descriptor: surface("a"), adapter: {} }); const second = registry.register({ descriptor: surface("a"), adapter: {} }); expect(registry.unregister("a", first.registrationToken)).toBe(false); expect(registry.getByTargetId("a")?.generation).toBe(second.generation); });
});

describe("universal surface host", () => {
  let registry: UniversalInputRegistry; let host: UniversalInputAuthorityHost;
  beforeEach(() => { registry = new UniversalInputRegistry(); host = new UniversalInputAuthorityHost(registry); });
  it.each([["OPEN_SURFACE", "open"], ["CLOSE_SURFACE", "close"], ["ACTIVATE_SURFACE", "activate"], ["DEACTIVATE_SURFACE", "deactivate"], ["EXPAND_SURFACE", "expand"], ["COLLAPSE_SURFACE", "collapse"], ["NEXT_STEP", "nextStep"], ["PREVIOUS_STEP", "previousStep"], ["DISMISS_SURFACE", "dismiss"]] as const)("delegates %s", async (type, method) => { const fn = vi.fn(); registry.register({ descriptor: surface("target", type === "ACTIVATE_SURFACE" ? { active: false } : {}), adapter: { [method]: fn } }); expect((await host.execute({ type, executiveTargetId: "target" })).status).toBe("EXECUTED"); expect(fn).toHaveBeenCalledOnce(); });
  it("reads state, validates steps and reports missing capability and disabled targets", async () => { registry.register({ descriptor: surface("wizard", { surfaceType: "wizard", stepCount: 2 }), adapter: { readState: () => ({ visible: true, active: true, open: true, expanded: false, selected: false, modal: false, disabled: false }), goToStep: vi.fn() } }); expect((await host.execute({ type: "READ_SURFACE_STATE", executiveTargetId: "wizard" })).value).toMatchObject({ open: true }); expect((await host.execute({ type: "GO_TO_STEP", executiveTargetId: "wizard", step: 2 })).status).toBe("INVALID_STEP"); expect((await host.execute({ type: "CLOSE_SURFACE", executiveTargetId: "wizard" })).status).toBe("CAPABILITY_UNAVAILABLE"); registry.register({ descriptor: surface("disabled", { disabled: true }), adapter: { open: vi.fn() } }); expect((await host.execute({ type: "OPEN_SURFACE", executiveTargetId: "disabled" })).status).toBe("SURFACE_DISABLED"); });
  it("prepares hidden tab panel and section before focusing a child", async () => { const calls: string[] = []; registry.register({ descriptor: surface("page"), adapter: {} }); registry.register({ descriptor: surface("panel", { surfaceType: "tab_panel", parentTargetId: "page", visibility: "hidden", active: false }), adapter: { reveal: () => { calls.push("panel"); } } }); registry.register({ descriptor: surface("section", { parentTargetId: "panel", visibility: "hidden", active: false }), adapter: { reveal: () => { calls.push("section"); } } }); registry.register({ descriptor: { executiveTargetId: "field", authorityKey: "field", targetKind: "field", module: "test", label: "field", parentTargetId: "section", focusable: true }, adapter: { focus: () => { calls.push("field"); } } }); const result = await host.execute({ type: "FOCUS", executiveTargetId: "field" }); expect(result.status).toBe("EXECUTED"); expect(calls).toEqual(["panel", "section", "field"]); });
  it("reports partial reveal chains and adapter exceptions", async () => { registry.register({ descriptor: surface("parent", { visibility: "hidden" }), adapter: {} }); registry.register({ descriptor: surface("child", { parentTargetId: "parent" }), adapter: { focus: vi.fn() } }); expect((await host.execute({ type: "FOCUS", executiveTargetId: "child" })).status).toBe("CAPABILITY_UNAVAILABLE"); registry.register({ descriptor: surface("boom"), adapter: { open: () => { throw new Error("boom"); } } }); expect((await host.execute({ type: "OPEN_SURFACE", executiveTargetId: "boom" })).status).toBe("EXECUTION_FAILED"); });
  it("rejects ambiguous authority keys and stale commands", async () => { const first = registry.register({ descriptor: surface("a", { authorityKey: "same" }), adapter: { open: vi.fn() } }); registry.register({ descriptor: surface("b", { authorityKey: "same" }), adapter: {} }); expect((await host.execute({ type: "OPEN_SURFACE", authorityKey: "same" })).status).toBe("AMBIGUOUS_TARGET"); expect((await host.execute({ type: "OPEN_SURFACE", executiveTargetId: "a", expectedGeneration: first.generation + 1 })).status).toBe("STALE_TARGET"); });
});
