import { readFileSync } from "node:fs";
import { describe, expect, it, vi } from "vitest";
import { UniversalInputAuthorityHost } from "../host";
import { UniversalInputRegistry } from "../registry";
import type { UniversalInputTargetDescriptor } from "../contracts";

const field = (id: string, authorityKey = `key.${id}`, overrides: Partial<UniversalInputTargetDescriptor> = {}): UniversalInputTargetDescriptor => ({ executiveTargetId: id, authorityKey, targetKind: "field", module: "test", entityType: "record", fieldId: id, fieldType: "text", label: id, readable: true, mutable: true, clearable: true, focusable: true, order: 0, ...overrides });

describe("Universal Input Registry", () => {
  it("registers, discovers and unregisters targets", () => { const registry = new UniversalInputRegistry(); const registered = registry.register({ descriptor: field("field.a"), adapter: {} }); expect(registry.discover().fields).toHaveLength(1); expect(registry.unregister("field.a", registered.registrationToken)).toBe(true); expect(registry.list()).toHaveLength(0); });
  it("protects a replacement from stale cleanup", () => { const registry = new UniversalInputRegistry(); const old = registry.register({ descriptor: field("field.a"), adapter: {} }); const current = registry.register({ descriptor: field("field.a"), adapter: {} }); expect(registry.unregister("field.a", old.registrationToken)).toBe(false); expect(registry.getByTargetId("field.a")?.registrationToken).toBe(current.registrationToken); });
  it("returns stable immutable snapshots in deterministic order", () => { const registry = new UniversalInputRegistry(); registry.register({ descriptor: field("field.z", "z", { order: 2 }), adapter: {} }); registry.register({ descriptor: field("field.a", "a", { order: 1 }), adapter: {} }); const snapshot = registry.getSnapshot(); expect(snapshot).toBe(registry.getSnapshot()); expect(snapshot.fields.map((item) => item.executiveTargetId)).toEqual(["field.a", "field.z"]); expect(Object.isFrozen(snapshot)).toBe(true); expect(Object.isFrozen(snapshot.fields)).toBe(true); });
  it("resolves authority keys exactly", () => { const registry = new UniversalInputRegistry(); registry.register({ descriptor: field("field.email", "customers.customer.email"), adapter: {} }); expect(registry.getByAuthorityKey("customers.customer.email")).toHaveLength(1); expect(registry.getByAuthorityKey("email")).toHaveLength(0); });
});

describe("Universal Input Authority Host", () => {
  it("rejects ambiguous authority keys", async () => { const registry = new UniversalInputRegistry(); registry.register({ descriptor: field("a", "same"), adapter: { read: () => 1 } }); registry.register({ descriptor: field("b", "same"), adapter: { read: () => 2 } }); expect(await new UniversalInputAuthorityHost(registry).execute({ type: "READ", authorityKey: "same" })).toEqual({ status: "AMBIGUOUS_TARGET" }); });
  it("resolves target IDs and executes SET/CLEAR", async () => { const registry = new UniversalInputRegistry(); const set = vi.fn(); const clear = vi.fn(); registry.register({ descriptor: field("field.a"), adapter: { set, clear } }); const host = new UniversalInputAuthorityHost(registry); expect((await host.execute({ type: "SET", executiveTargetId: "field.a", value: "x" })).status).toBe("EXECUTED"); expect((await host.execute({ type: "CLEAR", executiveTargetId: "field.a" })).status).toBe("EXECUTED"); expect(set).toHaveBeenCalledWith("x"); expect(clear).toHaveBeenCalledOnce(); });
  it("rejects stale generation and token", async () => { const registry = new UniversalInputRegistry(); const registration = registry.register({ descriptor: field("field.a"), adapter: { read: () => 1 } }); const host = new UniversalInputAuthorityHost(registry); expect((await host.execute({ type: "READ", executiveTargetId: "field.a", expectedGeneration: registration.generation + 1 })).status).toBe("STALE_TARGET"); expect((await host.execute({ type: "READ", executiveTargetId: "field.a", expectedRegistrationToken: "old" })).status).toBe("STALE_TARGET"); });
  it("rejects missing capabilities", async () => { const registry = new UniversalInputRegistry(); registry.register({ descriptor: field("field.a"), adapter: {} }); expect((await new UniversalInputAuthorityHost(registry).execute({ type: "FOCUS", executiveTargetId: "field.a" })).status).toBe("CAPABILITY_UNAVAILABLE"); });
  it("rejects writes to read-only targets", async () => { const registry = new UniversalInputRegistry(); registry.register({ descriptor: field("field.a", "a", { mutable: false, readOnly: true }), adapter: { set: vi.fn() } }); expect((await new UniversalInputAuthorityHost(registry).execute({ type: "SET", executiveTargetId: "field.a", value: 1 })).status).toBe("READ_ONLY"); });
  it("propagates validation failure", async () => { const registry = new UniversalInputRegistry(); registry.register({ descriptor: field("field.a"), adapter: { validate: () => ({ valid: false, missing: true, message: "Required" }) } }); const result = await new UniversalInputAuthorityHost(registry).execute({ type: "VALIDATE", executiveTargetId: "field.a" }); expect(result.status).toBe("VALIDATION_FAILED"); expect(result.validation?.missing).toBe(true); });
  it("focuses through the adapter without DOM lookup", async () => { const registry = new UniversalInputRegistry(); const focus = vi.fn(); registry.register({ descriptor: field("field.a"), adapter: { focus } }); expect((await new UniversalInputAuthorityHost(registry).execute({ type: "FOCUS", executiveTargetId: "field.a" })).status).toBe("EXECUTED"); expect(focus).toHaveBeenCalledOnce(); });
  it("delegates COMMIT only to the adapter", async () => { const registry = new UniversalInputRegistry(); const commit = vi.fn().mockResolvedValue({ saved: true }); registry.register({ descriptor: { ...field("action.commit"), targetKind: "action" }, adapter: { commit } }); const result = await new UniversalInputAuthorityHost(registry).execute({ type: "COMMIT", executiveTargetId: "action.commit" }); expect(commit).toHaveBeenCalledOnce(); expect(result.value).toEqual({ saved: true }); });
  it("converts adapter exceptions into safe failures", async () => { const registry = new UniversalInputRegistry(); registry.register({ descriptor: field("field.a"), adapter: { read: () => { throw new Error("boom"); } } }); expect(await new UniversalInputAuthorityHost(registry).execute({ type: "READ", executiveTargetId: "field.a" })).toMatchObject({ status: "EXECUTION_FAILED", error: "boom" }); });
});

describe("generic boundaries", () => {
  const source = (name: string) => readFileSync(new URL(`../${name}`, import.meta.url), "utf8");
  it("keeps customer and persistence imports outside the generic core", () => { const all = [source("contracts.ts"), source("registry.ts"), source("host.ts")].join("\n"); expect(all).not.toMatch(/@\/lib\/customers|prisma|repository/i); });
  it("contains no module routing or DOM authority", () => { const host = source("host.ts"); const registry = source("registry.ts"); expect(host).not.toMatch(/case\s+["'](?:customers|products|suppliers)|querySelector|getElementById/i); expect(registry).not.toMatch(/window|document|CustomEvent/); });
  it("does not leak React or HTMLElement through adapter contracts", () => { const contracts = source("contracts.ts"); expect(contracts).not.toMatch(/HTMLElement|React|setState/); });
});
