import { cancelCustomFieldCreate, confirmCustomFieldCreate, requestCustomFieldCreate } from "./customers-client";
export type CustomFieldConversationLifecycle = "IDLE" | "PLANNING" | "AWAITING_CLARIFICATION" | "AWAITING_APPROVAL" | "SUBMITTING" | "SUCCEEDED" | "FAILED" | "CANCELLED" | "EXPIRED";
export type PendingCustomFieldConversation = { lifecycle: CustomFieldConversationLifecycle; definition?: Record<string, unknown>; approvalId?: string; definitionId?: string; error?: string; updatedAt: string; expiresAt?: string };
const yes = /^(evet|onaylıyorum|onayliyorum|evet[,.]?\s*alanı oluştur|onayla)$/i; const no = /^(hayır|hayir|iptal|vazgeç|vazgec)$/i;
const normalizeKey = (value: string) => value.trim().toLocaleLowerCase("tr-TR").normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/ı/g, "i").replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "").slice(0, 64);
function obviousPlan(utterance: string) { const match = utterance.match(/(?:müşterilere?\s+)?(.+?)\s+(?:diye\s+)?(metin|sayı|tarih|seçim|seçenekli)\s+alan[ıi]\s+(?:ekle|oluştur)/i); if (!match) return null; const label = match[1]!.trim(); if (/varsayılan vade/i.test(label)) return { conflict: "Bu kavram mevcut Vade (gün) alanıyla zaten temsil ediliyor." } as const; const optionsMatch = utterance.match(/seçenekler\s+(.+)$/i); const options = optionsMatch?.[1]?.split(/\s*,\s*/).filter(Boolean) ?? []; const valueType = /sayı/i.test(match[2]!) ? "integer" : /tarih/i.test(match[2]!) ? "date" : /seçim|seçenekli/i.test(match[2]!) || options.length ? "enum" : "string"; return { definition: { module: "customers", entityType: "customer", key: normalizeKey(label), label, valueType, required: /zorunlu/i.test(utterance), ...(options.length ? { options } : {}), uiSection: "Özel Alanlar" } } as const; }
export class CustomerCustomFieldConversationCoordinator {
  state: PendingCustomFieldConversation = { lifecycle: "IDLE", updatedAt: new Date(0).toISOString() };
  async execute(utterance: string): Promise<{ handled: boolean; status: "CLARIFICATION" | "EXECUTED" | "FAILED"; message: string | null }> {
    if (this.state.lifecycle === "AWAITING_APPROVAL" && yes.test(utterance.trim())) { const pending = this.state; this.state = { ...pending, lifecycle: "SUBMITTING", updatedAt: new Date().toISOString() }; const response = await confirmCustomFieldCreate(pending.approvalId!, pending.definition!); if (!response.ok) { this.state = { ...this.state, lifecycle: "FAILED", error: response.error, updatedAt: new Date().toISOString() }; return { handled: true, status: "FAILED", message: response.error }; } const definitionId = response.data.execution.entityRef?.entityId; if (!definitionId) return { handled: true, status: "FAILED", message: "Alan oluşturma sonucu doğrulanamadı." }; this.state = { ...this.state, lifecycle: "SUCCEEDED", definitionId, updatedAt: new Date().toISOString() }; if (typeof window !== "undefined") window.dispatchEvent(new CustomEvent("customer-field-registry-changed")); return { handled: true, status: "EXECUTED", message: `${String(pending.definition!.label)} alanı oluşturuldu.` }; }
    if (this.state.lifecycle === "AWAITING_APPROVAL" && no.test(utterance.trim())) { await cancelCustomFieldCreate(this.state.approvalId!); this.state = { lifecycle: "CANCELLED", updatedAt: new Date().toISOString() }; return { handled: true, status: "EXECUTED", message: "Alan oluşturma iptal edildi." }; }
    const plan = obviousPlan(utterance); if (!plan) return { handled: false, status: "EXECUTED", message: null }; if ("conflict" in plan) return { handled: true, status: "CLARIFICATION", message: plan.conflict! };
    this.state = { lifecycle: "PLANNING", definition: plan.definition, updatedAt: new Date().toISOString() }; const response = await requestCustomFieldCreate(plan.definition); if (!response.ok) { this.state = { ...this.state, lifecycle: "FAILED", error: response.error, updatedAt: new Date().toISOString() }; return { handled: true, status: "FAILED", message: response.error }; } this.state = { ...this.state, lifecycle: "AWAITING_APPROVAL", approvalId: response.data.approval.approvalId, expiresAt: response.data.approval.expiresAt, updatedAt: new Date().toISOString() }; const d = plan.definition; return { handled: true, status: "CLARIFICATION", message: `${d.label} alanı ${d.key} anahtarıyla ${d.valueType} tipinde${d.required ? " ve zorunlu" : ""} oluşturulacak. Onaylıyor musun?` };
  }
  reset() { this.state = { lifecycle: "IDLE", updatedAt: new Date(0).toISOString() }; }
}
export const customerCustomFieldConversationCoordinator = new CustomerCustomFieldConversationCoordinator();
