import type { StructuredFieldCandidate } from "@/lib/field-authority/structured-field-ingestion";
export type CustomerIngestionLifecycle = "IDLE" | "UPLOADING" | "EXTRACTING" | "REVIEW_REQUIRED" | "APPLYING_TO_DRAFT" | "READY" | "SUBMITTING" | "SUCCEEDED" | "FAILED" | "CANCELLED" | "EXPIRED";
export type CustomerIngestionPreviewState = { lifecycle: CustomerIngestionLifecycle; source?: { sourceId: string; filename: string; mediaType: string; size: number }; candidates: StructuredFieldCandidate[]; accepted: string[]; rejected: string[]; edits: Record<string, unknown>; conflicts: string[]; warnings: string[]; targetOperation: "CREATE_NEW_CUSTOMER" | "UPDATE_EXISTING_CUSTOMER"; targetCustomerId?: string; draftSnapshot: Record<string, unknown>; executionId?: string; entityId?: string; error?: string; expiresAt?: string };
export class CustomerIngestionPreviewRuntime {
  state: CustomerIngestionPreviewState = { lifecycle: "IDLE", candidates: [], accepted: [], rejected: [], edits: {}, conflicts: [], warnings: [], targetOperation: "CREATE_NEW_CUSTOMER", draftSnapshot: {} };
  load(input: Pick<CustomerIngestionPreviewState, "source" | "candidates" | "conflicts" | "warnings" | "expiresAt">) { this.state = { ...this.state, ...input, lifecycle: "REVIEW_REQUIRED", accepted: input.candidates.map((item) => item.fieldId), rejected: [], edits: {} }; return this.state; }
  decide(fieldId: string, accepted: boolean) { this.assertReview(); this.state = { ...this.state, accepted: accepted ? [...new Set([...this.state.accepted, fieldId])] : this.state.accepted.filter((id) => id !== fieldId), rejected: accepted ? this.state.rejected.filter((id) => id !== fieldId) : [...new Set([...this.state.rejected, fieldId])] }; return this.state; }
  edit(fieldId: string, value: unknown) { this.assertReview(); if (!this.state.candidates.some((item) => item.fieldId === fieldId)) throw new Error("CANDIDATE_NOT_FOUND"); this.state = { ...this.state, edits: { ...this.state.edits, [fieldId]: value } }; return this.state; }
  applyToDraft(current: Record<string, unknown>) { this.assertReview(); const values = { ...current }; for (const candidate of this.state.candidates) if (this.state.accepted.includes(candidate.fieldId)) values[candidate.fieldId] = this.state.edits[candidate.fieldId] ?? candidate.normalizedValue; this.state = { ...this.state, lifecycle: "READY", draftSnapshot: values }; return this.state; }
  cancel() { this.state = { lifecycle: "CANCELLED", candidates: [], accepted: [], rejected: [], edits: {}, conflicts: [], warnings: [], targetOperation: "CREATE_NEW_CUSTOMER", draftSnapshot: {} }; return this.state; }
  private assertReview() { if (this.state.expiresAt && Date.now() > new Date(this.state.expiresAt).getTime()) { this.state = { ...this.state, lifecycle: "EXPIRED" }; throw new Error("PREVIEW_EXPIRED"); } if (this.state.lifecycle !== "REVIEW_REQUIRED") throw new Error("PREVIEW_NOT_REVIEWABLE"); }
}
