import { cancelCustomFieldChange, cancelCustomFieldCreate, confirmCustomFieldCreate, confirmCustomFieldDeprecate, confirmCustomFieldUpdate, listCustomerFieldDefinitions, requestCustomFieldCreate, requestCustomFieldDeprecate, requestCustomFieldUpdate, resolveCustomFieldConversationCommand } from "./customers-client";
import type { ModuleFieldDefinition } from "@/lib/field-authority/field-authority";
export type CustomFieldConversationIntent = "CREATE_CUSTOM_FIELD" | "UPDATE_CUSTOM_FIELD_DEFINITION" | "DEPRECATE_CUSTOM_FIELD" | "STATUS_QUERY" | "CONFIRM" | "CANCEL" | "CLARIFICATION_REQUIRED" | "NOT_CUSTOM_FIELD_REQUEST";
export type CustomFieldConversationLifecycle = "IDLE" | "PLANNING" | "AWAITING_CLARIFICATION" | "AWAITING_APPROVAL" | "SUBMITTING" | "SUCCEEDED" | "FAILED" | "CANCELLED" | "EXPIRED";
type PendingAction = "CREATE" | "UPDATE" | "DEPRECATE";
export type PendingCustomFieldConversation = { lifecycle: CustomFieldConversationLifecycle; intent?: CustomFieldConversationIntent; action?: PendingAction; definition?: Record<string, unknown>; definitionId?: string; definitionLabel?: string; approvalId?: string; error?: string; updatedAt: string; expiresAt?: string };
const yes = /^(evet|onaylıyorum|onayliyorum|evet[,.]?\s*alanı oluştur|onayla)$/i; const no = /^(hayır|hayir|iptal|vazgeç|vazgec)$/i;
const normalize = (value: string) => value.trim().toLocaleLowerCase("tr-TR");
const normalizeKey = (value: string) => normalize(value).normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/ı/g, "i").replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "").slice(0, 64);
function createPlan(utterance: string) { const match = utterance.match(/(?:müşterilere?\s+)?(.+?)\s+(?:diye\s+)?(metin|sayı|tarih|seçim|seçenekli)\s+alan[ıi]\s+(?:ekle|oluştur)/i); if (!match) return null; const label = match[1]!.trim(); if (/varsayılan vade/i.test(label)) return { conflict: "Bu kavram mevcut Vade (gün) alanıyla zaten temsil ediliyor." } as const; const options = utterance.match(/seçenekler\s+(.+)$/i)?.[1]?.split(/\s*,\s*/).filter(Boolean) ?? []; const valueType = /sayı/i.test(match[2]!) ? "integer" : /tarih/i.test(match[2]!) ? "date" : /seçim|seçenekli/i.test(match[2]!) || options.length ? "enum" : "string"; return { definition: { module: "customers", entityType: "customer", key: normalizeKey(label), label, valueType, required: /zorunlu/i.test(utterance), ...(options.length ? { options } : {}), uiSection: "Özel Alanlar" } } as const; }
function findCustom(fields: ModuleFieldDefinition[], label: string) { const target = normalize(label).replace(/\s+alan[ıi]$/i, ""); return fields.filter((field) => field.custom && [field.label, field.key].some((value) => normalize(value) === target)); }
function definitionId(field: ModuleFieldDefinition) { return field.fieldId.replace(/^customer\.custom\./, ""); }
export class CustomerCustomFieldConversationCoordinator {
  state: PendingCustomFieldConversation = { lifecycle: "IDLE", updatedAt: new Date(0).toISOString() };
  async execute(utterance: string): Promise<{ handled: boolean; status: "CLARIFICATION" | "EXECUTED" | "FAILED"; message: string | null }> {
    if (this.state.lifecycle === "AWAITING_APPROVAL" && yes.test(utterance.trim())) return this.confirm();
    if (this.state.lifecycle === "AWAITING_APPROVAL" && no.test(utterance.trim())) return this.cancel();
    if (this.state.lifecycle !== "IDLE" && /işlem bitti mi|durum ne|ne durumda/i.test(utterance)) return { handled: true, status: "CLARIFICATION", message: this.statusMessage() };
    if (/alan|field|seçenek/i.test(utterance)) { const planned = await resolveCustomFieldConversationCommand(utterance); if (planned.ok) { const plan = planned.data.plan; if (plan.intent === "CREATE_CUSTOM_FIELD") return this.request("CREATE", plan.definition, undefined, String(plan.definition.label)); if (plan.intent === "UPDATE_CUSTOM_FIELD_DEFINITION" || plan.intent === "DEPRECATE_CUSTOM_FIELD") { const fields = await listCustomerFieldDefinitions(); if (!fields.ok) return { handled: true, status: "FAILED", message: fields.error }; const field = fields.data.fields.find((item) => item.fieldId === `customer.custom.${plan.definitionId}`); if (!field) return { handled: true, status: "CLARIFICATION", message: "Aktif özel alan bulunamadı." }; return plan.intent === "UPDATE_CUSTOM_FIELD_DEFINITION" ? this.request("UPDATE", plan.input, plan.definitionId, field.label) : this.request("DEPRECATE", {}, plan.definitionId, field.label); } if (plan.intent === "CLARIFICATION_REQUIRED" && !/güvenli biçimde doğrulanamadı/.test(plan.reason)) return { handled: true, status: "CLARIFICATION", message: plan.reason }; if (plan.intent === "STATUS_QUERY") return { handled: true, status: "CLARIFICATION", message: this.statusMessage() }; } }
    const create = createPlan(utterance); if (create) { if ("conflict" in create) return { handled: true, status: "CLARIFICATION", message: create.conflict! }; return this.request("CREATE", create.definition, undefined, String(create.definition.label)); }
    const deprecate = utterance.match(/^(.+?)\s+alan[ıi]n[ıi]\s+(?:kaldır|sil|devre dışı bırak)$/i); const required = utterance.match(/^(.+?)\s+alan[ıi]n[ıi]\s+zorunlu\s+yap$/i); const enumOption = utterance.match(/^(.+?)\s+(?:alan[ıi]\s+)?seçeneklerine\s+(.+?)\s+ekle$/i);
    if (!deprecate && !required && !enumOption) return { handled: false, status: "EXECUTED", message: null };
    const fieldsResult = await listCustomerFieldDefinitions(); if (!fieldsResult.ok) return { handled: true, status: "FAILED", message: fieldsResult.error };
    const label = (deprecate ?? required ?? enumOption)![1]!; const matches = findCustom(fieldsResult.data.fields, label);
    if (matches.length !== 1) return { handled: true, status: "CLARIFICATION", message: matches.length ? `Birden fazla alan eşleşti: ${matches.map((item) => item.label).join(", ")}. Hangisi?` : "Bu adla aktif bir özel alan bulamadım." };
    const field = matches[0]!; const id = definitionId(field);
    if (deprecate) return this.request("DEPRECATE", {}, id, field.label);
    if (required) return this.request("UPDATE", { required: true }, id, field.label);
    if (field.valueType !== "enum") return { handled: true, status: "CLARIFICATION", message: `${field.label} seçim alanı değil; seçenek eklenemez.` };
    const option = enumOption![2]!.trim(); const options = [...new Set([...(field.validation?.options ?? []), option])]; return this.request("UPDATE", { options }, id, field.label);
  }
  private async request(action: PendingAction, definition: Record<string, unknown>, id?: string, label?: string) { this.state = { lifecycle: "PLANNING", intent: action === "CREATE" ? "CREATE_CUSTOM_FIELD" : action === "UPDATE" ? "UPDATE_CUSTOM_FIELD_DEFINITION" : "DEPRECATE_CUSTOM_FIELD", action, definition, definitionId: id, definitionLabel: label, updatedAt: new Date().toISOString() }; const response = action === "CREATE" ? await requestCustomFieldCreate(definition) : action === "UPDATE" ? await requestCustomFieldUpdate(id!, definition) : await requestCustomFieldDeprecate(id!); if (!response.ok) { this.state = { ...this.state, lifecycle: "FAILED", error: response.error }; return { handled: true, status: "FAILED" as const, message: response.error }; } this.state = { ...this.state, lifecycle: "AWAITING_APPROVAL", approvalId: response.data.approval.approvalId, expiresAt: response.data.approval.expiresAt, updatedAt: new Date().toISOString() }; const message = action === "CREATE" ? `${label} alanı ${String(definition.key)} anahtarıyla ${String(definition.valueType)} tipinde${definition.required ? " ve zorunlu" : ""} oluşturulacak. Onaylıyor musun?` : action === "UPDATE" ? `${label} alan tanımı güncellenecek. Onaylıyor musun?` : `${label} alanı kaldırılacak; mevcut değerler korunacak ve yeni yazımlar duracak. Onaylıyor musun?`; return { handled: true, status: "CLARIFICATION" as const, message }; }
  private async confirm() { const pending = this.state; if (pending.expiresAt && Date.now() >= new Date(pending.expiresAt).getTime()) { this.state = { ...pending, lifecycle: "EXPIRED" }; return { handled: true, status: "FAILED" as const, message: "Alan değişikliği onayının süresi doldu." }; } this.state = { ...pending, lifecycle: "SUBMITTING", updatedAt: new Date().toISOString() }; const response = pending.action === "CREATE" ? await confirmCustomFieldCreate(pending.approvalId!, pending.definition!) : pending.action === "UPDATE" ? await confirmCustomFieldUpdate(pending.definitionId!, pending.approvalId!, pending.definition!) : await confirmCustomFieldDeprecate(pending.definitionId!, pending.approvalId!); if (!response.ok) { this.state = { ...this.state, lifecycle: "FAILED", error: response.error }; return { handled: true, status: "FAILED" as const, message: response.error }; } const id = response.data.execution.entityRef?.entityId; if (!id) return { handled: true, status: "FAILED" as const, message: "Alan işlemi sonucu doğrulanamadı." }; this.state = { ...this.state, lifecycle: "SUCCEEDED", definitionId: id, updatedAt: new Date().toISOString() }; if (typeof window !== "undefined") window.dispatchEvent(new CustomEvent("customer-field-registry-changed")); return { handled: true, status: "EXECUTED" as const, message: pending.action === "CREATE" ? `${pending.definitionLabel} alanı oluşturuldu.` : pending.action === "UPDATE" ? `${pending.definitionLabel} alanı güncellendi.` : `${pending.definitionLabel} alanı kaldırıldı.` }; }
  private async cancel() { const pending = this.state; if (pending.action === "CREATE") await cancelCustomFieldCreate(pending.approvalId!); else await cancelCustomFieldChange(pending.definitionId!, pending.action === "UPDATE" ? "update" : "deprecate", pending.approvalId!); this.state = { lifecycle: "CANCELLED", updatedAt: new Date().toISOString() }; return { handled: true, status: "EXECUTED" as const, message: "Alan değişikliği iptal edildi." }; }
  private statusMessage() { return this.state.lifecycle === "SUCCEEDED" ? "Alan değişikliği gerçek yürütme sonucuyla tamamlandı." : this.state.lifecycle === "AWAITING_APPROVAL" ? "Alan değişikliği onayınızı bekliyor." : this.state.lifecycle === "FAILED" ? `Alan değişikliği tamamlanamadı: ${this.state.error ?? "güvenli hata"}.` : "Alan değişikliği henüz tamamlanmadı."; }
  reset() { this.state = { lifecycle: "IDLE", updatedAt: new Date(0).toISOString() }; }
}
export const customerCustomFieldConversationCoordinator = new CustomerCustomFieldConversationCoordinator();
