import type { ModuleFieldDefinition, ModuleFieldValueType } from "@/lib/field-authority/field-authority";
export const CUSTOMER_FIELD_SECTIONS = ["Kimlik ve İletişim", "Yetkili Kişi", "Resmi Bilgiler", "Adres Bilgileri", "Finansal / Ticari Koşullar", "Sistem Ayarları", "Özel Alanlar", "Notlar"] as const;
type Spec = [key: string, label: string, valueType: ModuleFieldValueType, section: string, writable: boolean, options?: string[], storageKind?: ModuleFieldDefinition["storageKind"], nestedPath?: string[]];
const specs: Spec[] = [
  ["displayName", "Firma adı", "string", "Kimlik ve İletişim", true], ["legalName", "Ticari unvan", "string", "Kimlik ve İletişim", true], ["tier", "Müşteri grubu", "string", "Kimlik ve İletişim", true], ["phone", "Telefon", "phone", "Kimlik ve İletişim", true], ["email", "E-posta", "email", "Kimlik ve İletişim", true],
  ["primaryContact.fullName", "Yetkili kişi", "string", "Yetkili Kişi", true, undefined, "relation", ["primaryContact", "fullName"]], ["primaryContact.title", "Yetkili unvanı", "string", "Yetkili Kişi", true, undefined, "relation", ["primaryContact", "title"]], ["primaryContact.phone", "Yetkili telefonu", "phone", "Yetkili Kişi", true, undefined, "relation", ["primaryContact", "phone"]], ["primaryContact.email", "Yetkili e-postası", "email", "Yetkili Kişi", true, undefined, "relation", ["primaryContact", "email"]],
  ["cariKodu", "Cari kodu", "string", "Resmi Bilgiler", true], ["taxNumber", "Vergi numarası", "string", "Resmi Bilgiler", true], ["taxOffice", "Vergi dairesi", "string", "Resmi Bilgiler", true], ["mersisNo", "MERSİS numarası", "string", "Resmi Bilgiler", true], ["tradeRegistryNo", "Ticaret sicil numarası", "string", "Resmi Bilgiler", true],
  ...(["billingAddress", "shippingAddress"] as const).flatMap((address) => (["line1", "line2", "district", "city", "postalCode", "country"] as const).map((part) => [`${address}.${part}`, `${address === "billingAddress" ? "Fatura" : "Teslimat"} ${part}`, "string", "Adres Bilgileri", true, undefined, "json", [address, part]] as Spec)),
  ["currency", "Para birimi", "enum", "Finansal / Ticari Koşullar", true, ["TRY", "USD", "EUR", "GBP"]], ["commercialTerms.paymentTermDays", "Vade (gün)", "integer", "Finansal / Ticari Koşullar", true, undefined, "commercial_terms", ["commercialTerms", "paymentTermDays"]], ["commercialTerms.creditLimitCents", "Kredi limiti", "money", "Finansal / Ticari Koşullar", true, undefined, "commercial_terms", ["commercialTerms", "creditLimitCents"]], ["commercialTerms.discountRateBasisPoints", "İskonto oranı", "percentage", "Finansal / Ticari Koşullar", true, undefined, "commercial_terms", ["commercialTerms", "discountRateBasisPoints"]], ["commercialTerms.deliveryTerm", "Teslimat koşulu", "string", "Finansal / Ticari Koşullar", true, undefined, "commercial_terms", ["commercialTerms", "deliveryTerm"]], ["commercialTerms.notes", "Ticari koşul notu", "multiline_string", "Finansal / Ticari Koşullar", true, undefined, "commercial_terms", ["commercialTerms", "notes"]],
  ["eInvoiceEnabled", "E-Fatura", "boolean", "Sistem Ayarları", true], ["eArchiveEnabled", "E-Arşiv", "boolean", "Sistem Ayarları", true], ["healthScore", "İlişki skoru", "integer", "Sistem Ayarları", true], ["status", "Durum", "enum", "Sistem Ayarları", false, ["ACTIVE", "PASSIVE", "BLOCKED"]], ["source", "Kaynak", "string", "Sistem Ayarları", false], ["balanceCents", "Bakiye", "money", "Sistem Ayarları", false], ["organizationId", "Organizasyon", "string", "Sistem Ayarları", false], ["createdByUserId", "Oluşturan", "string", "Sistem Ayarları", false], ["updatedByUserId", "Güncelleyen", "string", "Sistem Ayarları", false], ["createdAt", "Oluşturulma", "datetime", "Sistem Ayarları", false], ["updatedAt", "Güncellenme", "datetime", "Sistem Ayarları", false],
  ["metrixNote", "Notlar", "multiline_string", "Notlar", true],
];
const aliases: Record<string, string[]> = { displayName: ["firma adı", "firma ismi", "adı"], legalName: ["ticari unvan"], phone: ["telefonu", "firma telefonu"], email: ["e-posta adresi", "e-posta", "eposta"], "primaryContact.fullName": ["yetkili", "yetkilisi"], "primaryContact.title": ["yetkili unvanı", "unvanı"], taxNumber: ["vergi numarası", "vergi no"], taxOffice: ["vergi dairesi"], currency: ["para birimi"], "commercialTerms.paymentTermDays": ["vadesi", "varsayılan vade"], "billingAddress.line1": ["fatura adresi"], "shippingAddress.line1": ["teslimat adresi"] };
export const CUSTOMER_BUILT_IN_FIELDS: readonly ModuleFieldDefinition[] = specs.map(([key, label, valueType, uiSection, writable, options, storageKind = "scalar", nestedPath], index) => ({ fieldId: `customer.${key}`, module: "customers", entityType: "customer", key, label, description: `${label} alanı`, valueType, storageKind, requiredOnCreate: key === "displayName", requiredOnUpdate: false, readable: key !== "organizationId", writable, clearable: key !== "displayName" && writable, searchable: ["displayName", "legalName", "phone", "email", "taxNumber"].includes(key), filterable: ["tier", "currency", "status"].includes(key), sortable: ["displayName", "createdAt", "updatedAt"].includes(key), reportable: key !== "organizationId", sourceOfTruth: storageKind === "scalar" ? (writable ? "entity" : "system") : "relation", sensitivity: key.includes("tax") || key.includes("email") || key.includes("phone") ? "SENSITIVE" : "INTERNAL", riskLevel: writable ? "LOW" : "HIGH", approvalPolicy: "NONE", permissionRead: key === "organizationId" ? "server-only" : "customers.read", permissionWrite: writable ? "customers.write" : null, validation: { ...(options ? { options } : {}), ...(key === "healthScore" ? { min: 0, max: 100 } : {}), ...(key.endsWith("paymentTermDays") ? { min: 0, max: 3650 } : {}) }, normalization: valueType === "email" ? "email" : key === "currency" ? "currency" : valueType === "integer" ? "integer" : valueType === "money" ? "money_cents" : valueType === "percentage" ? "percentage_basis_points" : "trim", nestedPath, uiSection, uiOrder: index, custom: false, state: "ACTIVE", aliases: aliases[key] ?? [label.toLocaleLowerCase("tr-TR")] }));
export type CustomerCustomFieldDefinitionRecord = { id: string; organizationId: string; key: string; label: string; description: string | null; valueType: string; required: boolean; options: unknown; active: boolean };
export function customerCustomDefinitionToField(record: CustomerCustomFieldDefinitionRecord): ModuleFieldDefinition { if (!record.active) throw new Error("Inactive custom field."); const valueType = record.valueType as ModuleFieldValueType; return { fieldId: `customer.custom.${record.id}`, module: "customers", entityType: "customer", key: `custom.${record.id}`, label: record.label, description: record.description ?? record.label, valueType, storageKind: "custom_value", requiredOnCreate: record.required, requiredOnUpdate: false, readable: true, writable: true, clearable: !record.required, searchable: false, filterable: valueType === "enum", sortable: false, reportable: true, sourceOfTruth: "relation", sensitivity: "INTERNAL", riskLevel: "LOW", approvalPolicy: "NONE", permissionRead: "customers.read", permissionWrite: "customers.write", validation: Array.isArray(record.options) ? { options: record.options.filter((x): x is string => typeof x === "string") } : undefined, normalization: "trim", uiSection: "Özel Alanlar", uiOrder: 1000, custom: true, state: "ACTIVE", aliases: [record.label.toLocaleLowerCase("tr-TR"), record.key] }; }
export function getCustomerFieldById(fieldId: string) { return CUSTOMER_BUILT_IN_FIELDS.find((field) => field.fieldId === fieldId) ?? null; }
