import { CUSTOMER_BUILT_IN_FIELDS } from "./customer-field-registry";
import { dispatchCustomerCreateCommand, getActiveCustomerCreateSurfaceDescriptor, subscribeCustomerCreateSurfaceMount } from "./customer-create-surface-command-channel";
import { listCustomerFieldDefinitions } from "./customers-client";
import type { StructuredFieldCandidate } from "@/lib/field-authority/structured-field-ingestion";
import { clearBrowserAttachmentSession, readBrowserAttachmentSession, writeBrowserAttachmentSession, type AttachmentReference } from "@/lib/conversation-attachments/attachment-session";

export type AttachmentConversationOutcome = "ATTACHMENT_EXTRACT" | "PREVIEW_STATUS" | "ACCEPT_CANDIDATES" | "REJECT_CANDIDATES" | "EDIT_CANDIDATE" | "APPLY_TO_DRAFT" | "COMMIT" | "CANCEL" | "DUPLICATE_RESOLUTION" | "CLARIFICATION_REQUIRED" | "NOT_ATTACHMENT_INTENT";
type Preview = { lifecycle: "REVIEW_REQUIRED" | "DUPLICATE_CONFLICT" | "READY" | "SUCCEEDED" | "FAILED" | "CANCELLED"; attachment: AttachmentReference; extractionRequestId: string; candidates: StructuredFieldCandidate[]; duplicates: Array<{ customerId: string; displayName: string; strength: "STRONG" | "WEAK"; matchedFields: string[] }>; accepted: string[]; rejected: string[]; edits: Record<string, unknown>; duplicateResolution?: { kind: "CREATE_NEW_ANYWAY"; confirmed: boolean }; appliedSurfaceToken?: string; entityId?: string };
type State = { attachment?: AttachmentReference; preview?: Preview };
const normalize = (value: string) => value.trim().toLocaleLowerCase("tr-TR");
function read(): State { return readBrowserAttachmentSession() as State; }
function write(state: State) { writeBrowserAttachmentSession(state); }

export class CustomerAttachmentConversationCoordinator {
  private replayUnsubscribe?: () => void;
  async execute(utterance: string): Promise<{ handled: boolean; outcome: AttachmentConversationOutcome; message: string | null }> {
    const text = normalize(utterance); const state = read();
    const isExtract = /bu (belgedeki|görseldeki)|bu görselden|yüklediğim .*bilgileri|belgeden .*hazırla|müşteri kaydı oluştur/.test(text);
    if (isExtract) { if (!state.attachment) return { handled: true, outcome: "CLARIFICATION_REQUIRED", message: "Bu komuta bağlı bir belge yok. Önce dosyayı yükleyin." }; if (Date.now() >= new Date(state.attachment.expiresAt).getTime()) return { handled: true, outcome: "CLARIFICATION_REQUIRED", message: "Belge oturumunun süresi doldu. Dosyayı yeniden yükleyin." }; const response = await fetch("/api/customers/document-extractions", { method: "POST", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ attachmentRef: state.attachment.attachmentRef, ...(state.attachment.conversationId ? { conversationId: state.attachment.conversationId } : {}), targetOperation: "CREATE_NEW_CUSTOMER" }) }); const json = await response.json() as { ok: true; data: Omit<Preview, "accepted" | "rejected" | "edits"> } | { ok: false; error: { message: string } }; if (!json.ok) return { handled: true, outcome: "ATTACHMENT_EXTRACT", message: json.error.message }; const preview: Preview = { ...json.data, accepted: json.data.candidates.filter((item) => item.conflictStatus === "NONE").map((item) => item.fieldId), rejected: [], edits: {} }; write({ attachment: state.attachment, preview }); return { handled: true, outcome: "ATTACHMENT_EXTRACT", message: `Belgeden ${preview.candidates.length} alan çıkardım. Kaydetmeden önce seçimlerinizi inceleyin.` }; }
    if (!state.preview) { if (/çıkardığın bilgileri göster|işlem bitti mi|belgeyi iptal et|taslağa uygula/.test(text)) return { handled: true, outcome: "CLARIFICATION_REQUIRED", message: state.attachment ? "Belge alındı; henüz çıkarım yapılmadı." : "Aktif bir belge önizlemesi yok." }; return { handled: false, outcome: "NOT_ATTACHMENT_INTENT", message: null }; }
    const preview = state.preview;
    const strong = preview.duplicates.filter((item) => item.strength === "STRONG");
    if (/^mevcut müşteriyi aç$/i.test(text)) { if (strong.length !== 1) return { handled: true, outcome: "CLARIFICATION_REQUIRED", message: strong.length ? `Birden fazla güçlü eşleşme var: ${strong.map((item) => item.displayName).join(", ")}. Hangisi?` : "Açılacak güçlü müşteri eşleşmesi yok." }; if (typeof window !== "undefined") window.location.assign(`/metrix/customers/${encodeURIComponent(strong[0]!.customerId)}`); return { handled: true, outcome: "DUPLICATE_RESOLUTION", message: `${strong[0]!.displayName} açılıyor.` }; }
    if (/^yine de yeni kayıt oluştur$/i.test(text)) { if (!strong.length) return { handled: true, outcome: "CLARIFICATION_REQUIRED", message: "Güçlü duplicate olmadığı için ek onay gerekmiyor." }; preview.duplicateResolution = { kind: "CREATE_NEW_ANYWAY", confirmed: false }; write({ attachment: state.attachment, preview }); return { handled: true, outcome: "CLARIFICATION_REQUIRED", message: "Güçlü eşleşmeye rağmen yeni müşteri oluşturulacak. Devam etmek için açıkça onaylayın." }; }
    if (preview.duplicateResolution?.kind === "CREATE_NEW_ANYWAY" && /^(evet|onaylıyorum|onayliyorum|onayla)$/i.test(text)) { preview.duplicateResolution.confirmed = true; preview.duplicates = preview.duplicates.map((item) => item.strength === "STRONG" ? { ...item, strength: "WEAK" as const } : item); preview.lifecycle = "REVIEW_REQUIRED"; write({ attachment: state.attachment, preview }); return { handled: true, outcome: "DUPLICATE_RESOLUTION", message: "Yeni kayıt istisnası onaylandı; adayları taslağa uygulayabilirsiniz." }; }
    if (/çıkardığın bilgileri göster|işlem bitti mi|durum ne/.test(text)) return { handled: true, outcome: "PREVIEW_STATUS", message: this.status(preview) };
    if (/belgeyi iptal et/.test(text)) { await fetch(`/api/customers/document-attachments/${encodeURIComponent(preview.attachment.attachmentRef)}`, { method: "DELETE", credentials: "include" }); write({}); return { handled: true, outcome: "CANCEL", message: "Belge önizlemesi iptal edildi; hiçbir müşteri kaydı değiştirilmedi." }; }
    const decision = text.match(/^(.+?)(?:n[ıi]|y[ıi])\s+(kabul et|reddet)$/); if (decision) { const candidate = await this.resolveCandidate(preview, decision[1]!); if (!candidate) return { handled: true, outcome: "CLARIFICATION_REQUIRED", message: "Alan adı tek bir adayla eşleşmedi." }; const accept = decision[2] === "kabul et"; preview.accepted = accept ? [...new Set([...preview.accepted, candidate.fieldId])] : preview.accepted.filter((id) => id !== candidate.fieldId); preview.rejected = accept ? preview.rejected.filter((id) => id !== candidate.fieldId) : [...new Set([...preview.rejected, candidate.fieldId])]; write({ attachment: state.attachment, preview }); return { handled: true, outcome: accept ? "ACCEPT_CANDIDATES" : "REJECT_CANDIDATES", message: `${candidate.fieldId} ${accept ? "kabul edildi" : "reddedildi"}.` }; }
    const edit = utterance.match(/^(.+?)(?:n[ıi]|y[ıi])\s+(.+?)\s+olarak\s+düzelt$/i); if (edit) { const candidate = await this.resolveCandidate(preview, edit[1]!); if (!candidate) return { handled: true, outcome: "CLARIFICATION_REQUIRED", message: "Alan adı tek bir adayla eşleşmedi." }; preview.edits[candidate.fieldId] = edit[2]!.trim(); preview.accepted = [...new Set([...preview.accepted, candidate.fieldId])]; write({ attachment: state.attachment, preview }); return { handled: true, outcome: "EDIT_CANDIDATE", message: `${candidate.fieldId} adayı güncellendi; henüz taslağa uygulanmadı.` }; }
    if (/hepsini taslağa uygula|seçilenleri taslağa uygula/.test(text)) return this.apply(state, preview);
    if (/onaylıyorum,? kaydet|kaydet$/i.test(text)) { if (preview.lifecycle !== "READY") return { handled: true, outcome: "CLARIFICATION_REQUIRED", message: "Önce adayları müşteri taslağına uygulayın." }; const descriptor = getActiveCustomerCreateSurfaceDescriptor(); if (!descriptor || descriptor.token !== preview.appliedSurfaceToken) return { handled: true, outcome: "CLARIFICATION_REQUIRED", message: "Bağlı müşteri taslağı artık aktif değil; alanları yeniden taslağa uygulayın." }; const outcome = await dispatchCustomerCreateCommand(descriptor.token, { type: "commit" }); if (outcome.status !== "EXECUTED" || !outcome.navigation || outcome.navigation.kind !== "customer.detail") return { handled: true, outcome: outcome.status === "MISSING_FIELDS" ? "CLARIFICATION_REQUIRED" : "COMMIT", message: outcome.message ?? "Müşteri kaydı tamamlanamadı." }; preview.lifecycle = "SUCCEEDED"; preview.entityId = outcome.navigation.customerId; write({ attachment: state.attachment, preview }); if (typeof window !== "undefined") window.location.assign(`/metrix/customers/${encodeURIComponent(preview.entityId)}`); return { handled: true, outcome: "COMMIT", message: "Müşteri kaydedildi." }; }
    return { handled: true, outcome: "CLARIFICATION_REQUIRED", message: "Belge önizlemesi aktif. Adayları kabul edebilir, reddedebilir, düzeltebilir, taslağa uygulayabilir veya iptal edebilirsiniz." };
  }
  private async apply(state: State, preview: Preview) { if (preview.duplicates.some((item) => item.strength === "STRONG")) return { handled: true, outcome: "DUPLICATE_RESOLUTION" as const, message: `Güçlü eşleşme var: ${preview.duplicates.map((item) => item.displayName).join(", ")}. Mevcut müşteriyi açın, güncelleyin veya yeni kayıt için açıkça onay verin.` }; const descriptor = getActiveCustomerCreateSurfaceDescriptor(); if (!descriptor) { this.replayUnsubscribe?.(); this.replayUnsubscribe = subscribeCustomerCreateSurfaceMount(() => { this.replayUnsubscribe?.(); this.replayUnsubscribe = undefined; void this.apply(read(), read().preview!); }); if (typeof window !== "undefined") window.location.assign("/metrix/customers/new"); return { handled: true, outcome: "APPLY_TO_DRAFT" as const, message: "Müşteri oluşturma formu açılıyor; önizleme aynı taslağa uygulanacak." }; } if (preview.appliedSurfaceToken === descriptor.token) return { handled: true, outcome: "APPLY_TO_DRAFT" as const, message: "Alanlar bu taslağa zaten uygulandı." }; await dispatchCustomerCreateCommand(descriptor.token, { type: "bind_ingestion", attachmentRef: preview.attachment.attachmentRef }); const registryResult = await listCustomerFieldDefinitions(); if (!registryResult.ok) return { handled: true, outcome: "APPLY_TO_DRAFT" as const, message: registryResult.error }; const registry = [...CUSTOMER_BUILT_IN_FIELDS, ...registryResult.data.fields]; for (const candidate of preview.candidates) { if (!preview.accepted.includes(candidate.fieldId)) continue; const field = registry.find((item) => item.fieldId === candidate.fieldId); if (!field?.writable || (candidate.conflictStatus === "CONFLICT" && preview.edits[candidate.fieldId] === undefined)) continue; const key = field.custom ? `custom.${field.fieldId.replace("customer.custom.", "")}` : field.key; const outcome = await dispatchCustomerCreateCommand(descriptor.token, { type: "set_field", field: key as never, value: preview.edits[candidate.fieldId] ?? candidate.normalizedValue }); if (outcome.status !== "EXECUTED") return { handled: true, outcome: "APPLY_TO_DRAFT" as const, message: outcome.message ?? "Alanlar taslağa uygulanamadı." }; } preview.lifecycle = "READY"; preview.appliedSurfaceToken = descriptor.token; write({ attachment: state.attachment, preview }); return { handled: true, outcome: "APPLY_TO_DRAFT" as const, message: "Alanlar taslağa uygulandı." }; }
  private async resolveCandidate(preview: Preview, label: string) { const registry = await listCustomerFieldDefinitions(); if (!registry.ok) return undefined; const target = normalize(label); const fields = [...CUSTOMER_BUILT_IN_FIELDS, ...registry.data.fields].filter((field) => normalize(field.label) === target || normalize(field.key) === target); const candidates = preview.candidates.filter((item) => fields.some((field) => field.fieldId === item.fieldId)); return candidates.length === 1 ? candidates[0] : undefined; }
  private status(preview: Preview) { if (preview.lifecycle === "SUCCEEDED" && preview.entityId) return `Müşteri kaydedildi. Kayıt kimliği: ${preview.entityId}.`; if (preview.lifecycle === "READY") return "Belge alanları taslakta hazır; müşteri henüz kaydedilmedi."; return `${preview.candidates.length} aday inceleme bekliyor; müşteri henüz kaydedilmedi.`; }
  reset() { this.replayUnsubscribe?.(); this.replayUnsubscribe = undefined; clearBrowserAttachmentSession(); }
}
export const customerAttachmentConversationCoordinator = new CustomerAttachmentConversationCoordinator();
