import type { ModuleFieldDefinition } from "@/lib/field-authority/field-authority";
import type { EntityResolutionProvider } from "@/lib/universal-capture/contracts";
import type { CaptureDomainHandoffProvider } from "@/lib/universal-capture/handoff";
import { adaptPlannerCandidates, type SourceAdapterInput } from "@/lib/universal-capture/adapters";
import type { CustomerCreatePlan } from "./customer-create-conversation-plan";
import type { GenericCustomerFieldPlan } from "./customer-generic-field-planner";
import { resolveCustomerReference, type ResolvableCustomer } from "./customer-resolution";

export type CustomerCaptureDataProvider = Readonly<{ list(organizationId: string): Promise<readonly ResolvableCustomer[]>; baseline(organizationId: string, customerId: string): Promise<Readonly<Record<string, unknown>>> }>;
export function createCustomerEntityResolutionProvider(data: CustomerCaptureDataProvider): EntityResolutionProvider { return Object.freeze({ entityType: "customer", async resolve({ context, hint, operation }) { const customers = await data.list(context.organizationId); const signals = [hint.reference, ...Object.values(hint.identifiers ?? {})].filter((value): value is string => Boolean(value)); if (!signals.length) return Object.freeze({ status: operation === "CREATE" && hint.createIfMissing ? "NEW_ENTITY" : "NOT_FOUND", entityType: "customer", reference: null, candidates: [], confidence: operation === "CREATE" ? 1 : 0, evidence: [], reasonCodes: [operation === "CREATE" ? "CREATE_INTENT" : "REFERENCE_REQUIRED"] }); const resolutions = signals.map((signal) => resolveCustomerReference(customers, signal)); const matched = resolutions.flatMap((resolution) => resolution.status === "RESOLVED" ? [resolution.customer] : []); const unique = [...new Map(matched.map((customer) => [customer.id, customer])).values()]; if (unique.length > 1) return Object.freeze({ status: "CONFLICT", entityType: "customer", reference: null, candidates: Object.freeze(unique.map((customer) => Object.freeze({ reference: Object.freeze({ organizationId: context.organizationId, entityType: "customer", entityId: customer.id }), displayName: customer.displayName, score: .9, evidence: Object.freeze([]) }))), confidence: .4, evidence: [], reasonCodes: ["STRONG_IDENTIFIERS_CONFLICT"] }); if (unique.length === 1) return Object.freeze({ status: "RESOLVED", entityType: "customer", reference: Object.freeze({ organizationId: context.organizationId, entityType: "customer", entityId: unique[0]!.id }), candidates: [], confidence: 1, evidence: [], reasonCodes: [signals.length > 1 ? "CUSTOMER_IDENTIFIERS_CONSISTENT" : "CUSTOMER_REFERENCE_EXACT_OR_UNIQUE"] }); const ambiguous = resolutions.flatMap((resolution) => resolution.status === "AMBIGUOUS" ? resolution.options : []); if (ambiguous.length) return Object.freeze({ status: "AMBIGUOUS", entityType: "customer", reference: null, candidates: Object.freeze([...new Map(ambiguous.map((customer) => [customer.id, customer])).values()].map((customer) => Object.freeze({ reference: Object.freeze({ organizationId: context.organizationId, entityType: "customer", entityId: customer.id }), displayName: customer.displayName, score: .5, evidence: Object.freeze([]) }))), confidence: .5, evidence: [], reasonCodes: ["CUSTOMER_REFERENCE_AMBIGUOUS"] }); return Object.freeze({ status: hint.createIfMissing ? "NEW_ENTITY" : "NOT_FOUND", entityType: "customer", reference: null, candidates: [], confidence: hint.createIfMissing ? 1 : 0, evidence: [], reasonCodes: [hint.createIfMissing ? "CUSTOMER_NEW_ENTITY" : "CUSTOMER_NOT_FOUND"] }); }, readBaseline({ context, reference }) { if (reference.organizationId !== context.organizationId) throw new Error("CROSS_TENANT_ENTITY_REFERENCE"); return data.baseline(context.organizationId, reference.entityId); } }); }
export const customerCaptureHandoffProvider: CaptureDomainHandoffProvider = Object.freeze({ entityType: "customer", plan({ result, explicitCommitIntent }) { const resolution = result.entityResolution; if (!resolution.reference && resolution.status !== "NEW_ENTITY") return null; const create = resolution.status === "NEW_ENTITY"; if (create && !result.draftOperations.some((operation) => operation.fieldId === "customer.displayName")) return null; return Object.freeze({ captureId: result.captureId, actionName: create ? "customer.create" : "customer.update", target: resolution.reference ?? Object.freeze({ entityType: "customer", entityId: "NEW" as const }), fieldValues: Object.freeze(Object.fromEntries(result.draftOperations.map((operation) => [operation.fieldId, operation.kind === "CLEAR" ? null : operation.value]))), operations: result.draftOperations, requiresConfirmation: result.userInteraction === "CONFIRMATION", requiresApproval: result.userInteraction === "APPROVAL", explicitCommitIntent }); } });
export function adaptCustomerCreatePlan(input: SourceAdapterInput & Readonly<{ plan: Extract<CustomerCreatePlan, { kind: "CREATE_PLAN" }>; fields: readonly ModuleFieldDefinition[]; sourceRef?: string }>) { const byKey = new Map(input.fields.map((field) => [field.key, field])); return adaptPlannerCandidates({ ...input, candidates: Object.entries(input.plan.fields).map(([key, value]) => ({ fieldId: byKey.get(key)?.fieldId, key, value, confidence: .92, explicit: true })), sourceRef: input.sourceRef }); }
export function adaptCustomerFieldPlan(input: SourceAdapterInput & Readonly<{ plan: Extract<GenericCustomerFieldPlan, { kind: "SET_FIELDS" }>; sourceRef?: string }>) { return adaptPlannerCandidates({ ...input, candidates: input.plan.fields.map((field) => ({ fieldId: field.fieldId, value: field.value, confidence: .92, explicit: true })), sourceRef: input.sourceRef }); }
