import type { ModuleFieldDefinition } from "@/lib/field-authority/field-authority";
import { mapModuleFieldValueType, type UniversalInputTargetDescriptor } from "@/lib/input-authority";

export type CustomerUniversalMode = "create" | "edit";
export function customerTargetId(mode: CustomerUniversalMode, kind: "page" | "surface" | "section" | "field" | "action", name: string, entityId?: string) { const instance = mode === "create" ? "create" : entityId; return `${kind}.customers.${instance}.${name}`; }
export function customerSectionTargetId(mode: CustomerUniversalMode, section: string, entityId?: string) { return customerTargetId(mode, "section", slug(section), entityId); }
export function customerTabTargetId(entityId: string, tab: string) { return customerTargetId("edit", "surface", `tab.${tab}`, entityId); }
export function customerTabPanelTargetId(entityId: string, tab: string) { return customerTargetId("edit", "surface", `tab-panel.${tab}`, entityId); }
export function customerAuthorityKey(fieldOrAction: string) { return `customers.customer.${fieldOrAction}`; }
export function customerFieldDescriptor(field: ModuleFieldDefinition, mode: CustomerUniversalMode, entityId?: string): UniversalInputTargetDescriptor { const sectionId = customerSectionTargetId(mode, field.uiSection, entityId); return { executiveTargetId: customerTargetId(mode, "field", field.fieldId, entityId), authorityKey: customerAuthorityKey(field.key), targetKind: "field", module: field.module, entityType: field.entityType, ...(entityId ? { entityId } : {}), fieldId: field.fieldId, fieldType: mapModuleFieldValueType(field.valueType), label: field.label, description: field.description, parentTargetId: sectionId, parentSurfaceId: sectionId, sectionId, surfaceId: customerTargetId(mode, "surface", "form", entityId), required: mode === "create" ? field.requiredOnCreate : field.requiredOnUpdate, readable: field.readable, mutable: field.writable, clearable: field.clearable, focusable: field.writable, supportsVoice: field.writable, supportsDraft: mode === "edit", supportsApproval: field.approvalPolicy !== "NONE", approvalPolicy: field.approvalPolicy, riskLevel: field.riskLevel, permissionRead: field.permissionRead, permissionWrite: field.permissionWrite, validation: { state: "unknown", ...field.validation }, aliases: field.aliases, order: field.uiOrder, visibility: field.state === "ACTIVE" ? "visible" : "hidden", disabled: !field.writable, readOnly: !field.writable }; }
function slug(value: string) { return value.toLocaleLowerCase("tr-TR").normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/ı/g, "i").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, ""); }
