import { ApiValidationError } from "@/lib/api/validation";
import { normalizeFieldValue } from "@/lib/field-authority/field-authority";
import { CUSTOMER_BUILT_IN_FIELDS } from "./customer-field-registry";
import type { CreateCustomerBody } from "./customers-client";
const allowedTopLevel = new Set(["displayName", "legalName", "phone", "email", "metrixNote", "tier", "healthScore", "currency", "cariKodu", "taxNumber", "taxOffice", "mersisNo", "tradeRegistryNo", "billingAddress", "shippingAddress", "eInvoiceEnabled", "eArchiveEnabled", "primaryContact", "commercialTerms", "customFields"]);
export function validateCustomerCreateBody(raw: Record<string, unknown>): CreateCustomerBody {
  for (const key of Object.keys(raw)) if (!allowedTopLevel.has(key)) throw new ApiValidationError(`${key} is not an allowed customer field.`);
  const display = CUSTOMER_BUILT_IN_FIELDS.find((field) => field.key === "displayName")!; let displayName: unknown;
  try { displayName = normalizeFieldValue(display, raw.displayName); } catch { throw new ApiValidationError("displayName is required."); }
  const result: Record<string, unknown> = { displayName };
  for (const [key, value] of Object.entries(raw)) { if (key === "displayName" || value === undefined) continue; if (["primaryContact", "billingAddress", "shippingAddress", "commercialTerms"].includes(key)) { if (typeof value !== "object" || value === null || Array.isArray(value)) throw new ApiValidationError(`${key} must be an object.`); result[key] = validateNested(key, value as Record<string, unknown>); continue; } if (key === "customFields") { if (!Array.isArray(value) || value.some((item) => typeof item !== "object" || item === null || Array.isArray(item) || Object.keys(item).sort().join() !== "definitionId,value" || typeof (item as Record<string, unknown>).definitionId !== "string")) throw new ApiValidationError("customFields must contain strict definitionId/value entries."); result[key] = value; continue; } const field = CUSTOMER_BUILT_IN_FIELDS.find((item) => item.key === key); if (!field || !field.writable) throw new ApiValidationError(`${key} is not writable.`); try { result[key] = normalizeFieldValue(field, value); } catch (error) { throw new ApiValidationError(error instanceof Error ? error.message : `${key} is invalid.`); } }
  return result as CreateCustomerBody;
}
function validateNested(root: string, value: Record<string, unknown>) { const allowed: Record<string, string[]> = { primaryContact: ["fullName", "title", "phone", "email"], billingAddress: ["line1", "line2", "district", "city", "postalCode", "country"], shippingAddress: ["line1", "line2", "district", "city", "postalCode", "country"], commercialTerms: ["paymentTermDays", "creditLimitCents", "defaultCurrency", "discountRateBasisPoints", "deliveryTerm", "notes"] }; const result: Record<string, unknown> = {}; for (const [key, nestedValue] of Object.entries(value)) { if (!allowed[root]?.includes(key)) throw new ApiValidationError(`${root}.${key} is not an allowed customer field.`); const registryKey = root === "commercialTerms" && key === "defaultCurrency" ? "currency" : `${root}.${key}`; const field = CUSTOMER_BUILT_IN_FIELDS.find((item) => item.key === registryKey); if (!field) throw new ApiValidationError(`${root}.${key} is unavailable.`); try { result[key] = normalizeFieldValue(field, nestedValue); } catch (error) { throw new ApiValidationError(error instanceof Error ? error.message : `${root}.${key} is invalid.`); } } return result; }
