import { canAccessField, normalizeFieldValue, type FieldAuthorityContext, type ModuleFieldDefinition } from "@/lib/field-authority/field-authority";
import type { StructuredFieldCandidate } from "@/lib/field-authority/structured-field-ingestion";

export type CustomerIngestionLifecycle = "IDLE" | "ATTACHMENT_READY" | "EXTRACTING" | "REVIEW_REQUIRED" | "DUPLICATE_CONFLICT" | "APPLYING_TO_DRAFT" | "READY" | "SUBMITTING" | "SUCCEEDED" | "FAILED" | "CANCELLED" | "EXPIRED";
export type DuplicateResolution = { kind: "OPEN_EXISTING" | "UPDATE_EXISTING"; customerId: string; expectedVersion?: string } | { kind: "CREATE_NEW_ANYWAY"; confirmed: boolean };
export type CustomerIngestionPreviewState = { lifecycle: CustomerIngestionLifecycle; attachment?: { attachmentRef: string; conversationId?: string; filename: string; mimeType: string; size: number }; extractionRequestId?: string; candidates: StructuredFieldCandidate[]; accepted: string[]; rejected: string[]; edits: Record<string, unknown>; conflicts: string[]; warnings: string[]; duplicateMatches: Array<{ customerId: string; strength: "STRONG" | "WEAK" }>; duplicateResolution?: DuplicateResolution; activeSurfaceToken?: string; targetOperation: "CREATE_NEW_CUSTOMER" | "UPDATE_EXISTING_CUSTOMER"; draftSnapshot: Record<string, unknown>; executionId?: string; entityId?: string; error?: string; updatedAt: string; expiresAt?: string };
const initial = (): CustomerIngestionPreviewState => ({ lifecycle: "IDLE", candidates: [], accepted: [], rejected: [], edits: {}, conflicts: [], warnings: [], duplicateMatches: [], targetOperation: "CREATE_NEW_CUSTOMER", draftSnapshot: {}, updatedAt: new Date(0).toISOString() });
export class CustomerIngestionPreviewRuntime {
  state: CustomerIngestionPreviewState = initial();
  private replayedTokens = new Set<string>();
  private commitPromise?: Promise<{ executionId: string; entityId: string }>;
  attach(attachment: NonNullable<CustomerIngestionPreviewState["attachment"]>, expiresAt: string) { this.state = { ...initial(), lifecycle: "ATTACHMENT_READY", attachment, expiresAt, updatedAt: new Date().toISOString() }; return this.state; }
  extracting(extractionRequestId: string) { this.assertNotExpired(); if (this.state.lifecycle !== "ATTACHMENT_READY") throw new Error("ATTACHMENT_NOT_READY"); this.state = { ...this.state, lifecycle: "EXTRACTING", extractionRequestId, updatedAt: new Date().toISOString() }; return this.state; }
  load(input: Pick<CustomerIngestionPreviewState, "attachment" | "extractionRequestId" | "candidates" | "conflicts" | "warnings" | "expiresAt"> & { duplicateMatches?: CustomerIngestionPreviewState["duplicateMatches"] }) { const duplicateMatches = input.duplicateMatches ?? []; this.state = { ...this.state, ...input, duplicateMatches, lifecycle: duplicateMatches.some((item) => item.strength === "STRONG") ? "DUPLICATE_CONFLICT" : "REVIEW_REQUIRED", accepted: input.candidates.filter((item) => item.conflictStatus === "NONE").map((item) => item.fieldId), rejected: [], edits: {}, updatedAt: new Date().toISOString() }; return this.state; }
  decide(fieldId: string, accepted: boolean) { this.assertReview(); this.assertCandidate(fieldId); this.state = { ...this.state, accepted: accepted ? [...new Set([...this.state.accepted, fieldId])] : this.state.accepted.filter((id) => id !== fieldId), rejected: accepted ? this.state.rejected.filter((id) => id !== fieldId) : [...new Set([...this.state.rejected, fieldId])], updatedAt: new Date().toISOString() }; return this.state; }
  edit(fieldId: string, value: unknown, fields?: readonly ModuleFieldDefinition[], context?: FieldAuthorityContext) { this.assertReview(); this.assertCandidate(fieldId); const field = fields?.find((item) => item.fieldId === fieldId); if (fields && (!field || (context && !canAccessField(field, context).writable))) throw new Error("FIELD_NOT_WRITABLE"); const normalized = field ? normalizeFieldValue(field, value) : value; this.state = { ...this.state, edits: { ...this.state.edits, [fieldId]: normalized }, conflicts: this.state.conflicts.filter((id) => id !== fieldId), accepted: [...new Set([...this.state.accepted, fieldId])], updatedAt: new Date().toISOString() }; return this.state; }
  resolveDuplicate(resolution: DuplicateResolution) { if (this.state.lifecycle !== "DUPLICATE_CONFLICT") throw new Error("DUPLICATE_RESOLUTION_NOT_REQUIRED"); if ((resolution.kind === "OPEN_EXISTING" || resolution.kind === "UPDATE_EXISTING") && !this.state.duplicateMatches.some((item) => item.customerId === resolution.customerId)) throw new Error("UNTRUSTED_CUSTOMER_ID"); this.state = { ...this.state, duplicateResolution: resolution, lifecycle: resolution.kind === "CREATE_NEW_ANYWAY" && !resolution.confirmed ? "DUPLICATE_CONFLICT" : "REVIEW_REQUIRED", targetOperation: resolution.kind === "UPDATE_EXISTING" ? "UPDATE_EXISTING_CUSTOMER" : "CREATE_NEW_CUSTOMER", updatedAt: new Date().toISOString() }; return this.state; }
  applyToDraft(current: Record<string, unknown>, fields?: readonly ModuleFieldDefinition[], context?: FieldAuthorityContext) { this.assertReview(); if (this.state.conflicts.some((id) => this.state.accepted.includes(id) && this.state.edits[id] === undefined)) throw new Error("CONFLICT_REQUIRES_DECISION"); const values = { ...current }; this.state = { ...this.state, lifecycle: "APPLYING_TO_DRAFT" }; for (const candidate of this.state.candidates) { if (!this.state.accepted.includes(candidate.fieldId)) continue; const field = fields?.find((item) => item.fieldId === candidate.fieldId); if (fields && (!field || (context && !canAccessField(field, context).writable))) throw new Error("FIELD_NOT_WRITABLE"); values[candidate.fieldId] = field ? normalizeFieldValue(field, this.state.edits[candidate.fieldId] ?? candidate.normalizedValue) : this.state.edits[candidate.fieldId] ?? candidate.normalizedValue; } this.state = { ...this.state, lifecycle: "READY", draftSnapshot: values, updatedAt: new Date().toISOString() }; return this.state; }
  replayToSurface(token: string, replay: (values: Record<string, unknown>) => void) { this.assertNotExpired(); if (this.state.lifecycle !== "READY" || this.replayedTokens.has(token)) return false; this.replayedTokens.add(token); replay(this.state.draftSnapshot); this.state = { ...this.state, activeSurfaceToken: token, updatedAt: new Date().toISOString() }; return true; }
  async commit(execute: () => Promise<{ executionId: string; entityId: string }>) { this.assertNotExpired(); if (this.state.lifecycle === "SUCCEEDED") return { executionId: this.state.executionId!, entityId: this.state.entityId! }; if (this.state.lifecycle !== "READY" && this.state.lifecycle !== "SUBMITTING") throw new Error("PREVIEW_NOT_READY"); if (!this.commitPromise) { this.state = { ...this.state, lifecycle: "SUBMITTING", updatedAt: new Date().toISOString() }; this.commitPromise = execute().then((result) => { this.state = { ...this.state, lifecycle: "SUCCEEDED", ...result, updatedAt: new Date().toISOString() }; return result; }).catch((error) => { this.state = { ...this.state, lifecycle: "FAILED", error: error instanceof Error ? error.message : "COMMIT_FAILED", updatedAt: new Date().toISOString() }; this.commitPromise = undefined; throw error; }); } return this.commitPromise; }
  cancel() { this.commitPromise = undefined; this.state = { ...initial(), lifecycle: "CANCELLED", updatedAt: new Date().toISOString() }; return this.state; }
  private assertCandidate(fieldId: string) { if (!this.state.candidates.some((item) => item.fieldId === fieldId)) throw new Error("CANDIDATE_NOT_FOUND"); }
  private assertReview() { this.assertNotExpired(); if (!["REVIEW_REQUIRED", "DUPLICATE_CONFLICT"].includes(this.state.lifecycle)) throw new Error("PREVIEW_NOT_REVIEWABLE"); }
  private assertNotExpired() { if (this.state.expiresAt && Date.now() > new Date(this.state.expiresAt).getTime()) { this.state = { ...initial(), lifecycle: "EXPIRED", updatedAt: new Date().toISOString() }; throw new Error("PREVIEW_EXPIRED"); } }
}
