import { normalizeFieldValue, type ModuleFieldDefinition } from "@/lib/field-authority/field-authority";
export type GenericCustomerFieldPlan = { kind: "OPEN_CREATE" } | { kind: "SET_FIELDS"; fields: Array<{ fieldId: string; value: unknown }>; explicitCommit: boolean } | { kind: "CLEAR_FIELDS"; fieldIds: string[] } | { kind: "COMMIT" } | { kind: "STATUS_QUERY" } | { kind: "MISSING_FIELDS_QUERY" } | { kind: "CREATE_CUSTOM_FIELD"; definition: { key: string; label: string; valueType: string; options: string[] }; requiresExplicitApproval: true } | { kind: "UPDATE_CUSTOM_FIELD_DEFINITION"; fieldId: string; active: boolean; requiresExplicitApproval: true } | { kind: "CANCEL" } | { kind: "CLARIFICATION_REQUIRED"; reason: string } | { kind: "NOT_HANDLED" };
export function validateGenericCustomerFieldPlan(raw: unknown, safeFields: readonly ModuleFieldDefinition[]): GenericCustomerFieldPlan | null {
  if (typeof raw !== "object" || raw === null || Array.isArray(raw)) return null;
  const plan = raw as Record<string, unknown>; const byId = new Map(safeFields.map((field) => [field.fieldId, field]));
  if (plan.kind === "SET_FIELDS" && Array.isArray(plan.fields) && typeof plan.explicitCommit === "boolean" && hasOnly(plan, ["kind", "fields", "explicitCommit"])) { const fields: Array<{ fieldId: string; value: unknown }> = []; for (const item of plan.fields) { if (typeof item !== "object" || item === null || Array.isArray(item) || !hasOnly(item as Record<string, unknown>, ["fieldId", "value"])) return null; const candidate = item as Record<string, unknown>; const field = byId.get(String(candidate.fieldId)); if (!field?.writable) return null; try { fields.push({ fieldId: field.fieldId, value: normalizeFieldValue(field, candidate.value) }); } catch { return null; } } return { kind: "SET_FIELDS", fields, explicitCommit: plan.explicitCommit }; }
  if (plan.kind === "CLEAR_FIELDS" && Array.isArray(plan.fieldIds) && hasOnly(plan, ["kind", "fieldIds"])) { const ids = plan.fieldIds.filter((id): id is string => typeof id === "string"); if (ids.length !== plan.fieldIds.length || ids.some((id) => !byId.get(id)?.clearable)) return null; return { kind: "CLEAR_FIELDS", fieldIds: ids }; }
  if (plan.kind === "CREATE_CUSTOM_FIELD" && typeof plan.definition === "object" && plan.definition !== null && !Array.isArray(plan.definition) && plan.requiresExplicitApproval === true && hasOnly(plan, ["kind", "definition", "requiresExplicitApproval"])) { const definition = plan.definition as Record<string, unknown>; if (!hasOnly(definition, ["key", "label", "valueType", "options"]) || typeof definition.key !== "string" || typeof definition.label !== "string" || typeof definition.valueType !== "string" || !Array.isArray(definition.options) || !definition.options.every((item) => typeof item === "string")) return null; return { kind: "CREATE_CUSTOM_FIELD", definition: { key: definition.key, label: definition.label, valueType: definition.valueType, options: definition.options as string[] }, requiresExplicitApproval: true }; }
  if (plan.kind === "UPDATE_CUSTOM_FIELD_DEFINITION" && typeof plan.fieldId === "string" && plan.fieldId.startsWith("customer.custom.") && typeof plan.active === "boolean" && plan.requiresExplicitApproval === true && hasOnly(plan, ["kind", "fieldId", "active", "requiresExplicitApproval"])) return { kind: plan.kind, fieldId: plan.fieldId, active: plan.active, requiresExplicitApproval: true };
  if (["OPEN_CREATE", "COMMIT", "STATUS_QUERY", "MISSING_FIELDS_QUERY", "CANCEL", "NOT_HANDLED"].includes(String(plan.kind)) && Object.keys(plan).length === 1) return plan as GenericCustomerFieldPlan;
  if (plan.kind === "CLARIFICATION_REQUIRED" && typeof plan.reason === "string" && hasOnly(plan, ["kind", "reason"])) return { kind: plan.kind, reason: plan.reason };
  return null;
}
function hasOnly(value: Record<string, unknown>, keys: string[]) { return Object.keys(value).sort().join() === [...keys].sort().join(); }
export function buildGenericCustomerFieldPrompt(input: { operation: "create" | "update"; safeFields: readonly ModuleFieldDefinition[]; currentDraft: Record<string, unknown>; missingRequiredFields: string[] }) { const fields = input.safeFields.filter((field) => field.readable).map(({ fieldId, label, description, valueType, writable, clearable, aliases, validation }) => ({ fieldId, label, description, valueType, writable, clearable, aliases, validation })); return `Customer field planner. Strict JSON only. Never invent a fieldId, route, action, actor, organization or storage path. Operation: ${input.operation}. Safe fields: ${JSON.stringify(fields)}. Current draft: ${JSON.stringify(input.currentDraft)}. Missing required: ${JSON.stringify(input.missingRequiredFields)}.`; }
