import { isRecord } from "@/lib/api/validation";
export const PRODUCT_EDIT_FIELD_NAMES = ["name", "type", "category", "unit", "costCents", "priceCents", "currency", "stockBehavior", "status"] as const;
export const PRODUCT_CLEARABLE_FIELD_NAMES = ["category", "unit", "costCents", "priceCents", "stockBehavior"] as const;
export const PRODUCT_TYPE_VALUES = ["PRODUCT", "SERVICE"] as const;
export const PRODUCT_STATUS_VALUES = ["ACTIVE", "PASSIVE", "ARCHIVED"] as const;
export type ProductEditFieldName = (typeof PRODUCT_EDIT_FIELD_NAMES)[number];
export type ProductEditCommand = { type: "set_field"; field: ProductEditFieldName; value: string } | { type: "clear_field"; field: (typeof PRODUCT_CLEARABLE_FIELD_NAMES)[number] } | { type: "revert_field"; field: ProductEditFieldName } | { type: "commit" } | { type: "discard" };
export type ProductEditCommandResolution = { kind: "executable"; command: ProductEditCommand } | { kind: "unsupported" } | { kind: "clarification_required"; message: string };
export type ProductEditCommandExecutionResult = { status: "EXECUTED"; command: ProductEditCommand; appliedField?: string; appliedValue?: string; commitOutcome?: "SAVED"; revertedFields?: string[] } | { status: "UNSUPPORTED" } | { status: "CLARIFICATION_REQUIRED"; message: string } | { status: "NO_ACTIVE_SURFACE" } | { status: "STALE_SURFACE" } | { status: "VALIDATION_FAILED"; reason: string } | { status: "EXECUTION_FAILED"; error: string };
function member(value: unknown, values: readonly string[]): value is string { return typeof value === "string" && values.includes(value); }
export function validateProductEditCommandResolution(raw: unknown): ProductEditCommandResolution | null { if (!isRecord(raw)) return null; if (raw.result === "unsupported") return { kind: "unsupported" }; if (raw.result === "clarification_required") return typeof raw.message === "string" && raw.message.trim() ? { kind: "clarification_required", message: raw.message.trim() } : null; if (raw.result !== "executable") return null; if (raw.action === "commit" || raw.action === "discard") return { kind: "executable", command: { type: raw.action } }; if (raw.action === "set_field" && member(raw.field, PRODUCT_EDIT_FIELD_NAMES) && typeof raw.value === "string" && raw.value.trim() && (raw.field !== "type" || member(raw.value, PRODUCT_TYPE_VALUES)) && (raw.field !== "status" || member(raw.value, PRODUCT_STATUS_VALUES))) return { kind: "executable", command: { type: "set_field", field: raw.field as ProductEditFieldName, value: raw.value } }; if (raw.action === "clear_field" && member(raw.field, PRODUCT_CLEARABLE_FIELD_NAMES)) return { kind: "executable", command: { type: "clear_field", field: raw.field as (typeof PRODUCT_CLEARABLE_FIELD_NAMES)[number] } }; if (raw.action === "revert_field" && member(raw.field, PRODUCT_EDIT_FIELD_NAMES)) return { kind: "executable", command: { type: "revert_field", field: raw.field as ProductEditFieldName } }; return null; }
export function revalidateProductEditCommandResolution(raw: unknown): ProductEditCommandResolution | null { if (!isRecord(raw)) return null; if (raw.kind === "unsupported") return { kind: "unsupported" }; if (raw.kind === "clarification_required") return typeof raw.message === "string" && raw.message.trim() ? { kind: "clarification_required", message: raw.message.trim() } : null; if (raw.kind !== "executable" || !isRecord(raw.command)) return null; return validateProductEditCommandResolution({ result: "executable", action: raw.command.type, ...raw.command }); }
