"use client";

import { useCallback, useEffect, useMemo, useState, type ReactNode } from "react";
import { getDelivery, mutateDelivery, type DeliveryRecord } from "@/lib/deliveries/deliveries-client";
import type { DeliveryEditCommand, DeliveryEditCommandExecutionResult } from "@/lib/deliveries/delivery-edit-command-contract";
import { registerDeliveryEditSurfaceTarget, unregisterDeliveryEditSurfaceTarget } from "@/lib/deliveries/delivery-edit-surface-command-channel";

const TRANSITIONS: Record<string, readonly string[]> = { DRAFT: ["PREPARING", "CANCELLED"], PREPARING: ["PICKING", "CANCELLED"], PICKING: ["PACKING", "CANCELLED"], PACKING: ["LOADED", "CANCELLED"], LOADED: ["DISPATCHED", "CANCELLED"], DISPATCHED: ["AT_DELIVERY_POINT", "FAILED_DELIVERY"], AT_DELIVERY_POINT: ["DELIVERED", "FAILED_DELIVERY"], DELIVERED: ["COMPLETED"], FAILED_DELIVERY: ["RESCHEDULED"], RESCHEDULED: ["DISPATCHED", "CANCELLED"], COMPLETED: [], CANCELLED: [] };
const STATUS: Record<string, string> = { DRAFT: "Taslak", PREPARING: "Hazırlanıyor", PICKING: "Toplanıyor", PACKING: "Paketleniyor", LOADED: "Yüklendi", DISPATCHED: "Sevk edildi", AT_DELIVERY_POINT: "Teslimat noktasında", DELIVERED: "Teslim edildi", COMPLETED: "Tamamlandı", FAILED_DELIVERY: "Teslim edilemedi", RESCHEDULED: "Yeniden planlandı", CANCELLED: "İptal edildi" };
const EXCEPTIONS = ["CUSTOMER_NOT_AT_ADDRESS", "DELIVERY_REFUSED", "PRODUCT_DAMAGED", "VEHICLE_BREAKDOWN", "WRONG_ADDRESS", "SHORTAGE_FOUND", "DELIVERY_POSTPONED", "OTHER"] as const;
const EXCEPTION: Record<string, string> = { CUSTOMER_NOT_AT_ADDRESS: "Müşteri adreste yok", DELIVERY_REFUSED: "Teslimat reddedildi", PRODUCT_DAMAGED: "Ürün hasarlı", VEHICLE_BREAKDOWN: "Araç arızası", WRONG_ADDRESS: "Yanlış adres", SHORTAGE_FOUND: "Eksik ürün", DELIVERY_POSTPONED: "Teslimat ertelendi", OTHER: "Diğer" };
const CONDITIONS = ["OK", "SHORT", "DAMAGED", "WRONG_ITEM", "MIXED"] as const;
const CONDITION: Record<string, string> = { OK: "Sorunsuz", SHORT: "Eksik", DAMAGED: "Hasarlı", WRONG_ITEM: "Yanlış ürün", MIXED: "Karışık" };
const inputClass = "w-full rounded-xl border border-white/[.1] bg-white/[.04] px-3 py-2.5 text-sm text-[#EDE7D9] outline-none focus:border-[#34e6cf]/45";

export function DeliveryActionSurface({ deliveryId, onReady, onFailure }: { deliveryId: string; onReady?: () => void; onFailure?: () => void }) {
  const [delivery, setDelivery] = useState<DeliveryRecord | null>(null); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  const [conditionItem, setConditionItem] = useState(""); const [condition, setCondition] = useState<typeof CONDITIONS[number]>("OK");
  const [exceptionCategory, setExceptionCategory] = useState<typeof EXCEPTIONS[number]>(EXCEPTIONS[0]); const [exceptionNote, setExceptionNote] = useState("");
  const [confirmationCode, setConfirmationCode] = useState(""); const [receiverName, setReceiverName] = useState(""); const [signatureCaptured, setSignatureCaptured] = useState(false); const [proofNote, setProofNote] = useState("");
  const [statusReason, setStatusReason] = useState(""); const [cancelReason, setCancelReason] = useState("");
  const load = useCallback(async () => { const result = await getDelivery(deliveryId); if (result.ok) { setDelivery(result.data.delivery); setError(null); onReady?.(); } else { setError(result.error); onFailure?.(); } }, [deliveryId, onFailure, onReady]);
  useEffect(() => { void load(); }, [load]); useEffect(() => { if (delivery?.items[0]) setConditionItem((value) => value || delivery.items[0]!.id); }, [delivery]);
  const targets = useMemo(() => delivery ? (TRANSITIONS[delivery.status] ?? []).filter((value) => value !== "CANCELLED") : [], [delivery]);
  const act = useCallback(async (payload: Record<string, unknown>, reset?: () => void): Promise<string | null> => { setBusy(true); setError(null); const result = await mutateDelivery(deliveryId, payload); if (result.ok) { reset?.(); await load(); setBusy(false); return null; } setError(result.error); setBusy(false); return result.error; }, [deliveryId, load]);
  useEffect(() => {
    const runtime = { getState: () => ({ activeTab: "actions" as const }), applyCommand: async (command: DeliveryEditCommand): Promise<DeliveryEditCommandExecutionResult> => { const commandError = await act(commandPayload(command)); return commandError ? { status: "EXECUTION_FAILED", error: commandError } : { status: "EXECUTED", command }; } };
    const token = registerDeliveryEditSurfaceTarget({ entityId: deliveryId, runtime });
    return () => unregisterDeliveryEditSurfaceTarget(token);
  }, [act, deliveryId]);
  if (!delivery && !error) return <p className="py-12 text-center text-sm text-[#7C7466]">İrsaliye yükleniyor…</p>;
  if (!delivery) return <Message error={error ?? "İrsaliye bulunamadı."}/>;
  const canCancel = (TRANSITIONS[delivery.status] ?? []).includes("CANCELLED");
  return <div className="mx-auto max-w-5xl space-y-4 pb-8" data-delivery-action-surface={delivery.id}>
    <header className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs uppercase tracking-[.18em] text-[#7C7466]">İrsaliye çalışma alanı</p><h2 className="mt-1 text-xl font-semibold text-[#EDE7D9]">{delivery.deliveryNumber}</h2><p className="mt-1 text-sm text-[#A79F91]">{delivery.customer?.displayName ?? "Müşteri"}{delivery.carrier ? ` · ${delivery.carrier}` : ""}</p></div><Badge>{STATUS[delivery.status] ?? delivery.status}</Badge></header>
    {error ? <Message error={error}/> : null}
    <Card title="İrsaliye kalemleri"><div className="space-y-2">{delivery.items.map((item) => <div className="flex items-center justify-between gap-3 rounded-xl border border-white/[.06] bg-black/10 p-3" key={item.id}><div><p className="text-sm font-semibold text-[#EDE7D9]">{item.name}</p><p className="mt-1 text-xs text-[#7C7466]">{item.quantity} {item.unit ?? "birim"}</p></div><Badge>{item.conditionFlag ? CONDITION[item.conditionFlag] ?? item.conditionFlag : "Durum yok"}</Badge></div>)}</div></Card>
    <div className="grid gap-4 lg:grid-cols-2">
      <Card title="Kalem durumu"><form className="space-y-3" onSubmit={(e) => { e.preventDefault(); void act({ action: "item-condition", deliveryItemId: conditionItem, conditionFlag: condition }); }}><Select label="İrsaliye kalemi" value={conditionItem} set={setConditionItem} options={delivery.items.map((item) => ({ value: item.id, label: item.name }))}/><Select label="Durum bayrağı" value={condition} set={(value) => setCondition(value as typeof condition)} options={CONDITIONS.map((value) => ({ value, label: CONDITION[value] }))}/><Action disabled={busy || !conditionItem}>Kalem durumunu kaydet</Action></form></Card>
      <Card title="İstisna kaydı"><form className="space-y-3" onSubmit={(e) => { e.preventDefault(); void act({ action: "exception", category: exceptionCategory, note: exceptionNote }, () => setExceptionNote("")); }}><Select label="İstisna kategorisi" value={exceptionCategory} set={(value) => setExceptionCategory(value as typeof exceptionCategory)} options={EXCEPTIONS.map((value) => ({ value, label: EXCEPTION[value] }))}/><Field label="Not"><textarea aria-label="İstisna notu" className={`${inputClass} min-h-20`} value={exceptionNote} onChange={(e) => setExceptionNote(e.target.value)}/></Field><Action disabled={busy}>İstisna kaydet</Action></form></Card>
    </div>
    <Card title="Teslimat kanıtı"><form className="grid gap-3 md:grid-cols-2" onSubmit={(e) => { e.preventDefault(); void act({ action: "proof", confirmationCode, receiverName, signatureCaptured, note: proofNote }, () => { setConfirmationCode(""); setReceiverName(""); setSignatureCaptured(false); setProofNote(""); }); }}><Field label="Onay kodu"><input aria-label="Teslimat onay kodu" className={inputClass} value={confirmationCode} onChange={(e) => setConfirmationCode(e.target.value)}/></Field><Field label="Alıcı adı"><input aria-label="Teslim alan kişi" className={inputClass} value={receiverName} onChange={(e) => setReceiverName(e.target.value)}/></Field><Field label="Not"><textarea aria-label="Teslimat kanıtı notu" className={`${inputClass} min-h-20`} value={proofNote} onChange={(e) => setProofNote(e.target.value)}/></Field><label className="flex items-center gap-2 text-sm text-[#A79F91]"><input aria-label="İmza alındı" checked={signatureCaptured} onChange={(e) => setSignatureCaptured(e.target.checked)} type="checkbox"/>İmza alındı</label><div className="md:col-span-2"><Action disabled={busy}>Teslimat kanıtını kaydet</Action></div></form>{delivery.deliveryProof ? <p className="mt-3 text-xs text-[#A79F91]">Son kanıt: {delivery.receiverName ?? "Alıcı belirtilmedi"} · {delivery.deliveryProof.confirmationCode ?? "Kod yok"} · {delivery.deliveryProof.signatureCaptured ? "İmzalı" : "İmza yok"}</p> : null}</Card>
    <Card title="Durum yönetimi"><Field label="Geçiş sebebi"><input aria-label="Durum geçişi sebebi" className={inputClass} value={statusReason} onChange={(e) => setStatusReason(e.target.value)}/></Field><div className="mt-3 flex flex-wrap gap-2">{targets.map((target) => <button className="rounded-xl border border-[#34e6cf]/25 bg-[#34e6cf]/10 px-3 py-2 text-xs font-semibold text-[#34e6cf] disabled:opacity-40" disabled={busy} key={target} onClick={() => void act({ toStatus: target, reason: statusReason }, () => setStatusReason(""))} type="button">{STATUS[target] ?? target}</button>)}{!targets.length && !canCancel ? <p className="text-sm text-[#7C7466]">Bu durumdan izin verilen başka bir geçiş yok.</p> : null}</div>{canCancel ? <form className="mt-4 flex flex-col gap-3 border-t border-white/[.07] pt-4 sm:flex-row sm:items-end" onSubmit={(e) => { e.preventDefault(); void act({ action: "cancel", reason: cancelReason }, () => setCancelReason("")); }}><div className="flex-1"><Field label="İptal sebebi"><input aria-label="İrsaliye iptal sebebi" className={inputClass} required value={cancelReason} onChange={(e) => setCancelReason(e.target.value)}/></Field></div><Action disabled={busy || !cancelReason.trim()} danger>İrsaliyeyi iptal et</Action></form> : null}</Card>
    <div className="grid gap-4 lg:grid-cols-2"><History title="İstisna geçmişi" empty="Henüz istisna yok" rows={[...delivery.exceptions].reverse().map((row) => <HistoryRow key={row.id} title={EXCEPTION[row.category] ?? row.category} detail={row.note ?? "Not yok"} date={row.createdAt}/>)}/><History title="Durum geçmişi" empty="Henüz durum kaydı yok" rows={[...delivery.statusHistory].reverse().map((row) => <HistoryRow key={row.id} title={`${row.fromStatus ? STATUS[row.fromStatus] ?? row.fromStatus : "Başlangıç"} → ${STATUS[row.toStatus] ?? row.toStatus}`} detail={row.reason ?? "Sebep belirtilmedi"} date={row.createdAt}/>)}/></div>
  </div>;
}

function Card({ title, children }: { title: string; children: ReactNode }) { return <section className="rounded-[20px] border border-white/[.08] bg-white/[.035] p-4"><h3 className="mb-3 text-sm font-semibold text-[#EDE7D9]">{title}</h3>{children}</section>; }
function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="block text-xs font-medium text-[#A79F91]"><span className="mb-1.5 block">{label}</span>{children}</label>; }
function Select({ label, value, set, options }: { label: string; value: string; set: (value: string) => void; options: Array<{ value: string; label: string }> }) { return <Field label={label}><select aria-label={label} className={inputClass} value={value} onChange={(e) => set(e.target.value)}>{options.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></Field>; }
function Action({ children, disabled, danger }: { children: ReactNode; disabled: boolean; danger?: boolean }) { return <button className={`rounded-xl px-4 py-2.5 text-sm font-bold disabled:opacity-40 ${danger ? "border border-[#f16a7a]/30 bg-[#f16a7a]/10 text-[#f16a7a]" : "bg-[#34e6cf] text-[#14120F]"}`} disabled={disabled} type="submit">{children}</button>; }
function Badge({ children }: { children: ReactNode }) { return <span className="rounded-full border border-[#C9BFA8]/20 bg-[#C9BFA8]/10 px-3 py-1.5 text-xs font-semibold text-[#C9BFA8]">{children}</span>; }
function Message({ error }: { error: string }) { return <p className="rounded-xl border border-[#f16a7a]/20 bg-[#f16a7a]/10 p-3 text-sm text-[#f16a7a]" role="alert">{error}</p>; }
function History({ title, empty, rows }: { title: string; empty: string; rows: ReactNode[] }) { return <Card title={title}>{rows.length ? <div className="space-y-3">{rows}</div> : <p className="text-xs text-[#7C7466]">{empty}</p>}</Card>; }
function HistoryRow({ title, detail, date }: { title: string; detail: string; date: string }) { return <article className="border-b border-white/[.06] pb-3 last:border-0 last:pb-0"><p className="text-xs font-semibold text-[#EDE7D9]">{title}</p><p className="mt-1 text-xs text-[#A79F91]">{detail}</p><time className="mt-1 block text-[10px] text-[#7C7466]">{new Intl.DateTimeFormat("tr-TR", { dateStyle: "medium", timeStyle: "short" }).format(new Date(date))}</time></article>; }
function commandPayload(command: DeliveryEditCommand): Record<string, unknown> {
  switch (command.type) {
    case "flag_item_condition": return { action: "item-condition", deliveryItemId: command.deliveryItemId, conditionFlag: command.condition };
    case "record_exception": return { action: "exception", category: command.category, note: command.note };
    case "record_proof": return { action: "proof", confirmationCode: command.confirmationCode, receiverName: command.receiverName, signatureCaptured: command.signatureCaptured, note: command.note };
    case "transition_status": return { toStatus: command.toStatus, reason: command.reason };
    case "cancel": return { action: "cancel", reason: command.reason };
  }
}
