import type { WorkspaceDomain } from "./contracts";

export type DomainSurfaceAdapter = Readonly<{
  domainKey: WorkspaceDomain; entityTypes: readonly string[]; endpoint: string;
  // The JSON key the endpoint's list response nests its rows under — not
  // always domainKey pluralized (e.g. offer's Prisma/API model is Quote,
  // so /api/quotes responds with { quotes: [...] }). This is the single
  // canonical source LivingWorkspaceHost's generic list reader uses to find
  // rows; every WorkspaceDomain must have one, so a new domain can never
  // silently render "Kayıt bulunamadı" from a forgotten hand-written list.
  responseKey: string;
  fieldRegistry: readonly string[]; allowedListColumns: readonly string[];
  allowedFilters: readonly string[]; allowedSorts: readonly string[];
  summaryMetrics: readonly string[]; supportedQuickActions: readonly string[];
  permissionRequirements: readonly string[];
  emptyStateCode: string; dataQualityCode: string;
}>;
export const DOMAIN_SURFACE_ADAPTERS: Readonly<Record<WorkspaceDomain, DomainSurfaceAdapter>> = Object.freeze({
  company: Object.freeze({ domainKey:"company", entityTypes:["Company"], endpoint:"/api/company", responseKey:"company", fieldRegistry:["summary","risks","opportunities","dataQuality"], allowedListColumns:[], allowedFilters:[], allowedSorts:[], summaryMetrics:["profileReadiness","activeGoals","openManagementIssues","connectedDataSources"], supportedQuickActions:[], permissionRequirements:["company.read"], emptyStateCode:"COMPANY_CANONICAL_DATA_EMPTY", dataQualityCode:"COMPANY_MODEL_DATA_QUALITY" }),
  customer: Object.freeze({ domainKey:"customer", entityTypes:["Customer"], endpoint:"/api/customers", responseKey:"customers", fieldRegistry:["displayName","legalName","status","balanceCents","currency","updatedAt"], allowedListColumns:["displayName","status","balanceCents","currency","updatedAt"], allowedFilters:["displayName","status","balanceCents"], allowedSorts:["displayName","balanceCents","updatedAt"], summaryMetrics:["count","activeCount","balanceCents"], supportedQuickActions:["open-detail"], permissionRequirements:["customers.read"], emptyStateCode:"CUSTOMER_CANONICAL_DATA_EMPTY", dataQualityCode:"OVERDUE_REQUIRES_DUE_DATE_CAPABILITY" }),
  supplier: Object.freeze({ domainKey:"supplier", entityTypes:["Supplier"], endpoint:"/api/suppliers", responseKey:"suppliers", fieldRegistry:["displayName","legalName","status","taxNumber","phone","email","score","onTimeDeliveryRate","avgLeadTimeDays","dependencyRiskFlag","updatedAt"], allowedListColumns:["displayName","score","onTimeDeliveryRate","dependencyRiskFlag","updatedAt"], allowedFilters:["displayName","status","taxNumber"], allowedSorts:["displayName","score","updatedAt"], summaryMetrics:["count","activeCount"], supportedQuickActions:["open-detail"], permissionRequirements:["suppliers.read"], emptyStateCode:"SUPPLIER_CANONICAL_DATA_EMPTY", dataQualityCode:"SUPPLIER_MODEL_DATA_QUALITY" }),
  product: Object.freeze({ domainKey:"product", entityTypes:["ProductService"], endpoint:"/api/products", responseKey:"products", fieldRegistry:["name","type","category","priceCents","costCents","currency","status","stock"], allowedListColumns:["name","type","category","priceCents","costCents","currency","status","stock"], allowedFilters:["name","type","category","priceCents","status","stock"], allowedSorts:["name","priceCents","costCents","updatedAt"], summaryMetrics:["count","activeCount","depletedStockCount"], supportedQuickActions:["open-detail"], permissionRequirements:["products.read"], emptyStateCode:"PRODUCT_CANONICAL_DATA_EMPTY", dataQualityCode:"STOCK_REQUIRES_CANONICAL_ATTRIBUTE" }),
  notification: Object.freeze({ domainKey:"notification", entityTypes:["Notification"], endpoint:"/api/notifications", responseKey:"notifications", fieldRegistry:["title","body","severity","type","isRead","createdAt"], allowedListColumns:["title","severity","type","isRead","createdAt"], allowedFilters:["severity","type","isRead"], allowedSorts:["createdAt"], summaryMetrics:["count","unreadCount"], supportedQuickActions:["open-detail"], permissionRequirements:["notifications.read"], emptyStateCode:"NOTIFICATION_CANONICAL_DATA_EMPTY", dataQualityCode:"NOTIFICATION_MODEL_DATA_QUALITY" }),
  task: Object.freeze({ domainKey:"task", entityTypes:["Task"], endpoint:"/api/tasks", responseKey:"tasks", fieldRegistry:["title","description","dueDate","priority","status"], allowedListColumns:["title","dueDate","priority","status"], allowedFilters:["status","priority"], allowedSorts:["dueDate","createdAt"], summaryMetrics:["count","openCount","overdueCount"], supportedQuickActions:["open-detail"], permissionRequirements:["tasks.read"], emptyStateCode:"TASK_CANONICAL_DATA_EMPTY", dataQualityCode:"TASK_MODEL_DATA_QUALITY" }),
  calendar: Object.freeze({ domainKey:"calendar", entityTypes:["CalendarEvent"], endpoint:"/api/calendar-events", responseKey:"events", fieldRegistry:["title","startAt","endAt","allDay","status","recurrenceFrequency","relatedTaskId","relatedCustomerId","relatedOrderId"], allowedListColumns:["title","startAt","endAt","allDay","status","recurrenceFrequency"], allowedFilters:["status","allDay"], allowedSorts:["startAt","endAt"], summaryMetrics:["count"], supportedQuickActions:[], permissionRequirements:["calendar.read"], emptyStateCode:"CALENDAR_CANONICAL_DATA_EMPTY", dataQualityCode:"CALENDAR_MODEL_DATA_QUALITY" }),
  offer: Object.freeze({ domainKey:"offer", entityTypes:["Quote"], endpoint:"/api/quotes", responseKey:"quotes", fieldRegistry:["customerName","title","amount","currency","status","updatedAt"], allowedListColumns:["customerName","title","amount","status","updatedAt"], allowedFilters:["status","customerName"], allowedSorts:["updatedAt","amount"], summaryMetrics:["count","openCount","amount"], supportedQuickActions:["open-detail"], permissionRequirements:["offers.read"], emptyStateCode:"OFFER_CANONICAL_DATA_EMPTY", dataQualityCode:"OFFER_MODEL_DATA_QUALITY" }),
  payment: Object.freeze({ domainKey:"payment", entityTypes:["Payment"], endpoint:"/api/payments", responseKey:"payments", fieldRegistry:["title","amount","currency","status","dueDate","createdAt","invoiceNumber","invoiceTitle"], allowedListColumns:["title","invoiceNumber","invoiceTitle","amount","currency","status","dueDate"], allowedFilters:["status"], allowedSorts:["dueDate","createdAt"], summaryMetrics:["count","overdueCount","amount"], supportedQuickActions:["open-detail"], permissionRequirements:["payments.read"], emptyStateCode:"PAYMENT_CANONICAL_DATA_EMPTY", dataQualityCode:"PAYMENT_MODEL_DATA_QUALITY" }),
  invoice: Object.freeze({ domainKey:"invoice", entityTypes:["Invoice"], endpoint:"/api/invoices", responseKey:"invoices", fieldRegistry:["invoiceNumber","title","totalAmount","currency","status","dueDate","paymentCount","paymentReferences"], allowedListColumns:["invoiceNumber","title","totalAmount","currency","status","paymentCount","paymentReferences","dueDate"], allowedFilters:["status"], allowedSorts:["dueDate","createdAt"], summaryMetrics:["count","overdueCount","totalAmount"], supportedQuickActions:["open-detail"], permissionRequirements:["invoices.read"], emptyStateCode:"INVOICE_CANONICAL_DATA_EMPTY", dataQualityCode:"INVOICE_MODEL_DATA_QUALITY" }),
  order: Object.freeze({ domainKey:"order", entityTypes:["Order"], endpoint:"/api/orders", responseKey:"orders", fieldRegistry:["orderNumber","status","fulfillmentSummary","reservationStatus","priorityLabel","priorityExplanation","deliveryProgressSummary","revisionHistorySummary","deadlineAt","commitmentAt","currency","createdAt","updatedAt"], allowedListColumns:["orderNumber","priorityLabel","reservationStatus","fulfillmentSummary","deliveryProgressSummary","revisionHistorySummary","deadlineAt","commitmentAt","currency","createdAt"], allowedFilters:["status","priorityLabel"], allowedSorts:["createdAt","deadlineAt"], summaryMetrics:["count","activeCount"], supportedQuickActions:["open-detail"], permissionRequirements:["orders.read"], emptyStateCode:"ORDER_CANONICAL_DATA_EMPTY", dataQualityCode:"ORDER_MODEL_DATA_QUALITY" }),
  delivery: Object.freeze({ domainKey:"delivery", entityTypes:["Delivery"], endpoint:"/api/deliveries", responseKey:"deliveries", fieldRegistry:["deliveryNumber","status","carrier","integritySummary","onTimeDeliveryRate","firstAttemptSuccessRate","damageRate","deliveryAddress","dispatchedAt","deliveredAt","createdAt","updatedAt"], allowedListColumns:["deliveryNumber","carrier","integritySummary","onTimeDeliveryRate","firstAttemptSuccessRate","damageRate","status","dispatchedAt"], allowedFilters:["status","carrier"], allowedSorts:["createdAt","dispatchedAt"], summaryMetrics:["count","activeCount"], supportedQuickActions:["open-detail"], permissionRequirements:["deliveries.read"], emptyStateCode:"DELIVERY_CANONICAL_DATA_EMPTY", dataQualityCode:"DELIVERY_MODEL_DATA_QUALITY" }),
  accounting: Object.freeze({ domainKey:"accounting", entityTypes:["AccountingSummary"], endpoint:"/api/accounting/summary", responseKey:"summary", fieldRegistry:["cashPosition","totalReceivable","totalPayable","monthlyRevenue","monthlyExpense","monthlyTaxLiability"], allowedListColumns:[], allowedFilters:[], allowedSorts:[], summaryMetrics:["cashPosition","totalReceivable","totalPayable","monthlyRevenue","monthlyExpense","monthlyTaxLiability"], supportedQuickActions:[], permissionRequirements:["accounting.read"], emptyStateCode:"ACCOUNTING_CANONICAL_DATA_EMPTY", dataQualityCode:"ACCOUNTING_COMPUTED_SUMMARY_DATA_QUALITY" }),
  finance: Object.freeze({ domainKey:"finance", entityTypes:["FinanceSummary"], endpoint:"/api/finance/summary", responseKey:"summary", fieldRegistry:["accountingSummary","financialHealthIntelligence","expenseContext","expenseIntelligence"], allowedListColumns:[], allowedFilters:[], allowedSorts:[], summaryMetrics:["financialHealthLevel","cashPressureLevel","collectionCoverageRatio","monthlyBurnRate","overdueCount"], supportedQuickActions:[], permissionRequirements:["finance.read"], emptyStateCode:"FINANCE_CANONICAL_DATA_EMPTY", dataQualityCode:"FINANCE_COMPUTED_INTELLIGENCE_DATA_QUALITY" }),
  team: Object.freeze({ domainKey:"team", entityTypes:["OrganizationMember"], endpoint:"/api/organization-members", responseKey:"members", fieldRegistry:["email","fullName","role","status","joinedAt"], allowedListColumns:["email","role","status","joinedAt"], allowedFilters:["role","status"], allowedSorts:["joinedAt"], summaryMetrics:["count","activeCount"], supportedQuickActions:["invite","change-role","disable"], permissionRequirements:["members.manage"], emptyStateCode:"TEAM_EMPTY", dataQualityCode:"TEAM_MEMBERSHIP_DATA_QUALITY" }),
  goal: Object.freeze({ domainKey:"goal", entityTypes:["SalesGoal"], endpoint:"/api/goals", responseKey:"goals", fieldRegistry:["title","period","status","targetRevenueCents","targetCollectionCents","actualValue","forecastValue","startsAt","endsAt"], allowedListColumns:["title","period","status","targetRevenueCents","targetCollectionCents","actualValue","forecastValue","startsAt","endsAt"], allowedFilters:["period","status"], allowedSorts:["startsAt","endsAt"], summaryMetrics:["count","activeCount"], supportedQuickActions:["open-detail"], permissionRequirements:["goals.write"], emptyStateCode:"GOAL_CANONICAL_DATA_EMPTY", dataQualityCode:"GOAL_MODEL_DATA_QUALITY" }),
  stock: Object.freeze({ domainKey:"stock", entityTypes:["Stock"], endpoint:"/api/stock", responseKey:"stocks", fieldRegistry:["productServiceName","warehouseName","quantity","reservedQuantity","availableQuantity","status","lot","batch","serialNumber","location","healthSummary","openVarianceCount","riskSignalCount","opportunitySignalCount","createdAt","updatedAt"], allowedListColumns:["productServiceName","warehouseName","quantity","reservedQuantity","availableQuantity","status","updatedAt"], allowedFilters:["status"], allowedSorts:["createdAt","updatedAt"], summaryMetrics:["count","availableCount"], supportedQuickActions:[], permissionRequirements:["stock.read"], emptyStateCode:"STOCK_CANONICAL_DATA_EMPTY", dataQualityCode:"STOCK_MODEL_DATA_QUALITY" }),
  report: Object.freeze({ domainKey:"report", entityTypes:["ExecutiveReport"], endpoint:"/api/reports/board", responseKey:"report", fieldRegistry:["reportType","title","executiveSummary","sections","overallConfidence","dataQualityNote","generatedAt"], allowedListColumns:[], allowedFilters:[], allowedSorts:[], summaryMetrics:["overallConfidence","sectionCount"], supportedQuickActions:[], permissionRequirements:["report.read"], emptyStateCode:"REPORT_CANONICAL_DATA_EMPTY", dataQualityCode:"REPORT_COMPUTED_SUMMARY_DATA_QUALITY" }),
  document: Object.freeze({ domainKey:"document", entityTypes:["Document"], endpoint:"/api/documents", responseKey:"documents", fieldRegistry:["filename","mimeType","sizeBytes","relatedEntityType","relatedEntityId","documentType","version","status","source","verified","createdAt","updatedAt"], allowedListColumns:["filename","documentType","relatedEntityType","status","verified","createdAt"], allowedFilters:["status","documentType","relatedEntityType"], allowedSorts:["createdAt","updatedAt"], summaryMetrics:["count"], supportedQuickActions:[], permissionRequirements:["document.read"], emptyStateCode:"DOCUMENT_CANONICAL_DATA_EMPTY", dataQualityCode:"DOCUMENT_MODEL_DATA_QUALITY" }),
  kpi: Object.freeze({ domainKey:"kpi", entityTypes:["KpiDefinition"], endpoint:"/api/kpis", responseKey:"kpis", fieldRegistry:["key","label","description","scope","period","targetRelation","active","version","rationale","linkedGoalCount","createdAt","updatedAt"], allowedListColumns:["label","scope","period","active","linkedGoalCount","updatedAt"], allowedFilters:["scope","period","active"], allowedSorts:["createdAt","updatedAt"], summaryMetrics:["count"], supportedQuickActions:[], permissionRequirements:["goals.write"], emptyStateCode:"KPI_CANONICAL_DATA_EMPTY", dataQualityCode:"KPI_MODEL_DATA_QUALITY" }),
  production: Object.freeze({ domainKey:"production", entityTypes:["ProductionOrder"], endpoint:"/api/production", responseKey:"productions", fieldRegistry:["orderNumber","status","quantityPlanned","quantityProduced","plannedStartAt","plannedEndAt","actualStartAt","actualEndAt","notes","createdAt","updatedAt"], allowedListColumns:["orderNumber","status","quantityPlanned","quantityProduced","plannedStartAt","plannedEndAt"], allowedFilters:["status"], allowedSorts:["createdAt","plannedStartAt"], summaryMetrics:["count","activeCount"], supportedQuickActions:["open-detail"], permissionRequirements:["production.read"], emptyStateCode:"PRODUCTION_CANONICAL_DATA_EMPTY", dataQualityCode:"PRODUCTION_MODEL_DATA_QUALITY" }),
});
