import type { WorkspaceDomain } from "./contracts";

export type DomainSurfaceAdapter = Readonly<{
  domainKey: WorkspaceDomain; entityTypes: readonly string[]; endpoint: string;
  fieldRegistry: readonly string[]; allowedListColumns: readonly string[];
  allowedFilters: readonly string[]; allowedSorts: readonly string[];
  summaryMetrics: readonly string[]; supportedQuickActions: readonly string[];
  fullPageRoutes: readonly string[]; permissionRequirements: readonly string[];
  emptyStateCode: string; dataQualityCode: string;
}>;
export const DOMAIN_SURFACE_ADAPTERS: Readonly<Record<WorkspaceDomain, DomainSurfaceAdapter>> = Object.freeze({
  company: Object.freeze({ domainKey:"company", entityTypes:["Company"], endpoint:"/api/company", fieldRegistry:["summary","risks","opportunities","dataQuality"], allowedListColumns:[], allowedFilters:[], allowedSorts:[], summaryMetrics:["profileReadiness","activeGoals","openManagementIssues","connectedDataSources"], supportedQuickActions:["open-full-page"], fullPageRoutes:["/metrix/company"], permissionRequirements:["company.read"], emptyStateCode:"COMPANY_CANONICAL_DATA_EMPTY", dataQualityCode:"COMPANY_MODEL_DATA_QUALITY" }),
  customer: Object.freeze({ domainKey:"customer", entityTypes:["Customer"], endpoint:"/api/customers", fieldRegistry:["displayName","legalName","status","balanceCents","currency","updatedAt"], allowedListColumns:["displayName","status","balanceCents","currency","updatedAt"], allowedFilters:["displayName","status","balanceCents"], allowedSorts:["displayName","balanceCents","updatedAt"], summaryMetrics:["count","balanceCents"], supportedQuickActions:["open-detail","open-full-page"], fullPageRoutes:["/metrix/customers"], permissionRequirements:["customers.read"], emptyStateCode:"CUSTOMER_CANONICAL_DATA_EMPTY", dataQualityCode:"OVERDUE_REQUIRES_DUE_DATE_CAPABILITY" }),
  product: Object.freeze({ domainKey:"product", entityTypes:["ProductService"], endpoint:"/api/products", fieldRegistry:["name","type","category","priceCents","costCents","currency","status","stock"], allowedListColumns:["name","type","category","priceCents","costCents","currency","status","stock"], allowedFilters:["name","type","category","priceCents","status","stock"], allowedSorts:["name","priceCents","costCents","updatedAt"], summaryMetrics:["count"], supportedQuickActions:["open-full-page"], fullPageRoutes:["/metrix/products"], permissionRequirements:["products.read"], emptyStateCode:"PRODUCT_CANONICAL_DATA_EMPTY", dataQualityCode:"STOCK_REQUIRES_CANONICAL_ATTRIBUTE" }),
  notification: Object.freeze({ domainKey:"notification", entityTypes:["Notification"], endpoint:"/api/notifications", fieldRegistry:["title","body","severity","type","isRead","createdAt"], allowedListColumns:["title","severity","type","isRead","createdAt"], allowedFilters:["severity","type","isRead"], allowedSorts:["createdAt"], summaryMetrics:["count","unreadCount"], supportedQuickActions:["open-full-page"], fullPageRoutes:["/metrix/notifications"], permissionRequirements:["notifications.read"], emptyStateCode:"NOTIFICATION_CANONICAL_DATA_EMPTY", dataQualityCode:"NOTIFICATION_MODEL_DATA_QUALITY" }),
  task: Object.freeze({ domainKey:"task", entityTypes:["Task"], endpoint:"/api/tasks", fieldRegistry:["title","description","dueDate","priority","status"], allowedListColumns:["title","dueDate","priority","status"], allowedFilters:["status","priority"], allowedSorts:["dueDate","createdAt"], summaryMetrics:["count","openCount","overdueCount"], supportedQuickActions:["open-full-page"], fullPageRoutes:["/metrix/tasks","/metrix/tasks/new"], permissionRequirements:["tasks.read"], emptyStateCode:"TASK_CANONICAL_DATA_EMPTY", dataQualityCode:"TASK_MODEL_DATA_QUALITY" }),
  offer: Object.freeze({ domainKey:"offer", entityTypes:["Quote"], endpoint:"/api/quotes", fieldRegistry:["customerName","title","amount","currency","status","updatedAt"], allowedListColumns:["customerName","title","amount","status","updatedAt"], allowedFilters:["status","customerName"], allowedSorts:["updatedAt","amount"], summaryMetrics:["count"], supportedQuickActions:["open-full-page"], fullPageRoutes:["/metrix/offers"], permissionRequirements:["offers.read"], emptyStateCode:"OFFER_CANONICAL_DATA_EMPTY", dataQualityCode:"OFFER_MODEL_DATA_QUALITY" }),
});
