// Single, domain-agnostic authority for turning any conversation-extension
// handoff into the assistant's user-facing message. Works purely off the
// generic ConversationExtensionHandoff shape (never a domain's outcomeCode
// vocabulary), so it applies unchanged to every current domain (customers,
// tasks, quotes) and any future one without new code per capability. A
// domain may still layer richer wording on top (see route.ts's
// buildCustomerCreateHandoffMessage), but whenever it doesn't, this is the
// floor every domain gets — the AI backend never gets to contradict an
// already-resolved extension outcome.

import type { ConversationExtensionHandoff } from "./conversation-extension-handoff";

export function buildUniversalHandoffMessage(handoff: ConversationExtensionHandoff): string | null {
  if (handoff.resultStatus === "FAILED") {
    return "Bu işlemi gerçekleştiremedim. Tekrar dener misiniz?";
  }
  if (handoff.resultStatus === "APPROVAL_REQUIRED") {
    return "Bu işlem onay gerektiriyor; devam etmeden önce onayınızı bekliyorum.";
  }
  if (handoff.resultStatus === "CLARIFICATION_REQUIRED") {
    if (handoff.entityResolution === "AMBIGUOUS" && handoff.candidateNames.length > 0) {
      return `Bu isimle eşleşen birden fazla kayıt var: ${joinNames(handoff.candidateNames)}. Hangisini kastettiğinizi belirtir misiniz?`;
    }
    if (handoff.entityResolution === "NOT_FOUND") {
      return "Bu isimle eşleşen bir kayıt bulamadım. Başka bir isimle mi deneyelim, yoksa yeni bir kayıt mı oluşturalım?";
    }
    return "Devam edebilmem için biraz daha bilgi verir misiniz?";
  }
  if (handoff.resultStatus === "EXECUTED") {
    if (handoff.mutationPerformed) {
      return handoff.navigationRequested && handoff.navigationStatus === "COMPLETED"
        ? "İşlemi tamamladım ve ilgili kaydı çalışma alanında açtım."
        : "İşlemi tamamladım.";
    }
    if (handoff.navigationRequested && handoff.navigationStatus === "COMPLETED") {
      return "İlgili kaydı çalışma alanında açtım, yukarıda inceleyebilirsiniz.";
    }
    return "İşlemi tamamladım.";
  }
  if (handoff.resultStatus === "OBSERVED" && handoff.candidateNames.length > 0) {
    return `Kanonik kayıtlara göre: ${joinNames(handoff.candidateNames)}.`;
  }
  return null;
}

// A completed mutation OR a completed navigation is the authoritative,
// final result of this turn. Progressive enrichment is generated by a
// second, independent model call that receives the first response as
// plain text but never the handoff itself — it has no way to know a
// record/workspace was already, definitively opened, and free-generating
// without that evidence reliably produces a contradicting continuation
// (observed live: "İlgili kaydı çalışma alanında açtım..." immediately
// followed by "Excel dosyasının tam adı ve içeriğini... belirtmeniz
// gerekiyor", as if the same turn's own first sentence hadn't happened).
// Keep the deterministic confirmation final for both cases.
export function shouldAppendProgressiveEnrichment(handoff: ConversationExtensionHandoff | null): boolean {
  if (!handoff || handoff.resultStatus !== "EXECUTED") return true;
  return !(handoff.mutationPerformed || (handoff.navigationRequested && handoff.navigationStatus === "COMPLETED"));
}

function joinNames(names: readonly string[]): string {
  return names.length === 1 ? names[0]! : `${names.slice(0, -1).join(", ")} ve ${names[names.length - 1]}`;
}

// Living Workspace Determinism Operation: no conversation extension claimed
// this turn (no handoff at all — not even a FAILED/CLARIFICATION_REQUIRED
// one), yet the turn still looks record-mutation-shaped via business-
// navigation's own create-Surface resolution (customer/offer/task.create —
// a Workspace surface for a create-domain was resolved, but nothing
// confirms a mutation happened through it). Nothing confirms a mutation
// happened, so the free-text response must never be trusted to say so on
// its own — domain-agnostic and evidence-gated, never word-matched.
//
// Legacy Conversation Ownership & Dangling Stream Closure: this used to
// fire on this MUTATION_SURFACE_RESOLVED signal (and, separately, on
// userMotivation === "kayit_islem" && shouldInvokeExecutiveBrain alone)
// unconditionally — written when "no handoff" reliably meant nobody would
// generate a real answer for a recognized mutation intent. That premise is
// retired: shouldInvokeExecutiveBrain is exactly the signal that now routes
// the turn to the METRIX Executive Agent instead (see route.ts's
// executiveAgentWillRespond), which owns it for real via its own tools —
// regardless of which clause below would otherwise fire. A live regression
// (2026-09-05: "'İkinci görüşmeyi planla' başlıklı bir görev oluştur.",
// task.create resolving MUTATION_SURFACE_RESOLVED) proved the guard must
// check this Agent-eligibility signal directly, not just the narrower
// userMotivation combination — any single "let something else claim
// ownership of this signal" carve-out reintroduces the same bug under a
// different trigger. shouldInvokeExecutiveBrain is therefore a blanket
// early-exit here, ahead of both remaining clauses.
export function buildUnconfirmedMutationIntentMessage(input: {
  hasHandoff: boolean;
  shouldInvokeExecutiveBrain: boolean;
  mutationSurfaceResolved: boolean;
}): string | null {
  if (input.hasHandoff || input.shouldInvokeExecutiveBrain || !input.mutationSurfaceResolved) return null;
  return "Bu işlemi bu turda tamamladığımı doğrulayamadım; ilgili kaydı veya çalışma alanını netleştiremedim. Tekrar ifade eder misiniz, ya da hangi kayıt/işlem olduğunu belirtir misiniz?";
}
