import { listSuppliers } from "@/lib/suppliers/suppliers-client";
import { resolveSupplierReference } from "@/lib/suppliers/supplier-resolution";
import type { ConversationExtension, ConversationExtensionSource } from "./conversation-extension-contract";
import { dispatchConversationNavigation } from "./conversation-navigation-runtime";
import { supplierHandoff } from "./conversation-extension-handoff";

const LIST_SUPPLIERS_PATTERN = /^(?:(?:tedarikçilerimizi|tedarikçileri|tedarikcilerimizi|tedarikcileri)\s+(?:göster|goster)|tedarikçi\s+listesi)[.!]?$/i;
const CREATE_SUPPLIER_PATTERN = /^(?:yeni\s+(?:bir\s+)?)?tedarik(?:çi|ci)\s+ekle[.!]?$/i;
const OPEN_SUPPLIER_PATTERN = /^(.+?)\s+tedarikçisini\s+aç[.!]?$/i;
function navigate(route: string, source: ConversationExtensionSource, correlationId: string) { if (typeof window === "undefined") return; void dispatchConversationNavigation({ route, source, correlationId, expectedSurfaceAuthorityKey: route.endsWith("/new") ? "suppliers.create.page" : "suppliers.list.page" }); }
async function resolve(reference: string) { const response=await listSuppliers(); if(!response.ok)return {error:response.error} as const; return {resolution:resolveSupplierReference(response.data.suppliers,reference)} as const; }
export const supplierManagementConversationExtension: ConversationExtension = { getActiveScopeKey(){ return typeof window === "undefined" ? null : `suppliers-management:${window.location.pathname}`; }, async execute(utterance,source="written",correlationId=crypto.randomUUID()){ const text=utterance.trim(); if(LIST_SUPPLIERS_PATTERN.test(text)){navigate("/metrix/suppliers",source,correlationId);return {status:"HANDOFF",handoff:supplierHandoff({operation:"NAVIGATE",outcomeCode:"SUPPLIER_LIST_OPENED",resultStatus:"EXECUTED",entityResolution:"NOT_REQUIRED",navigationRequested:true,navigationStatus:"COMPLETED"})};} if(CREATE_SUPPLIER_PATTERN.test(text)){navigate("/metrix/suppliers/new",source,correlationId);return {status:"HANDOFF",handoff:supplierHandoff({operation:"NAVIGATE",outcomeCode:"SUPPLIER_CREATE_OPENED",resultStatus:"EXECUTED",entityResolution:"NOT_REQUIRED",navigationRequested:true,navigationStatus:"COMPLETED"})};} const open=text.match(OPEN_SUPPLIER_PATTERN); if(!open)return {status:"NOT_HANDLED",handoff:null}; const found=await resolve(open[1]!.trim()); if("error" in found)return {status:"HANDOFF",handoff:supplierHandoff({operation:"NAVIGATE",outcomeCode:"SUPPLIER_LOOKUP_FAILED",resultStatus:"FAILED",failureCode:"SUPPLIER_LOOKUP_FAILED"})}; if(found.resolution.status!=="RESOLVED")return {status:"HANDOFF",handoff:supplierHandoff({operation:"NAVIGATE",outcomeCode:found.resolution.status==="AMBIGUOUS"?"SUPPLIER_AMBIGUOUS":"SUPPLIER_NOT_FOUND",resultStatus:"CLARIFICATION_REQUIRED",entityResolution:found.resolution.status})}; navigate("/metrix/suppliers",source,correlationId); return {status:"HANDOFF",handoff:supplierHandoff({operation:"NAVIGATE",outcomeCode:"SUPPLIER_OPENED",resultStatus:"EXECUTED",entityResolution:"RESOLVED",navigationRequested:true,navigationStatus:"COMPLETED",candidateNames:[found.resolution.supplier.displayName]})}; } };
