import { listSuppliers } from "@/lib/suppliers/suppliers-client";
import { resolveSupplierReference } from "@/lib/suppliers/supplier-resolution";
import type { ConversationExtension, ConversationExtensionSource } from "./conversation-extension-contract";
import { dispatchConversationNavigation } from "./conversation-navigation-runtime";
import { supplierHandoff } from "./conversation-extension-handoff";

const LIST = /^(?:(?:tedarikçilerimizi|tedarikçileri|tedarikcilerimizi|tedarikcileri)\s+(?:göster|goster)|tedarikçi\s+listesi)[.!]?$/iu;
const CREATE = /^(?:yeni\s+(?:bir\s+)?)?tedarik(?:çi|ci)\s+ekle[.!]?$/iu;
const OPEN = /^(.+?)\s+tedarikçisini\s+aç[.!]?$/iu;
const PERFORMANCE = /^(.+?)(?:'|’)?(?:nin|nın|nun|nün|in|ın|un|ün)\s+(?:performansını\s+göster|ne\s+kadar\s+güvenilir)[.!]?$/iu;
const ALTERNATIVE = /^(.+?)\s+için\s+(?:alternatif\s+tedarikçi\s+var\s+mı|başka\s+tedarikçi\s+öner)[?!.]?$/iu;

function navigate(route:string,source:ConversationExtensionSource,correlationId:string){if(typeof window!=="undefined")void dispatchConversationNavigation({route,source,correlationId,expectedSurfaceAuthorityKey:route.endsWith("/new")?"suppliers.create.page":"suppliers.list.page"});}
async function resolve(reference:string){const response=await listSuppliers();if(!response.ok)return {error:response.error} as const;return {resolution:resolveSupplierReference(response.data.suppliers,reference)} as const;}
async function findProduct(reference:string){const response=await fetch("/api/products?status=ACTIVE",{credentials:"include"});const payload=await response.json() as {ok?:boolean;data?:{products:Array<{id:string;name:string}>}};if(!payload.ok||!payload.data)return null;const needle=reference.toLocaleLowerCase("tr-TR");return payload.data.products.find((product)=>product.name.toLocaleLowerCase("tr-TR")===needle)??payload.data.products.find((product)=>product.name.toLocaleLowerCase("tr-TR").includes(needle))??null;}

export const supplierManagementConversationExtension:ConversationExtension={getActiveScopeKey(){return typeof window==="undefined"?null:`suppliers-management:${window.location.pathname}`;},async execute(utterance,source="written",correlationId=crypto.randomUUID()){
  const text=utterance.trim();
  const alternative=text.match(ALTERNATIVE);
  if(alternative){const product=await findProduct(alternative[1]!.trim());if(!product)return {status:"HANDOFF",handoff:supplierHandoff({operation:"QUERY",outcomeCode:"SUPPLIER_PRODUCT_NOT_FOUND",resultStatus:"CLARIFICATION_REQUIRED",entityResolution:"NOT_FOUND"})};const response=await fetch(`/api/suppliers/alternatives?productServiceId=${encodeURIComponent(product.id)}`,{credentials:"include"});const payload=await response.json() as {ok?:boolean;data?:{alternatives:Array<{displayName:string}>}};const names=payload.data?.alternatives.map((item)=>item.displayName)??[];navigate("/metrix/suppliers",source,correlationId);return {status:"HANDOFF",handoff:supplierHandoff({operation:"QUERY",outcomeCode:names.length?"ALTERNATIVE_SUPPLIERS_FOUND":"ALTERNATIVE_SUPPLIERS_NOT_FOUND",resultStatus:"EXECUTED",entityResolution:"NOT_REQUIRED",candidateNames:names,navigationRequested:true,navigationStatus:"COMPLETED"})};}
  if(LIST.test(text)){navigate("/metrix/suppliers",source,correlationId);return {status:"HANDOFF",handoff:supplierHandoff({operation:"NAVIGATE",outcomeCode:"SUPPLIER_LIST_OPENED",resultStatus:"EXECUTED",entityResolution:"NOT_REQUIRED",navigationRequested:true,navigationStatus:"COMPLETED"})};}
  if(CREATE.test(text)){navigate("/metrix/suppliers/new",source,correlationId);return {status:"HANDOFF",handoff:supplierHandoff({operation:"NAVIGATE",outcomeCode:"SUPPLIER_CREATE_OPENED",resultStatus:"EXECUTED",entityResolution:"NOT_REQUIRED",navigationRequested:true,navigationStatus:"COMPLETED"})};}
  const match=text.match(PERFORMANCE)??text.match(OPEN);if(!match)return {status:"NOT_HANDLED",handoff:null};const found=await resolve(match[1]!.trim());if("error" in found)return {status:"HANDOFF",handoff:supplierHandoff({operation:"NAVIGATE",outcomeCode:"SUPPLIER_LOOKUP_FAILED",resultStatus:"FAILED",failureCode:"SUPPLIER_LOOKUP_FAILED"})};if(found.resolution.status!=="RESOLVED")return {status:"HANDOFF",handoff:supplierHandoff({operation:"NAVIGATE",outcomeCode:found.resolution.status==="AMBIGUOUS"?"SUPPLIER_AMBIGUOUS":"SUPPLIER_NOT_FOUND",resultStatus:"CLARIFICATION_REQUIRED",entityResolution:found.resolution.status})};await fetch(`/api/suppliers/${encodeURIComponent(found.resolution.supplier.id)}`,{credentials:"include"});navigate(`/metrix/suppliers/${encodeURIComponent(found.resolution.supplier.id)}`,source,correlationId);return {status:"HANDOFF",handoff:supplierHandoff({operation:"NAVIGATE",outcomeCode:"SUPPLIER_PERFORMANCE_OPENED",resultStatus:"EXECUTED",entityResolution:"RESOLVED",navigationRequested:true,navigationStatus:"COMPLETED",candidateNames:[found.resolution.supplier.displayName]})};
}};
