import type { ActionDefinition } from "../action-registry.types";

const OWNER_MODULE = "corporate_cards";

export const corporateCardActionDefinitions: ActionDefinition[] = [
  {
    actionName: "corporateCard.create",
    actionClass: "DOMAIN",
    ownerModule: OWNER_MODULE,
    inputSchema: {
      cardholderMemberId: { type: "string", required: true },
      label: { type: "string", required: true },
      bankName: { type: "string", required: false },
      last4: { type: "string", required: false },
      currency: { type: "string", required: false },
    },
    riskLevelBase: "LOW",
    requiredPermissionSet: ["corporate_cards.write"],
    approvalPolicy: "NONE",
    approvalTtlClass: "STANDARD",
    isReversible: false,
    compensationRef: null,
  },
  {
    actionName: "corporateCard.updateStatus",
    actionClass: "DOMAIN",
    ownerModule: OWNER_MODULE,
    inputSchema: {
      corporateCardId: { type: "string", required: true },
      status: { type: "string", required: true },
    },
    riskLevelBase: "LOW",
    requiredPermissionSet: ["corporate_cards.write"],
    approvalPolicy: "NONE",
    approvalTtlClass: "STANDARD",
    isReversible: false,
    compensationRef: null,
  },
  {
    actionName: "cardStatement.open",
    actionClass: "DOMAIN",
    ownerModule: OWNER_MODULE,
    inputSchema: {
      corporateCardId: { type: "string", required: true },
      periodStart: { type: "string", required: true },
      periodEnd: { type: "string", required: true },
      dueDate: { type: "string", required: true },
    },
    riskLevelBase: "LOW",
    requiredPermissionSet: ["corporate_cards.write"],
    approvalPolicy: "NONE",
    approvalTtlClass: "STANDARD",
    isReversible: false,
    compensationRef: null,
  },
  {
    actionName: "cardStatement.close",
    actionClass: "DOMAIN",
    ownerModule: OWNER_MODULE,
    inputSchema: {
      cardStatementId: { type: "string", required: true },
    },
    riskLevelBase: "MEDIUM",
    requiredPermissionSet: ["corporate_cards.write"],
    approvalPolicy: "NONE",
    approvalTtlClass: "STANDARD",
    isReversible: false,
    compensationRef: null,
  },
  {
    actionName: "cardStatement.pay",
    actionClass: "DOMAIN",
    ownerModule: OWNER_MODULE,
    inputSchema: {
      cardStatementId: { type: "string", required: true },
      amount: { type: "number", required: true },
      paymentMethod: { type: "string", required: true },
      financialAccountReference: { type: "string", required: true },
      occurredAt: { type: "string", required: false },
      idempotencyKey: { type: "string", required: false },
    },
    riskLevelBase: "HIGH",
    requiredPermissionSet: ["corporate_cards.write"],
    approvalPolicy: "CONDITIONAL",
    approvalTtlClass: "SHORT",
    isReversible: false,
    compensationRef: null,
  },
  {
    actionName: "cardStatement.payment.reverse",
    actionClass: "DOMAIN",
    ownerModule: OWNER_MODULE,
    inputSchema: {
      cardStatementPaymentId: { type: "string", required: true },
      reason: { type: "string", required: true },
    },
    riskLevelBase: "HIGH",
    requiredPermissionSet: ["corporate_cards.reverse"],
    approvalPolicy: "CONDITIONAL",
    approvalTtlClass: "SHORT",
    isReversible: false,
    compensationRef: null,
  },
];
