import type { ActionDefinition } from "../action-registry.types";

const OWNER_MODULE = "employee_advances";

export const employeeAdvanceActionDefinitions: ActionDefinition[] = [
  {
    actionName: "employeeAdvance.create",
    actionClass: "DOMAIN",
    ownerModule: OWNER_MODULE,
    inputSchema: {
      employeeMemberId: { type: "string", required: true },
      amount: { type: "number", required: true },
      currency: { type: "string", required: false },
      note: { type: "string", required: false },
    },
    riskLevelBase: "LOW",
    requiredPermissionSet: ["employee_advances.write"],
    approvalPolicy: "NONE",
    approvalTtlClass: "STANDARD",
    isReversible: false,
    compensationRef: null,
  },
  {
    actionName: "employeeAdvance.move",
    actionClass: "DOMAIN",
    ownerModule: OWNER_MODULE,
    inputSchema: {
      employeeAdvanceId: { type: "string", required: true },
      direction: { type: "string", required: true },
      amount: { type: "number", required: true },
      paymentMethod: { type: "string", required: true },
      financialAccountReference: { type: "string", required: true },
      occurredAt: { type: "string", required: false },
      idempotencyKey: { type: "string", required: false },
    },
    riskLevelBase: "HIGH",
    requiredPermissionSet: ["employee_advances.write"],
    approvalPolicy: "CONDITIONAL",
    approvalTtlClass: "SHORT",
    isReversible: false,
    compensationRef: null,
  },
  {
    actionName: "employeeAdvance.movement.reverse",
    actionClass: "DOMAIN",
    ownerModule: OWNER_MODULE,
    inputSchema: {
      employeeAdvanceMovementId: { type: "string", required: true },
      reason: { type: "string", required: true },
    },
    riskLevelBase: "HIGH",
    requiredPermissionSet: ["employee_advances.reverse"],
    approvalPolicy: "CONDITIONAL",
    approvalTtlClass: "SHORT",
    isReversible: false,
    compensationRef: null,
  },
  {
    actionName: "employeeAdvance.reconcile",
    actionClass: "DOMAIN",
    ownerModule: OWNER_MODULE,
    inputSchema: {
      employeeAdvanceId: { type: "string", required: true },
      expenseId: { type: "string", required: true },
      amount: { type: "number", required: true },
      occurredAt: { type: "string", required: false },
      idempotencyKey: { type: "string", required: false },
    },
    riskLevelBase: "MEDIUM",
    requiredPermissionSet: ["employee_advances.write"],
    approvalPolicy: "NONE",
    approvalTtlClass: "STANDARD",
    isReversible: false,
    compensationRef: null,
  },
  {
    actionName: "employeeAdvance.reconciliation.reverse",
    actionClass: "DOMAIN",
    ownerModule: OWNER_MODULE,
    inputSchema: {
      employeeAdvanceReconciliationId: { type: "string", required: true },
      reason: { type: "string", required: true },
    },
    riskLevelBase: "MEDIUM",
    requiredPermissionSet: ["employee_advances.reverse"],
    approvalPolicy: "NONE",
    approvalTtlClass: "STANDARD",
    isReversible: false,
    compensationRef: null,
  },
];
