import type { ActionDefinition } from "../action-registry.types";

const OWNER_MODULE = "expenses";

const mutableMetadata = {
  description: { type: "string" as const, required: false },
  subcategory: { type: "string" as const, required: false },
  netAmount: { type: "number" as const, required: false },
  taxRate: { type: "number" as const, required: false },
  taxAmount: { type: "number" as const, required: false },
  vendorName: { type: "string" as const, required: false },
  supplierId: { type: "string" as const, required: false },
  customerId: { type: "string" as const, required: false },
  employeeMemberId: { type: "string" as const, required: false },
  note: { type: "string" as const, required: false },
};

export const expenseActionDefinitions: ActionDefinition[] = [
  {
    actionName: "expense.create",
    actionClass: "DOMAIN",
    ownerModule: OWNER_MODULE,
    inputSchema: {
      title: { type: "string", required: true },
      category: { type: "string", required: true },
      amount: { type: "number", required: true },
      expenseDate: { type: "string", required: true },
      currency: { type: "string", required: false },
      recurrenceType: { type: "string", required: false },
      ...mutableMetadata,
    },
    riskLevelBase: "LOW",
    requiredPermissionSet: ["expenses.write"],
    approvalPolicy: "NONE",
    approvalTtlClass: "STANDARD",
    isReversible: true,
    compensationRef: "expense.cancel",
  },
  {
    actionName: "expense.update",
    actionClass: "DOMAIN",
    ownerModule: OWNER_MODULE,
    inputSchema: {
      expenseId: { type: "string", required: true },
      title: { type: "string", required: false },
      category: { type: "string", required: false },
      amount: { type: "number", required: false },
      expenseDate: { type: "string", required: false },
      ...mutableMetadata,
    },
    riskLevelBase: "LOW",
    requiredPermissionSet: ["expenses.write"],
    approvalPolicy: "NONE",
    approvalTtlClass: "STANDARD",
    isReversible: false,
    compensationRef: null,
  },
  {
    actionName: "expense.cancel",
    actionClass: "DOMAIN",
    ownerModule: OWNER_MODULE,
    inputSchema: {
      expenseId: { type: "string", required: true },
      reason: { type: "string", required: false },
    },
    riskLevelBase: "LOW",
    requiredPermissionSet: ["expenses.write"],
    approvalPolicy: "NONE",
    approvalTtlClass: "STANDARD",
    isReversible: false,
    compensationRef: null,
  },
  {
    actionName: "expense.settle",
    actionClass: "DOMAIN",
    ownerModule: OWNER_MODULE,
    inputSchema: {
      expenseId: { type: "string", required: true },
      amount: { type: "number", required: true },
      paymentMethod: { type: "string", required: true },
      financialAccountReference: { type: "string", required: true },
      occurredAt: { type: "string", required: false },
      idempotencyKey: { type: "string", required: false },
    },
    riskLevelBase: "HIGH",
    requiredPermissionSet: ["expenses.write"],
    approvalPolicy: "CONDITIONAL",
    approvalTtlClass: "SHORT",
    isReversible: false,
    compensationRef: null,
  },
  {
    actionName: "expense.settlement.reverse",
    actionClass: "DOMAIN",
    ownerModule: OWNER_MODULE,
    inputSchema: {
      expenseSettlementId: { type: "string", required: true },
      reason: { type: "string", required: true },
    },
    riskLevelBase: "HIGH",
    requiredPermissionSet: ["expenses.reverse"],
    approvalPolicy: "CONDITIONAL",
    approvalTtlClass: "SHORT",
    isReversible: false,
    compensationRef: null,
  },
];
