import type { ActionDefinition } from "../action-registry.types";

const OWNER_MODULE = "financial-instruments";

export const financialInstrumentActionDefinitions: ActionDefinition[] = [
  {
    actionName: "financialInstrument.register",
    actionClass: "DOMAIN",
    ownerModule: OWNER_MODULE,
    inputSchema: {
      instrumentType: { type: "enum", required: true, enumValues: ["CHEQUE", "PROMISSORY_NOTE"] },
      direction: { type: "enum", required: true, enumValues: ["RECEIVED", "ISSUED"] },
      customerId: { type: "string", required: false },
      supplierId: { type: "string", required: false },
      amount: { type: "number", required: true },
      currency: { type: "string", required: false },
      issueDate: { type: "string", required: false },
      maturityDate: { type: "string", required: true },
      instrumentNumber: { type: "string", required: false },
      bankName: { type: "string", required: false },
      branchName: { type: "string", required: false },
      drawerName: { type: "string", required: false },
      notes: { type: "string", required: false },
    },
    riskLevelBase: "LOW",
    requiredPermissionSet: ["financial_instruments.write"],
    approvalPolicy: "NONE",
    approvalTtlClass: "STANDARD",
    isReversible: true,
    compensationRef: "financialInstrument.cancel",
  },
  {
    actionName: "financialInstrument.applyToObligation",
    actionClass: "DOMAIN",
    ownerModule: OWNER_MODULE,
    inputSchema: {
      instrumentId: { type: "string", required: true },
      obligationScheduleLineId: { type: "string", required: true },
      amount: { type: "number", required: true },
    },
    riskLevelBase: "MEDIUM",
    requiredPermissionSet: ["financial_instruments.write"],
    approvalPolicy: "NONE",
    approvalTtlClass: "STANDARD",
    isReversible: false,
    compensationRef: null,
  },
  {
    actionName: "financialInstrument.clear",
    actionClass: "DOMAIN",
    ownerModule: OWNER_MODULE,
    inputSchema: {
      instrumentId: { type: "string", required: true },
      paymentMethod: { type: "string", required: true },
      financialAccountReference: { type: "string", required: true },
      occurredAt: { type: "string", required: false },
    },
    riskLevelBase: "HIGH",
    requiredPermissionSet: ["financial_instruments.clear"],
    approvalPolicy: "CONDITIONAL",
    approvalTtlClass: "SHORT",
    isReversible: false,
    compensationRef: null,
  },
  {
    actionName: "financialInstrument.bounce",
    actionClass: "DOMAIN",
    ownerModule: OWNER_MODULE,
    inputSchema: {
      instrumentId: { type: "string", required: true },
      reason: { type: "string", required: true },
    },
    riskLevelBase: "MEDIUM",
    requiredPermissionSet: ["financial_instruments.write"],
    approvalPolicy: "NONE",
    approvalTtlClass: "STANDARD",
    isReversible: false,
    compensationRef: null,
  },
  {
    actionName: "financialInstrument.cancel",
    actionClass: "DOMAIN",
    ownerModule: OWNER_MODULE,
    inputSchema: {
      instrumentId: { type: "string", required: true },
      reason: { type: "string", required: true },
    },
    riskLevelBase: "LOW",
    requiredPermissionSet: ["financial_instruments.write"],
    approvalPolicy: "NONE",
    approvalTtlClass: "STANDARD",
    isReversible: false,
    compensationRef: null,
  },
];
