import type { ActionDefinition } from "../action-registry.types";

const OWNER_MODULE = "loans";

export const loanActionDefinitions: ActionDefinition[] = [
  {
    actionName: "loan.create",
    actionClass: "DOMAIN",
    ownerModule: OWNER_MODULE,
    inputSchema: {
      lenderName: { type: "string", required: true },
      principalAmount: { type: "number", required: true },
      startDate: { type: "string", required: true },
      installments: { type: "json", required: true },
      currency: { type: "string", required: false },
      interestRate: { type: "number", required: false },
      note: { type: "string", required: false },
    },
    riskLevelBase: "MEDIUM",
    requiredPermissionSet: ["loans.write"],
    approvalPolicy: "NONE",
    approvalTtlClass: "STANDARD",
    isReversible: false,
    compensationRef: null,
  },
  {
    actionName: "loan.draw",
    actionClass: "DOMAIN",
    ownerModule: OWNER_MODULE,
    inputSchema: {
      loanId: { type: "string", required: true },
      amount: { type: "number", required: true },
      paymentMethod: { type: "string", required: true },
      financialAccountReference: { type: "string", required: true },
      occurredAt: { type: "string", required: false },
      idempotencyKey: { type: "string", required: false },
    },
    riskLevelBase: "HIGH",
    requiredPermissionSet: ["loans.write"],
    approvalPolicy: "CONDITIONAL",
    approvalTtlClass: "SHORT",
    isReversible: false,
    compensationRef: null,
  },
  {
    actionName: "loan.drawdown.reverse",
    actionClass: "DOMAIN",
    ownerModule: OWNER_MODULE,
    inputSchema: {
      loanDrawdownId: { type: "string", required: true },
      reason: { type: "string", required: true },
    },
    riskLevelBase: "HIGH",
    requiredPermissionSet: ["loans.reverse"],
    approvalPolicy: "CONDITIONAL",
    approvalTtlClass: "SHORT",
    isReversible: false,
    compensationRef: null,
  },
  {
    actionName: "loan.installment.repay",
    actionClass: "DOMAIN",
    ownerModule: OWNER_MODULE,
    inputSchema: {
      loanInstallmentId: { type: "string", required: true },
      amount: { type: "number", required: true },
      principalPortion: { type: "number", required: true },
      interestPortion: { type: "number", required: false },
      paymentMethod: { type: "string", required: true },
      financialAccountReference: { type: "string", required: true },
      occurredAt: { type: "string", required: false },
      idempotencyKey: { type: "string", required: false },
    },
    riskLevelBase: "HIGH",
    requiredPermissionSet: ["loans.write"],
    approvalPolicy: "CONDITIONAL",
    approvalTtlClass: "SHORT",
    isReversible: false,
    compensationRef: null,
  },
  {
    actionName: "loan.repayment.reverse",
    actionClass: "DOMAIN",
    ownerModule: OWNER_MODULE,
    inputSchema: {
      loanRepaymentId: { type: "string", required: true },
      reason: { type: "string", required: true },
    },
    riskLevelBase: "HIGH",
    requiredPermissionSet: ["loans.reverse"],
    approvalPolicy: "CONDITIONAL",
    approvalTtlClass: "SHORT",
    isReversible: false,
    compensationRef: null,
  },
];
