CREATE TYPE "CalendarEventStatus" AS ENUM ('DRAFT', 'PLANNED', 'CONFIRMED', 'CANCELLED', 'POSTPONED', 'COMPLETED', 'ARCHIVED');
CREATE TYPE "CalendarRecurrenceFrequency" AS ENUM ('DAILY', 'WEEKLY', 'MONTHLY', 'YEARLY');
CREATE TYPE "CalendarEventSource" AS ENUM ('USER_COMMAND', 'EXECUTIVE_DECISION', 'SYSTEM');
CREATE TABLE "CalendarEvent" ("id" TEXT NOT NULL, "organizationId" TEXT NOT NULL, "title" TEXT NOT NULL, "description" TEXT, "startAt" TIMESTAMP(3) NOT NULL, "endAt" TIMESTAMP(3) NOT NULL, "allDay" BOOLEAN NOT NULL DEFAULT false, "timeZone" TEXT NOT NULL DEFAULT 'Europe/Istanbul', "status" "CalendarEventStatus" NOT NULL DEFAULT 'PLANNED', "cancellationReason" TEXT, "postponedFromAt" TIMESTAMP(3), "recurrenceFrequency" "CalendarRecurrenceFrequency", "recurrenceInterval" INTEGER, "recurrenceUntil" TIMESTAMP(3), "recurrenceCount" INTEGER, "relatedTaskId" TEXT, "relatedCustomerId" TEXT, "relatedOrderId" TEXT, "source" "CalendarEventSource" NOT NULL DEFAULT 'USER_COMMAND', "dynamicAttributes" JSONB, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "CalendarEvent_pkey" PRIMARY KEY ("id"));
CREATE TABLE "CalendarEventParticipant" ("id" TEXT NOT NULL, "organizationId" TEXT NOT NULL, "eventId" TEXT NOT NULL, "memberId" TEXT, "customerId" TEXT, CONSTRAINT "CalendarEventParticipant_pkey" PRIMARY KEY ("id"), CONSTRAINT "CalendarEventParticipant_exactly_one_reference" CHECK (("memberId" IS NOT NULL) <> ("customerId" IS NOT NULL)));
CREATE TABLE "CalendarEventStatusHistory" ("id" TEXT NOT NULL, "organizationId" TEXT NOT NULL, "eventId" TEXT NOT NULL, "fromStatus" "CalendarEventStatus", "toStatus" "CalendarEventStatus" NOT NULL, "reason" TEXT, "performedById" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "CalendarEventStatusHistory_pkey" PRIMARY KEY ("id"));
CREATE INDEX "CalendarEvent_organizationId_startAt_idx" ON "CalendarEvent"("organizationId", "startAt");
CREATE INDEX "CalendarEvent_organizationId_status_idx" ON "CalendarEvent"("organizationId", "status");
CREATE INDEX "CalendarEvent_organizationId_relatedTaskId_idx" ON "CalendarEvent"("organizationId", "relatedTaskId");
CREATE INDEX "CalendarEvent_organizationId_relatedCustomerId_idx" ON "CalendarEvent"("organizationId", "relatedCustomerId");
CREATE INDEX "CalendarEvent_organizationId_relatedOrderId_idx" ON "CalendarEvent"("organizationId", "relatedOrderId");
CREATE INDEX "CalendarEventParticipant_organizationId_eventId_idx" ON "CalendarEventParticipant"("organizationId", "eventId");
CREATE INDEX "CalendarEventParticipant_organizationId_memberId_idx" ON "CalendarEventParticipant"("organizationId", "memberId");
CREATE INDEX "CalendarEventParticipant_organizationId_customerId_idx" ON "CalendarEventParticipant"("organizationId", "customerId");
CREATE INDEX "CalendarEventStatusHistory_organizationId_eventId_idx" ON "CalendarEventStatusHistory"("organizationId", "eventId");
CREATE INDEX "CalendarEventStatusHistory_eventId_createdAt_idx" ON "CalendarEventStatusHistory"("eventId", "createdAt");
ALTER TABLE "CalendarEvent" ADD CONSTRAINT "CalendarEvent_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "CalendarEvent" ADD CONSTRAINT "CalendarEvent_relatedTaskId_fkey" FOREIGN KEY ("relatedTaskId") REFERENCES "Task"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "CalendarEvent" ADD CONSTRAINT "CalendarEvent_relatedCustomerId_fkey" FOREIGN KEY ("relatedCustomerId") REFERENCES "Customer"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "CalendarEvent" ADD CONSTRAINT "CalendarEvent_relatedOrderId_fkey" FOREIGN KEY ("relatedOrderId") REFERENCES "Order"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "CalendarEventParticipant" ADD CONSTRAINT "CalendarEventParticipant_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "CalendarEventParticipant" ADD CONSTRAINT "CalendarEventParticipant_eventId_fkey" FOREIGN KEY ("eventId") REFERENCES "CalendarEvent"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "CalendarEventParticipant" ADD CONSTRAINT "CalendarEventParticipant_memberId_fkey" FOREIGN KEY ("memberId") REFERENCES "OrganizationMember"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "CalendarEventParticipant" ADD CONSTRAINT "CalendarEventParticipant_customerId_fkey" FOREIGN KEY ("customerId") REFERENCES "Customer"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "CalendarEventStatusHistory" ADD CONSTRAINT "CalendarEventStatusHistory_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "CalendarEventStatusHistory" ADD CONSTRAINT "CalendarEventStatusHistory_eventId_fkey" FOREIGN KEY ("eventId") REFERENCES "CalendarEvent"("id") ON DELETE CASCADE ON UPDATE CASCADE;
