import { Prisma } from "@prisma/client";
import { prisma } from "@/lib/core/shared/prisma";
import { MODULE_FIELD_VALUE_TYPES, normalizeFieldValue, type ModuleFieldDefinition, type ModuleFieldValueType } from "./field-authority";
import { customerCustomDefinitionToField } from "@/lib/customers/customer-field-registry";
export type CreateCustomFieldDefinitionInput = { organizationId: string; actorId: string; module: "customers"; entityType: "customer"; key: string; label: string; description?: string; valueType: ModuleFieldValueType; required?: boolean; options?: string[]; defaultValue?: unknown; validation?: Record<string, unknown> };
export function validateCustomFieldDefinition(input: CreateCustomFieldDefinitionInput): string[] { const errors: string[] = []; if (!/^[a-z][a-z0-9_]{1,63}$/.test(input.key)) errors.push("key must be stable lower_snake_case."); if (!input.label.trim() || input.label.length > 100) errors.push("label is invalid."); if (!MODULE_FIELD_VALUE_TYPES.includes(input.valueType)) errors.push("valueType is invalid."); if (input.valueType === "enum" && (!input.options || input.options.length < 2 || new Set(input.options).size !== input.options.length)) errors.push("enum options must contain unique values."); if (input.valueType !== "enum" && input.options?.length) errors.push("options are only allowed for enum fields."); return errors; }
export function requestCustomFieldDefinitionChange(input: CreateCustomFieldDefinitionInput) { const errors = validateCustomFieldDefinition(input); if (errors.length) return { status: "REJECTED" as const, errors }; return { status: "APPROVAL_REQUIRED" as const, approvalPolicy: "EXPLICIT" as const, riskLevel: "HIGH" as const, preview: { key: input.key, label: input.label, valueType: input.valueType, options: input.options ?? [] } }; }
export async function createApprovedCustomFieldDefinition(input: CreateCustomFieldDefinitionInput) { const errors = validateCustomFieldDefinition(input); if (errors.length) throw new Error(errors.join(" ")); try { const record = await prisma.customFieldDefinition.create({ data: { organizationId: input.organizationId, createdByUserId: input.actorId, module: input.module, entityType: input.entityType, key: input.key, label: input.label.trim(), description: input.description?.trim(), valueType: input.valueType, required: input.required ?? false, optionsJson: input.options ?? Prisma.JsonNull, defaultValueJson: input.defaultValue === undefined ? Prisma.JsonNull : input.defaultValue as Prisma.InputJsonValue, validationJson: input.validation === undefined ? Prisma.JsonNull : input.validation as Prisma.InputJsonValue } }); return record; } catch (error) { if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === "P2002") throw new Error("CUSTOM_FIELD_KEY_ALREADY_EXISTS"); throw error; } }
export async function listCustomerCustomFields(organizationId: string) { return prisma.customFieldDefinition.findMany({ where: { organizationId, module: "customers", entityType: "customer", active: true }, orderBy: { createdAt: "asc" } }); }
export async function deprecateCustomerCustomField(input: { organizationId: string; definitionId: string }) { const result = await prisma.customFieldDefinition.updateMany({ where: { id: input.definitionId, organizationId: input.organizationId, module: "customers", entityType: "customer", active: true }, data: { active: false, deprecatedAt: new Date() } }); if (!result.count) throw new Error("CUSTOM_FIELD_NOT_FOUND"); }
export function validateCustomerCustomFieldValue(record: { id: string; organizationId: string; key: string; label: string; description: string | null; valueType: string; required: boolean; optionsJson: unknown; active: boolean }, organizationId: string, value: unknown) { if (record.organizationId !== organizationId) throw new Error("CUSTOM_FIELD_TENANT_MISMATCH"); const field = customerCustomDefinitionToField({ ...record, options: record.optionsJson }); return normalizeFieldValue(field as ModuleFieldDefinition, value); }
