import { normalizeFieldValue, type ModuleFieldDefinition } from "./field-authority";
export type StructuredFieldSource = { sourceId: string; mediaType: string; page?: number; location?: string; evidence?: string };
export type StructuredFieldCandidate = { fieldId: string; extractedValue: unknown; normalizedValue?: unknown; confidence: number; source: StructuredFieldSource; warnings: string[]; conflicts: string[]; conflictStatus: "NONE" | "CONFLICT"; requiresUserConfirmation: true };
export type UnsupportedFieldObservation = { label: string; explanation: string; source?: StructuredFieldSource; executable: false };
export type StructuredExtractionPayload = { candidates: StructuredFieldCandidate[]; unsupportedObservations: UnsupportedFieldObservation[] };
export type StructuredFieldExtractionAdapter = { extract(input: { sourceId: string; filename: string; mediaType: string; bytes: Uint8Array; safeFields: Array<Pick<ModuleFieldDefinition, "fieldId" | "label" | "valueType">> }): Promise<unknown> };
const boundedStrings = (value: unknown) => Array.isArray(value) ? value.filter((x): x is string => typeof x === "string").slice(0, 20).map((x) => x.slice(0, 300)) : [];
export function validateStructuredFieldCandidates(raw: unknown, fields: readonly ModuleFieldDefinition[]): StructuredFieldCandidate[] {
  const input = Array.isArray(raw) ? raw : typeof raw === "object" && raw !== null && Array.isArray((raw as Record<string, unknown>).candidates) ? (raw as Record<string, unknown>).candidates as unknown[] : null;
  if (!input) throw new Error("Candidate output must be an array."); const byId = new Map(fields.map((field) => [field.fieldId, field]));
  return input.map((candidate) => { if (typeof candidate !== "object" || candidate === null || Array.isArray(candidate)) throw new Error("Invalid candidate."); const value = candidate as Record<string, unknown>; const field = byId.get(String(value.fieldId)); if (!field || !field.writable) throw new Error("Unsupported field candidate."); if (typeof value.confidence !== "number" || value.confidence < 0 || value.confidence > 1) throw new Error("Invalid confidence."); if (typeof value.source !== "object" || value.source === null || Array.isArray(value.source)) throw new Error("Invalid source."); const sourceValue = value.source as Record<string, unknown>; const source: StructuredFieldSource = { sourceId: String(sourceValue.sourceId ?? ""), mediaType: String(sourceValue.mediaType ?? ""), ...(typeof sourceValue.page === "number" ? { page: sourceValue.page } : {}), ...(typeof sourceValue.location === "string" ? { location: sourceValue.location.slice(0, 120) } : {}), ...(typeof sourceValue.evidence === "string" ? { evidence: sourceValue.evidence.slice(0, 300) } : {}) }; if (!source.sourceId || !source.mediaType) throw new Error("Invalid source."); const normalizedValue = normalizeFieldValue(field, value.extractedValue); const conflicts = boundedStrings(value.conflicts); return { fieldId: field.fieldId, extractedValue: value.extractedValue, normalizedValue, confidence: value.confidence, source, warnings: boundedStrings(value.warnings), conflicts, conflictStatus: conflicts.length ? "CONFLICT" : "NONE", requiresUserConfirmation: true as const }; });
}
export function validateStructuredExtractionPayload(raw: unknown, fields: readonly ModuleFieldDefinition[]): StructuredExtractionPayload { const candidates = validateStructuredFieldCandidates(raw, fields); const observationsRaw = typeof raw === "object" && raw !== null && Array.isArray((raw as Record<string, unknown>).unsupportedObservations) ? (raw as Record<string, unknown>).unsupportedObservations as unknown[] : []; const unsupportedObservations = observationsRaw.flatMap((item) => { if (!item || typeof item !== "object" || Array.isArray(item)) return []; const value = item as Record<string, unknown>; if (typeof value.label !== "string" || typeof value.explanation !== "string") return []; return [{ label: value.label.slice(0, 100), explanation: value.explanation.slice(0, 300), executable: false as const }]; }); return { candidates, unsupportedObservations }; }
export function previewCandidatesInDraft(candidates: readonly StructuredFieldCandidate[], current: Record<string, unknown>) { const values = { ...current }; const conflicts: string[] = []; for (const candidate of candidates) { if (values[candidate.fieldId] !== undefined && JSON.stringify(values[candidate.fieldId]) !== JSON.stringify(candidate.normalizedValue)) conflicts.push(candidate.fieldId); values[candidate.fieldId] = candidate.normalizedValue; } return { values, conflicts, committed: false as const }; }
