import { normalizeFieldValue, type ModuleFieldDefinition } from "./field-authority";
export type StructuredFieldSource = { sourceId: string; mediaType: string; page?: number; location?: string };
export type StructuredFieldCandidate = { fieldId: string; extractedValue: unknown; confidence: number; source: StructuredFieldSource; warnings: string[]; conflicts: string[]; requiresUserConfirmation: true };
export type StructuredFieldExtractionAdapter = { extract(input: { sourceId: string; mediaType: string; bytes: Uint8Array; safeFields: Array<Pick<ModuleFieldDefinition, "fieldId" | "label" | "valueType">> }): Promise<unknown> };
export function validateStructuredFieldCandidates(raw: unknown, fields: readonly ModuleFieldDefinition[]): StructuredFieldCandidate[] {
  if (!Array.isArray(raw)) throw new Error("Candidate output must be an array."); const byId = new Map(fields.map((field) => [field.fieldId, field]));
  return raw.map((candidate) => { if (typeof candidate !== "object" || candidate === null || Array.isArray(candidate)) throw new Error("Invalid candidate."); const value = candidate as Record<string, unknown>; const field = byId.get(String(value.fieldId)); if (!field || !field.writable) throw new Error("Unsupported field candidate."); if (typeof value.confidence !== "number" || value.confidence < 0 || value.confidence > 1) throw new Error("Invalid confidence."); if (typeof value.source !== "object" || value.source === null) throw new Error("Invalid source."); return { fieldId: field.fieldId, extractedValue: normalizeFieldValue(field, value.extractedValue), confidence: value.confidence, source: value.source as StructuredFieldSource, warnings: Array.isArray(value.warnings) ? value.warnings.filter((x): x is string => typeof x === "string") : [], conflicts: Array.isArray(value.conflicts) ? value.conflicts.filter((x): x is string => typeof x === "string") : [], requiresUserConfirmation: true as const }; });
}
export function previewCandidatesInDraft(candidates: readonly StructuredFieldCandidate[], current: Record<string, unknown>) { const values = { ...current }; const conflicts: string[] = []; for (const candidate of candidates) { if (values[candidate.fieldId] !== undefined && JSON.stringify(values[candidate.fieldId]) !== JSON.stringify(candidate.extractedValue)) conflicts.push(candidate.fieldId); values[candidate.fieldId] = candidate.extractedValue; } return { values, conflicts, committed: false as const }; }
