import { isRecord } from "@/lib/api/validation";
export const SUPPLIER_EDIT_FIELD_NAMES = ["displayName", "legalName", "phone", "email", "website", "taxNumber", "taxOffice", "metrixNote", "riskNotes", "status"] as const;
export const SUPPLIER_CLEARABLE_FIELD_NAMES = ["legalName", "phone", "email", "website", "taxNumber", "taxOffice", "metrixNote", "riskNotes"] as const;
export const SUPPLIER_STATUS_VALUES = ["ACTIVE", "PASSIVE", "ARCHIVED"] as const;
export type SupplierEditFieldName = (typeof SUPPLIER_EDIT_FIELD_NAMES)[number];
export type SupplierEditCommand = { type: "set_field"; field: SupplierEditFieldName; value: string } | { type: "clear_field"; field: (typeof SUPPLIER_CLEARABLE_FIELD_NAMES)[number] } | { type: "revert_field"; field: SupplierEditFieldName } | { type: "commit" } | { type: "discard" };
export type SupplierEditCommandResolution = { kind: "executable"; command: SupplierEditCommand } | { kind: "unsupported" } | { kind: "clarification_required"; message: string };
export type SupplierEditCommandExecutionResult = { status: "EXECUTED"; command: SupplierEditCommand; appliedField?: string; appliedValue?: string; commitOutcome?: "SAVED"; revertedFields?: string[] } | { status: "UNSUPPORTED" } | { status: "CLARIFICATION_REQUIRED"; message: string } | { status: "NO_ACTIVE_SURFACE" } | { status: "STALE_SURFACE" } | { status: "VALIDATION_FAILED"; reason: string } | { status: "EXECUTION_FAILED"; error: string };
function member(value: unknown, values: readonly string[]): value is string { return typeof value === "string" && values.includes(value); }
export function validateSupplierEditCommandResolution(raw: unknown): SupplierEditCommandResolution | null { if (!isRecord(raw)) return null; if (raw.result === "unsupported") return { kind: "unsupported" }; if (raw.result === "clarification_required") return typeof raw.message === "string" && raw.message.trim() ? { kind: "clarification_required", message: raw.message.trim() } : null; if (raw.result !== "executable") return null; if (raw.action === "commit" || raw.action === "discard") return { kind: "executable", command: { type: raw.action } }; if (raw.action === "set_field" && member(raw.field, SUPPLIER_EDIT_FIELD_NAMES) && typeof raw.value === "string" && raw.value.trim() && (raw.field !== "status" || member(raw.value, SUPPLIER_STATUS_VALUES))) return { kind: "executable", command: { type: "set_field", field: raw.field as SupplierEditFieldName, value: raw.value } }; if (raw.action === "clear_field" && member(raw.field, SUPPLIER_CLEARABLE_FIELD_NAMES)) return { kind: "executable", command: { type: "clear_field", field: raw.field as (typeof SUPPLIER_CLEARABLE_FIELD_NAMES)[number] } }; if (raw.action === "revert_field" && member(raw.field, SUPPLIER_EDIT_FIELD_NAMES)) return { kind: "executable", command: { type: "revert_field", field: raw.field as SupplierEditFieldName } }; return null; }
export function revalidateSupplierEditCommandResolution(raw: unknown): SupplierEditCommandResolution | null { if (!isRecord(raw)) return null; if (raw.kind === "unsupported") return { kind: "unsupported" }; if (raw.kind === "clarification_required") return typeof raw.message === "string" && raw.message.trim() ? { kind: "clarification_required", message: raw.message.trim() } : null; if (raw.kind !== "executable" || !isRecord(raw.command)) return null; return validateSupplierEditCommandResolution({ result: "executable", action: raw.command.type, ...raw.command }); }
