"use client";

import { useCallback, useEffect, useState, type FormEvent, type ReactNode } from "react";
import { cancelGoal, getGoal, updateGoal, type GoalPeriod, type GoalRecord, type GoalStatus } from "@/lib/goals/goals-client";

type Draft = { title: string; period: GoalPeriod; revenue: string; collection: string; startsAt: string; endsAt: string; status: GoalStatus };
const inputClass = "w-full rounded-xl border border-white/[.1] bg-white/[.04] px-3 py-2.5 text-sm text-[#EDE7D9] outline-none focus:border-[#34e6cf]/45";
const PERIODS: Array<[GoalPeriod, string]> = [["MONTHLY", "Aylık"], ["QUARTERLY", "Çeyreklik"], ["YEARLY", "Yıllık"], ["CUSTOM", "Özel"]];
const STATUSES: Array<[GoalStatus, string]> = [["ACTIVE", "Aktif"], ["COMPLETED", "Tamamlandı"], ["CANCELLED", "İptal"]];
const STATUS_LABELS = Object.fromEntries(STATUSES) as Record<GoalStatus, string>;

export function GoalEditSurface({ goalId, onReady, onFailure }: { goalId: string; onReady?: () => void; onFailure?: () => void }) {
  const [goal, setGoal] = useState<GoalRecord | null>(null); const [draft, setDraft] = useState<Draft | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null);
  const load = useCallback(async () => { const result = await getGoal(goalId); if (result.ok) { setGoal(result.data.goal); setDraft(toDraft(result.data.goal)); setError(null); onReady?.(); } else { setError(result.error); onFailure?.(); } }, [goalId, onFailure, onReady]);
  useEffect(() => { void load(); }, [load]);
  if (!goal || !draft) return error ? <Message error>{error}</Message> : <p className="py-12 text-center text-sm text-[#7C7466]">Hedef yükleniyor…</p>;
  const set = <K extends keyof Draft>(key: K, value: Draft[K]) => { setDraft((current) => current ? { ...current, [key]: value } : current); setNotice(null); };
  async function save(event: FormEvent) { event.preventDefault(); if (!draft?.title.trim()) return; const revenue = cents(draft.revenue); const collection = cents(draft.collection); if (revenue === null || collection === null) { setError("Hedef tutarları geçerli bir sayı olmalıdır."); return; } setBusy(true); setError(null); setNotice(null); const result = await updateGoal(goalId, { title: draft.title.trim(), period: draft.period, targetRevenueCents: revenue ?? undefined, targetCollectionCents: collection ?? undefined, startsAt: isoDate(draft.startsAt), endsAt: isoDate(draft.endsAt), status: draft.status }); if (result.ok) { setGoal(result.data.goal); setDraft(toDraft(result.data.goal)); setNotice("Hedef bilgileri kaydedildi."); } else setError(result.error); setBusy(false); }
  function discard() { if (!goal) return; setDraft(toDraft(goal)); setError(null); setNotice("Değişiklikler geri alındı."); }
  async function cancel() { setBusy(true); setError(null); setNotice(null); const result = await cancelGoal(goalId); if (result.ok) { await load(); setNotice("Hedef iptal edildi."); } else setError(result.error); setBusy(false); }
  return <div className="mx-auto max-w-5xl space-y-4 pb-8" data-goal-edit-surface={goal.id}><header className="flex items-start justify-between gap-3"><div><p className="text-xs uppercase tracking-[.18em] text-[#7C7466]">Hedef çalışma alanı</p><h2 className="mt-1 text-xl font-semibold text-[#EDE7D9]">{goal.title}</h2><p className="mt-1 text-sm text-[#A79F91]">Hedef dönemi, tutarları ve durumunu yönetin.</p></div><span className="rounded-full border border-[#C9BFA8]/20 bg-[#C9BFA8]/10 px-3 py-1.5 text-xs font-semibold text-[#C9BFA8]">{STATUS_LABELS[goal.status]}</span></header>{error ? <Message error>{error}</Message> : null}{notice ? <Message>{notice}</Message> : null}<form className="space-y-4" onSubmit={save}><Card title="Hedef bilgileri"><div className="grid gap-3 md:grid-cols-2"><Input label="Başlık" required value={draft.title} onChange={(v) => set("title", v)}/><Select label="Dönem" value={draft.period} options={PERIODS} onChange={(v) => set("period", v as GoalPeriod)}/><Input label="Hedef gelir (₺)" min="0" step="0.01" type="number" value={draft.revenue} onChange={(v) => set("revenue", v)}/><Input label="Hedef tahsilat (₺)" min="0" step="0.01" type="number" value={draft.collection} onChange={(v) => set("collection", v)}/><Input label="Başlangıç tarihi" type="date" value={draft.startsAt} onChange={(v) => set("startsAt", v)}/><Input label="Bitiş tarihi" type="date" value={draft.endsAt} onChange={(v) => set("endsAt", v)}/><Select label="Durum" value={draft.status} options={STATUSES} onChange={(v) => set("status", v as GoalStatus)}/></div></Card><Card title="Gerçekleşme bilgileri"><div className="grid gap-3 md:grid-cols-2"><Read label="Hedef türü" value={goal.goalType}/><Read label="Kapsam" value={goal.scope}/><Read label="Gerçekleşen değer" value={goal.actualValue}/><Read label="Tahmin" value={goal.forecastValue}/></div></Card><div className="flex flex-wrap items-center justify-between gap-3"><button className="rounded-xl border border-[#f16a7a]/30 bg-[#f16a7a]/10 px-4 py-2.5 text-sm font-bold text-[#f16a7a] disabled:opacity-40" disabled={busy || goal.status === "CANCELLED"} onClick={() => void cancel()} type="button">Hedefi iptal et</button><div className="flex gap-2"><button className="rounded-xl border border-white/10 px-4 py-2.5 text-sm font-semibold text-[#C9BFA8] disabled:opacity-40" disabled={busy} onClick={discard} type="button">Geri al</button><button className="rounded-xl bg-[#34e6cf] px-4 py-2.5 text-sm font-bold text-[#14120F] disabled:opacity-40" disabled={busy || !draft.title.trim()} type="submit">Değişiklikleri kaydet</button></div></div></form></div>;
}

function toDraft(goal: GoalRecord): Draft { return { title: goal.title, period: goal.period, revenue: money(goal.targetRevenueCents), collection: money(goal.targetCollectionCents), startsAt: date(goal.startsAt), endsAt: date(goal.endsAt), status: goal.status }; }
function money(value: string | null) { return value === null ? "" : String(Number(value) / 100); }
function cents(value: string): number | undefined | null { if (!value.trim()) return undefined; const number = Number(value.replace(",", ".")); return Number.isFinite(number) && number >= 0 ? Math.round(number * 100) : null; }
function date(value: string | null) { return value ? value.slice(0, 10) : ""; }
function isoDate(value: string): string | undefined { return value ? new Date(`${value}T00:00:00.000Z`).toISOString() : undefined; }
function Card({ title, children }: { title: string; children: ReactNode }) { return <section className="rounded-[20px] border border-white/[.08] bg-white/[.035] p-4"><h3 className="mb-3 text-sm font-semibold text-[#EDE7D9]">{title}</h3>{children}</section>; }
function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="block text-xs font-medium text-[#A79F91]"><span className="mb-1.5 block">{label}</span>{children}</label>; }
function Input({ label, value, onChange, ...props }: { label: string; value: string; onChange: (value: string) => void; required?: boolean; type?: string; min?: string; step?: string }) { return <Field label={label}><input aria-label={label} className={inputClass} value={value} onChange={(event) => onChange(event.target.value)} {...props}/></Field>; }
function Select({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: Array<[string, string]> }) { return <Field label={label}><select aria-label={label} className={inputClass} value={value} onChange={(event) => onChange(event.target.value)}>{options.map(([key, text]) => <option key={key} value={key}>{text}</option>)}</select></Field>; }
function Read({ label, value }: { label: string; value: string | null }) { return <div className="rounded-xl border border-white/[.08] bg-black/10 p-3"><p className="text-xs text-[#7C7466]">{label}</p><p className="mt-1 text-sm text-[#EDE7D9]">{value || "Belirtilmemiş"}</p></div>; }
function Message({ children, error = false }: { children: ReactNode; error?: boolean }) { return <p className={`rounded-xl border p-3 text-sm ${error ? "border-[#f16a7a]/20 bg-[#f16a7a]/10 text-[#f16a7a]" : "border-[#34e6cf]/20 bg-[#34e6cf]/10 text-[#34e6cf]"}`} role={error ? "alert" : "status"}>{children}</p>; }
