"use client";
import { useEffect, useMemo, useState } from "react";
import { WorkspaceSurface } from "./WorkspaceSurface";

type CalendarItem = { id: string; title: string; dueDate: string; kind: string; status?: string };
const SOURCES = ["/api/tasks", "/api/invoices", "/api/payments", "/api/collection-actions"];
export function CalendarWorkspace({ onReady }: { onReady?: () => void }) {
  const [items, setItems] = useState<CalendarItem[]>([]); const [cursor, setCursor] = useState(() => new Date()); const [selected, setSelected] = useState(() => new Date()); const [view, setView] = useState<"month" | "week" | "day">("month");
  useEffect(() => { const controller = new AbortController(); void Promise.all(SOURCES.map((source) => fetch(source, { credentials: "include", signal: controller.signal }).then((response) => response.json()).catch(() => null))).then((payloads) => { const next: CalendarItem[] = []; payloads.forEach((payload, index) => { const key = ["tasks", "invoices", "payments", "collectionActions"][index]; const rows = payload?.data?.[key]; if (!Array.isArray(rows)) return; rows.forEach((row) => { if (row?.dueDate) next.push({ id: String(row.id), title: String(row.title ?? row.invoiceNumber ?? "Takip edilecek kayıt"), dueDate: String(row.dueDate), kind: key === "tasks" ? "Görev" : key === "invoices" ? "Fatura" : key === "payments" ? "Tahsilat" : "Takip", status: row.status ? String(row.status) : undefined }); }); }); setItems(next); onReady?.(); }); return () => controller.abort(); }, [onReady]);
  const days = useMemo(() => { const start = new Date(cursor.getFullYear(), cursor.getMonth(), 1); const end = new Date(cursor.getFullYear(), cursor.getMonth() + 1, 0); const first = start.getDay() === 0 ? 6 : start.getDay() - 1; return Array.from({ length: first + end.getDate() }, (_, i) => i < first ? null : new Date(cursor.getFullYear(), cursor.getMonth(), i - first + 1)); }, [cursor]);
  const selectedKey = selected.toISOString().slice(0, 10); const selectedItems = items.filter((item) => item.dueDate.slice(0, 10) === selectedKey);
  return <WorkspaceSurface title="Günlük iş programı" subtitle="Görevler, vadeler ve takipler tek takvimde" kpis={[{ label: "Bu ay", value: items.filter((i) => i.dueDate.startsWith(`${cursor.getFullYear()}-${String(cursor.getMonth() + 1).padStart(2, "0")}`)).length }, { label: "Seçili gün", value: selectedItems.length }]} actions={<div className="calendar-toolbar"><button type="button" onClick={() => setCursor(new Date(cursor.getFullYear(), cursor.getMonth() - 1, 1))}>‹</button><strong>{new Intl.DateTimeFormat("tr-TR", { month: "long", year: "numeric" }).format(cursor)}</strong><button type="button" onClick={() => setCursor(new Date(cursor.getFullYear(), cursor.getMonth() + 1, 1))}>›</button><span className="calendar-spacer" />{(["month", "week", "day"] as const).map((mode) => <button className={view === mode ? "is-active" : ""} key={mode} type="button" onClick={() => setView(mode)}>{mode === "month" ? "Ay" : mode === "week" ? "Hafta" : "Gün"}</button>)}</div>}><div className={`calendar-grid calendar-${view}`}><div className="calendar-weekdays">{["Pzt", "Sal", "Çar", "Per", "Cum", "Cmt", "Paz"].map((day) => <span key={day}>{day}</span>)}</div><div className="calendar-days">{days.map((day, index) => day ? <button className={day.toISOString().slice(0, 10) === selectedKey ? "is-selected" : ""} key={day.toISOString()} type="button" onClick={() => setSelected(day)}><time>{day.getDate()}</time>{items.filter((item) => item.dueDate.slice(0, 10) === day.toISOString().slice(0, 10)).length ? <b>{items.filter((item) => item.dueDate.slice(0, 10) === day.toISOString().slice(0, 10)).length}</b> : null}</button> : <span key={`blank-${index}`} />)}</div></div><div className="calendar-agenda"><h3>{new Intl.DateTimeFormat("tr-TR", { dateStyle: "full" }).format(selected)}</h3>{selectedItems.length ? selectedItems.map((item) => <div className="calendar-item" key={item.id}><span>{item.kind}</span><strong>{item.title}</strong><small>{item.status ?? "Takipte"}</small></div>) : <p>Bu gün için planlanmış iş bulunmuyor.</p>}</div></WorkspaceSurface>;
}
