"use client";
import { useEffect, useState } from "react";
import { DOMAIN_SURFACE_ADAPTERS, type WorkspaceDirective } from "@/lib/living-workspace";
import { WorkspaceSurface } from "./WorkspaceSurface";

export function CanonicalDomainSurface({ directive, onReady, onFailure }: { directive: WorkspaceDirective; onReady: () => void; onFailure: () => void }) {
  const [rows, setRows] = useState<Array<Record<string, unknown>> | null>(null);
  useEffect(() => { const controller = new AbortController(); const adapter = DOMAIN_SURFACE_ADAPTERS[directive.domain]; fetch(adapter.endpoint, { credentials: "include", signal: controller.signal }).then((r) => r.json()).then((payload) => { if (!payload.ok) throw new Error("canonical surface failed"); const data = payload.data as Record<string, unknown>; const value = data[adapter.responseKey]; setRows(Array.isArray(value) ? value as Array<Record<string, unknown>> : []); onReady(); }).catch(() => { if (!controller.signal.aborted) onFailure(); }); return () => controller.abort(); }, [directive, onFailure, onReady]);
  const surface = directive.surfaces.find((item) => item.surfaceId === directive.primarySurfaceId);
  const columns = surface?.columns ?? DOMAIN_SURFACE_ADAPTERS[directive.domain].allowedListColumns.slice(0, 5);
  return <div className="mx-auto max-w-5xl">{rows === null ? <WorkspaceSurface title={directive.title} subtitle="Bilinen bilgiler hazırlanıyor…" identity={directive.entityId ? humanIdentity(directive.entityType, directive.entityId) : undefined}><div className="workspace-loading">{directive.title}</div></WorkspaceSurface> : <WorkspaceSurface title={humanTitle(directive.title)} subtitle={directive.subtitle} identity={directive.entityId ? humanIdentity(directive.entityType, directive.entityId) : undefined}><div className="grid gap-3">{rows.length ? rows.slice(0, 50).map((row, index) => <article className="workspace-record" key={String(row.id ?? index)}>{columns.map((column) => <div className="workspace-record-field" key={column}><span>{humanLabel(column)}</span><strong>{humanValue(row[column], column)}</strong></div>)}</article>) : <p className="workspace-empty">Bu görünümde kayıt bulunmuyor.</p>}</div></WorkspaceSurface>}</div>;
}

function humanTitle(value: string) { return value.replace(/^(payment|invoice|task|quote|product):/iu, "").replace(/\b(list|detail)\b/giu, "").trim() || "Çalışma alanı"; }
function humanIdentity(type: string, id: string) { return `${type === "Payment" ? "Tahsilat" : type} · ${id.slice(0, 8)}`; }
function humanLabel(key: string) { return ({ displayName: "Müşteri", customerName: "Müşteri", balanceCents: "Bakiye", dueDate: "Vade", createdAt: "Oluşturulma", updatedAt: "Güncelleme", status: "Durum", amount: "Tutar", totalAmount: "Toplam tutar", title: "Başlık", description: "Açıklama", invoiceNumber: "Fatura numarası", currency: "Para birimi", priority: "Öncelik" } as Record<string, string>)[key] ?? key.replace(/([A-Z])/g, " $1").replace(/^./, (c) => c.toUpperCase()); }
function humanValue(value: unknown, key: string) { if (value === null || value === undefined || value === "") return key === "dueDate" ? "Vade tanımlanmamış" : "Belirtilmemiş"; if (/(date|At)$/iu.test(key) && typeof value === "string") { const date = new Date(value); if (!Number.isNaN(date.valueOf())) return new Intl.DateTimeFormat("tr-TR", { dateStyle: "medium", timeStyle: "short" }).format(date); } if (key.endsWith("Cents")) return new Intl.NumberFormat("tr-TR", { style: "currency", currency: "TRY" }).format(Number(value) / 100); return typeof value === "number" ? new Intl.NumberFormat("tr-TR").format(value) : String(value); }
